Paparazzi UAS: sw/airborne/mcu_periph/adc.h File Reference
adc.h File Reference
arch independent ADC (Analog to Digital Converter) API
#include <inttypes.h>
#include "mcu_periph/adc_arch.h"
Data Structures
struct adc_buf
Generic interface for all ADC hardware drivers, independent from microcontroller architecture.
Macros
#define NB_ADC 8
#define MAX_AV_NB_SAMPLE 0x20
#define DEFAULT_AV_NB_SAMPLE 0x20
Functions
void adc_buf_channel (uint8_t adc_channel, struct adc_buf *s, uint8_t av_nb_sample)
Registers a buffer to be used to store the specified converted channel Usage:
void adc_init (void)
Starts conversions.
Detailed Description
arch independent ADC (Analog to Digital Converter) API
Facility to store last values in a circular buffer for a specific channel:
allocate a (struct adc_buf)
register it with the adc_buf_channel function
Definition in file adc.h.
Macro Definition Documentation
#define DEFAULT_AV_NB_SAMPLE 0x20
Definition at line 48 of file adc.h.
Referenced by agl_vf_init(), baro_init(), electrical_init(), and maxbotix_init().
#define MAX_AV_NB_SAMPLE 0x20
Definition at line 47 of file adc.h.
#define NB_ADC 8
Definition at line 44 of file adc.h.
Function Documentation
void adc_buf_channel (uint8_t adc_channel, struct adc_buf * s, uint8_t av_nb_sample)
Registers a buffer to be used to store the specified converted channel Usage:
struct adc_buf channel_buf;
adc_buf_channel(1, &channel_buf, 12);
Registers channel_buf as buffer for ADC channel 1, with max index 12 (12 samples).
Definition at line 59 of file adc_arch.c.
References adc_buf::av_nb_sample.
Referenced by adc_generic_init(), agl_vf_init(), airspeed_adc_init(), AOA_adc_init(), baro_init(), electrical_init(), enose_init(), humid_hih_init(), imu_impl_init(), infrared_adc_init(), light_solar_init(), light_temt_init(), maxbotix_init(), and temp_tcouple_adc_init().
void adc_init (void)
Starts conversions.
Definition at line 194 of file adc_arch.c.
References _VIC_ADDR, _VIC_CNTL, AD0CR, AD1CR, ADC1, ADC_AD0CR_SEL_HW_SCAN, ADC_AD1CR_SEL_HW_SCAN, adc_channel_map, adc_init_irq(), adc_init_rcc(), adc_init_single(), adc_injected_channels, adc_new_data_trigger, ADC_PINSEL0_ONES, ADC_PINSEL1_ONES, adcISR0(), adcISR1(), BOARD_ADC_CHANNEL_1, BOARD_ADC_CHANNEL_2, BOARD_ADC_CHANNEL_3, BOARD_ADC_CHANNEL_4, channel, FALSE, NB_ADC1_CHANNELS, NB_ADC2_CHANNELS, PINSEL0, PINSEL1, USE_AD1_2, USE_AD1_4, VIC_AD0, VIC_AD1, VIC_BIT, VIC_ENABLE, VICIntEnable, and VICIntSelect.
Referenced by mcu_init().