Paparazzi UAS: sw/airborne/peripherals/adxl345_spi.h File Reference
adxl345_spi.h File Reference
Driver for the accelerometer ADXL345 from Analog Devices using SPI.
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "mcu_periph/spi.h"
#include "peripherals/adxl345.h"
Data Structures
struct Adxl345_Spi
Functions
void adxl345_spi_init (struct Adxl345_Spi *adxl, struct spi_periph *spi_p, uint8_t addr)
void adxl345_spi_start_configure (struct Adxl345_Spi *adxl)
void adxl345_spi_read (struct Adxl345_Spi *adxl)
void adxl345_spi_event (struct Adxl345_Spi *adxl)
static void adxl345_spi_periodic (struct Adxl345_Spi *adxl)
convenience function: read or start configuration if not already initialized
Detailed Description
Driver for the accelerometer ADXL345 from Analog Devices using SPI.
Definition in file adxl345_spi.h.
Function Documentation
void adxl345_spi_event (struct Adxl345_Spi * adxl)
Definition at line 130 of file adxl345_spi.c.
References adxl345_spi_send_config(), ADXL_CONF_UNINIT, Adxl345_Spi::data, Adxl345_Spi::data_available, Adxl345_Spi::init_status, Adxl345_Spi::initialized, Int16FromBuf, Adxl345_Spi::rx_buf, Adxl345_Spi::spi_trans, SPITransDone, SPITransFailed, SPITransSuccess, spi_transaction::status, TRUE, Adxl345_Spi::vect, Int16Vect3::x, Int16Vect3::y, and Int16Vect3::z.
Referenced by imu_aspirin_event().
void adxl345_spi_init (struct Adxl345_Spi * adxl, struct spi_periph * spi_p, uint8_t addr)
Definition at line 35 of file adxl345_spi.c.
References adxl345_set_default_config(), ADXL_CONF_UNINIT, spi_transaction::after_cb, spi_transaction::before_cb, spi_transaction::bitorder, spi_transaction::cdiv, Adxl345_Spi::config, spi_transaction::cpha, spi_transaction::cpol, Adxl345_Spi::data_available, spi_transaction::dss, FALSE, Adxl345_Spi::init_status, Adxl345_Spi::initialized, spi_transaction::input_buf, spi_transaction::input_length, spi_transaction::output_buf, spi_transaction::output_length, Adxl345_Spi::rx_buf, spi_transaction::select, spi_transaction::slave_idx, Adxl345_Spi::spi_p, Adxl345_Spi::spi_trans, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, SPITransDone, spi_transaction::status, and Adxl345_Spi::tx_buf.
Referenced by imu_impl_init().
static void adxl345_spi_periodic (struct Adxl345_Spi * adxl) inline static
convenience function: read or start configuration if not already initialized
Definition at line 61 of file adxl345_spi.h.
References adxl345_spi_read(), adxl345_spi_start_configure(), and Adxl345_Spi::initialized.
Referenced by imu_periodic().
void adxl345_spi_read (struct Adxl345_Spi * adxl)
Definition at line 117 of file adxl345_spi.c.
References ADXL345_REG_DATA_X0, Adxl345_Spi::initialized, spi_transaction::input_length, spi_transaction::output_length, Adxl345_Spi::spi_p, spi_submit(), Adxl345_Spi::spi_trans, SPITransDone, spi_transaction::status, and Adxl345_Spi::tx_buf.
Referenced by adxl345_spi_periodic().
void adxl345_spi_start_configure (struct Adxl345_Spi * adxl)
Definition at line 107 of file adxl345_spi.c.
References adxl345_spi_send_config(), ADXL_CONF_UNINIT, Adxl345_Spi::init_status, Adxl345_Spi::spi_trans, SPITransDone, SPITransSuccess, and spi_transaction::status.
Referenced by adxl345_spi_periodic().