Paparazzi UAS: sw/airborne/peripherals/adxl345.h File Reference
adxl345.h File Reference
Analog Devices ADXL345 accelerometer driver common interface (I2C and SPI).
#include "std.h"
#include "peripherals/adxl345_regs.h"
Data Structures
struct Adxl345Config
Enumerations
enum Adxl345ConfStatus {
ADXL_CONF_UNINIT = 0, ADXL_CONF_RATE = 1, ADXL_CONF_INT = 2, ADXL_CONF_FORMAT = 3,
ADXL_CONF_ENABLE = 4, ADXL_CONF_DONE = 5
}
Functions
static void adxl345_set_default_config (struct Adxl345Config *c)
static uint8_t adxl345_data_format (struct Adxl345Config *c)
Detailed Description
Analog Devices ADXL345 accelerometer driver common interface (I2C and SPI).
Definition in file adxl345.h.
Enumeration Type Documentation
enum Adxl345ConfStatus
Enumerator:
ADXL_CONF_UNINIT
ADXL_CONF_RATE
ADXL_CONF_INT
ADXL_CONF_FORMAT
ADXL_CONF_ENABLE
ADXL_CONF_DONE
Definition at line 36 of file adxl345.h.
Function Documentation
static uint8_t adxl345_data_format (struct Adxl345Config * c) inline static
Definition at line 69 of file adxl345.h.
References Adxl345Config::full_res, Adxl345Config::int_invert, Adxl345Config::justify_msb, Adxl345Config::range, Adxl345Config::self_test, and Adxl345Config::spi_3_wire.
Referenced by adxl345_spi_send_config().
static void adxl345_set_default_config (struct Adxl345Config * c) inline static
Definition at line 56 of file adxl345.h.
References ADXL345_RANGE_16G, ADXL345_RATE_100HZ, Adxl345Config::drdy_int_enable, FALSE, Adxl345Config::full_res, Adxl345Config::int_invert, Adxl345Config::justify_msb, Adxl345Config::range, Adxl345Config::rate, Adxl345Config::self_test, Adxl345Config::spi_3_wire, and TRUE.
Referenced by adxl345_i2c_init(), and adxl345_spi_init().