Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_int_cmpl_euler.c File Reference
ahrs_int_cmpl_euler.c File Reference
Complementary filter in euler representation (fixed-point).
#include "ahrs_int_cmpl_euler.h"
#include "state.h"
#include "subsystems/imu.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "math/pprz_trig_int.h"
#include "math/pprz_algebra_int.h"
#include "generated/airframe.h"
Macros
#define FACE_REINJ_1 1024
#define AHRS_MAG_OFFSET 0.
#define F_UPDATE 512
#define PI_INTEG_EULER (INT32_ANGLE_PI * F_UPDATE)
#define TWO_PI_INTEG_EULER (INT32_ANGLE_2_PI * F_UPDATE)
#define INTEG_EULER_NORMALIZE(_a)
#define NOISE_FILTER_GAIN 50
Functions
static void get_phi_theta_measurement_fom_accel (int32_t *phi_meas, int32_t *theta_meas, struct Int32Vect3 accel)
static void get_psi_measurement_from_mag (int32_t *psi_meas, int32_t phi_est, int32_t theta_est, struct Int32Vect3 mag)
static void set_body_state_from_euler (void)
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Variables
struct AhrsIntCmplEuler ahrs_impl
Detailed Description
Complementary filter in euler representation (fixed-point).
Estimate the attitude, heading and gyro bias.
Definition in file ahrs_int_cmpl_euler.c.
Macro Definition Documentation
#define AHRS_MAG_OFFSET 0.
Definition at line 46 of file ahrs_int_cmpl_euler.c.
Referenced by ahrs_init().
#define F_UPDATE 512
Definition at line 68 of file ahrs_int_cmpl_euler.c.
Referenced by ahrs_align(), ahrs_propagate(), get_phi_theta_measurement_fom_accel(), and get_psi_measurement_from_mag().
#define FACE_REINJ_1 1024
Definition at line 42 of file ahrs_int_cmpl_euler.c.
Referenced by ahrs_init().
#define INTEG_EULER_NORMALIZE (_a)
Value:
{                         \
    while (_a >  PI_INTEG_EULER)  _a -= TWO_PI_INTEG_EULER; \
    while (_a < -PI_INTEG_EULER)  _a += TWO_PI_INTEG_EULER; \
  }
Definition at line 72 of file ahrs_int_cmpl_euler.c.
Referenced by ahrs_propagate().
#define NOISE_FILTER_GAIN 50
Definition at line 111 of file ahrs_int_cmpl_euler.c.
Referenced by ahrs_propagate(), and ahrs_update_accel().
#define PI_INTEG_EULER (INT32_ANGLE_PI * F_UPDATE)
Definition at line 70 of file ahrs_int_cmpl_euler.c.
#define TWO_PI_INTEG_EULER (INT32_ANGLE_2_PI * F_UPDATE)
Definition at line 71 of file ahrs_int_cmpl_euler.c.
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 90 of file ahrs_int_cmpl_euler.c.
References ahrs, ahrs_aligner, ahrs_impl, AHRS_RUNNING, EULERS_COPY, EULERS_SDIV, F_UPDATE, get_phi_theta_measurement_fom_accel(), get_psi_measurement_from_mag(), AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, AhrsIntExternQuat::ltp_to_imu_euler, RATES_COPY, set_body_state_from_euler(), and Ahrs::status.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 77 of file ahrs_int_cmpl_euler.c.
References ahrs, ahrs_impl, AHRS_MAG_OFFSET, AHRS_UNINIT, Imu::body_to_imu_rmat, FACE_REINJ_1, imu, AhrsIntExternQuat::imu_rate, INT32_EULERS_OF_RMAT, INT_RATES_ZERO, AhrsIntExternQuat::ltp_to_imu_euler, AhrsIntExternQuat::mag_offset, and Ahrs::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 159 of file ahrs_int_cmpl_euler.c.
References ahrs_impl, EULERS_ADD, EULERS_DIFF, EULERS_SDIV, F_UPDATE, Imu::gyro, imu, AhrsIntExternQuat::imu_rate, INT32_EULERS_DOT_OF_RATES, INTEG_EULER_NORMALIZE, AhrsIntExternQuat::ltp_to_imu_euler, NOISE_FILTER_GAIN, RATES_ADD, RATES_COPY, RATES_DIFF, RATES_SDIV, RATES_SUM_SCALED, and set_body_state_from_euler().
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 209 of file ahrs_int_cmpl_euler.c.
References Imu::accel, ahrs_impl, get_phi_theta_measurement_fom_accel(), imu, NOISE_FILTER_GAIN, VECT3_COPY, VECT3_SDIV, and VECT3_SUM_SCALED.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 236 of file ahrs_int_cmpl_euler.c.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 230 of file ahrs_int_cmpl_euler.c.
References ahrs_impl, get_psi_measurement_from_mag(), imu, AhrsIntExternQuat::ltp_to_imu_euler, Imu::mag, Int32Eulers::phi, and Int32Eulers::theta.
static void get_phi_theta_measurement_fom_accel (int32_t * phi_meas, int32_t * theta_meas, struct Int32Vect3 accel) inline static
Definition at line 241 of file ahrs_int_cmpl_euler.c.
References F_UPDATE, INT32_ATAN2, INT32_TRIG_FRAC, INT_MULT_RSHIFT, and PPRZ_ITRIG_COS.
Referenced by ahrs_align(), and ahrs_update_accel().
static void get_psi_measurement_from_mag (int32_t * psi_meas, int32_t phi_est, int32_t theta_est, struct Int32Vect3 mag) inline static
Definition at line 254 of file ahrs_int_cmpl_euler.c.
References ahrs_impl, F_UPDATE, INT32_ANGLE_FRAC, INT32_TRIG_FRAC, AhrsIntExternQuat::mag_offset, PPRZ_ITRIG_COS, and PPRZ_ITRIG_SIN.
Referenced by ahrs_align(), and ahrs_update_mag().
static void set_body_state_from_euler (void) inline static
Definition at line 282 of file ahrs_int_cmpl_euler.c.
References ahrs_impl, ANGLE_BFP_OF_REAL, Imu::body_to_imu_rmat, imu, AhrsIntExternQuat::imu_rate, ins_pitch_neutral, ins_roll_neutral, INT32_EULERS_OF_RMAT, INT32_RMAT_COMP_INV, INT32_RMAT_OF_EULERS, INT32_RMAT_TRANSP_RATEMULT, AhrsIntExternQuat::ltp_to_imu_euler, Int32Eulers::phi, stateSetBodyRates_i(), stateSetNedToBodyEulers_i(), stateSetNedToBodyRMat_i(), and Int32Eulers::theta.
Referenced by ahrs_align(), and ahrs_propagate().
Variable Documentation
struct AhrsIntCmplEuler ahrs_impl
Definition at line 62 of file ahrs_int_cmpl_euler.c.