Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_float_cmpl.c File Reference
ahrs_float_cmpl.c File Reference
#include "subsystems/ahrs.h"
#include "subsystems/ahrs/ahrs_float_cmpl.h"
#include "subsystems/ahrs/ahrs_float_utils.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "subsystems/imu.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_simple_matrix.h"
#include "generated/airframe.h"
#include "subsystems/gps.h"
Defines
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
Functions
void ahrs_update_mag_full (void)
void ahrs_update_mag_2d (void)
void ahrs_update_mag_2d_dumb (void)
static void compute_body_orientation_and_rates (void)
Compute body orientation and rates from imu orientation and rates.
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
void ahrs_update_heading (float heading)
Update yaw based on a heading measurement.
void ahrs_realign_heading (float heading)
Hard reset yaw to a heading.
Variables
struct AhrsFloatCmpl ahrs_impl
Define Documentation
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
Definition at line 54 of file ahrs_float_cmpl.c.
Referenced by ahrs_propagate(), and on_gyro_event().
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 104 of file ahrs_float_cmpl.c.
References ahrs, ahrs_aligner, ahrs_float_get_quat_from_accel(), ahrs_float_get_quat_from_accel_mag(), ahrs_impl, AHRS_RUNNING, compute_body_orientation_and_rates(), FALSE, FLOAT_RMAT_OF_QUAT, AhrsFloatCmpl::gyro_bias, AhrsFloatCmpl::heading_aligned, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, AhrsFloatCmpl::ltp_to_imu_quat, AhrsFloatCmpl::ltp_to_imu_rmat, RATES_COPY, RATES_FLOAT_OF_BFP, Ahrs::status, and TRUE.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 79 of file ahrs_float_cmpl.c.
References ahrs, ahrs_impl, AHRS_UNINIT, AhrsFloatCmpl::body_to_imu_quat, AhrsFloatCmpl::body_to_imu_rmat, AhrsFloatCmpl::correct_gravity, FALSE, FLOAT_QUAT_OF_EULERS, FLOAT_RATES_ZERO, FLOAT_RMAT_OF_EULERS, AhrsFloatCmpl::heading_aligned, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, AhrsFloatCmpl::imu_rate, AhrsFloatCmpl::ltp_to_imu_quat, AhrsFloatCmpl::ltp_to_imu_rmat, AhrsFloatCmpl::ltp_vel_norm_valid, QUAT_COPY, RMAT_COPY, Ahrs::status, and TRUE.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 131 of file ahrs_float_cmpl.c.
References ahrs_impl, AHRS_PROPAGATE_FREQUENCY, compute_body_orientation_and_rates(), dt, FLOAT_QUAT_INTEGRATE, FLOAT_QUAT_NORMALIZE, FLOAT_QUAT_OF_RMAT, FLOAT_RATES_LIN_CMB, FLOAT_RATES_ZERO, FLOAT_RMAT_INTEGRATE_FI, FLOAT_RMAT_OF_QUAT, float_rmat_reorthogonalize(), AhrsFloatCmpl::gyro_bias, Imu::gyro_prev, imu, AhrsFloatCmpl::imu_rate, AhrsFloatCmpl::ltp_to_imu_quat, AhrsFloatCmpl::ltp_to_imu_rmat, AhrsFloatCmpl::rate_correction, RATES_COPY, RATES_FLOAT_OF_BFP, RATES_SUB, and RATES_SUM.
void ahrs_realign_heading (float heading)
Hard reset yaw to a heading.
Doesn't affect the bias. Sets ahrs_impl.heading_aligned to TRUE.
Parameters:
heading Heading in body frame, radians (CW/north)
Definition at line 379 of file ahrs_float_cmpl.c.
References ahrs_impl, AhrsFloatCmpl::body_to_imu_quat, FLOAT_ANGLE_NORMALIZE, FLOAT_QUAT_COMP, FLOAT_QUAT_COMP_NORM_SHORTEST, FLOAT_QUAT_INV_COMP_NORM_SHORTEST, FLOAT_QUAT_NORMALIZE, FLOAT_RMAT_OF_QUAT, AhrsFloatCmpl::heading_aligned, AhrsFloatCmpl::ltp_to_imu_quat, AhrsFloatCmpl::ltp_to_imu_rmat, FloatQuat::qi, QUAT_COPY, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, stateGetNedToBodyQuat_f(), stateSetNedToBodyQuat_f(), and TRUE.
Referenced by ahrs_update_gps().
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 167 of file ahrs_float_cmpl.c.
References Imu::accel, ACCELS_FLOAT_OF_BFP, ahrs_impl, AhrsFloatCmpl::body_to_imu_rmat, AhrsFloatCmpl::correct_gravity, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, FLOAT_VECT3_CROSS_PRODUCT, FLOAT_VECT3_NORM, AhrsFloatCmpl::gyro_bias, imu, AhrsFloatCmpl::ltp_to_imu_rmat, AhrsFloatCmpl::ltp_vel_norm, AhrsFloatCmpl::ltp_vel_norm_valid, AhrsFloatCmpl::rate_correction, RMAT_ELMT, stateGetBodyRates_f(), VECT3_DIFF, and VECT3_RATES_CROSS_VECT3.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 309 of file ahrs_float_cmpl.c.
References ahrs_impl, ahrs_realign_heading(), ahrs_update_heading(), GpsState::cacc, GpsState::course, FALSE, GpsState::fix, gps, GPS_FIX_3D, GpsState::gspeed, AhrsFloatCmpl::heading_aligned, AhrsFloatCmpl::ltp_vel_norm, AhrsFloatCmpl::ltp_vel_norm_valid, GpsState::speed_3d, and TRUE.
void ahrs_update_heading (float heading)
Update yaw based on a heading measurement.
e.g. from GPS course
Parameters:
heading Heading in body frame, radians (CW/north)
Definition at line 341 of file ahrs_float_cmpl.c.
References ahrs_impl, FLOAT_ANGLE_NORMALIZE, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, AhrsFloatCmpl::gyro_bias, AhrsFloatCmpl::ltp_to_imu_rmat, AhrsFloatCmpl::rate_correction, RMAT_ELMT, stateGetNedToBodyRMat_f(), FloatVect2::x, FloatVect2::y, and FloatVect3::z.
Referenced by ahrs_update_gps().
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 225 of file ahrs_float_cmpl.c.
Referenced by ahrs_update(), and on_mag_event().
static void ahrs_update_mag_2d (void) [inline]
Definition at line 256 of file ahrs_float_cmpl.c.
References AHRS_H_X, AHRS_H_Y, ahrs_impl, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, FLOAT_RMAT_VECT3_TRANSP_MUL, AhrsFloatCmpl::gyro_bias, imu, AhrsFloatCmpl::ltp_to_imu_rmat, Imu::mag, MAGS_FLOAT_OF_BFP, AhrsFloatCmpl::rate_correction, FloatVect2::x, FloatVect3::x, FloatVect2::y, and FloatVect3::y.
Referenced by ahrs_update_mag().
void ahrs_update_mag_2d_dumb (void)
Definition at line 284 of file ahrs_float_cmpl.c.
References ahrs_impl, FLOAT_EULERS_OF_RMAT, FLOAT_RATES_ADD_SCALED_VECT, AhrsFloatCmpl::gyro_bias, imu, AhrsFloatCmpl::ltp_to_imu_rmat, Imu::mag, MAGS_FLOAT_OF_BFP, FloatEulers::phi, AhrsFloatCmpl::rate_correction, RMAT_ELMT, FloatEulers::theta, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
static void ahrs_update_mag_full (void) [inline]
Definition at line 233 of file ahrs_float_cmpl.c.
References AHRS_H_X, AHRS_H_Y, ahrs_impl, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, FLOAT_VECT3_CROSS_PRODUCT, AhrsFloatCmpl::gyro_bias, imu, AhrsFloatCmpl::ltp_to_imu_rmat, Imu::mag, MAGS_FLOAT_OF_BFP, and AhrsFloatCmpl::rate_correction.
Referenced by ahrs_update_mag().
static void compute_body_orientation_and_rates (void) [inline, static]
Compute body orientation and rates from imu orientation and rates.
Definition at line 419 of file ahrs_float_cmpl.c.
References ahrs_impl, AhrsFloatCmpl::body_to_imu_quat, AhrsFloatCmpl::body_to_imu_rmat, FLOAT_QUAT_COMP_INV, FLOAT_QUAT_NORMALIZE, FLOAT_QUAT_OF_EULERS, FLOAT_RMAT_TRANSP_RATEMULT, AhrsFloatCmpl::imu_rate, ins_pitch_neutral, ins_roll_neutral, AhrsFloatCmpl::ltp_to_imu_quat, stateSetBodyRates_f(), and stateSetNedToBodyQuat_f().
Referenced by ahrs_align(), and ahrs_propagate().
Variable Documentation
struct AhrsFloatCmpl ahrs_impl
Definition at line 77 of file ahrs_float_cmpl.c.
Referenced by ahrs_align(), ahrs_init(), ahrs_propagate(), ahrs_realign_heading(), ahrs_update_accel(), ahrs_update_gps(), ahrs_update_heading(), ahrs_update_mag(), ahrs_update_mag_2d(), ahrs_update_mag_2d_dumb(), ahrs_update_mag_full(), compute_ahrs_representations(), compute_body_orientation_and_rates(), Drift_correction(), get_psi_measurement_from_mag(), Matrix_update(), Normalize(), set_body_orientation_and_rates(), set_body_state_from_euler(), and set_body_state_from_quat().