Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_sim.h File Reference
ahrs_sim.h File Reference
#include "subsystems/ahrs.h"
#include "std.h"
Functions
void update_ahrs_from_sim (void)
Variables
bool_t ahrs_sim_available
Function Documentation
void update_ahrs_from_sim (void)
Definition at line 51 of file ahrs_sim.c.
References ins_pitch_neutral, ins_roll_neutral, FloatEulers::phi, sim_p, sim_phi, sim_psi, sim_q, sim_r, sim_theta, stateSetBodyRates_f(), stateSetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by ahrs_align(), and ahrs_propagate().
Variable Documentation
bool_t ahrs_sim_available
Definition at line 17 of file jsbsim_ahrs.c.
Referenced by ahrs_init(), ahrs_propagate(), provide_attitude(), provide_attitude_and_rates(), and provide_rates().