Paparazzi UAS: sw/airborne/modules/ins/ahrs_chimu_uart.c File Reference
ahrs_chimu_uart.c File Reference
#include <stdbool.h>
#include "state.h"
#include "subsystems/gps.h"
#include "subsystems/ahrs.h"
#include "generated/airframe.h"
#include "ins_module.h"
#include "imu_chimu.h"
#include "led.h"
Functions
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void parse_ins_msg (void)
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Variables
CHIMU_PARSER_DATA CHIMU_DATA
INS_FORMAT ins_roll_neutral
INS_FORMAT ins_pitch_neutral
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 67 of file ahrs_chimu_uart.c.
References ahrs, AHRS_RUNNING, and Ahrs::status.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 36 of file ahrs_chimu_uart.c.
References ahrs, AHRS_UNINIT, CHIMU_BROADCAST, CHIMU_Checksum(), CHIMU_Init(), CHIMU_STX, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, InsSend, InsUartSend1, MSG00_PING, MSG09_ESTIMATOR, MSG10_UARTSETTINGS, new_ins_attitude, and Ahrs::status.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 101 of file ahrs_chimu_uart.c.
void parse_ins_msg (void) [inline]
Definition at line 73 of file ahrs_chimu_uart.c.
References CHIMU_Parse(), DefaultChannel, DefaultDevice, CHIMU_attitude_data::euler, InsLink, LED_TOGGLE, CHIMU_PARSER_DATA::m_attitude, CHIMU_PARSER_DATA::m_MsgID, new_ins_attitude, CHIMU_Euler::phi, CHIMU_Euler::psi, stateSetNedToBodyEulers_f(), and CHIMU_Euler::theta.
Variable Documentation
CHIMU_PARSER_DATA CHIMU_DATA
Definition at line 31 of file ahrs_chimu_uart.c.
INS_FORMAT ins_pitch_neutral
Definition at line 34 of file ahrs_chimu_uart.c.
INS_FORMAT ins_roll_neutral
Todo:
harmonize infrared neutrals with ins_neutrals or get rid of ins neutrals this ins only needed for sim right now
Definition at line 33 of file ahrs_chimu_uart.c.