Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_float_utils.h File Reference
ahrs_float_utils.h File Reference
Utility functions for floating point AHRS implementations.
#include "subsystems/ahrs/ahrs_magnetic_field_model.h"
#include "std.h"
Functions
static void ahrs_float_get_euler_from_accel_mag (struct FloatEulers *e, struct Int32Vect3 *accel, struct Int32Vect3 *mag)
static void ahrs_float_get_quat_from_accel (struct FloatQuat *q, struct Int32Vect3 *accel)
Compute a quaternion representing roll and pitch from an accelerometer measurement.
static void ahrs_float_get_quat_from_accel_mag (struct FloatQuat *q, struct Int32Vect3 *accel, struct Int32Vect3 *mag)
Detailed Description
Utility functions for floating point AHRS implementations.
Definition in file ahrs_float_utils.h.
Function Documentation
static void ahrs_float_get_euler_from_accel_mag (struct FloatEulers * e, struct Int32Vect3 * accel, struct Int32Vect3 * mag) inline static
Definition at line 37 of file ahrs_float_utils.h.
References ACCELS_FLOAT_OF_BFP, AHRS_H_X, AHRS_H_Y, EULERS_ASSIGN, MAGS_FLOAT_OF_BFP, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ahrs_align().
static void ahrs_float_get_quat_from_accel (struct FloatQuat * q, struct Int32Vect3 * accel) inline static
Compute a quaternion representing roll and pitch from an accelerometer measurement.
Definition at line 61 of file ahrs_float_utils.h.
References ACCELS_FLOAT_OF_BFP, FLOAT_QUAT_NORMALIZE, FLOAT_VECT3_NORMALIZE, FloatQuat::qi, QUAT_ASSIGN, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ahrs_align(), ahrs_float_get_quat_from_accel_mag(), and ahrs_int_get_quat_from_accel().
static void ahrs_float_get_quat_from_accel_mag (struct FloatQuat * q, struct Int32Vect3 * accel, struct Int32Vect3 * mag) inline static
Definition at line 86 of file ahrs_float_utils.h.
References ahrs_float_get_quat_from_accel(), AHRS_H_X, AHRS_H_Y, FLOAT_QUAT_COMP_NORM_SHORTEST, FLOAT_QUAT_NORMALIZE, FLOAT_RMAT_OF_QUAT, FLOAT_RMAT_VECT3_TRANSP_MUL, MAGS_FLOAT_OF_BFP, FloatQuat::qi, QUAT_ASSIGN, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, SQUARE, FloatVect3::x, and FloatVect3::y.
Referenced by ahrs_align(), and ahrs_int_get_quat_from_accel_mag().