Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_float_dcm.c File Reference
ahrs_float_dcm.c File Reference
Attitude estimation for fixedwings based on the DCM Theory: http://code.google.com/p/gentlenav/downloads/list file DCMDraft2.pdf.
#include "std.h"
#include "subsystems/ahrs.h"
#include "subsystems/ahrs/ahrs_float_dcm.h"
#include "subsystems/ahrs/ahrs_float_utils.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "subsystems/imu.h"
#include "firmwares/fixedwing/autopilot.h"
#include "subsystems/ahrs/ahrs_float_dcm_algebra.h"
#include "math/pprz_algebra_float.h"
#include "state.h"
#include "subsystems/gps.h"
#include <string.h>
#include "led.h"
Macros
#define INS_ROLL_NEUTRAL_DEFAULT 0
#define INS_PITCH_NEUTRAL_DEFAULT 0
Functions
static void compute_ahrs_representations (void)
static void set_body_orientation_and_rates (void)
static void set_dcm_matrix_from_rmat (struct FloatRMat *rmat)
void Normalize (void)
void Drift_correction (void)
void Matrix_update (void)
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Variables
float ins_roll_neutral = INS_ROLL_NEUTRAL_DEFAULT
float ins_pitch_neutral = INS_PITCH_NEUTRAL_DEFAULT
struct AhrsFloatDCM ahrs_impl
const float G_Dt = 1. / ((float) AHRS_PROPAGATE_FREQUENCY)
struct FloatVect3 accel_float = {0,0,0}
float Omega_Vector [3] = {0,0,0}
float Omega_P [3] = {0,0,0}
float Omega_I [3] = {0,0,0}
float Omega [3] = {0,0,0}
float DCM_Matrix [3][3] = {{1,0,0},{0,1,0},{0,0,1}}
float Update_Matrix [3][3] = {{0,1,2},{3,4,5},{6,7,8}}
float Temporary_Matrix [3][3] = {{0,0,0},{0,0,0},{0,0,0}}
float MAG_Heading_X = 1
float MAG_Heading_Y = 0
Detailed Description
Attitude estimation for fixedwings based on the DCM Theory: http://code.google.com/p/gentlenav/downloads/list file DCMDraft2.pdf.
Options: -USE_HIGH_ACCEL_FLAG: no compensation when high accelerations present -USE_MAGNETOMETER_ONGROUND: use magnetic compensation before takeoff only while GPS course not good -USE_AHRS_GPS_ACCELERATIONS: forward acceleration compensation from GPS speed
Definition in file ahrs_float_dcm.c.
Macro Definition Documentation
#define INS_PITCH_NEUTRAL_DEFAULT 0
Definition at line 65 of file ahrs_float_dcm.c.
Referenced by ahrs_init(), ArduIMU_init(), and xsens_init().
#define INS_ROLL_NEUTRAL_DEFAULT 0
Definition at line 62 of file ahrs_float_dcm.c.
Referenced by ahrs_init(), ArduIMU_init(), and xsens_init().
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 164 of file ahrs_float_dcm.c.
References ahrs, ahrs_aligner, ahrs_float_get_euler_from_accel_mag(), ahrs_impl, AHRS_RUNNING, FLOAT_RMAT_OF_EULERS, AhrsFloatCmpl::gyro_bias, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, RATES_COPY, RATES_FLOAT_OF_BFP, set_body_orientation_and_rates(), set_dcm_matrix_from_rmat(), and Ahrs::status.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 134 of file ahrs_float_dcm.c.
References ahrs, ahrs_impl, AHRS_UNINIT, AhrsFloatCmpl::body_to_imu_rmat, EULERS_COPY, FALSE, FLOAT_RATES_ZERO, FLOAT_RMAT_OF_EULERS, high_accel_done, high_accel_flag, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, AhrsFloatCmpl::imu_rate, set_dcm_matrix_from_rmat(), and Ahrs::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 188 of file ahrs_float_dcm.c.
References ahrs_impl, compute_ahrs_representations(), Imu::gyro, AhrsFloatCmpl::gyro_bias, imu, AhrsFloatCmpl::imu_rate, Matrix_update(), Normalize(), FloatRates::p, FloatRates::q, FloatRates::r, RATES_DIFF, and RATES_FLOAT_OF_BFP.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 244 of file ahrs_float_dcm.c.
References Imu::accel, ACCELS_FLOAT_OF_BFP, ahrs_impl, Drift_correction(), imu, Omega, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 219 of file ahrs_float_dcm.c.
References ahrs_impl, GpsState::course, FALSE, GpsState::fix, gps, GPS_FIX_3D, GpsState::gspeed, GpsState::speed_3d, and TRUE.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 275 of file ahrs_float_dcm.c.
References ahrs_impl, DefaultChannel, DefaultDevice, imu, Imu::mag, MAG_Heading_X, MAG_Heading_Y, FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, FloatVect3::z, and Int32Vect3::z.
static void compute_ahrs_representations (void) inline static
Definition at line 591 of file ahrs_float_dcm.c.
References ahrs_impl, DCM_Matrix, GRAVITY, set_body_orientation_and_rates(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ahrs_propagate().
void Drift_correction (void)
Definition at line 411 of file ahrs_float_dcm.c.
References ahrs_impl, commands, DCM_Matrix, FALSE, GRAVITY, high_accel_done, high_accel_flag, HIGH_ACCEL_HIGH_THRUST, HIGH_ACCEL_HIGH_THRUST_RESUME, HIGH_ACCEL_LOW_SPEED, imu, imu_health, Ki_ROLLPITCH, Ki_YAW, Kp_ROLLPITCH, Kp_YAW, launch, Imu::mag, MAG_Heading_X, MAG_Heading_Y, Omega_I, Omega_P, stateGetHorizontalSpeedNorm_f(), TRUE, Vector_Add(), Vector_Cross_Product(), Vector_Dot_Product(), Vector_Scale(), FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, and FloatVect3::z.
Referenced by ahrs_update_accel().
void Matrix_update (void)
Definition at line 528 of file ahrs_float_dcm.c.
References ahrs_impl, DCM_Matrix, G_Dt, AhrsFloatCmpl::imu_rate, Matrix_Multiply(), Omega, Omega_I, Omega_P, Omega_Vector, FloatRates::p, FloatRates::q, FloatRates::r, Temporary_Matrix, Update_Matrix, Vector_Add(), FloatVect3::x, and FloatVect3::y.
Referenced by ahrs_propagate().
void Normalize (void)
Definition at line 330 of file ahrs_float_dcm.c.
References ahrs_impl, AhrsFloatCmpl::body_to_imu_rmat, DCM_Matrix, FALSE, renorm_blowup_count, renorm_sqrt_count, set_dcm_matrix_from_rmat(), TRUE, Vector_Add(), Vector_Cross_Product(), Vector_Dot_Product(), and Vector_Scale().
Referenced by ahrs_propagate().
static void set_body_orientation_and_rates (void) inline static
Definition at line 569 of file ahrs_float_dcm.c.
References ahrs_impl, AhrsFloatCmpl::body_to_imu_rmat, FLOAT_EULERS_OF_RMAT, FLOAT_RMAT_COMP_INV, FLOAT_RMAT_OF_EULERS, FLOAT_RMAT_TRANSP_RATEMULT, AhrsFloatCmpl::imu_rate, ins_pitch_neutral, ins_roll_neutral, FloatEulers::phi, stateSetBodyRates_f(), stateSetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by ahrs_align(), and compute_ahrs_representations().
static void set_dcm_matrix_from_rmat (struct FloatRMat * rmat) inline static
Definition at line 124 of file ahrs_float_dcm.c.
References DCM_Matrix, and RMAT_ELMT.
Referenced by ahrs_align(), ahrs_init(), and Normalize().
Variable Documentation
struct FloatVect3 accel_float = {0,0,0}
Definition at line 81 of file ahrs_float_dcm.c.
struct AhrsFloatDCM ahrs_impl
Definition at line 71 of file ahrs_float_dcm.c.
float DCM_Matrix[3][3] = {{1,0,0},{0,1,0},{0,0,1}}
Definition at line 88 of file ahrs_float_dcm.c.
Referenced by compute_ahrs_representations(), Drift_correction(), Matrix_update(), Normalize(), and set_dcm_matrix_from_rmat().
const float G_Dt = 1. / ((float) AHRS_PROPAGATE_FREQUENCY)
Definition at line 79 of file ahrs_float_dcm.c.
Referenced by Matrix_update().
float ins_pitch_neutral = INS_PITCH_NEUTRAL_DEFAULT
Definition at line 68 of file ahrs_float_dcm.c.
float ins_roll_neutral = INS_ROLL_NEUTRAL_DEFAULT
Todo:
harmonize infrared neutrals with ins_neutrals or get rid of ins neutrals this ins only needed for sim right now
Definition at line 67 of file ahrs_float_dcm.c.
float MAG_Heading_X = 1
Definition at line 93 of file ahrs_float_dcm.c.
Referenced by ahrs_update_mag(), and Drift_correction().
float MAG_Heading_Y = 0
Definition at line 94 of file ahrs_float_dcm.c.
Referenced by ahrs_update_mag(), and Drift_correction().
float Omega[3] = {0,0,0}
Definition at line 86 of file ahrs_float_dcm.c.
Referenced by ahrs_update_accel(), and Matrix_update().
float Omega_I[3] = {0,0,0}
Definition at line 85 of file ahrs_float_dcm.c.
Referenced by Drift_correction(), and Matrix_update().
float Omega_P[3] = {0,0,0}
Definition at line 84 of file ahrs_float_dcm.c.
Referenced by Drift_correction(), and Matrix_update().
float Omega_Vector[3] = {0,0,0}
Definition at line 83 of file ahrs_float_dcm.c.
Referenced by Matrix_update().
float Temporary_Matrix[3][3] = {{0,0,0},{0,0,0},{0,0,0}}
Definition at line 90 of file ahrs_float_dcm.c.
Referenced by Matrix_update().
float Update_Matrix[3][3] = {{0,1,2},{3,4,5},{6,7,8}}
Definition at line 89 of file ahrs_float_dcm.c.
Referenced by Matrix_update().