Paparazzi UAS: sw/airborne/modules/ins/alt_filter.h File Reference
alt_filter.h File Reference
Data Structures
struct TypeKalman
Defines
#define KALT_N_ETAT 3
Functions
void alt_filter_init (void)
void alt_filter_periodic (void)
Variables
TypeKalman alt_filter
Define Documentation
#define KALT_N_ETAT 3
Definition at line 36 of file alt_filter.h.
Function Documentation
void alt_filter_init (void)
Definition at line 52 of file alt_filter.c.
References kalmanInit(), last_baro_alt, last_gps_alt, MarcheAleaAccelerometre, MarcheAleaBiaisAltimetre, SigAltiAltimetre, and SigAltiGPS.
void alt_filter_periodic (void)
Definition at line 63 of file alt_filter.c.
References baro_ets_altitude, DefaultChannel, DefaultDevice, gps, GpsFixValid, GpsState::hmsl, kalmanCorrectionAltimetre(), kalmanCorrectionGPS(), kalmanEstimation(), last_baro_alt, last_gps_alt, TypeKalman::P, and TypeKalman::X.
Variable Documentation
TypeKalman alt_filter
Definition at line 34 of file alt_filter.c.