Paparazzi UAS: sw/airborne/modules/enose/anemotaxis.h File Reference
anemotaxis.h File Reference
#include "std.h"
Functions
bool_t nav_anemotaxis_downwind (uint8_t c, float radius)
bool_t nav_anemotaxis_init (uint8_t c)
bool_t nav_anemotaxis (uint8_t c, uint8_t c1, uint8_t c2, uint8_t plume)
Function Documentation
bool_t nav_anemotaxis (uint8_t c, uint8_t c1, uint8_t c2, uint8_t plume)
Not null even if wind_east=wind_north=0
Definition at line 39 of file anemotaxis.c.
References c, c1, c2, chemo_sensor, CROSSWIND, DEFAULT_CIRCLE_RADIUS, last_plume, last_plume_was_here(), Max, nav_init_stage(), NavApproaching, NavCircleWaypoint, NavQdrCloseTo, NavSegment, sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), TRUE, UTURN, waypoints, point::x, FloatVect2::x, EnuCoor_f::x, EnuCoor_i::x, point::y, FloatVect2::y, EnuCoor_f::y, and EnuCoor_i::y.
bool_t nav_anemotaxis_downwind (uint8_t c, float radius)
Definition at line 20 of file anemotaxis.c.
References c, FALSE, stateGetHorizontalWindspeed_f(), waypoints, FloatVect2::x, EnuCoor_i::x, FloatVect2::y, and EnuCoor_i::y.
bool_t nav_anemotaxis_init (uint8_t c)
Definition at line 28 of file anemotaxis.c.
References c, DEFAULT_CIRCLE_RADIUS, FALSE, last_plume_was_here(), sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), UTURN, waypoints, FloatVect2::x, EnuCoor_f::x, EnuCoor_i::x, FloatVect2::y, EnuCoor_f::y, and EnuCoor_i::y.