Paparazzi UAS: sw/airborne/arch/lpc21/subsystems/datalink/audio_telemetry_hw.h File Reference
audio_telemetry_hw.h File Reference
#include "LPC21xx.h"
#include <BOARD_CONFIG>
Macros
#define SAMPLES_PER_PERIOD 4
#define SAMPLE_PERIOD (PCLK/4762/SAMPLES_PER_PERIOD/T1_PCLK_DIV)
#define AUDIO_TELEMETRY_CHECK_RUNNING() {}
Functions
void TIMER1_ISR (void)
static void audio_telemetry_init (void)
Macro Definition Documentation
#define AUDIO_TELEMETRY_CHECK_RUNNING () {}
Definition at line 56 of file audio_telemetry_hw.h.
#define SAMPLE_PERIOD (PCLK/4762/SAMPLES_PER_PERIOD/T1_PCLK_DIV)
Definition at line 29 of file audio_telemetry_hw.h.
Referenced by audio_telemetry_init().
#define SAMPLES_PER_PERIOD 4
Definition at line 28 of file audio_telemetry_hw.h.
Referenced by TIMER1_ISR().
Function Documentation
static void audio_telemetry_init (void) inline static
Definition at line 31 of file audio_telemetry_hw.h.
References PINSEL1, SAMPLE_PERIOD, T1MCR, T1MR0, T1PR, T1TCR, TCR_ENABLE, TCR_RESET, TIMER1_ISR(), TMCR_MR0_I, TMCR_MR0_R, VIC_BIT, VIC_ENABLE, VIC_TIMER1, VICIntEnable, VICIntSelect, VICVectAddr1, and VICVectCntl1.
Referenced by init_ap().
void TIMER1_ISR (void)
Definition at line 62 of file audio_telemetry_hw.c.
References audio_telemetry_phase, audio_telemetry_sample, audio_telemetry_sample_idx, DACR, get_next_bit(), ISR_ENTRY, ISR_EXIT, SAMPLES_PER_PERIOD, T1IR, TIR_MR0I, and VICVectAddr.
Referenced by audio_telemetry_init().