Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot_arming_switch.h File Reference
autopilot_arming_switch.h File Reference
Arm the motors using a switch.
#include "autopilot_rc_helpers.h"
Enumerations
enum arming_state {
STATE_UNINIT, STATE_WAITING, STATE_STARTABLE, STATE_MOTORS_ON,
STATUS_MOTORS_OFF, STATUS_M_OFF_STICK_PUSHED, STATUS_START_MOTORS, STATUS_MOTORS_ON,
STATUS_M_ON_STICK_PUSHED, STATUS_STOP_MOTORS
}
Functions
static void autopilot_arming_init (void)
static void autopilot_arming_set (bool_t motors_on)
static void autopilot_arming_check_motors_on (void)
State machine to check if motors should be turned ON or OFF using the kill switch.
Variables
enum arming_state autopilot_arming_state
bool_t autopilot_unarmed_in_auto
Detailed Description
Arm the motors using a switch.
Definition in file autopilot_arming_switch.h.
Enumeration Type Documentation
enum arming_state
Enumerator:
STATE_UNINIT
STATE_WAITING
STATE_STARTABLE
STATE_MOTORS_ON
STATUS_MOTORS_OFF
STATUS_M_OFF_STICK_PUSHED
STATUS_START_MOTORS
STATUS_MOTORS_ON
STATUS_M_ON_STICK_PUSHED
STATUS_STOP_MOTORS
Definition at line 38 of file autopilot_arming_switch.h.
Function Documentation
static void autopilot_arming_check_motors_on (void) inline static
State machine to check if motors should be turned ON or OFF using the kill switch.
If kill switch is off during startup (unkilled), you need to kill again first, then unkill to start. Also to start the motors, throttle needs to be down, other sticks centered, AHRS aligned and you need be in manual mode.
Definition at line 78 of file autopilot_arming_switch.h.
References autopilot_arming_state, autopilot_mode, autopilot_motors_on, autopilot_unarmed_in_auto, FALSE, kill_switch_is_on(), MODE_MANUAL, rc_attitude_sticks_centered(), STATE_MOTORS_ON, STATE_STARTABLE, STATE_UNINIT, STATE_WAITING, THROTTLE_STICK_DOWN, and TRUE.
Referenced by autopilot_on_rc_frame().
static void autopilot_arming_init (void) inline static
Definition at line 48 of file autopilot_arming_switch.h.
References autopilot_arming_state, autopilot_unarmed_in_auto, FALSE, and STATE_UNINIT.
Referenced by autopilot_init().
static void autopilot_arming_set (bool_t motors_on) inline static
Definition at line 53 of file autopilot_arming_switch.h.
References autopilot_arming_state, autopilot_mode, autopilot_unarmed_in_auto, FALSE, MODE_MANUAL, STATE_MOTORS_ON, STATE_STARTABLE, and TRUE.
Referenced by autopilot_set_motors_on().
Variable Documentation
enum arming_state autopilot_arming_state
Definition at line 45 of file autopilot_arming_switch.h.
Referenced by autopilot_arming_check_motors_on(), autopilot_arming_init(), and autopilot_arming_set().
bool_t autopilot_unarmed_in_auto
Definition at line 46 of file autopilot_arming_switch.h.
Referenced by autopilot_arming_check_motors_on(), autopilot_arming_init(), and autopilot_arming_set().