Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot_rc_helpers.h File Reference
autopilot_rc_helpers.h File Reference
Some helper functions to check RC sticks.
#include "generated/airframe.h"
#include "subsystems/radio_control.h"
Macros
#define AUTOPILOT_THROTTLE_THRESHOLD (MAX_PPRZ / 20)
#define AUTOPILOT_YAW_THRESHOLD (MAX_PPRZ * 19 / 20)
#define AUTOPILOT_STICK_CENTER_THRESHOLD (MAX_PPRZ * 1 / 20)
#define THROTTLE_STICK_DOWN() (radio_control.values[RADIO_THROTTLE] < AUTOPILOT_THROTTLE_THRESHOLD)
#define YAW_STICK_PUSHED()
#define YAW_STICK_CENTERED()
#define PITCH_STICK_CENTERED()
#define ROLL_STICK_CENTERED()
Functions
static bool_t rc_attitude_sticks_centered (void)
static bool_t kill_switch_is_on (void)
static uint8_t percent_from_rc (int channel)
Detailed Description
Some helper functions to check RC sticks.
Definition in file autopilot_rc_helpers.h.
Macro Definition Documentation
#define AUTOPILOT_STICK_CENTER_THRESHOLD (MAX_PPRZ * 1 / 20)
Definition at line 37 of file autopilot_rc_helpers.h.
#define AUTOPILOT_THROTTLE_THRESHOLD (MAX_PPRZ / 20)
Definition at line 34 of file autopilot_rc_helpers.h.
#define AUTOPILOT_YAW_THRESHOLD (MAX_PPRZ * 19 / 20)
Definition at line 35 of file autopilot_rc_helpers.h.
#define PITCH_STICK_CENTERED ()
Value:
(radio_control.values[RADIO_PITCH] < AUTOPILOT_STICK_CENTER_THRESHOLD && \
   radio_control.values[RADIO_PITCH] > -AUTOPILOT_STICK_CENTER_THRESHOLD)
Definition at line 48 of file autopilot_rc_helpers.h.
Referenced by rc_attitude_sticks_centered().
#define ROLL_STICK_CENTERED ()
Value:
(radio_control.values[RADIO_ROLL] < AUTOPILOT_STICK_CENTER_THRESHOLD && \
   radio_control.values[RADIO_ROLL] > -AUTOPILOT_STICK_CENTER_THRESHOLD)
Definition at line 51 of file autopilot_rc_helpers.h.
Referenced by rc_attitude_sticks_centered().
#define THROTTLE_STICK_DOWN () (radio_control.values[RADIO_THROTTLE] < AUTOPILOT_THROTTLE_THRESHOLD)
Definition at line 40 of file autopilot_rc_helpers.h.
Referenced by autopilot_arming_check_motors_on(), and autopilot_check_in_flight().
#define YAW_STICK_CENTERED ()
Value:
(radio_control.values[RADIO_YAW] < AUTOPILOT_STICK_CENTER_THRESHOLD && \
   radio_control.values[RADIO_YAW] > -AUTOPILOT_STICK_CENTER_THRESHOLD)
Definition at line 45 of file autopilot_rc_helpers.h.
Referenced by rc_attitude_sticks_centered().
#define YAW_STICK_PUSHED ()
Value:
(radio_control.values[RADIO_YAW] > AUTOPILOT_YAW_THRESHOLD ||  \
   radio_control.values[RADIO_YAW] < -AUTOPILOT_YAW_THRESHOLD)
Definition at line 42 of file autopilot_rc_helpers.h.
Referenced by autopilot_arming_check_motors_on().
Function Documentation
static bool_t kill_switch_is_on (void) inline static
Definition at line 67 of file autopilot_rc_helpers.h.
References FALSE.
Referenced by autopilot_arming_check_motors_on(), and autopilot_on_rc_frame().
static uint8_t percent_from_rc (int channel) inline static
Definition at line 72 of file autopilot_rc_helpers.h.
References MAX_PPRZ, radio_control, and RadioControl::values.
static bool_t rc_attitude_sticks_centered (void) inline static
Definition at line 55 of file autopilot_rc_helpers.h.
References PITCH_STICK_CENTERED, ROLL_STICK_CENTERED, and YAW_STICK_CENTERED.
Referenced by autopilot_arming_check_motors_on().