Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot.c File Reference
autopilot.c File Reference
#include "firmwares/rotorcraft/autopilot.h"
#include "subsystems/radio_control.h"
#include "subsystems/gps.h"
#include "firmwares/rotorcraft/commands.h"
#include "firmwares/rotorcraft/navigation.h"
#include "firmwares/rotorcraft/guidance.h"
#include "firmwares/rotorcraft/stabilization.h"
#include "led.h"
#include "subsystems/ahrs.h"
#include "autopilot_arming_yaw.h"
Defines
#define AUTOPILOT_IN_FLIGHT_TIME 40
Functions
static int ahrs_is_aligned (void)
void autopilot_init (void)
void autopilot_periodic (void)
void autopilot_set_mode (uint8_t new_autopilot_mode)
static void autopilot_check_in_flight (bool_t motors_on)
void autopilot_set_motors_on (bool_t motors_on)
void autopilot_on_rc_frame (void)
Variables
uint8_t autopilot_mode
uint8_t autopilot_mode_auto2
bool_t autopilot_in_flight
uint32_t autopilot_in_flight_counter
uint16_t autopilot_flight_time
flight time in seconds.
bool_t autopilot_motors_on
bool_t kill_throttle
bool_t autopilot_rc
bool_t autopilot_power_switch
bool_t autopilot_detect_ground
bool_t autopilot_detect_ground_once
Define Documentation
#define AUTOPILOT_IN_FLIGHT_TIME 40
Definition at line 48 of file autopilot.c.
Referenced by autopilot_check_in_flight().
Function Documentation
static int ahrs_is_aligned (void) [inline, static]
Definition at line 52 of file autopilot.c.
References ahrs, AHRS_RUNNING, and Ahrs::status.
Referenced by autopilot_set_mode(), and autopilot_set_motors_on().
static void autopilot_check_in_flight (bool_t motors_on) [inline, static]
Definition at line 205 of file autopilot.c.
References autopilot_in_flight, autopilot_in_flight_counter, AUTOPILOT_IN_FLIGHT_TIME, FALSE, THROTTLE_STICK_DOWN, and TRUE.
Referenced by autopilot_on_rc_frame().
void autopilot_init (void)
Definition at line 69 of file autopilot.c.
References AP_MODE_KILL, autopilot_arming_init(), autopilot_detect_ground, autopilot_detect_ground_once, autopilot_flight_time, autopilot_in_flight, autopilot_in_flight_counter, autopilot_mode, autopilot_mode_auto2, autopilot_motors_on, autopilot_power_switch, autopilot_rc, FALSE, kill_throttle, LED_ON, MODE_AUTO2, POWER_SWITCH_LED, and TRUE.
Referenced by main_init().
void autopilot_on_rc_frame (void)
Definition at line 245 of file autopilot.c.
References AP_MODE_FAILSAFE, AP_MODE_KILL, AP_MODE_NAV, AP_MODE_OF_PPRZ, autopilot_arming_check_motors_on(), autopilot_check_in_flight(), autopilot_in_flight, autopilot_mode, autopilot_motors_on, autopilot_set_mode(), GpsIsLost(), guidance_h_read_rc(), guidance_v_read_rc(), kill_switch_is_on(), kill_throttle, radio_control, RADIO_MODE, and RadioControl::values.
Referenced by main_event(), and on_rc_message().
void autopilot_periodic (void)
Definition at line 88 of file autopilot.c.
References AP_MODE_FAILSAFE, AP_MODE_KILL, autopilot_detect_ground, autopilot_in_flight, autopilot_mode, autopilot_motors_on, autopilot_set_mode(), commands_failsafe, FALSE, guidance_h_run(), guidance_v_run(), nav_periodic_task(), NAV_PRESCALER, SetCommands, and stabilization_cmd.
Referenced by main_periodic().
void autopilot_set_mode (uint8_t new_autopilot_mode)
Definition at line 118 of file autopilot.c.
References ahrs_is_aligned(), AP_MODE_ATTITUDE_CLIMB, AP_MODE_ATTITUDE_DIRECT, AP_MODE_ATTITUDE_RC_CLIMB, AP_MODE_ATTITUDE_Z_HOLD, AP_MODE_FAILSAFE, AP_MODE_HOVER_CLIMB, AP_MODE_HOVER_DIRECT, AP_MODE_HOVER_Z_HOLD, AP_MODE_KILL, AP_MODE_NAV, AP_MODE_RATE_DIRECT, AP_MODE_RATE_RC_CLIMB, AP_MODE_RATE_Z_HOLD, AP_MODE_RC_DIRECT, autopilot_in_flight, autopilot_in_flight_counter, autopilot_mode, autopilot_set_motors_on(), FALSE, GUIDANCE_H_MODE_ATTITUDE, guidance_h_mode_changed(), GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_KILL, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_v_mode_changed(), GUIDANCE_V_MODE_CLIMB, GUIDANCE_V_MODE_HOVER, GUIDANCE_V_MODE_KILL, GUIDANCE_V_MODE_NAV, GUIDANCE_V_MODE_RC_CLIMB, GUIDANCE_V_MODE_RC_DIRECT, guidance_v_zd_sp, FloatEulers::phi, SPEED_BFP_OF_REAL, stab_att_sp_euler, and FloatEulers::theta.
Referenced by autopilot_on_rc_frame(), autopilot_periodic(), and failsafe_check().
void autopilot_set_motors_on (bool_t motors_on)
Definition at line 235 of file autopilot.c.
References ahrs_is_aligned(), autopilot_arming_set(), autopilot_motors_on, FALSE, kill_throttle, and TRUE.
Referenced by autopilot_set_mode().
Variable Documentation
bool_t autopilot_detect_ground
Definition at line 45 of file autopilot.c.
Referenced by autopilot_init(), autopilot_periodic(), DetectGroundEvent(), and nav_detect_ground().
bool_t autopilot_detect_ground_once
Definition at line 46 of file autopilot.c.
Referenced by autopilot_init(), and DetectGroundEvent().
uint16_t autopilot_flight_time
flight time in seconds.
Definition at line 37 of file autopilot.c.
Referenced by attitude_loop(), autopilot_init(), generic_com_periodic(), gsm_send_report_continue(), main_periodic(), monitor_task(), and telecommand_task().
bool_t autopilot_in_flight
Definition at line 35 of file autopilot.c.
Referenced by autopilot_check_in_flight(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), and main_periodic().
uint32_t autopilot_in_flight_counter
Definition at line 36 of file autopilot.c.
Referenced by autopilot_check_in_flight(), autopilot_init(), and autopilot_set_mode().
uint8_t autopilot_mode
Definition at line 32 of file autopilot.c.
Referenced by autopilot_arming_check_motors_on(), autopilot_arming_set(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), DetectGroundEvent(), and failsafe_check().
uint8_t autopilot_mode_auto2
Definition at line 33 of file autopilot.c.
Referenced by autopilot_init().
bool_t autopilot_motors_on
Definition at line 39 of file autopilot.c.
Referenced by autopilot_arming_check_motors_on(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_motors_on(), and main_periodic().
bool_t autopilot_power_switch
Definition at line 43 of file autopilot.c.
Referenced by autopilot_init().
bool_t autopilot_rc
Definition at line 42 of file autopilot.c.
Referenced by autopilot_init(), and main_event().
bool_t kill_throttle
Definition at line 40 of file autopilot.c.
Referenced by attitude_loop(), autopilot_init(), autopilot_on_rc_frame(), autopilot_set_motors_on(), BungeeTakeoff(), InitializeBungeeTakeoff(), monitor_task(), and SkidLanding().