Paparazzi UAS: sw/airborne/modules/sensors/baro_board_module.c File Reference
baro_board_module.c File Reference
#include "modules/sensors/baro_board_module.h"
Macros
#define BARO_STARTUP_COUNTER 200
Functions
void baro_init (void)
Implementation of the generic baro interface initialization.
void baro_periodic (void)
Implementation of the generic baro interface periodic task.
Variables
struct Baro baro
Generic barometer interface, assuming the barometer is read through Aspirin IMU directly.
uint16_t startup_cnt
Macro Definition Documentation
#define BARO_STARTUP_COUNTER 200
Definition at line 34 of file baro_board_module.c.
Referenced by baro_init().
Function Documentation
void baro_init (void)
Implementation of the generic baro interface initialization.
No need to call this functions from the modules, already done by main.
Definition at line 40 of file baro_board_module.c.
References Baro::absolute, adc_buf_channel(), ADC_CHANNEL_BARO, baro, baro_board, BARO_STARTUP_COUNTER, BS_UNINITIALIZED, BaroBoard::buf, DACSet(), BaroBoard::data_available, DEFAULT_AV_NB_SAMPLE, Baro::differential, FALSE, LED_OFF, BaroBoard::offset, startup_cnt, Baro::status, and BaroBoard::value_filtered.
void baro_periodic (void)
Implementation of the generic baro interface periodic task.
No need to call this functions from the modules, already done by main.
Definition at line 50 of file baro_board_module.c.
References Baro::absolute, adc_buf::av_nb_sample, baro, baro_board, baro_board_calibrate(), BS_RUNNING, BS_UNINITIALIZED, BaroBoard::buf, BaroBoard::data_available, startup_cnt, Baro::status, adc_buf::sum, TRUE, and BaroBoard::value_filtered.
Variable Documentation
struct Baro baro
Generic barometer interface, assuming the barometer is read through Aspirin IMU directly.
Edit by: Michal Podhradsky, micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu Utah State University, http://aggieair.usu.edu/
Definition at line 31 of file baro_board_module.c.
uint16_t startup_cnt
Definition at line 35 of file baro_board_module.c.