Paparazzi UAS: sw/airborne/boards/lisa_m/baro_ms5611_spi.c File Reference
baro_ms5611_spi.c File Reference
#include "subsystems/sensors/baro.h"
#include "peripherals/ms5611.h"
#include "led.h"
#include "std.h"
#include "mcu_periph/sys_time.h"
#include "mcu_periph/spi.h"
Macros
#define MS5611_SPI_DEV spi2
Measurement Specialties (Intersema) MS5611-01BA pressure/temperature sensor interface for I2C.
#define MS5611_BUFFER_LENGTH 4
Functions
static void trans_cb_ms5611 (struct spi_transaction *trans)
static int8_t baro_ms5611_crc (uint16_t *prom)
void baro_init (void)
void baro_periodic (void)
void baro_event (void(*b_abs_handler)(void), void(*b_diff_handler)(void))
Variables
struct Baro baro
struct spi_transaction ms5611_trans
uint8_t ms5611_status
int32_t prom_cnt
uint16_t ms5611_c [PROM_NB]
uint32_t ms5611_d1
uint32_t ms5611_d2
float fbaroms
float ftempms
volatile uint8_t input_buf_ms5611 [MS5611_BUFFER_LENGTH]
volatile uint8_t output_buf_ms5611 [MS5611_BUFFER_LENGTH]
Macro Definition Documentation
#define MS5611_BUFFER_LENGTH 4
Definition at line 17 of file baro_ms5611_spi.c.
Referenced by baro_init().
#define MS5611_SPI_DEV spi2
Measurement Specialties (Intersema) MS5611-01BA pressure/temperature sensor interface for I2C.
Edit by: Michal Podhradsky, micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu Utah State University, http://aggieair.usu.edu/
Definition at line 15 of file baro_ms5611_spi.c.
Referenced by baro_event(), and baro_periodic().
Function Documentation
void baro_event (void(*)(void) b_abs_handler, void(*)(void) b_diff_handler)
Definition at line 130 of file baro_ms5611_spi.c.
References Baro::absolute, bmp085_baro_calibration::ac5, bmp085_baro_calibration::ac6, bmp085_baro_calibration::b5, baro, baro_apply_calibration(), baro_board, baro_init(), baro_ms5611_crc(), baro_trans, BMP085_OSS, BS_RUNNING, i2c_transaction::buf, calibration, DefaultChannel, DefaultDevice, Baro::differential, dt, fbaroms, ftempms, I2CTransPending, I2CTransRunning, I2CTransSuccess, LBS_READING, LBS_READING_TEMP, LBS_REQUEST, LBS_REQUEST_TEMP, bmp085_baro_calibration::mc, bmp085_baro_calibration::md, MS5611_ADC_D1, MS5611_ADC_D2, ms5611_c, MS5611_CONV_D2, ms5611_d1, ms5611_d2, MS5611_IDLE, MS5611_PROM, MS5611_PROM_READ, MS5611_RESET, MS5611_RESET_OK, MS5611_SPI_DEV, MS5611_START_CONV_D2, ms5611_status, ms5611_trans, prom_cnt, PROM_NB, spi_submit(), SPITransDone, SPITransSuccess, BaroBoard::status, Baro::status, i2c_transaction::status, and t2.
void baro_init (void)
Definition at line 63 of file baro_ms5611_spi.c.
References baro, BS_UNINITIALIZED, input_buf_ms5611, MS5611_BUFFER_LENGTH, MS5611_SLAVE_DEV, ms5611_status, ms5611_trans, MS5611_UNINIT, prom_cnt, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, Baro::status, and trans_cb_ms5611().
static int8_t baro_ms5611_crc (uint16_t * prom) static
Definition at line 39 of file baro_ms5611_spi.c.
References crc.
Referenced by baro_event().
void baro_periodic (void)
Definition at line 82 of file baro_ms5611_spi.c.
References DefaultChannel, DefaultDevice, MS5611_ADC_D1, MS5611_ADC_D2, MS5611_ADC_READ, ms5611_c, MS5611_CONV_D1, MS5611_CONV_D1_OK, MS5611_CONV_D2, MS5611_CONV_D2_OK, MS5611_IDLE, MS5611_PROM, MS5611_PROM_READ, MS5611_RESET, MS5611_RESET_OK, MS5611_SOFT_RESET, MS5611_SPI_DEV, MS5611_START_CONV_D1, ms5611_status, ms5611_trans, MS5611_UNINIT, sys_time::nb_sec, prom_cnt, and spi_submit().
static void trans_cb_ms5611 (struct spi_transaction * trans) static
Definition at line 57 of file baro_ms5611_spi.c.
References LED_TOGGLE.
Referenced by baro_init().
Variable Documentation
struct Baro baro
Definition at line 28 of file baro_ms5611_spi.c.
float fbaroms
Definition at line 34 of file baro_ms5611_spi.c.
float ftempms
Definition at line 34 of file baro_ms5611_spi.c.
volatile uint8_t input_buf_ms5611[MS5611_BUFFER_LENGTH]
Definition at line 35 of file baro_ms5611_spi.c.
Referenced by baro_init().
uint16_t ms5611_c[PROM_NB]
Definition at line 32 of file baro_ms5611_spi.c.
uint32_t ms5611_d1
Definition at line 33 of file baro_ms5611_spi.c.
uint32_t ms5611_d2
Definition at line 33 of file baro_ms5611_spi.c.
uint8_t ms5611_status
Definition at line 30 of file baro_ms5611_spi.c.
struct spi_transaction ms5611_trans
Definition at line 29 of file baro_ms5611_spi.c.
volatile uint8_t output_buf_ms5611[MS5611_BUFFER_LENGTH]
Definition at line 36 of file baro_ms5611_spi.c.
int32_t prom_cnt
Definition at line 31 of file baro_ms5611_spi.c.