Paparazzi UAS: sw/airborne/boards/booz/baro_board.h File Reference
baro_board.h File Reference
#include "std.h"
#include "subsystems/sensors/baro.h"
#include "mcu_periph/adc.h"
#include "mcu_periph/dac.h"
Data Structures
struct BaroBoard
Macros
#define BaroEvent(_b_abs_handler, _b_diff_handler)
Functions
void baro_board_calibrate (void)
static void baro_board_SetOffset (uint16_t _o)
Variables
struct BaroBoard baro_board
Macro Definition Documentation
#define BaroEvent (_b_abs_handler, _b_diff_handler)
Value:
{ \
    if (baro_board.data_available) {      \
      _b_abs_handler();         \
      baro_board.data_available = FALSE;    \
    }             \
  }
Definition at line 22 of file baro_board.h.
Referenced by event_task_ap(), main_event(), main_event_task(), and test_baro_event().
Function Documentation
void baro_board_calibrate (void)
Definition at line 68 of file baro_board.c.
References baro, baro_board, BOOZ_ANALOG_BARO_THRESHOLD, BS_RUNNING, DACSet(), LED_ON, LED_TOGGLE, BaroBoard::offset, Baro::status, and BaroBoard::value_filtered.
Referenced by baro_periodic().
static void baro_board_SetOffset (uint16_t _o) inline static
Definition at line 29 of file baro_board.h.
References baro_board, DACSet(), and BaroBoard::offset.
Variable Documentation
struct BaroBoard baro_board
Definition at line 35 of file baro_board.c.