Paparazzi UAS: sw/airborne/modules/cam_control/cam_track.h File Reference
cam_track.h File Reference
blob tracking with cmucam
#include <inttypes.h>
#include "math/pprz_algebra_float.h"
#include "mcu_periph/uart.h"
Macros
#define __CamLink(dev, _x) dev##_x
#define _CamLink(dev, _x) __CamLink(dev, _x)
#define CamLink(_x) _CamLink(CAM_LINK, _x)
#define CamBuffer() CamLink(ChAvailable())
#define ReadCamBuffer() { while (CamLink(ChAvailable())&&!cam_msg_received) parse_cam_buffer(CamLink(Getch())); }
#define CamUartSend1(c) CamLink(Transmit(c))
#define CamUartSetBaudrate(_b) CamLink(SetBaudrate(_b))
#define CamUartRunning CamLink(TxRunning)
#define CamEventCheckAndHandle()
Functions
void track_init (void)
void track_periodic_task (void)
void track_event (void)
void parse_cam_msg (void)
void parse_cam_buffer (uint8_t)
Variables
struct FloatVect3 target_pos_ned
struct FloatVect3 target_speed_ned
struct FloatVect3 target_accel_ned
volatile uint8_t cam_msg_received
Detailed Description
blob tracking with cmucam
Definition in file cam_track.h.
Macro Definition Documentation
#define __CamLink (dev, _x) dev##_x
Definition at line 48 of file cam_track.h.
#define _CamLink (dev, _x) __CamLink(dev, _x)
Definition at line 49 of file cam_track.h.
#define CamBuffer () CamLink(ChAvailable())
Definition at line 52 of file cam_track.h.
#define CamEventCheckAndHandle ()
Value:
{ \
  if (CamBuffer()) {          \
    ReadCamBuffer();          \
  }                           \
  if (cam_msg_received) {     \
    parse_cam_msg();          \
    track_event();            \
    cam_msg_received = FALSE; \
  }                           \
}
Definition at line 58 of file cam_track.h.
#define CamLink (_x) _CamLink(CAM_LINK, _x)
Definition at line 50 of file cam_track.h.
#define CamUartRunning CamLink(TxRunning)
Definition at line 56 of file cam_track.h.
#define CamUartSend1 (c) CamLink(Transmit(c))
Definition at line 54 of file cam_track.h.
Referenced by track_periodic_task().
#define CamUartSetBaudrate (_b) CamLink(SetBaudrate(_b))
Definition at line 55 of file cam_track.h.
#define ReadCamBuffer () { while (CamLink(ChAvailable())&&!cam_msg_received) parse_cam_buffer(CamLink(Getch())); }
Definition at line 53 of file cam_track.h.
Function Documentation
void parse_cam_buffer (uint8_t)
Definition at line 197 of file cam_track.c.
References c, cam_data_buf, cam_data_idx, cam_data_len, CAM_END, CAM_MAX_PAYLOAD, cam_msg_received, CAM_START_1, CAM_START_2, cam_status, GOT_DATA, GOT_LEN, GOT_START_1, GOT_START_2, TRUE, and UNINIT.
void parse_cam_msg (void)
Definition at line 164 of file cam_track.c.
References cam_data_buf, target_pos_ned, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
void track_event (void)
Definition at line 121 of file cam_track.c.
References ACCEL_BFP_OF_REAL, b2_hff_lost_counter, b2_hff_state, b2_hff_update_pos(), FALSE, Ins::hf_realign, ins, ins_ltp_accel, ins_ltp_initialised, ins_ltp_pos, ins_ltp_speed, INS_NED_TO_STATE, ins_realign_h(), last_pos_ned, POS_BFP_OF_REAL, SPEED_BFP_OF_REAL, stateSetPositionNed_i(), target_pos_ned, TRUE, VECT3_COPY, FloatVect2::x, FloatVect3::x, HfilterFloat::x, NedCoor_i::x, HfilterFloat::xdot, HfilterFloat::xdotdot, FloatVect2::y, FloatVect3::y, HfilterFloat::y, NedCoor_i::y, HfilterFloat::ydot, and HfilterFloat::ydotdot.
void track_init (void)
Definition at line 57 of file cam_track.c.
References CAM_DATA_LEN, cam_data_len, cam_status, ins_ltp_initialised, ins_update_on_agl, TRUE, and UNINIT.
void track_periodic_task (void)
Definition at line 67 of file cam_track.c.
References c, CamUartSend1, FloatEulers::phi, FloatEulers::psi, stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), FloatEulers::theta, and EnuCoor_f::z.
Variable Documentation
volatile uint8_t cam_msg_received
Definition at line 53 of file cam_track.c.
Referenced by parse_cam_buffer().
struct FloatVect3 target_accel_ned
Definition at line 34 of file cam_track.c.
struct FloatVect3 target_pos_ned
Definition at line 32 of file cam_track.c.
Referenced by parse_cam_msg(), and track_event().
struct FloatVect3 target_speed_ned
Definition at line 33 of file cam_track.c.