Paparazzi UAS: sw/airborne/mcu_periph/can.c File Reference
can.c File Reference
#include <stdint.h>
#include "mcu_periph/can.h"
#include "mcu_periph/can_arch.h"
Functions
void _can_run_rx_callback (uint32_t id, uint8_t *buf, uint8_t len)
void can_init (can_rx_callback_t callback)
int can_transmit (uint32_t id, const uint8_t *buf, uint8_t len)
Variables
can_rx_callback_t can_rx_callback
Function Documentation
void _can_run_rx_callback (uint32_t id, uint8_t * buf, uint8_t len)
Definition at line 45 of file can.c.
References can_rx_callback.
Referenced by usb_lp_can1_rx0_irq_handler().
void can_init (can_rx_callback_t callback)
Definition at line 34 of file can.c.
References can_hw_init(), and can_rx_callback.
int can_transmit (uint32_t id, const uint8_t * buf, uint8_t len)
Definition at line 40 of file can.c.
References can_hw_transmit().
Variable Documentation
can_rx_callback_t can_rx_callback
Definition at line 30 of file can.c.
Referenced by _can_run_rx_callback(), and can_init().