Paparazzi UAS: sw/airborne/modules/cartography/cartography.h File Reference
cartography.h File Reference
Functions
void init_carto (void)
Automatic survey of an oriented rectangle (defined by three points)
void periodic_downlink_carto (void)
void start_carto (void)
void stop_carto (void)
bool_t nav_survey_Inc_railnumberSinceBoot (void)
bool_t nav_survey_Snapshoot (void)
bool_t nav_survey_Snapshoot_Continu (void)
bool_t nav_survey_StopSnapshoot (void)
bool_t nav_survey_computefourth_corner (uint8_t wp1, uint8_t wp2, uint8_t wp3, uint8_t wp4)
bool_t nav_survey_losange_carto_init (uint8_t wp1, uint8_t wp2, uint8_t wp3, float distrail, float distplus)
bool_t nav_survey_losange_carto (void)
Variables
float distrailinteractif
Function Documentation
void init_carto (void)
Automatic survey of an oriented rectangle (defined by three points)
Definition at line 149 of file cartography.c.
bool_t nav_survey_computefourth_corner (uint8_t wp1, uint8_t wp2, uint8_t wp3, uint8_t wp4)
Definition at line 199 of file cartography.c.
References FALSE, nav_survey_computefourth_corner(), PRTDEB, PRTDEBSTR, waypoints, point::x, EnuCoor_i::x, point::y, and EnuCoor_i::y.
Referenced by nav_survey_computefourth_corner().
bool_t nav_survey_Inc_railnumberSinceBoot (void)
Definition at line 165 of file cartography.c.
References FALSE, and railnumberSinceBoot.
bool_t nav_survey_losange_carto (void)
Definition at line 407 of file cartography.c.
References angle_between, camera_snapshot_image_number, circleradiusmin, course_next_rail, distancefromrail, DISTLIMIT, distplus, distrail, DISTXY, FALSE, nav_route_xy(), nav_survey_ComputeProjectionOnLine(), nav_survey_losange_carto(), NavCircleWaypoint, norm12, norm13, normAM, normBM, numberofrailtodo, pointC, ProjectionInsideLimitOfRail, PRTDEB, PRTDEBSTR, railnumber, railnumberSinceBoot, signforturn, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), survey_losange_uturn, tempcircleradius, tempx, tempy, TRUE, UTURN, vec13, waypoints, point::x, EnuCoor_i::x, point::y, and EnuCoor_i::y.
Referenced by nav_survey_losange_carto().
bool_t nav_survey_losange_carto_init (uint8_t wp1, uint8_t wp2, uint8_t wp3, float distrail, float distplus)
Definition at line 309 of file cartography.c.
References angle1213, distplus, distrail, FALSE, norm12, norm13, NORMXY, numberofrailtodo, point3, PRTDEB, railnumber, railnumberSinceBoot, signforturn, survey_losange_uturn, vec13, waypoints, point::x, EnuCoor_i::x, point::y, and EnuCoor_i::y.
bool_t nav_survey_Snapshoot (void)
Definition at line 171 of file cartography.c.
References camera_snapshot_image_number, FALSE, PRTDEBSTR, and railnumberSinceBoot.
bool_t nav_survey_Snapshoot_Continu (void)
Definition at line 180 of file cartography.c.
References camera_snapshot_image_number, PRTDEBSTR, railnumberSinceBoot, and TRUE.
bool_t nav_survey_StopSnapshoot (void)
Definition at line 189 of file cartography.c.
References camera_snapshot_image_number, FALSE, and PRTDEBSTR.
void periodic_downlink_carto (void)
Definition at line 152 of file cartography.c.
References camera_snapshot_image_number, DefaultChannel, and DefaultDevice.
void start_carto (void)
Definition at line 156 of file cartography.c.
void stop_carto (void)
Definition at line 159 of file cartography.c.
Variable Documentation
float distrailinteractif
Definition at line 106 of file cartography.c.