Paparazzi UAS: sw/airborne/arch/lpc21/mcu_periph/dac_arch.h File Reference
dac_arch.h File Reference
LPC21 architecture
Handling of DAC hardware for lpc21xx.
#include "std.h"
#include "LPC21xx.h"
Functions
static void DACSet (uint16_t x)
Detailed Description
Handling of DAC hardware for lpc21xx.
Definition in file dac_arch.h.
Function Documentation
static void DACSet (uint16_t x) inline static
Definition at line 36 of file dac_arch.h.
References DACR.
Referenced by baro_board_calibrate(), baro_board_SetOffset(), and baro_init().