Paparazzi UAS: sw/airborne/subsystems/electrical.c File Reference
electrical.c File Reference
#include "subsystems/electrical.h"
#include "mcu_periph/adc.h"
#include "subsystems/commands.h"
#include "generated/airframe.h"
#include <BOARD_CONFIG>
Macros
#define VoltageOfAdc(adc) DefaultVoltageOfAdc(adc)
#define MilliAmpereOfAdc(adc) DefaultMilliAmpereOfAdc(adc)
#define CURRENT_ESTIMATION_NONLINEARITY 1.2
Functions
void electrical_init (void)
void electrical_periodic (void)
Variables
struct Electrical electrical
Macro Definition Documentation
#define CURRENT_ESTIMATION_NONLINEARITY 1.2
Definition at line 46 of file electrical.c.
Referenced by electrical_init().
#define MilliAmpereOfAdc (adc) DefaultMilliAmpereOfAdc(adc)
Definition at line 42 of file electrical.c.
Referenced by electrical_periodic().
#define VoltageOfAdc (adc) DefaultVoltageOfAdc(adc)
Definition at line 39 of file electrical.c.
Referenced by electrical_periodic().
Function Documentation
void electrical_init (void)
Definition at line 49 of file electrical.c.
References adc_buf_channel(), ADC_CHANNEL_VSUPPLY, Electrical::current, CURRENT_ESTIMATION_NONLINEARITY, DEFAULT_AV_NB_SAMPLE, electrical, and Electrical::vsupply.
Referenced by init_fbw(), and main_init().
void electrical_periodic (void)
Definition at line 66 of file electrical.c.
References commands, Electrical::current, electrical, MAX_PPRZ, MilliAmpereOfAdc, VoltageOfAdc, and Electrical::vsupply.
Referenced by handle_periodic_tasks(), handle_periodic_tasks_fbw(), and sim_periodic_task().
Variable Documentation
struct Electrical electrical
Definition at line 22 of file electrical.c.
Referenced by bat_checker_periodic(), electrical_init(), electrical_periodic(), ezcurrent_init(), ezcurrent_read_event(), generic_com_periodic(), and update_bat().