Paparazzi UAS: sw/airborne/modules/ins/fw_ins_vn100.c File Reference
fw_ins_vn100.c File Reference
#include "modules/ins/ins_vn100.h"
#include "mcu_periph/spi.h"
#include "state.h"
#include "generated/airframe.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
Defines
#define INS_YAW_NEUTRAL_DEFAULT 0.
driver for the VectorNav VN100 (Fixed-Wing part)
Functions
void ins_init (void)
INS initialization.
static bool_t ins_configure (void)
void ins_periodic (void)
INS periodic call.
void ins_event_task (void)
Define Documentation
#define INS_YAW_NEUTRAL_DEFAULT 0.
driver for the VectorNav VN100 (Fixed-Wing part)
Definition at line 35 of file fw_ins_vn100.c.
Referenced by ins_init().
Function Documentation
static bool_t ins_configure (void) [inline, static]
Definition at line 57 of file fw_ins_vn100.c.
References VN100_Req_Packet::CmdID, FALSE, ins_init_status, INS_VN100_READY, INS_VN100_SET_ADOF, INS_VN100_SET_ADOR, INS_VN100_SET_BAUD, last_received_packet, last_send_packet, VN100_Req_Packet::RegID, spi_buffer_input, spi_buffer_length, spi_buffer_output, TRUE, VN100_CmdID_WriteRegister, VN100_REG_ADOF, VN100_REG_ADOF_SIZE, VN100_REG_ADOR, VN100_REG_ADOR_SIZE, VN100_REG_SBAUD, and VN100_REG_SBAUD_SIZE.
Referenced by ins_periodic().
void ins_event_task (void)
Definition at line 109 of file fw_ins_vn100.c.
References FALSE, ins_eulers, ins_pitch_neutral, ins_rates, ins_roll_neutral, parse_ins_msg(), FloatEulers::phi, FloatEulers::psi, spi_message_received, stateSetNedToBodyEulers_f(), and FloatEulers::theta.
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 38 of file fw_ins_vn100.c.
Referenced by init_ap(), and main_init().
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 85 of file fw_ins_vn100.c.
Referenced by sensors_task().