Paparazzi UAS: sw/airborne/subsystems/navigation/gls.h File Reference
gls.h File Reference
gps landing system
#include "std.h"
#include "paparazzi.h"
Functions
bool_t gls_init (uint8_t _af, uint8_t _tod, uint8_t _td)
bool_t gls (uint8_t _af, uint8_t _tod, uint8_t _td)
Detailed Description
gps landing system
Definition in file gls.h.
Function Documentation
bool_t gls (uint8_t _af, uint8_t _tod, uint8_t _td)
Definition at line 125 of file gls.c.
References FALSE, init, Max, NavSegment, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), target_speed, TRUE, v_ctl_altitude_pgain, v_ctl_auto_airspeed_setpoint, WaypointAlt, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
bool_t gls_init (uint8_t _af, uint8_t _tod, uint8_t _td)
Definition at line 99 of file gls.c.
References app_angle, APP_ANGLE, app_intercept_af_tod, APP_INTERCEPT_AF_TOD, APP_TARGET_SPEED, FALSE, gls_compute_TOD(), init, target_speed, and TRUE.