Paparazzi UAS: sw/airborne/subsystems/gps/gps_nmea.h File Reference
gps_nmea.h File Reference
NMEA protocol specific code.
#include "mcu_periph/uart.h"
Data Structures
struct GpsNmea
Macros
#define GPS_NB_CHANNELS 16
#define NMEA_PRINT(...) {};
#define NMEA_MAXLEN 255
#define __GpsLink(dev, _x) dev##_x
#define _GpsLink(dev, _x) __GpsLink(dev, _x)
#define GpsLink(_x) _GpsLink(GPS_LINK, _x)
#define GpsBuffer() GpsLink(ChAvailable())
#define GpsEvent(_sol_available_callback)
#define ReadGpsBuffer()
#define gps_nmea_Reset(_val) { }
Functions
void nmea_parse_char (uint8_t c)
The function to be called when a characted friom the device is available.
void nmea_parse_msg (void)
parse_nmea_char() has a complete line.
Variables
struct GpsNmea gps_nmea
Detailed Description
NMEA protocol specific code.
Definition in file gps_nmea.h.
Macro Definition Documentation
#define GpsEvent (_sol_available_callback)
Value:
{        \
    if (GpsBuffer()) {                             \
      ReadGpsBuffer();                             \
    }                                              \
    if (gps_nmea.msg_available) {                  \
      nmea_parse_msg();          \
      if (gps_nmea.pos_available) {      \
        if (gps.fix == GPS_FIX_3D) {               \
          gps.last_fix_ticks = cpu_time_ticks;     \
          gps.last_fix_time = sys_time.nb_sec;        \
        }                                          \
        _sol_available_callback();                 \
      }                                            \
      gps_nmea.msg_available = FALSE;               \
    }                                              \
  }
Definition at line 64 of file gps_nmea.h.
#define ReadGpsBuffer ()
Value:
{         \
    while (GpsLink(ChAvailable())&&!gps_nmea.msg_available) \
      nmea_parse_char(GpsLink(Getch()));      \
  }
Definition at line 81 of file gps_nmea.h.
Function Documentation
void nmea_parse_char (uint8_t c)
The function to be called when a characted friom the device is available.
The function to be called when a characted friom the device is available.
It reads one character at a time setting gps_nmea.msg_available to TRUE after a full line.
Definition at line 410 of file gps_nmea.c.
References GpsNmea::msg_buf.
void nmea_parse_msg (void)
parse_nmea_char() has a complete line.
Find out what type of message it is and hand it to the parser for that type.
Definition at line 371 of file gps_nmea.c.
References GpsNmea::msg_buf, parse_nmea_GPGGA(), parse_nmea_GPGSA(), and parse_nmea_GPRMC().