Paparazzi UAS: sw/airborne/subsystems/gps/gps_nmea.c File Reference
gps_nmea.c File Reference
Parser for the NMEA protocol.
#include "subsystems/gps.h"
#include "led.h"
#include "math/pprz_geodetic_float.h"
#include <inttypes.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
Functions
void parse_nmea_GPGSA (void)
parse GPGSA-nmea-messages stored in nmea_msg_buf .
void parse_nmea_GPRMC (void)
parse GPRMC-nmea-messages stored in gps_nmea.msg_buf .
void parse_nmea_GPGGA (void)
parse GPGGA-nmea-messages stored in gps_nmea.msg_buf .
void gps_impl_init (void)
void nmea_parse_msg (void)
parse_nmea_char() has a complete line.
void nmea_parse_char (uint8_t c)
This is the actual parser.
Variables
struct GpsNmea gps_nmea
Detailed Description
Parser for the NMEA protocol.
TODO: THIS NMEA-PARSER IS NOT WELL TESTED AND INCOMPLETE!!! Status: Parsing GGA and RMC is complete, GSA and other records are incomplete.
Definition in file gps_nmea.c.
Function Documentation
void gps_impl_init (void)
Definition at line 61 of file gps_nmea.c.
References FALSE, GpsNmea::gps_nb_ovrn, gps_nmea, GpsNmea::msg_available, GpsNmea::msg_len, and GpsNmea::pos_available.
void nmea_parse_char (uint8_t c)
This is the actual parser.
The function to be called when a characted friom the device is available.
It reads one character at a time setting gps_nmea.msg_available to TRUE after a full line.
Definition at line 410 of file gps_nmea.c.
References c, gps_nmea, GpsNmea::msg_available, GpsNmea::msg_buf, GpsNmea::msg_len, NMEA_MAXLEN, and TRUE.
void nmea_parse_msg (void)
parse_nmea_char() has a complete line.
Find out what type of message it is and hand it to the parser for that type.
Definition at line 371 of file gps_nmea.c.
References gps_nmea, GpsNmea::msg_buf, GpsNmea::msg_len, NMEA_PRINT, parse_nmea_GPGGA(), parse_nmea_GPGSA(), and parse_nmea_GPRMC().
void parse_nmea_GPGGA (void)
parse GPGGA-nmea-messages stored in gps_nmea.msg_buf .
Definition at line 193 of file gps_nmea.c.
References LlaCoor_f::alt, LlaCoor_i::alt, UtmCoor_i::alt, UtmCoor_f::east, UtmCoor_i::east, ecef_of_lla_f(), GpsState::ecef_pos, FALSE, gps, gps_nmea, GpsState::hmsl, LlaCoor_f::lat, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_f::lon, LlaCoor_i::lon, GpsNmea::msg_buf, GpsNmea::msg_len, nav_utm_zone0, NMEA_PRINT, UtmCoor_f::north, UtmCoor_i::north, GpsState::num_sv, GpsState::pdop, GpsNmea::pos_available, GpsState::tow, TRUE, utm_of_lla_f(), GpsState::utm_pos, EcefCoor_f::x, EcefCoor_i::x, EcefCoor_f::y, EcefCoor_i::y, EcefCoor_f::z, EcefCoor_i::z, UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by nmea_parse_msg().
void parse_nmea_GPGSA (void)
parse GPGSA-nmea-messages stored in nmea_msg_buf .
Definition at line 73 of file gps_nmea.c.
References GpsState::fix, gps, gps_nmea, GpsNmea::msg_buf, GpsNmea::msg_len, and NMEA_PRINT.
Referenced by nmea_parse_msg().
void parse_nmea_GPRMC (void)
parse GPRMC-nmea-messages stored in gps_nmea.msg_buf .
Definition at line 114 of file gps_nmea.c.
References GpsState::course, gps, gps_nmea, GpsState::gspeed, GpsNmea::msg_buf, GpsNmea::msg_len, and NMEA_PRINT.
Referenced by nmea_parse_msg().
Variable Documentation
struct GpsNmea gps_nmea
Definition at line 54 of file gps_nmea.c.
Referenced by gps_impl_init(), nmea_parse_char(), nmea_parse_msg(), parse_nmea_GPGGA(), parse_nmea_GPGSA(), and parse_nmea_GPRMC().