Paparazzi UAS: sw/airborne/subsystems/gps/gps_skytraq.h File Reference
gps_skytraq.h File Reference
#include "mcu_periph/uart.h"
Data Structures
struct GpsSkytraq
Macros
#define SKYTRAQ_ID_NAVIGATION_DATA 0XA8
#define GPS_SKYTRAQ_MAX_PAYLOAD 255
#define __GpsLink(dev, _x) dev##_x
#define _GpsLink(dev, _x) __GpsLink(dev, _x)
#define GpsLink(_x) _GpsLink(GPS_LINK, _x)
#define GpsBuffer() GpsLink(ChAvailable())
#define GpsEvent(_sol_available_callback)
#define ReadGpsBuffer()
Enumerations
enum GpsSkytraqError {
GPS_SKYTRAQ_ERR_NONE = 0, GPS_SKYTRAQ_ERR_OVERRUN, GPS_SKYTRAQ_ERR_MSG_TOO_LONG, GPS_SKYTRAQ_ERR_CHECKSUM,
GPS_SKYTRAQ_ERR_OUT_OF_SYNC, GPS_SKYTRAQ_ERR_UNEXPECTED
}
Functions
void gps_skytraq_read_message (void)
void gps_skytraq_parse (uint8_t c)
Variables
struct GpsSkytraq gps_skytraq
Macro Definition Documentation
#define __GpsLink (dev, _x) dev##_x
Definition at line 61 of file gps_skytraq.h.
#define _GpsLink (dev, _x) __GpsLink(dev, _x)
Definition at line 62 of file gps_skytraq.h.
#define GPS_SKYTRAQ_MAX_PAYLOAD 255
Definition at line 39 of file gps_skytraq.h.
Referenced by gps_skytraq_parse().
#define GpsBuffer () GpsLink(ChAvailable())
Definition at line 65 of file gps_skytraq.h.
#define GpsEvent (_sol_available_callback)
Value:
{                     \
    if (GpsBuffer()) {                                          \
      ReadGpsBuffer();                                          \
    }                                                           \
    if (gps_skytraq.msg_available) {                            \
      gps_skytraq_read_message();                               \
      if (gps_skytraq.msg_id == SKYTRAQ_ID_NAVIGATION_DATA) { \
        if (gps.fix == GPS_FIX_3D) {                            \
          gps.last_fix_ticks = sys_time.nb_sec_rem;             \
          gps.last_fix_time = sys_time.nb_sec;                  \
        }                                                       \
        _sol_available_callback();                              \
      }                                                         \
      gps_skytraq.msg_available = FALSE;                        \
    }                                                           \
  }
Definition at line 67 of file gps_skytraq.h.
#define GpsLink (_x) _GpsLink(GPS_LINK, _x)
Definition at line 63 of file gps_skytraq.h.
#define ReadGpsBuffer ()
Value:
{           \
    while (GpsLink(ChAvailable())&&!gps_skytraq.msg_available)  \
      gps_skytraq_parse(GpsLink(Getch()));        \
  }
Definition at line 84 of file gps_skytraq.h.
#define SKYTRAQ_ID_NAVIGATION_DATA 0XA8
Definition at line 27 of file gps_skytraq.h.
Referenced by gps_skytraq_read_message().
Enumeration Type Documentation
enum GpsSkytraqError
Enumerator:
GPS_SKYTRAQ_ERR_NONE
GPS_SKYTRAQ_ERR_OVERRUN
GPS_SKYTRAQ_ERR_MSG_TOO_LONG
GPS_SKYTRAQ_ERR_CHECKSUM
GPS_SKYTRAQ_ERR_OUT_OF_SYNC
GPS_SKYTRAQ_ERR_UNEXPECTED
Definition at line 30 of file gps_skytraq.h.
Function Documentation
void gps_skytraq_parse (uint8_t c)
Definition at line 179 of file gps_skytraq.c.
References c, GpsSkytraq::checksum, GpsSkytraq::error_cnt, GpsSkytraq::error_last, GOT_CHECKSUM, GOT_ID, GOT_LEN1, GOT_LEN2, GOT_PAYLOAD, GOT_SYNC1, GOT_SYNC2, GOT_SYNC3, gps_skytraq, GPS_SKYTRAQ_ERR_CHECKSUM, GPS_SKYTRAQ_ERR_MSG_TOO_LONG, GPS_SKYTRAQ_ERR_OUT_OF_SYNC, GPS_SKYTRAQ_ERR_UNEXPECTED, GPS_SKYTRAQ_MAX_PAYLOAD, GpsSkytraq::len, GpsSkytraq::msg_available, GpsSkytraq::msg_buf, GpsSkytraq::msg_id, GpsSkytraq::msg_idx, SKYTRAQ_SYNC1, SKYTRAQ_SYNC2, SKYTRAQ_SYNC3, GpsSkytraq::status, TRUE, and UNINIT.
void gps_skytraq_read_message (void)
Definition at line 99 of file gps_skytraq.c.
References LlaCoor_i::alt, UtmCoor_i::alt, GpsState::course, distance_too_great(), UtmCoor_f::east, UtmCoor_i::east, LtpDef_i::ecef, GpsState::ecef_pos, GpsState::ecef_vel, GpsState::fix, gps, GPS_FIX_2D, GPS_FIX_3D, GPS_FIX_NONE, gps_skytraq, GpsState::gspeed, GpsState::hmsl, LlaCoor_f::lat, LlaCoor_i::lat, LED_ON, LED_TOGGLE, GpsState::lla_pos, LlaCoor_f::lon, LlaCoor_i::lon, ltp_def_from_ecef_i(), GpsSkytraq::msg_buf, GpsSkytraq::msg_id, nav_utm_zone0, ned_of_ecef_vect_i(), GpsState::ned_vel, UtmCoor_f::north, UtmCoor_i::north, GpsState::num_sv, GpsState::pdop, GpsSkytraq::ref_ltp, SKYTRAQ_FIX_2D, SKYTRAQ_FIX_3D, SKYTRAQ_FIX_3D_DGPS, SKYTRAQ_ID_NAVIGATION_DATA, SKYTRAQ_NAVIGATION_DATA_AEL, SKYTRAQ_NAVIGATION_DATA_ASL, SKYTRAQ_NAVIGATION_DATA_ECEFVX, SKYTRAQ_NAVIGATION_DATA_ECEFVY, SKYTRAQ_NAVIGATION_DATA_ECEFVZ, SKYTRAQ_NAVIGATION_DATA_ECEFX, SKYTRAQ_NAVIGATION_DATA_ECEFY, SKYTRAQ_NAVIGATION_DATA_ECEFZ, SKYTRAQ_NAVIGATION_DATA_FixMode, SKYTRAQ_NAVIGATION_DATA_LAT, SKYTRAQ_NAVIGATION_DATA_LON, SKYTRAQ_NAVIGATION_DATA_NumSV, SKYTRAQ_NAVIGATION_DATA_PDOP, SKYTRAQ_NAVIGATION_DATA_TOW, GpsState::speed_3d, GpsState::tow, utm_of_lla_f(), GpsState::utm_pos, EcefCoor_i::x, NedCoor_i::x, EcefCoor_i::y, NedCoor_i::y, EcefCoor_i::z, NedCoor_i::z, UtmCoor_f::zone, and UtmCoor_i::zone.
Variable Documentation
struct GpsSkytraq gps_skytraq
Definition at line 31 of file gps_skytraq.c.
Referenced by gps_impl_init(), gps_skytraq_parse(), and gps_skytraq_read_message().