Paparazzi UAS: Generic Orientation Representations
Generic Orientation Representations
Math Functions
This generic orientation representation consists of a struct, containing the 6 orientation representations, and a status variable.
Data Structures
struct OrientationReps
Defines
#define ORREP_QUAT_I 0
Quaternion (BFP int)
#define ORREP_EULER_I 1
zyx Euler (BFP int)
#define ORREP_RMAT_I 2
Rotation Matrix (BFP int)
#define ORREP_QUAT_F 3
Quaternion (float)
#define ORREP_EULER_F 4
zyx Euler (float)
#define ORREP_RMAT_F 5
Rotation Matrix (float)
Functions
void orientationCalcQuat_i (struct OrientationReps *orientation)
void orientationCalcRMat_i (struct OrientationReps *orientation)
void orientationCalcEulers_i (struct OrientationReps *orientation)
void orientationCalcQuat_f (struct OrientationReps *orientation)
void orientationCalcRMat_f (struct OrientationReps *orientation)
void orientationCalcEulers_f (struct OrientationReps *orientation)
static bool_t orienationCheckValid (struct OrientationReps *orientation)
Test if orientations are valid.
static void orientationSetQuat_i (struct OrientationReps *orientation, struct Int32Quat *quat)
Set vehicle body attitude from quaternion (int).
static void orientationSetRMat_i (struct OrientationReps *orientation, struct Int32RMat *rmat)
Set vehicle body attitude from rotation matrix (int).
static void orientationSetEulers_i (struct OrientationReps *orientation, struct Int32Eulers *eulers)
Set vehicle body attitude from euler angles (int).
static void orientationSetQuat_f (struct OrientationReps *orientation, struct FloatQuat *quat)
Set vehicle body attitude from quaternion (float).
static void orientationSetRMat_f (struct OrientationReps *orientation, struct FloatRMat *rmat)
Set vehicle body attitude from rotation matrix (float).
static void orientationSetEulers_f (struct OrientationReps *orientation, struct FloatEulers *eulers)
Set vehicle body attitude from euler angles (float).
static struct Int32Quat * orientationGetQuat_i (struct OrientationReps *orientation)
Get vehicle body attitude quaternion (int).
static struct Int32RMat * orientationGetRMat_i (struct OrientationReps *orientation)
Get vehicle body attitude rotation matrix (int).
static struct Int32Eulers * orientationGetEulers_i (struct OrientationReps *orientation)
Get vehicle body attitude euler angles (int).
static struct FloatQuat * orientationGetQuat_f (struct OrientationReps *orientation)
Get vehicle body attitude quaternion (float).
static struct FloatRMat * orientationGetRMat_f (struct OrientationReps *orientation)
Get vehicle body attitude rotation matrix (float).
static struct FloatEulers * orientationGetEulers_f (struct OrientationReps *orientation)
Get vehicle body attitude euler angles (float).
Detailed Description
This generic orientation representation consists of a struct, containing the 6 orientation representations, and a status variable.
The bits in the status variable indicate which representations of the orientation are up-to-date.
When a getter is used to get a certain representation, the status bit is checked to see if the current value is already available in the desired orientation representation. If the desired representation is not available, it will be calculated.
When a setter is used to set a representation, all status bits are cleared, and only the status bit for the set representation is set to one.
Define Documentation
#define ORREP_EULER_F 4
zyx Euler (float)
Definition at line 70 of file pprz_orientation_conversion.h.
Referenced by orientationCalcEulers_f(), orientationCalcEulers_i(), orientationCalcQuat_f(), orientationCalcQuat_i(), orientationCalcRMat_f(), orientationCalcRMat_i(), orientationGetEulers_f(), and orientationSetEulers_f().
#define ORREP_EULER_I 1
zyx Euler (BFP int)
Definition at line 67 of file pprz_orientation_conversion.h.
Referenced by orientationCalcEulers_f(), orientationCalcEulers_i(), orientationCalcQuat_f(), orientationCalcQuat_i(), orientationCalcRMat_f(), orientationCalcRMat_i(), orientationGetEulers_i(), and orientationSetEulers_i().
#define ORREP_QUAT_F 3
Quaternion (float)
Definition at line 69 of file pprz_orientation_conversion.h.
Referenced by orientationCalcEulers_f(), orientationCalcEulers_i(), orientationCalcQuat_f(), orientationCalcQuat_i(), orientationCalcRMat_f(), orientationCalcRMat_i(), orientationGetQuat_f(), and orientationSetQuat_f().
#define ORREP_QUAT_I 0
Quaternion (BFP int)
Definition at line 66 of file pprz_orientation_conversion.h.
Referenced by orientationCalcEulers_f(), orientationCalcEulers_i(), orientationCalcQuat_f(), orientationCalcQuat_i(), orientationCalcRMat_f(), orientationCalcRMat_i(), orientationGetQuat_i(), and orientationSetQuat_i().
#define ORREP_RMAT_F 5
Rotation Matrix (float)
Definition at line 71 of file pprz_orientation_conversion.h.
Referenced by orientationCalcEulers_f(), orientationCalcEulers_i(), orientationCalcQuat_f(), orientationCalcQuat_i(), orientationCalcRMat_f(), orientationCalcRMat_i(), orientationGetRMat_f(), and orientationSetRMat_f().
#define ORREP_RMAT_I 2
Rotation Matrix (BFP int)
Definition at line 68 of file pprz_orientation_conversion.h.
Referenced by orientationCalcEulers_f(), orientationCalcEulers_i(), orientationCalcQuat_f(), orientationCalcQuat_i(), orientationCalcRMat_f(), orientationCalcRMat_i(), orientationGetRMat_i(), and orientationSetRMat_i().
Function Documentation
static bool_t orienationCheckValid (struct OrientationReps * orientation) [inline, static]
Test if orientations are valid.
Definition at line 132 of file pprz_orientation_conversion.h.
References OrientationReps::status.
Referenced by stateIsAttitudeValid().
void orientationCalcEulers_f (struct OrientationReps * orientation)
Definition at line 184 of file pprz_orientation_conversion.c.
References OrientationReps::eulers_f, EULERS_FLOAT_OF_BFP, OrientationReps::eulers_i, FLOAT_EULERS_OF_QUAT, FLOAT_EULERS_OF_RMAT, ORREP_EULER_F, ORREP_EULER_I, ORREP_QUAT_F, ORREP_QUAT_I, ORREP_RMAT_F, ORREP_RMAT_I, OrientationReps::quat_f, QUAT_FLOAT_OF_BFP, OrientationReps::quat_i, OrientationReps::rmat_f, RMAT_FLOAT_OF_BFP, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by orientationGetEulers_f().
void orientationCalcEulers_i (struct OrientationReps * orientation)
Definition at line 103 of file pprz_orientation_conversion.c.
References EULERS_BFP_OF_REAL, OrientationReps::eulers_f, OrientationReps::eulers_i, INT32_EULERS_OF_QUAT, INT32_EULERS_OF_RMAT, ORREP_EULER_F, ORREP_EULER_I, ORREP_QUAT_F, ORREP_QUAT_I, ORREP_RMAT_F, ORREP_RMAT_I, QUAT_BFP_OF_REAL, OrientationReps::quat_f, OrientationReps::quat_i, RMAT_BFP_OF_REAL, OrientationReps::rmat_f, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by orientationGetEulers_i().
void orientationCalcQuat_f (struct OrientationReps * orientation)
Definition at line 130 of file pprz_orientation_conversion.c.
References OrientationReps::eulers_f, EULERS_FLOAT_OF_BFP, OrientationReps::eulers_i, FLOAT_QUAT_OF_EULERS, FLOAT_QUAT_OF_RMAT, ORREP_EULER_F, ORREP_EULER_I, ORREP_QUAT_F, ORREP_QUAT_I, ORREP_RMAT_F, ORREP_RMAT_I, OrientationReps::quat_f, QUAT_FLOAT_OF_BFP, OrientationReps::quat_i, OrientationReps::rmat_f, RMAT_FLOAT_OF_BFP, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by orientationGetQuat_f().
void orientationCalcQuat_i (struct OrientationReps * orientation)
Definition at line 49 of file pprz_orientation_conversion.c.
References EULERS_BFP_OF_REAL, OrientationReps::eulers_f, OrientationReps::eulers_i, INT32_QUAT_OF_EULERS, INT32_QUAT_OF_RMAT, ORREP_EULER_F, ORREP_EULER_I, ORREP_QUAT_F, ORREP_QUAT_I, ORREP_RMAT_F, ORREP_RMAT_I, QUAT_BFP_OF_REAL, OrientationReps::quat_f, OrientationReps::quat_i, RMAT_BFP_OF_REAL, OrientationReps::rmat_f, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by orientationGetQuat_i().
void orientationCalcRMat_f (struct OrientationReps * orientation)
Definition at line 157 of file pprz_orientation_conversion.c.
References OrientationReps::eulers_f, EULERS_FLOAT_OF_BFP, OrientationReps::eulers_i, FLOAT_RMAT_OF_EULERS, FLOAT_RMAT_OF_QUAT, ORREP_EULER_F, ORREP_EULER_I, ORREP_QUAT_F, ORREP_QUAT_I, ORREP_RMAT_F, ORREP_RMAT_I, OrientationReps::quat_f, QUAT_FLOAT_OF_BFP, OrientationReps::quat_i, OrientationReps::rmat_f, RMAT_FLOAT_OF_BFP, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by orientationGetRMat_f().
void orientationCalcRMat_i (struct OrientationReps * orientation)
Definition at line 76 of file pprz_orientation_conversion.c.
References EULERS_BFP_OF_REAL, OrientationReps::eulers_f, OrientationReps::eulers_i, INT32_RMAT_OF_EULERS, INT32_RMAT_OF_QUAT, ORREP_EULER_F, ORREP_EULER_I, ORREP_QUAT_F, ORREP_QUAT_I, ORREP_RMAT_F, ORREP_RMAT_I, QUAT_BFP_OF_REAL, OrientationReps::quat_f, OrientationReps::quat_i, RMAT_BFP_OF_REAL, OrientationReps::rmat_f, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by orientationGetRMat_i().
static struct FloatEulers* orientationGetEulers_f (struct OrientationReps * orientation) [static, read]
Get vehicle body attitude euler angles (float).
Definition at line 215 of file pprz_orientation_conversion.h.
References OrientationReps::eulers_f, orientationCalcEulers_f(), ORREP_EULER_F, and OrientationReps::status.
Referenced by stateGetNedToBodyEulers_f().
static struct Int32Eulers* orientationGetEulers_i (struct OrientationReps * orientation) [static, read]
Get vehicle body attitude euler angles (int).
Definition at line 194 of file pprz_orientation_conversion.h.
References OrientationReps::eulers_i, orientationCalcEulers_i(), ORREP_EULER_I, and OrientationReps::status.
Referenced by stateGetNedToBodyEulers_i().
static struct FloatQuat* orientationGetQuat_f (struct OrientationReps * orientation) [static, read]
Get vehicle body attitude quaternion (float).
Definition at line 201 of file pprz_orientation_conversion.h.
References orientationCalcQuat_f(), ORREP_QUAT_F, OrientationReps::quat_f, and OrientationReps::status.
Referenced by stateGetNedToBodyQuat_f().
static struct Int32Quat* orientationGetQuat_i (struct OrientationReps * orientation) [static, read]
Get vehicle body attitude quaternion (int).
Definition at line 180 of file pprz_orientation_conversion.h.
References orientationCalcQuat_i(), ORREP_QUAT_I, OrientationReps::quat_i, and OrientationReps::status.
Referenced by stateGetNedToBodyQuat_i().
static struct FloatRMat* orientationGetRMat_f (struct OrientationReps * orientation) [static, read]
Get vehicle body attitude rotation matrix (float).
Definition at line 208 of file pprz_orientation_conversion.h.
References orientationCalcRMat_f(), ORREP_RMAT_F, OrientationReps::rmat_f, and OrientationReps::status.
Referenced by stateGetNedToBodyRMat_f().
static struct Int32RMat* orientationGetRMat_i (struct OrientationReps * orientation) [static, read]
Get vehicle body attitude rotation matrix (int).
Definition at line 187 of file pprz_orientation_conversion.h.
References orientationCalcRMat_i(), ORREP_RMAT_I, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by stateGetNedToBodyRMat_i().
static void orientationSetEulers_f (struct OrientationReps * orientation, struct FloatEulers * eulers) [inline, static]
Set vehicle body attitude from euler angles (float).
Definition at line 172 of file pprz_orientation_conversion.h.
References EULERS_COPY, OrientationReps::eulers_f, ORREP_EULER_F, and OrientationReps::status.
Referenced by stateSetNedToBodyEulers_f().
static void orientationSetEulers_i (struct OrientationReps * orientation, struct Int32Eulers * eulers) [inline, static]
Set vehicle body attitude from euler angles (int).
Definition at line 151 of file pprz_orientation_conversion.h.
References EULERS_COPY, OrientationReps::eulers_i, ORREP_EULER_I, and OrientationReps::status.
Referenced by stateSetNedToBodyEulers_i().
static void orientationSetQuat_f (struct OrientationReps * orientation, struct FloatQuat * quat) [inline, static]
Set vehicle body attitude from quaternion (float).
Definition at line 158 of file pprz_orientation_conversion.h.
References ORREP_QUAT_F, QUAT_COPY, OrientationReps::quat_f, and OrientationReps::status.
Referenced by stateSetNedToBodyQuat_f().
static void orientationSetQuat_i (struct OrientationReps * orientation, struct Int32Quat * quat) [inline, static]
Set vehicle body attitude from quaternion (int).
Definition at line 137 of file pprz_orientation_conversion.h.
References ORREP_QUAT_I, QUAT_COPY, OrientationReps::quat_i, and OrientationReps::status.
Referenced by stateSetNedToBodyQuat_i().
static void orientationSetRMat_f (struct OrientationReps * orientation, struct FloatRMat * rmat) [inline, static]
Set vehicle body attitude from rotation matrix (float).
Definition at line 165 of file pprz_orientation_conversion.h.
References ORREP_RMAT_F, RMAT_COPY, OrientationReps::rmat_f, and OrientationReps::status.
Referenced by stateSetNedToBodyRMat_f().
static void orientationSetRMat_i (struct OrientationReps * orientation, struct Int32RMat * rmat) [inline, static]
Set vehicle body attitude from rotation matrix (int).
Definition at line 144 of file pprz_orientation_conversion.h.
References ORREP_RMAT_I, RMAT_COPY, OrientationReps::rmat_i, and OrientationReps::status.
Referenced by stateSetNedToBodyRMat_i().