Paparazzi UAS: SPI Interface
SPI Interface
MCU Peripherals
Data Structures
struct spi_transaction
SPI transaction structure.
struct spi_periph
Macros
#define SPI_TRANSACTION_QUEUE_LEN 8
#define SPI_SLAVE0 0
#define SPI_SLAVE1 1
#define SPI_SLAVE2 2
#define SPI_SLAVE3 3
#define SPI_SLAVE4 4
#define SPI_SLAVE5 5
Typedefs
typedef void(* SPICallback)(struct spi_transaction *trans)
SPI Callback function.
Enumerations
enum SPIMode { SPIMaster, SPISlave }
enum SPISlaveSelect { SPISelectUnselect, SPISelect, SPIUnselect, SPINoSelect }
SPI slave selection behavior options.
enum SPIClockPhase { SPICphaEdge1, SPICphaEdge2 }
SPI CPHA (clock phase) options.
enum SPIClockPolarity { SPICpolIdleLow, SPICpolIdleHigh }
SPI CPOL (clock polarity) options.
enum SPIDataSizeSelect { SPIDss8bit, SPIDss16bit }
SPI data word size of transfer.
enum SPITransactionStatus {
SPITransPending, SPITransRunning, SPITransSuccess, SPITransFailed,
SPITransDone
}
SPI transaction status.
enum SPIStatus { SPIIdle, SPIRunning }
SPI peripheral status.
enum SPIBitOrder { SPIMSBFirst, SPILSBFirst }
enum SPIClockDiv {
SPIDiv2, SPIDiv4, SPIDiv8, SPIDiv16,
SPIDiv32, SPIDiv64, SPIDiv128, SPIDiv256
}
Peripheral clock divider.
Functions
void spi0_init (void)
void spi0_arch_init (void)
Architecture dependant SPI0 initialization.
void spi1_init (void)
void spi1_arch_init (void)
Architecture dependant SPI1 initialization.
void spi2_init (void)
void spi2_arch_init (void)
Architecture dependant SPI2 initialization.
void spi_init (struct spi_periph *p)
Initialize a spi peripheral.
void spi_init_slaves (void)
Initialize all used slaves and uselect them.
bool_t spi_submit (struct spi_periph *p, struct spi_transaction *t)
Submit a spi transaction.
void spi_slave_select (uint8_t slave)
Select a slave.
void spi_slave_unselect (uint8_t slave)
Unselect a slave.
bool_t spi_lock (struct spi_periph *p, uint8_t slave)
Lock the SPI fifo.
bool_t spi_resume (struct spi_periph *p, uint8_t slave)
Resume the SPI fifo.
void spi_slave_init (struct spi_periph *p)
Initialize a spi peripheral in slave mode.
bool_t spi_slave_register (struct spi_periph *p, struct spi_transaction *t)
Register a spi transaction in slave mode (only one transaction can be registered).
bool_t spi_slave_wait (struct spi_periph *p)
Initialized and wait for the next transaction.
Variables
struct spi_periph spi0
struct spi_periph spi1
struct spi_periph spi2
Detailed Description
Macro Definition Documentation
#define SPI_SLAVE0 0
Definition at line 181 of file spi.h.
Referenced by mcp355x_init(), spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SLAVE1 1
Definition at line 182 of file spi.h.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SLAVE2 2
Definition at line 183 of file spi.h.
#define SPI_SLAVE3 3
Definition at line 184 of file spi.h.
#define SPI_SLAVE4 4
Definition at line 185 of file spi.h.
#define SPI_SLAVE5 5
Definition at line 186 of file spi.h.
#define SPI_TRANSACTION_QUEUE_LEN 8
Definition at line 160 of file spi.h.
Referenced by spi_next_transaction(), spi_submit(), and SpiEndOfTransaction().
Typedef Documentation
typedef void(* SPICallback)(struct spi_transaction *trans)
SPI Callback function.
If not NULL (or 0), call function (with transaction as parameter) before or after transaction, e.g to allow execution of hardware specific actions
Definition at line 130 of file spi.h.
Enumeration Type Documentation
enum SPIBitOrder
Enumerator:
SPIMSBFirst
SPILSBFirst
Definition at line 105 of file spi.h.
enum SPIClockDiv
Peripheral clock divider.
Defines the SPI baudrate
Enumerator:
SPIDiv2
SPIDiv4
SPIDiv8
SPIDiv16
SPIDiv32
SPIDiv64
SPIDiv128
SPIDiv256
Definition at line 113 of file spi.h.
enum SPIClockPhase
SPI CPHA (clock phase) options.
Control whether data line is sampled at first or second edge of clock signal.
Enumerator:
SPICphaEdge1
CPHA = 0.
SPICphaEdge2
CPHA = 1.
Definition at line 67 of file spi.h.
enum SPIClockPolarity
SPI CPOL (clock polarity) options.
Control whether clock line is held low or high in idle state.
Enumerator:
SPICpolIdleLow
CPOL = 0.
SPICpolIdleHigh
CPOL = 1.
Definition at line 76 of file spi.h.
enum SPIDataSizeSelect
SPI data word size of transfer.
Enumerator:
SPIDss8bit
SPIDss16bit
Definition at line 83 of file spi.h.
enum SPIMode
Enumerator:
SPIMaster
SPISlave
Definition at line 46 of file spi.h.
enum SPISlaveSelect
SPI slave selection behavior options.
Default operation should be SelectUnselected, but some peripherals might need some special control. Use non-default control only if you know what you're doing.
Enumerator:
SPISelectUnselect
slave is selected before transaction and unselected after
SPISelect
slave is selected before transaction but not unselected
SPIUnselect
slave is not selected but unselected after transaction
SPINoSelect
slave is not selected nor unselected
Definition at line 56 of file spi.h.
enum SPIStatus
SPI peripheral status.
Enumerator:
SPIIdle
SPIRunning
Definition at line 100 of file spi.h.
enum SPITransactionStatus
SPI transaction status.
Enumerator:
SPITransPending
SPITransRunning
SPITransSuccess
SPITransFailed
SPITransDone
Definition at line 90 of file spi.h.
Function Documentation
void spi0_arch_init (void)
Architecture dependant SPI0 initialization.
Must be implemented by underlying architecture
Definition at line 396 of file spi_arch.c.
References spi_periph::init_struct, spi_periph::reg_addr, spi0, SPI0, and VIC_SPI0.
Referenced by spi0_init().
void spi0_init (void)
Definition at line 37 of file spi.c.
References spi0, spi0_arch_init(), and spi_init().
Referenced by mcu_init().
void spi1_arch_init (void)
Architecture dependant SPI1 initialization.
Must be implemented by underlying architecture
Definition at line 444 of file spi_arch.c.
References _VIC_ADDR, _VIC_CNTL, locm3_spi_comm::br, spi_periph_dma::comm, spi_periph_dma::comm_sig, locm3_spi_comm::cpha, locm3_spi_comm::cpol, locm3_spi_comm::dff, spi_periph_dma::dma, FALSE, get_comm_signature(), spi_periph::init_struct, locm3_spi_comm::lsbfirst, MASTER_SSP_CPHA, MASTER_SSP_CPOL, MASTER_SSP_DSS, MASTER_SSP_FRF, MASTER_SSP_LBM, MASTER_SSP_MS, MASTER_SSP_SCR, MASTER_SSP_SOD, PINSEL1, spi_periph::reg_addr, spi_periph_dma::rx_chan, spi_periph_dma::rx_dummy_buf, spi_periph_dma::rx_extra_dummy_dma, spi_periph_dma::rx_nvic_irq, set_default_comm_config(), spi1, SPI1, spi1_dma, spi1_ISR(), SPI1_VIC_SLOT, spi_arch_int_enable(), spi_periph_dma::spidr, SPIIdle, SSP_PINSEL1_MISO, SSP_PINSEL1_MOSI, SSP_PINSEL1_SCK, SSPCPSR, SSPCPSR_VAL, SSPCR0, SSPCR1, spi_periph::status, spi_periph::trans_extract_idx, spi_periph::trans_insert_idx, spi_periph_dma::tx_chan, spi_periph_dma::tx_dummy_buf, spi_periph_dma::tx_extra_dummy_dma, spi_periph_dma::tx_nvic_irq, VIC_BIT, VIC_ENABLE, VIC_SPI1, VICIntEnable, and VICIntSelect.
Referenced by spi1_init().
void spi1_init (void)
Definition at line 47 of file spi.c.
References spi1, spi1_arch_init(), and spi_init().
Referenced by mcu_init().
void spi2_arch_init (void)
Architecture dependant SPI2 initialization.
Must be implemented by underlying architecture
Definition at line 735 of file spi_arch.c.
References locm3_spi_comm::br, spi_periph_dma::comm, spi_periph_dma::comm_sig, locm3_spi_comm::cpha, locm3_spi_comm::cpol, locm3_spi_comm::dff, spi_periph_dma::dma, FALSE, get_comm_signature(), spi_periph::init_struct, locm3_spi_comm::lsbfirst, spi_periph::reg_addr, spi_periph_dma::rx_chan, spi_periph_dma::rx_dummy_buf, spi_periph_dma::rx_extra_dummy_dma, spi_periph_dma::rx_nvic_irq, set_default_comm_config(), spi2, spi2_dma, spi_arch_int_enable(), spi_periph_dma::spidr, SPIIdle, spi_periph::status, spi_periph::trans_extract_idx, spi_periph::trans_insert_idx, spi_periph_dma::tx_chan, spi_periph_dma::tx_dummy_buf, spi_periph_dma::tx_extra_dummy_dma, and spi_periph_dma::tx_nvic_irq.
Referenced by spi2_init().
void spi2_init (void)
Definition at line 57 of file spi.c.
References spi2, spi2_arch_init(), and spi_init().
Referenced by mcu_init().
void spi_init (struct spi_periph * p)
Initialize a spi peripheral.
Parameters
p spi peripheral to be configured
Definition at line 74 of file spi.c.
References FALSE, spi_periph::mode, SPIIdle, SPIMaster, spi_periph::status, spi_periph::suspend, spi_periph::trans_extract_idx, and spi_periph::trans_insert_idx.
void spi_init_slaves (void)
Initialize all used slaves and uselect them.
Definition at line 501 of file spi_arch.c.
References SPI_SELECT_SLAVE0_IODIR, SPI_SELECT_SLAVE0_PERIPH, SPI_SELECT_SLAVE0_PIN, SPI_SELECT_SLAVE0_PINSEL, SPI_SELECT_SLAVE0_PINSEL_BIT, SPI_SELECT_SLAVE0_PINSEL_VAL, SPI_SELECT_SLAVE0_PORT, SPI_SELECT_SLAVE1_IODIR, SPI_SELECT_SLAVE1_PERIPH, SPI_SELECT_SLAVE1_PIN, SPI_SELECT_SLAVE1_PINSEL, SPI_SELECT_SLAVE1_PINSEL_BIT, SPI_SELECT_SLAVE1_PINSEL_VAL, SPI_SELECT_SLAVE1_PORT, SPI_SELECT_SLAVE2_PERIPH, SPI_SELECT_SLAVE2_PIN, SPI_SELECT_SLAVE2_PORT, SPI_SELECT_SLAVE3_PERIPH, SPI_SELECT_SLAVE3_PIN, SPI_SELECT_SLAVE3_PORT, SPI_SELECT_SLAVE4_PERIPH, SPI_SELECT_SLAVE4_PIN, SPI_SELECT_SLAVE4_PORT, SPI_SELECT_SLAVE5_PERIPH, SPI_SELECT_SLAVE5_PIN, SPI_SELECT_SLAVE5_PORT, SPI_SLAVE0, SPI_SLAVE1, and SpiSlaveUnselect().
Referenced by mcu_init().
bool_t spi_lock (struct spi_periph * p, uint8_t slave)
Lock the SPI fifo.
This will stop the SPI fifo after the current transaction if any, or before the next one if none are pending. Only the slave that locks the fifo can unlock it.
Parameters
p spi peripheral to be used
slave slave id
Returns
true if correctly locked
Definition at line 533 of file spi_arch.c.
References FALSE, spi_periph::init_struct, spi_arch_int_disable(), spi_arch_int_enable(), spi_periph::suspend, TRUE, VIC_BIT, VICIntEnable, and VICIntEnClear.
Referenced by max1168_lock_cb().
bool_t spi_resume (struct spi_periph * p, uint8_t slave)
Resume the SPI fifo.
Only the slave that locks the fifo can unlock it.
Parameters
p spi peripheral to be used
slave slave id
Returns
true if correctly unlocked
Definition at line 545 of file spi_arch.c.
References FALSE, spi_periph::init_struct, spi_arch_int_disable(), spi_arch_int_enable(), spi_start_dma_transaction(), SPIIdle, SpiStart(), spi_periph::status, spi_periph::suspend, spi_periph::trans, spi_periph::trans_extract_idx, spi_periph::trans_insert_idx, TRUE, VIC_BIT, VICIntEnable, and VICIntEnClear.
Referenced by max1168_event().
void spi_slave_init (struct spi_periph * p)
Initialize a spi peripheral in slave mode.
Parameters
p spi peripheral to be configured
Definition at line 127 of file spi.c.
References FALSE, spi_periph::mode, SPIIdle, SPISlave, spi_periph::status, spi_periph::suspend, spi_periph::trans_extract_idx, and spi_periph::trans_insert_idx.
bool_t spi_slave_register (struct spi_periph * p, struct spi_transaction * t)
Register a spi transaction in slave mode (only one transaction can be registered).
Must be implemented by the underlying architecture
Parameters
p spi peripheral to be used
t spi transaction
Returns
return true if registered with success
Definition at line 645 of file spi_arch.c.
References spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, FALSE, SpiClearCPHA(), SpiClearCPOL(), SPICphaEdge2, SPICpolIdleHigh, SPIIdle, SpiSetCPHA(), SpiSetCPOL(), SpiSetDataSize(), SPITransFailed, SPITransPending, spi_transaction::status, spi_periph::status, spi_periph::trans, spi_periph::trans_insert_idx, and TRUE.
void spi_slave_select (uint8_t slave)
Select a slave.
Parameters
slave slave id
Definition at line 525 of file spi_arch.c.
References SpiSlaveSelect().
void spi_slave_unselect (uint8_t slave)
Unselect a slave.
Parameters
slave slave id
Definition at line 529 of file spi_arch.c.
References SpiSlaveUnselect().
Referenced by max1168_event().
bool_t spi_slave_wait (struct spi_periph * p)
Initialized and wait for the next transaction.
If a transaction is registered for this peripheral, the spi will be waiting for a communication from the master
Parameters
p spi peripheral to be used
Returns
return true if a transaction was register for this peripheral
Definition at line 668 of file spi_arch.c.
References FALSE, SpiSlaveStart(), spi_periph::trans, spi_periph::trans_extract_idx, spi_periph::trans_insert_idx, and TRUE.
bool_t spi_submit (struct spi_periph * p, struct spi_transaction * t)
Submit a spi transaction.
Must be implemented by the underlying architecture
Parameters
p spi peripheral to be used
t spi transaction
Returns
TRUE if insertion to the transaction queue succeded
Definition at line 469 of file spi_arch.c.
References disableIRQ(), FALSE, spi_periph::init_struct, spi_transaction::input_length, spi_transaction::output_length, restoreIRQ(), spi_arch_int_disable(), spi_arch_int_enable(), spi_start_dma_transaction(), SPI_TRANSACTION_QUEUE_LEN, SPIIdle, SpiStart(), SPITransFailed, SPITransPending, spi_transaction::status, spi_periph::status, spi_periph::suspend, spi_periph::trans, spi_periph::trans_extract_idx, spi_periph::trans_insert_idx, TRUE, VIC_BIT, VICIntEnable, and VICIntEnClear.
Referenced by adxl345_spi_read(), adxl345_spi_write_to_reg(), baro_event(), baro_periodic(), high_speed_logger_spi_link_periodic(), imu_periodic(), ins_configure(), max1168_read(), mcp355x_read(), mpu_configure(), mpu_set(), mpu_wait_slave4_ready(), ms2100_event(), ms2100_read(), read_data(), vn100_periodic_task(), w5100_get(), w5100_set(), and write_to_reg().
Variable Documentation
struct spi_periph spi0
Todo:
SPI error struct
Definition at line 35 of file spi.c.
Referenced by spi0_arch_init(), and spi0_init().
struct spi_periph spi1
Definition at line 45 of file spi.c.
Referenced by dma1_channel2_isr(), dma1_channel3_isr(), mcp355x_read(), spi1_arch_init(), spi1_init(), and spi1_ISR().
struct spi_periph spi2
Definition at line 55 of file spi.c.
Referenced by dma1_channel4_isr(), dma1_channel5_isr(), spi2_arch_init(), and spi2_init().