Paparazzi UAS: MCU Peripherals
MCU Peripherals
Modules
I2C Interface
SPI Interface
Functions
void mcu_init (void)
Microcontroller peripherals initialization.
Detailed Description
Function Documentation
void mcu_init (void)
Microcontroller peripherals initialization.
This function is responisble for setting up the microcontroller after Reset.
Definition at line 60 of file mcu.c.
References adc_init(), dac_init(), led_init(), mcu_arch_init(), spi0_init(), spi1_init(), spi2_init(), spi_init_slaves(), sys_time_init(), and VCOM_init().
Referenced by init_fbw(), main(), and main_init().