Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c File Reference
guidance_h.c File Reference
Horizontal guidance for rotorcrafts.
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.h"
#include "firmwares/rotorcraft/navigation.h"
#include "state.h"
#include "generated/airframe.h"
Macros
#define GUIDANCE_H_AGAIN 0
#define GUIDANCE_H_MAX_BANK RadOfDeg(20)
#define GuidanceHSetRef(_pos, _speed, _accel)
#define MAX_POS_ERR POS_BFP_OF_REAL(16.)
#define MAX_SPEED_ERR SPEED_BFP_OF_REAL(16.)
#define MAX_POS_ERR_SUM ((int32_t)(MAX_POS_ERR)<< 12)
#define GH_GAIN_SCALE 2
#define TRAJ_MAX_BANK BFP_OF_REAL(GUIDANCE_H_MAX_BANK, INT32_ANGLE_FRAC)
maximum bank angle: default 20 deg
Functions
static void guidance_h_update_reference (bool_t use_ref)
static void guidance_h_traj_run (bool_t in_flight)
static void guidance_h_hover_enter (void)
static void guidance_h_nav_enter (void)
void guidance_h_init (void)
void guidance_h_mode_changed (uint8_t new_mode)
void guidance_h_read_rc (bool_t in_flight)
void guidance_h_run (bool_t in_flight)
Variables
uint8_t guidance_h_mode
struct Int32Vect2 guidance_h_pos_sp
horizontal position setpoint in NED.
struct Int32Vect2 guidance_h_pos_ref
with INT32_POS_FRAC
struct Int32Vect2 guidance_h_speed_ref
with INT32_SPEED_FRAC
struct Int32Vect2 guidance_h_accel_ref
with INT32_ACCEL_FRAC
struct Int32Vect2 guidance_h_pos_err
struct Int32Vect2 guidance_h_speed_err
struct Int32Vect2 guidance_h_pos_err_sum
struct Int32Vect2 guidance_h_nav_err
struct Int32Eulers guidance_h_rc_sp
with INT32_ANGLE_FRAC
struct Int32Vect2 guidance_h_command_earth
struct Int32Vect2 guidance_h_stick_earth_sp
struct Int32Eulers guidance_h_command_body
with INT32_ANGLE_FRAC
int32_t guidance_h_pgain
int32_t guidance_h_dgain
int32_t guidance_h_igain
int32_t guidance_h_again
Detailed Description
Horizontal guidance for rotorcrafts.
Definition in file guidance_h.c.
Macro Definition Documentation
#define GH_GAIN_SCALE 2
Definition at line 261 of file guidance_h.c.
Referenced by guidance_h_traj_run().
#define GUIDANCE_H_AGAIN 0
Definition at line 68 of file guidance_h.c.
Referenced by guidance_h_init().
#define GUIDANCE_H_MAX_BANK RadOfDeg(20)
Definition at line 76 of file guidance_h.c.
#define GuidanceHSetRef (_pos, _speed, _accel)
Value:
{ \
    gh_set_ref(_pos, _speed, _accel);        \
    VECT2_COPY(guidance_h_pos_ref,   _pos);     \
    VECT2_COPY(guidance_h_speed_ref, _speed);   \
    VECT2_COPY(guidance_h_accel_ref, _accel);   \
  }
Definition at line 84 of file guidance_h.c.
Referenced by guidance_h_nav_enter().
#define MAX_POS_ERR POS_BFP_OF_REAL(16.)
Definition at line 255 of file guidance_h.c.
Referenced by guidance_h_traj_run().
#define MAX_POS_ERR_SUM ((int32_t)(MAX_POS_ERR)<< 12)
Definition at line 257 of file guidance_h.c.
Referenced by guidance_h_traj_run().
#define MAX_SPEED_ERR SPEED_BFP_OF_REAL(16.)
Definition at line 256 of file guidance_h.c.
Referenced by guidance_h_traj_run().
#define TRAJ_MAX_BANK BFP_OF_REAL(GUIDANCE_H_MAX_BANK, INT32_ANGLE_FRAC)
maximum bank angle: default 20 deg
Definition at line 264 of file guidance_h.c.
Referenced by guidance_h_traj_run().
Function Documentation
static void guidance_h_hover_enter (void) inline static
Definition at line 328 of file guidance_h.c.
References guidance_h_pos_err_sum, guidance_h_pos_sp, guidance_h_rc_sp, INT_VECT2_ZERO, Int32Eulers::psi, reset_psi_ref_from_body(), stateGetNedToBodyEulers_i(), stateGetPositionNed_i(), and VECT2_COPY.
Referenced by guidance_h_mode_changed().
void guidance_h_init (void)
Definition at line 92 of file guidance_h.c.
References guidance_h_again, GUIDANCE_H_AGAIN, guidance_h_command_body, guidance_h_dgain, guidance_h_igain, guidance_h_mode, GUIDANCE_H_MODE_KILL, guidance_h_pgain, guidance_h_pos_err_sum, guidance_h_pos_sp, guidance_h_rc_sp, INT_EULERS_ZERO, and INT_VECT2_ZERO.
Referenced by main_init().
void guidance_h_mode_changed (uint8_t new_mode)
Definition at line 107 of file guidance_h.c.
References guidance_h_hover_enter(), guidance_h_mode, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_h_nav_enter(), stabilization_attitude_enter(), stabilization_attitude_reset_care_free_heading(), stabilization_none_enter(), and stabilization_rate_enter().
Referenced by autopilot_set_mode().
static void guidance_h_nav_enter (void) inline static
Definition at line 339 of file guidance_h.c.
References guidance_h_pos_err_sum, guidance_h_pos_sp, GuidanceHSetRef, INT32_VECT2_NED_OF_ENU, INT_VECT2_ZERO, nav_heading, navigation_carrot, Int32Eulers::psi, reset_psi_ref_from_body(), stateGetNedToBodyEulers_i(), stateGetPositionNed_i(), stateGetSpeedNed_i(), and VECT2_COPY.
Referenced by guidance_h_mode_changed(), and guidance_h_run().
void guidance_h_read_rc (bool_t in_flight)
Definition at line 142 of file guidance_h.c.
References guidance_h_mode, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_h_rc_sp, INT_EULERS_ZERO, radio_control, RC_OK, stabilization_attitude_read_rc(), stabilization_attitude_read_rc_setpoint_eulers(), stabilization_none_read_rc(), stabilization_rate_read_rc(), and RadioControl::status.
Referenced by autopilot_on_rc_frame().
void guidance_h_run (bool_t in_flight)
Definition at line 178 of file guidance_h.c.
References FALSE, guidance_h_command_body, guidance_h_mode, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_h_nav_enter(), guidance_h_pos_sp, guidance_h_rc_sp, guidance_h_traj_run(), guidance_h_update_reference(), horizontal_mode, HORIZONTAL_MODE_ATTITUDE, INT32_QUAT_OF_EULERS, INT32_QUAT_WRAP_SHORTEST, INT32_VECT2_NED_OF_ENU, nav_heading, nav_pitch, nav_roll, navigation_carrot, FloatEulers::phi, FloatEulers::psi, Int32Eulers::psi, stab_att_sp_euler, stab_att_sp_quat, stabilization_attitude_run(), stabilization_none_run(), stabilization_rate_run(), stateGetNedToBodyEulers_i(), FloatEulers::theta, and TRUE.
Referenced by autopilot_periodic().
static void guidance_h_traj_run (bool_t in_flight) inline static
Definition at line 266 of file guidance_h.c.
References EULERS_COPY, GH_GAIN_SCALE, guidance_h_accel_ref, guidance_h_again, guidance_h_command_body, guidance_h_command_earth, guidance_h_dgain, guidance_h_igain, guidance_h_pgain, guidance_h_pos_err, guidance_h_pos_err_sum, guidance_h_pos_ref, guidance_h_rc_sp, guidance_h_speed_err, guidance_h_speed_ref, INT32_POS_FRAC, INT32_QUAT_OF_EULERS, INT32_QUAT_WRAP_SHORTEST, INT32_SPEED_FRAC, INT32_TRIG_FRAC, INT_VECT2_ZERO, MAX_POS_ERR, MAX_POS_ERR_SUM, MAX_SPEED_ERR, Int32Eulers::phi, PPRZ_ITRIG_COS, PPRZ_ITRIG_SIN, Int32Eulers::psi, stab_att_sp_euler, stab_att_sp_quat, stateGetNedToBodyEulers_i(), stateGetPositionNed_i(), stateGetSpeedNed_i(), Int32Eulers::theta, TRAJ_MAX_BANK, VECT2_ADD, VECT2_DIFF, VECT2_STRIM, Int32Vect2::x, and Int32Vect2::y.
Referenced by guidance_h_run().
static void guidance_h_update_reference (bool_t use_ref) inline static
Definition at line 240 of file guidance_h.c.
References gh_accel_ref, GH_ACCEL_REF_FRAC, gh_pos_ref, GH_POS_REF_FRAC, gh_speed_ref, GH_SPEED_REF_FRAC, gh_update_ref_from_pos_sp(), guidance_h_accel_ref, guidance_h_pos_ref, guidance_h_pos_sp, guidance_h_speed_ref, INT32_ACCEL_FRAC, INT32_POS_FRAC, INT32_SPEED_FRAC, INT32_VECT2_LSHIFT, INT32_VECT2_RSHIFT, INT_VECT2_ZERO, and VECT2_COPY.
Referenced by guidance_h_run().
Variable Documentation
struct Int32Vect2 guidance_h_accel_ref
with INT32_ACCEL_FRAC
Definition at line 42 of file guidance_h.c.
Referenced by guidance_h_traj_run(), and guidance_h_update_reference().
int32_t guidance_h_again
Definition at line 57 of file guidance_h.c.
Referenced by guidance_h_init(), and guidance_h_traj_run().
struct Int32Eulers guidance_h_command_body
with INT32_ANGLE_FRAC
Definition at line 52 of file guidance_h.c.
Referenced by guidance_h_init(), guidance_h_run(), and guidance_h_traj_run().
struct Int32Vect2 guidance_h_command_earth
Definition at line 50 of file guidance_h.c.
Referenced by guidance_h_traj_run().
int32_t guidance_h_dgain
Definition at line 55 of file guidance_h.c.
Referenced by guidance_h_init(), and guidance_h_traj_run().
int32_t guidance_h_igain
Definition at line 56 of file guidance_h.c.
Referenced by guidance_h_init(), and guidance_h_traj_run().
uint8_t guidance_h_mode
Definition at line 37 of file guidance_h.c.
Referenced by guidance_h_init(), guidance_h_mode_changed(), guidance_h_read_rc(), guidance_h_run(), stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_read_rc_setpoint_eulers_f(), and stabilization_attitude_read_rc_setpoint_quat_f().
struct Int32Vect2 guidance_h_nav_err
Definition at line 47 of file guidance_h.c.
int32_t guidance_h_pgain
Definition at line 54 of file guidance_h.c.
Referenced by guidance_h_init(), and guidance_h_traj_run().
struct Int32Vect2 guidance_h_pos_err
Definition at line 44 of file guidance_h.c.
Referenced by guidance_h_traj_run().
struct Int32Vect2 guidance_h_pos_err_sum
Definition at line 46 of file guidance_h.c.
Referenced by guidance_h_hover_enter(), guidance_h_init(), guidance_h_nav_enter(), and guidance_h_traj_run().
struct Int32Vect2 guidance_h_pos_ref
with INT32_POS_FRAC
Definition at line 40 of file guidance_h.c.
Referenced by guidance_h_traj_run(), and guidance_h_update_reference().
struct Int32Vect2 guidance_h_pos_sp
horizontal position setpoint in NED.
fixed point representation: Q23.8 accuracy 0.0039, range 8388km
Definition at line 39 of file guidance_h.c.
Referenced by guidance_h_hover_enter(), guidance_h_init(), guidance_h_nav_enter(), guidance_h_run(), and guidance_h_update_reference().
struct Int32Eulers guidance_h_rc_sp
with INT32_ANGLE_FRAC
Definition at line 49 of file guidance_h.c.
Referenced by guidance_h_hover_enter(), guidance_h_init(), guidance_h_read_rc(), guidance_h_run(), and guidance_h_traj_run().
struct Int32Vect2 guidance_h_speed_err
Definition at line 45 of file guidance_h.c.
Referenced by guidance_h_traj_run().
struct Int32Vect2 guidance_h_speed_ref
with INT32_SPEED_FRAC
Definition at line 41 of file guidance_h.c.
Referenced by guidance_h_traj_run(), and guidance_h_update_reference().
struct Int32Vect2 guidance_h_stick_earth_sp
Definition at line 51 of file guidance_h.c.