Paparazzi UAS: sw/airborne/subsystems/ins/hf_float.h File Reference
hf_float.h File Reference
Horizontal filter (x,y) to estimate position and velocity.
#include "std.h"
#include "math/pprz_algebra_float.h"
#include "generated/airframe.h"
Data Structures
struct HfilterFloat
Macros
#define HFF_STATE_SIZE 2
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
#define HFF_FREQ (AHRS_PROPAGATE_FREQUENCY/HFF_PRESCALER)
#define DT_HFILTER (1./HFF_FREQ)
#define HFF_UPDATE_SPEED
#define HFF_LOST_LIMIT 1000
Functions
void b2_hff_init (float init_x, float init_xdot, float init_y, float init_ydot)
void b2_hff_propagate (void)
void b2_hff_update_gps (void)
void b2_hff_update_pos (struct FloatVect2 pos, struct FloatVect2 Rpos)
void b2_hff_update_vel (struct FloatVect2 vel, struct FloatVect2 Rvel)
void b2_hff_realign (struct FloatVect2 pos, struct FloatVect2 vel)
void b2_hff_store_accel_body (void)
Variables
struct HfilterFloat b2_hff_state
float b2_hff_x_meas
float b2_hff_y_meas
float b2_hff_xd_meas
float b2_hff_yd_meas
float b2_hff_xdd_meas
float b2_hff_ydd_meas
uint16_t b2_hff_lost_limit
uint16_t b2_hff_lost_counter
struct HfilterFloat * b2_hff_rb_last
int lag_counter_err
int save_counter
Detailed Description
Horizontal filter (x,y) to estimate position and velocity.
Definition in file hf_float.h.
Macro Definition Documentation
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
Definition at line 39 of file hf_float.h.
#define DT_HFILTER (1./HFF_FREQ)
Definition at line 54 of file hf_float.h.
Referenced by b2_hff_init(), b2_hff_propagate_x(), and b2_hff_propagate_y().
#define HFF_FREQ (AHRS_PROPAGATE_FREQUENCY/HFF_PRESCALER)
Definition at line 53 of file hf_float.h.
#define HFF_LOST_LIMIT 1000
Definition at line 89 of file hf_float.h.
Referenced by b2_hff_init().
#define HFF_STATE_SIZE 2
Definition at line 36 of file hf_float.h.
Referenced by b2_hff_init_x(), and b2_hff_init_y().
#define HFF_UPDATE_SPEED
Definition at line 56 of file hf_float.h.
Function Documentation
void b2_hff_init (float init_x, float init_xdot, float init_y, float init_ydot)
Definition at line 242 of file hf_float.c.
References acc_body, ACC_RB_MAXN, b2_hff_init_x(), b2_hff_init_y(), b2_hff_lost_counter, b2_hff_lost_limit, b2_hff_ps_counter, b2_hff_rb_n, b2_hff_state, DT_HFILTER, FALSE, HFF_LOST_LIMIT, HFF_R_POS, HFF_R_SPEED, HfilterFloat::lag_counter, lag_counter_err, AccBuf::n, past_save_counter, AccBuf::r, Rgps_pos, Rgps_vel, HfilterFloat::rollback, save_counter, SAVE_DONE, AccBuf::size, and AccBuf::w.
Referenced by ins_init().
void b2_hff_propagate (void)
Definition at line 426 of file hf_float.c.
References acc_body_mean, ACCEL_BFP_OF_REAL, ACCEL_FLOAT_OF_BFP, b2_hff_compute_accel_body_mean(), b2_hff_lost_counter, b2_hff_lost_limit, b2_hff_propagate_x(), b2_hff_propagate_y(), b2_hff_ps_counter, b2_hff_rb_n, b2_hff_state, b2_hff_store_accel_body(), b2_hff_xdd_meas, b2_hff_ydd_meas, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, INT32_RMAT_TRANSP_VMULT, HfilterFloat::lag_counter, POS_BFP_OF_REAL, PRINT_DBG, HfilterFloat::rollback, save_counter, SPEED_BFP_OF_REAL, stateGetNedToBodyRMat_i(), HfilterFloat::x, NedCoor_i::x, Int32Vect3::x, HfilterFloat::xdot, HfilterFloat::xdotdot, HfilterFloat::y, NedCoor_i::y, Int32Vect3::y, HfilterFloat::ydot, and HfilterFloat::ydotdot.
Referenced by ins_propagate().
void b2_hff_realign (struct FloatVect2 pos, struct FloatVect2 vel)
Definition at line 558 of file hf_float.c.
References b2_hff_rb_n, b2_hff_state, past_save_counter, save_counter, SAVE_DONE, FloatVect2::x, HfilterFloat::x, HfilterFloat::xdot, FloatVect2::y, HfilterFloat::y, and HfilterFloat::ydot.
Referenced by ins_realign_h(), and ins_update_gps().
void b2_hff_store_accel_body (void)
Definition at line 119 of file hf_float.c.
References acc_body, Imu::accel, Imu::body_to_imu_rmat, AccBuf::buf, imu, INT32_RMAT_TRANSP_VMULT, AccBuf::n, AccBuf::r, AccBuf::size, and AccBuf::w.
Referenced by b2_hff_propagate().
void b2_hff_update_gps (void)
Definition at line 493 of file hf_float.c.
References ACCEL_BFP_OF_REAL, b2_hff_lost_counter, b2_hff_rb_n, b2_hff_state, b2_hff_update_gps(), b2_hff_update_x(), b2_hff_update_xdot(), b2_hff_update_y(), b2_hff_update_ydot(), gps, HFF_R_POS_MIN, HFF_R_SPEED_MIN, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, HfilterFloat::lag_counter, lag_counter_err, GpsState::pacc, past_save_counter, POS_BFP_OF_REAL, PRINT_DBG, Rgps_pos, Rgps_vel, HfilterFloat::rollback, GpsState::sacc, save_counter, SPEED_BFP_OF_REAL, TRUE, HfilterFloat::x, NedCoor_i::x, HfilterFloat::xdot, HfilterFloat::xdotdot, HfilterFloat::y, NedCoor_i::y, HfilterFloat::ydot, and HfilterFloat::ydotdot.
Referenced by b2_hff_update_gps(), and ins_update_gps().
void b2_hff_update_pos (struct FloatVect2 pos, struct FloatVect2 Rpos)
Definition at line 646 of file hf_float.c.
References b2_hff_state, b2_hff_update_x(), b2_hff_update_y(), FloatVect2::x, and FloatVect2::y.
Referenced by track_event().
void b2_hff_update_vel (struct FloatVect2 vel, struct FloatVect2 Rvel)
Definition at line 717 of file hf_float.c.
References b2_hff_state, b2_hff_update_xdot(), b2_hff_update_ydot(), FloatVect2::x, and FloatVect2::y.
Variable Documentation
uint16_t b2_hff_lost_counter
Definition at line 217 of file hf_float.c.
Referenced by b2_hff_init(), b2_hff_propagate(), b2_hff_update_gps(), and track_event().
uint16_t b2_hff_lost_limit
Definition at line 216 of file hf_float.c.
Referenced by b2_hff_init(), and b2_hff_propagate().
struct HfilterFloat* b2_hff_rb_last
Definition at line 202 of file hf_float.c.
struct HfilterFloat b2_hff_state
Definition at line 86 of file hf_float.c.
Referenced by b2_hff_init(), b2_hff_init_x(), b2_hff_init_y(), b2_hff_propagate(), b2_hff_realign(), b2_hff_update_gps(), b2_hff_update_pos(), b2_hff_update_vel(), and track_event().
float b2_hff_x_meas
Definition at line 98 of file hf_float.c.
Referenced by b2_hff_update_x().
float b2_hff_xd_meas
Definition at line 94 of file hf_float.c.
Referenced by b2_hff_update_xdot().
float b2_hff_xdd_meas
Definition at line 90 of file hf_float.c.
Referenced by b2_hff_propagate(), and b2_hff_propagate_x().
float b2_hff_y_meas
Definition at line 99 of file hf_float.c.
Referenced by b2_hff_update_y().
float b2_hff_yd_meas
Definition at line 95 of file hf_float.c.
Referenced by b2_hff_update_ydot().
float b2_hff_ydd_meas
Definition at line 91 of file hf_float.c.
Referenced by b2_hff_propagate(), and b2_hff_propagate_y().
int lag_counter_err
Definition at line 207 of file hf_float.c.
Referenced by b2_hff_init(), and b2_hff_update_gps().
int save_counter
Definition at line 210 of file hf_float.c.
Referenced by b2_hff_init(), b2_hff_propagate(), b2_hff_realign(), and b2_hff_update_gps().