Paparazzi UAS: sw/airborne/peripherals/hmc58xx.h File Reference
hmc58xx.h File Reference
#include "std.h"
#include "mcu_periph/i2c.h"
#include "math/pprz_algebra_int.h"
#include "peripherals/hmc58xx_regs.h"
Data Structures
struct Hmc58xxConfig
struct Hmc58xx
Enumerations
enum Hmc58xxConfStatus {
HMC_CONF_UNINIT, HMC_CONF_CRA, HMC_CONF_CRB, HMC_CONF_MODE,
HMC_CONF_DONE
}
config status states
enum Hmc58xxType { HMC_TYPE_5843, HMC_TYPE_5883 }
Functions
void hmc58xx_init (struct Hmc58xx *hmc, struct i2c_periph *i2c_p, uint8_t addr)
Initialize Hmc58xx struct and set default config options.
void hmc58xx_start_configure (struct Hmc58xx *hmc)
void hmc58xx_read (struct Hmc58xx *hmc)
void hmc58xx_event (struct Hmc58xx *hmc)
static void hmc58xx_periodic (struct Hmc58xx *hmc)
convenience function: read or start configuration if not already initialized
Enumeration Type Documentation
enum Hmc58xxConfStatus
config status states
Enumerator:
HMC_CONF_UNINIT
HMC_CONF_CRA
HMC_CONF_CRB
HMC_CONF_MODE
HMC_CONF_DONE
Definition at line 47 of file hmc58xx.h.
enum Hmc58xxType
Enumerator:
HMC_TYPE_5843
HMC_TYPE_5883
Definition at line 55 of file hmc58xx.h.
Function Documentation
void hmc58xx_event (struct Hmc58xx * hmc)
Definition at line 136 of file hmc58xx.c.
References i2c_transaction::buf, Hmc58xx::data, Hmc58xx::data_available, hmc58xx_send_config(), HMC_CONF_UNINIT, HMC_TYPE_5843, Hmc58xx::i2c_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, Hmc58xx::init_status, Hmc58xx::initialized, Int16FromBuf, i2c_transaction::status, TRUE, Hmc58xx::type, Hmc58xx::vect, Int16Vect3::x, Int16Vect3::y, and Int16Vect3::z.
Referenced by imu_aspirin_event(), imu_aspirin_i2c_event(), imu_navgo_event(), imu_ppzuav_event(), and mag_hmc58xx_module_event().
void hmc58xx_init (struct Hmc58xx * hmc, struct i2c_periph * i2c_p, uint8_t addr)
Initialize Hmc58xx struct and set default config options.
Parameters
hmc Hmc58xx struct
i2c_p I2C periperal to use
addr I2C address of HMC58xx
Definition at line 62 of file hmc58xx.c.
References Hmc58xx::config, FALSE, hmc58xx_set_default_config(), HMC_CONF_UNINIT, HMC_TYPE_5883, Hmc58xx::i2c_p, Hmc58xx::i2c_trans, I2CTransDone, Hmc58xx::init_status, Hmc58xx::initialized, i2c_transaction::slave_addr, i2c_transaction::status, and Hmc58xx::type.
Referenced by imu_impl_init(), and mag_hmc58xx_module_init().
static void hmc58xx_periodic (struct Hmc58xx * hmc) inline static
convenience function: read or start configuration if not already initialized
Definition at line 84 of file hmc58xx.h.
References hmc58xx_read(), hmc58xx_start_configure(), and Hmc58xx::initialized.
Referenced by imu_periodic(), and mag_hmc58xx_module_periodic().
void hmc58xx_read (struct Hmc58xx * hmc)
Definition at line 123 of file hmc58xx.c.
References i2c_transaction::buf, HMC58XX_REG_DATXM, Hmc58xx::i2c_p, i2c_submit(), Hmc58xx::i2c_trans, I2CTransDone, I2CTransTxRx, Hmc58xx::initialized, i2c_transaction::len_r, i2c_transaction::len_w, i2c_transaction::status, and i2c_transaction::type.
Referenced by hmc58xx_periodic().
void hmc58xx_start_configure (struct Hmc58xx * hmc)
Definition at line 112 of file hmc58xx.c.
References hmc58xx_send_config(), HMC_CONF_UNINIT, Hmc58xx::i2c_trans, I2CTransDone, I2CTransSuccess, Hmc58xx::init_status, and i2c_transaction::status.
Referenced by hmc58xx_periodic().