Paparazzi UAS: sw/airborne/lisa/test/hs_gyro.c File Reference
hs_gyro.c File Reference
#include <inttypes.h>
#include "std.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
#include "subsystems/imu.h"
Defines
#define MEASURED_SENSOR gyro_unscaled.p
#define MEASURED_SENSOR_NB 0
#define NB_SAMPLES 20
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void on_gyro_accel_event (void)
static void on_accel_event (void)
static void on_mag_event (void)
int main (void)
Define Documentation
#define MEASURED_SENSOR gyro_unscaled.p
Definition at line 38 of file hs_gyro.c.
#define MEASURED_SENSOR_NB 0
Definition at line 39 of file hs_gyro.c.
Referenced by on_gyro_accel_event().
#define NB_SAMPLES 20
Definition at line 89 of file hs_gyro.c.
Referenced by on_gyro_accel_event().
Function Documentation
int main (void)
Definition at line 51 of file hs_gyro.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) [inline, static]
Definition at line 79 of file hs_gyro.c.
References ImuEvent, on_accel_event(), on_gyro_accel_event(), and on_mag_event().
Referenced by main().
static void main_init (void) [inline, static]
static void main_periodic_task (void) [inline, static]
Definition at line 70 of file hs_gyro.c.
References DefaultChannel, DefaultDevice, imu_periodic(), LED_PERIODIC, and LED_TOGGLE.
Referenced by main().
static void on_accel_event (void) [inline, static]
Definition at line 86 of file hs_gyro.c.
Referenced by main_event_task().
static void on_gyro_accel_event (void) [inline, static]
Definition at line 91 of file hs_gyro.c.
References DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, ImuScaleAccel, ImuScaleGyro, LED_TOGGLE, MEASURED_SENSOR_NB, NB_SAMPLES, Int32Rates::p, Int32Rates::q, and Int32Rates::r.
Referenced by main_event_task().
static void on_mag_event (void) [inline, static]
Definition at line 118 of file hs_gyro.c.
Referenced by main_event_task().