Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/obsolete/i2c_arch.old.c File Reference
i2c_arch.old.c File Reference
#include "mcu_periph/i2c.h"
#include <stm32/rcc.h>
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
Macros
#define I2C_BUSY 0x20
#define SPURIOUS_INTERRUPT(_periph, _status, _event) { if (_status == I2CAddrWrSent) abort_and_reset(_periph);}
#define OUT_OF_SYNC_STATE_MACHINE(_periph, _status, _event) { abort_and_reset(_periph);}
Functions
static void start_transaction (struct i2c_periph *p)
static void end_of_transaction (struct i2c_periph *p)
static void i2c_hard_reset (struct i2c_periph *p)
static void i2c_reset_init (struct i2c_periph *p)
static void i2c_delay (void)
static void i2c_apply_config (struct i2c_periph *p)
static void abort_and_reset (struct i2c_periph *p)
bool_t i2c_idle (struct i2c_periph *p)
bool_t i2c_submit (struct i2c_periph *p, struct i2c_transaction *t)
Macro Definition Documentation
#define I2C_BUSY 0x20
Definition at line 14 of file i2c_arch.old.c.
#define OUT_OF_SYNC_STATE_MACHINE (_periph, _status, _event) { abort_and_reset(_periph);}
Definition at line 22 of file i2c_arch.old.c.
#define SPURIOUS_INTERRUPT (_periph, _status, _event) { if (_status == I2CAddrWrSent) abort_and_reset(_periph);}
Definition at line 21 of file i2c_arch.old.c.
Function Documentation
static void abort_and_reset (struct i2c_periph * p) inline static
Definition at line 70 of file i2c_arch.old.c.
References end_of_transaction(), i2c_hard_reset(), I2CTransFailed, i2c_periph::reg_addr, i2c_transaction::status, i2c_periph::trans, and i2c_periph::trans_extract_idx.
static void end_of_transaction (struct i2c_periph * p) inline static
Definition at line 57 of file i2c_arch.old.c.
References I2C_TRANSACTION_QUEUE_LEN, I2CIdle, start_transaction(), i2c_periph::status, i2c_periph::trans_extract_idx, and i2c_periph::trans_insert_idx.
Referenced by abort_and_reset().
static void i2c_apply_config (struct i2c_periph * p) inline static
Definition at line 52 of file i2c_arch.old.c.
References i2c_periph::init_struct, and i2c_periph::reg_addr.
static void i2c_delay (void) inline static
Definition at line 47 of file i2c_arch.old.c.
static void i2c_hard_reset (struct i2c_periph * p) inline static
Referenced by abort_and_reset().
static void i2c_reset_init (struct i2c_periph * p) inline static
static void start_transaction (struct i2c_periph * p) static
Definition at line 611 of file i2c_arch.old.c.
References I2CStartRequested, i2c_periph::idx_buf, i2c_periph::reg_addr, and i2c_periph::status.
Referenced by end_of_transaction(), and i2c_submit().