Paparazzi UAS: sw/airborne/subsystems/imu/imu_aspirin.c File Reference
imu_aspirin.c File Reference
Driver for the Aspirin v1.x IMU.
#include "subsystems/imu.h"
#include "peripherals/hmc5843.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/spi.h"
Macros
#define ASPIRIN_ACCEL_RATE ADXL345_RATE_800
#define ADXL345_SLAVE_IDX SPI_SLAVE2
#define ADXL345_SPI_DEV spi2
#define ITG3200_SMPLRT_DIV 0x0E
#define ITG3200_FS_SEL 0x3
#define ITG3200_DLPF_CFG ITG3200_DLPF_256HZ
#define ITG3200_CLK_SEL 0x1
#define I2C2TransmitWithRetry(_t, _s_addr, _len)
Functions
void adxl345_write_to_reg (uint8_t _reg, uint8_t _val)
static void adxl345_trans_cb (struct spi_transaction *trans)
static void configure_gyro (void)
static void configure_accel (void)
static void send_i2c_msg_with_retry (struct i2c_transaction *t)
void imu_impl_init (void)
void imu_periodic (void)
Variables
struct ImuAspirin imu_aspirin
struct spi_transaction aspirin_adxl345
Detailed Description
Driver for the Aspirin v1.x IMU.
Definition in file imu_aspirin.c.
Macro Definition Documentation
#define ADXL345_SLAVE_IDX SPI_SLAVE2
Definition at line 39 of file imu_aspirin.c.
Referenced by imu_impl_init().
#define ADXL345_SPI_DEV spi2
Definition at line 43 of file imu_aspirin.c.
Referenced by imu_periodic().
#define ASPIRIN_ACCEL_RATE ADXL345_RATE_800
Definition at line 34 of file imu_aspirin.c.
Referenced by configure_accel().
#define I2C2TransmitWithRetry (_t, _s_addr, _len)
Value:
{ \
    _t.type = I2CTransTx;                           \
    _t.slave_addr = _s_addr;                        \
    _t.len_r = 0;                                   \
    _t.len_w = _len;                                \
    send_i2c_msg_with_retry(&(_t));                 \
  }
Definition at line 90 of file imu_aspirin.c.
Referenced by configure_gyro().
#define ITG3200_CLK_SEL 0x1
Definition at line 58 of file imu_aspirin.c.
Referenced by configure_gyro().
#define ITG3200_DLPF_CFG ITG3200_DLPF_256HZ
Definition at line 54 of file imu_aspirin.c.
Referenced by configure_gyro().
#define ITG3200_FS_SEL 0x3
Definition at line 51 of file imu_aspirin.c.
Referenced by configure_gyro().
#define ITG3200_SMPLRT_DIV 0x0E
Definition at line 48 of file imu_aspirin.c.
Referenced by configure_gyro().
Function Documentation
static void adxl345_trans_cb (struct spi_transaction * trans) static
Definition at line 152 of file imu_aspirin.c.
References ImuAspirin::accel_available, AspirinStatusUninit, imu_aspirin, ImuAspirin::status, and TRUE.
Referenced by imu_impl_init().
void adxl345_write_to_reg (uint8_t _reg, uint8_t _val)
Definition at line 20 of file imu_aspirin_arch.c.
static void configure_accel (void) static
Definition at line 194 of file imu_aspirin.c.
References ADXL345_FULL_RES, ADXL345_INT_INVERT, ADXL345_RANGE_16G, ADXL345_REG_BW_RATE, ADXL345_REG_DATA_FORMAT, ADXL345_REG_INT_ENABLE, ADXL345_REG_POWER_CTL, adxl345_write_to_reg(), and ASPIRIN_ACCEL_RATE.
Referenced by imu_periodic().
static void configure_gyro (void) static
Definition at line 159 of file imu_aspirin.c.
References i2c_transaction::buf, I2C2TransmitWithRetry, ImuAspirin::i2c_trans_gyro, imu_aspirin, ITG3200_CLK_SEL, ITG3200_DLPF_CFG, ITG3200_FS_SEL, ITG3200_I2C_ADDR, ITG3200_REG_DLPF_FS, ITG3200_REG_INT_CFG, ITG3200_REG_PWR_MGM, ITG3200_REG_SMPLRT_DIV, and ITG3200_SMPLRT_DIV.
Referenced by imu_periodic().
void imu_impl_init (void)
Definition at line 98 of file imu_aspirin.c.
References ImuAspirin::accel_available, ImuAspirin::accel_rx_buf, ImuAspirin::accel_tx_buf, ADXL345_SLAVE_IDX, adxl345_trans_cb(), spi_transaction::after_cb, aspirin_adxl345, AspirinStatusUninit, spi_transaction::bitorder, i2c_transaction::buf, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, FALSE, ImuAspirin::gyro_available_blaaa, hmc5843_init(), ImuAspirin::i2c_trans_gyro, I2CTransFailed, I2CTransTxRx, imu_aspirin, imu_aspirin_arch_init(), spi_transaction::input_buf, spi_transaction::input_length, ITG3200_ADDR, ITG3200_REG_GYRO_XOUT_H, i2c_transaction::len_r, i2c_transaction::len_w, ImuAspirin::mag_available, spi_transaction::output_buf, spi_transaction::output_length, spi_transaction::select, i2c_transaction::slave_addr, spi_transaction::slave_idx, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, i2c_transaction::status, ImuAspirin::status, and i2c_transaction::type.
void imu_periodic (void)
Definition at line 131 of file imu_aspirin.c.
References ImuAspirin::accel_tx_buf, ADXL345_REG_DATA_X0, ADXL345_SPI_DEV, aspirin_adxl345, AspirinStatusIdle, AspirinStatusUninit, configure_accel(), configure_gyro(), ImuAspirin::gyro_available_blaaa, hmc5843_periodic(), imu_aspirin, spi_submit(), ImuAspirin::status, ImuAspirin::time_since_last_accel_reading, ImuAspirin::time_since_last_reading, and TRUE.
static void send_i2c_msg_with_retry (struct i2c_transaction * t) static
Definition at line 76 of file imu_aspirin.c.
References i2c_submit(), I2CTransFailed, I2CTransPending, I2CTransRunning, I2CTransSuccess, and i2c_transaction::status.
Variable Documentation
struct spi_transaction aspirin_adxl345
Definition at line 64 of file imu_aspirin.c.
Referenced by imu_impl_init(), and imu_periodic().
struct ImuAspirin imu_aspirin
Definition at line 62 of file imu_aspirin.c.
Referenced by accel_copy_spi(), adxl345_trans_cb(), configure_gyro(), dma1_c4_irq_handler(), exti15_10_irq_handler(), exti15_10_isr(), gyro_copy_i2c(), gyro_read_i2c(), imu_impl_init(), imu_periodic(), and ImuEvent().