Paparazzi UAS: sw/airborne/subsystems/imu/imu_ppzuav.h File Reference
imu_ppzuav.h File Reference
Driver for the PPZUAV IMU.
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/itg3200.h"
#include "peripherals/hmc58xx.h"
#include "peripherals/adxl345_i2c.h"
Data Structures
struct ImuPpzuav
Macros
#define IMU_GYRO_P_SENS 4.973
default gyro sensitivy and neutral from the datasheet ITG3200 has 14.375 LSB/(deg/s) sens = 1/14.375 * pi/180 * 2^INT32_RATE_FRAC sens = 1/14.375 * pi/180 * 4096 = 4.973126
#define IMU_GYRO_P_SENS_NUM 4973
#define IMU_GYRO_P_SENS_DEN 1000
#define IMU_GYRO_Q_SENS 4.973
#define IMU_GYRO_Q_SENS_NUM 4973
#define IMU_GYRO_Q_SENS_DEN 1000
#define IMU_GYRO_R_SENS 4.973
#define IMU_GYRO_R_SENS_NUM 4973
#define IMU_GYRO_R_SENS_DEN 1000
#define IMU_ACCEL_X_SENS 37.91
default accel sensitivy from the ADXL345 datasheet sensitivity of x & y axes depends on supply voltage:
#define IMU_ACCEL_X_SENS_NUM 3791
#define IMU_ACCEL_X_SENS_DEN 100
#define IMU_ACCEL_Y_SENS 37.91
#define IMU_ACCEL_Y_SENS_NUM 3791
#define IMU_ACCEL_Y_SENS_DEN 100
#define IMU_ACCEL_Z_SENS 39.24
#define IMU_ACCEL_Z_SENS_NUM 3924
#define IMU_ACCEL_Z_SENS_DEN 100
Functions
void imu_ppzuav_event (void)
static void ImuEvent (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Variables
struct ImuPpzuav imu_ppzuav
Detailed Description
Driver for the PPZUAV IMU.
Interface and defaults for the PPZUAV IMU.
9DoM IMU with ITG-3200, ADXL345 and HMC5843, all via I2C.
Definition in file imu_ppzuav.h.
Macro Definition Documentation
#define IMU_ACCEL_X_SENS 37.91
default accel sensitivy from the ADXL345 datasheet sensitivity of x & y axes depends on supply voltage:
256 LSB/g @ 2.5V
265 LSB/g @ 3.3V z sensitivity stays at 256 LSB/g fixed point sens: 9.81 [m/s^2] / 256 [LSB/g] * 2^INT32_ACCEL_FRAC x/y sens = 9.81 / 265 * 1024 = 37.91 z sens = 9.81 / 256 * 1024 = 39.24
Definition at line 70 of file imu_ppzuav.h.
#define IMU_ACCEL_X_SENS_DEN 100
Definition at line 72 of file imu_ppzuav.h.
#define IMU_ACCEL_X_SENS_NUM 3791
Definition at line 71 of file imu_ppzuav.h.
#define IMU_ACCEL_Y_SENS 37.91
Definition at line 73 of file imu_ppzuav.h.
#define IMU_ACCEL_Y_SENS_DEN 100
Definition at line 75 of file imu_ppzuav.h.
#define IMU_ACCEL_Y_SENS_NUM 3791
Definition at line 74 of file imu_ppzuav.h.
#define IMU_ACCEL_Z_SENS 39.24
Definition at line 76 of file imu_ppzuav.h.
#define IMU_ACCEL_Z_SENS_DEN 100
Definition at line 78 of file imu_ppzuav.h.
#define IMU_ACCEL_Z_SENS_NUM 3924
Definition at line 77 of file imu_ppzuav.h.
#define IMU_GYRO_P_SENS 4.973
default gyro sensitivy and neutral from the datasheet ITG3200 has 14.375 LSB/(deg/s) sens = 1/14.375 * pi/180 * 2^INT32_RATE_FRAC sens = 1/14.375 * pi/180 * 4096 = 4.973126
Definition at line 48 of file imu_ppzuav.h.
#define IMU_GYRO_P_SENS_DEN 1000
Definition at line 50 of file imu_ppzuav.h.
#define IMU_GYRO_P_SENS_NUM 4973
Definition at line 49 of file imu_ppzuav.h.
#define IMU_GYRO_Q_SENS 4.973
Definition at line 51 of file imu_ppzuav.h.
#define IMU_GYRO_Q_SENS_DEN 1000
Definition at line 53 of file imu_ppzuav.h.
#define IMU_GYRO_Q_SENS_NUM 4973
Definition at line 52 of file imu_ppzuav.h.
#define IMU_GYRO_R_SENS 4.973
Definition at line 54 of file imu_ppzuav.h.
#define IMU_GYRO_R_SENS_DEN 1000
Definition at line 56 of file imu_ppzuav.h.
#define IMU_GYRO_R_SENS_NUM 4973
Definition at line 55 of file imu_ppzuav.h.
Function Documentation
void imu_ppzuav_event (void)
Definition at line 115 of file imu_ppzuav.c.
References ImuPpzuav::acc_adxl, Imu::accel_unscaled, ImuPpzuav::accel_valid, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, Itg3200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, Itg3200::data_available, FALSE, ImuPpzuav::gyro_itg, Imu::gyro_unscaled, ImuPpzuav::gyro_valid, hmc58xx_event(), imu, imu_ppzuav, itg3200_event(), ImuPpzuav::mag_hmc, Imu::mag_unscaled, ImuPpzuav::mag_valid, Int32Rates::p, Int32Rates::q, Int32Rates::r, Itg3200::rates, TRUE, Adxl345_I2c::vect, Hmc58xx::vect, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
static void ImuEvent (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) inline static
Definition at line 95 of file imu_ppzuav.h.
References ImuPpzuav::accel_valid, FALSE, ImuPpzuav::gyro_valid, imu_ppzuav, imu_ppzuav_event(), and ImuPpzuav::mag_valid.
Variable Documentation
struct ImuPpzuav imu_ppzuav
Definition at line 78 of file imu_ppzuav.c.
Referenced by imu_periodic(), imu_ppzuav_event(), and ImuEvent().