Paparazzi UAS: sw/airborne/subsystems/imu/imu_um6.c File Reference
imu_um6.c File Reference
Driver for CH Robotics UM6 IMU/AHRS subsystem.
#include "subsystems/imu/imu_um6.h"
#include "subsystems/imu.h"
#include "mcu_periph/sys_time.h"
Functions
void UM6_imu_align (void)
void UM6_send_packet (uint8_t *packet_buffer, uint8_t packet_length)
uint16_t UM6_calculate_checksum (uint8_t packet_buffer[], uint8_t packet_length)
bool_t UM6_verify_chk (uint8_t packet_buffer[], uint8_t packet_length)
void imu_impl_init (void)
void imu_periodic (void)
void UM6_packet_read_message (void)
void UM6_packet_parse (uint8_t c)
Variables
struct UM6Packet UM6_packet
uint8_t buf_out [IMU_UM6_BUFFER_LENGTH]
uint16_t data_chk
uint8_t PacketLength
uint8_t PacketType
uint8_t PacketAddr
enum UM6Status UM6_status
uint16_t chk_calc
uint16_t chk_rec
struct FloatVect3 UM6_accel
struct FloatRates UM6_rate
struct FloatVect3 UM6_mag
struct FloatEulers UM6_eulers
struct FloatQuat UM6_quat
Detailed Description
Driver for CH Robotics UM6 IMU/AHRS subsystem.
Takes care of configuration of the IMU, communication and parsing the received packets. See UM6 datasheet for configuration options. Should be used with AHRS subsystem.
Author
Michal Podhradsky micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu
Definition in file imu_um6.c.
Function Documentation
void imu_impl_init (void)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Definition at line 130 of file imu_um6.c.
References ImuNavgo::acc_valid, ImuNavgo::adxl, ADXL345_ADDR_ALT, adxl345_i2c_init(), buf_out, UM6Packet::chksm_error, Adxl345_I2c::config, Itg3200::config, data_chk, Itg3200Config::dlpf_cfg, FALSE, ImuNavgo::gyr_valid, UM6Packet::hdr_error, ImuNavgo::hmc, HMC58XX_ADDR, hmc58xx_init(), imu_navgo, IMU_UM6_COMMUNICATION_REG, IMU_UM6_MISC_CONFIG_REG, InitMedianFilterRatesInt, InitMedianFilterVect3Int, ImuNavgo::itg, ITG3200_ADDR_ALT, ITG3200_DLPF_10HZ, itg3200_init(), ImuNavgo::mag_valid, median_mag, UM6Packet::msg_available, UM6Packet::msg_idx, NAVGO_ACCEL_RATE, Adxl345Config::rate, Itg3200Config::smplrt_div, UM6Packet::status, UM6_calculate_checksum(), UM6_imu_align(), UM6_packet, UM6_send_packet(), UM6_status, UM6PacketWaiting, and UM6Uninit.
void imu_periodic (void)
Definition at line 189 of file imu_um6.c.
References ImuNavgo::adxl, adxl345_i2c_periodic(), ImuNavgo::hmc, hmc58xx_periodic(), imu_navgo, ins, ImuNavgo::itg, itg3200_periodic(), NAVGO_ACCEL_RATE, PERIODIC_FREQUENCY, TRUE, UM6_imu_align(), and Ins::vf_realign.
uint16_t UM6_calculate_checksum (uint8_t packet_buffer[], uint8_t packet_length) inline
Definition at line 66 of file imu_um6.c.
Referenced by imu_impl_init(), UM6_imu_align(), and UM6_verify_chk().
void UM6_imu_align (void) inline
Definition at line 80 of file imu_um6.c.
References buf_out, data_chk, IMU_UM6_RESET_EKF_CMD, IMU_UM6_SET_ACCEL_REF, IMU_UM6_SET_MAG_REF, IMU_UM6_ZERO_GYROS_CMD, UM6_calculate_checksum(), UM6_send_packet(), UM6_status, UM6Running, and UM6Uninit.
Referenced by imu_impl_init(), and imu_periodic().
void UM6_packet_parse (uint8_t c)
Definition at line 286 of file imu_um6.c.
References c, UM6Packet::chksm_error, FALSE, UM6Packet::hdr_error, UM6Packet::msg_available, UM6Packet::msg_buf, UM6Packet::msg_idx, PacketAddr, PacketLength, PacketType, UM6Packet::status, TRUE, UM6_packet, UM6_verify_chk(), UM6PacketReadingAddr, UM6PacketReadingData, UM6PacketReadingN, UM6PacketReadingPT, UM6PacketReadingS, and UM6PacketWaiting.
void UM6_packet_read_message (void)
Definition at line 208 of file imu_um6.c.
References Imu::accel, ACCELS_BFP_OF_REAL, ahrs_impl, EULERS_BFP_OF_REAL, EULERS_SMUL, Imu::gyro, imu, IMU_UM6_ACCEL_PROC, IMU_UM6_DATA_OFFSET, IMU_UM6_EULER, IMU_UM6_GYRO_PROC, IMU_UM6_MAG_PROC, IMU_UM6_QUAT, AhrsIntExternQuat::ltp_to_imu_euler, AhrsIntExternQuat::ltp_to_imu_quat, Imu::mag, MAGS_BFP_OF_REAL, UM6Packet::msg_buf, FloatRates::p, PacketAddr, PacketLength, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatQuat::qi, QUAT_BFP_OF_REAL, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatRates::r, RATES_BFP_OF_REAL, RATES_SMUL, FloatEulers::theta, UM6_accel, UM6_eulers, UM6_mag, UM6_packet, UM6_quat, UM6_rate, UM6_status, UM6Running, VECT3_SMUL, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
void UM6_send_packet (uint8_t * packet_buffer, uint8_t packet_length) inline
Definition at line 74 of file imu_um6.c.
References UM6Link.
Referenced by imu_impl_init(), and UM6_imu_align().
bool_t UM6_verify_chk (uint8_t packet_buffer[], uint8_t packet_length) inline
Definition at line 60 of file imu_um6.c.
References chk_calc, chk_rec, and UM6_calculate_checksum().
Referenced by UM6_packet_parse().
Variable Documentation
uint8_t buf_out[IMU_UM6_BUFFER_LENGTH]
Definition at line 38 of file imu_um6.c.
Referenced by imu_impl_init(), and UM6_imu_align().
uint16_t chk_calc
Definition at line 46 of file imu_um6.c.
Referenced by UM6_verify_chk().
uint16_t chk_rec
Definition at line 47 of file imu_um6.c.
Referenced by UM6_verify_chk().
uint16_t data_chk
Definition at line 39 of file imu_um6.c.
Referenced by imu_impl_init(), and UM6_imu_align().
uint8_t PacketAddr
Definition at line 43 of file imu_um6.c.
Referenced by UM6_packet_parse(), and UM6_packet_read_message().
uint8_t PacketLength
Definition at line 41 of file imu_um6.c.
Referenced by UM6_packet_parse(), and UM6_packet_read_message().
uint8_t PacketType
Definition at line 42 of file imu_um6.c.
Referenced by UM6_packet_parse().
struct FloatVect3 UM6_accel
Definition at line 49 of file imu_um6.c.
Referenced by UM6_packet_read_message().
struct FloatEulers UM6_eulers
Definition at line 52 of file imu_um6.c.
Referenced by UM6_packet_read_message().
struct FloatVect3 UM6_mag
Definition at line 51 of file imu_um6.c.
Referenced by UM6_packet_read_message().
struct UM6Packet UM6_packet
Definition at line 37 of file imu_um6.c.
Referenced by imu_impl_init(), UM6_packet_parse(), and UM6_packet_read_message().
struct FloatQuat UM6_quat
Definition at line 53 of file imu_um6.c.
Referenced by UM6_packet_read_message().
struct FloatRates UM6_rate
Definition at line 50 of file imu_um6.c.
Referenced by UM6_packet_read_message().
enum UM6Status UM6_status
Definition at line 44 of file imu_um6.c.
Referenced by imu_impl_init(), UM6_imu_align(), and UM6_packet_read_message().