Paparazzi UAS: sw/airborne/subsystems/imu.c File Reference
imu.c File Reference
Inertial Measurement Unit interface.
#include "subsystems/imu.h"
Functions
void imu_init (void)
void imu_float_init (struct ImuFloat *imuf)
Variables
struct Imu imu
global IMU state
Detailed Description
Inertial Measurement Unit interface.
Definition in file imu.c.
Function Documentation
void imu_float_init (struct ImuFloat * imuf)
Definition at line 62 of file imu.c.
References ImuFloat::body_to_imu_eulers, ImuFloat::body_to_imu_quat, ImuFloat::body_to_imu_rmat, EULERS_ASSIGN, FLOAT_QUAT_NORMALIZE, FLOAT_QUAT_OF_EULERS, FLOAT_RMAT_OF_EULERS, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, and IMU_BODY_TO_IMU_THETA.
void imu_init (void)
Definition at line 30 of file imu.c.
References Imu::accel_neutral, ANGLE_BFP_OF_REAL, Imu::body_to_imu_quat, Imu::body_to_imu_rmat, Imu::gyro_neutral, imu, IMU_ACCEL_X_NEUTRAL, IMU_ACCEL_Y_NEUTRAL, IMU_ACCEL_Z_NEUTRAL, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, IMU_GYRO_P_NEUTRAL, IMU_GYRO_Q_NEUTRAL, IMU_GYRO_R_NEUTRAL, imu_impl_init(), INT32_QUAT_NORMALIZE, INT32_QUAT_OF_EULERS, INT32_RMAT_OF_EULERS, INT_VECT3_ZERO, Imu::mag_neutral, RATES_ASSIGN, and VECT3_ASSIGN.
Referenced by init_ap(), and main_init().
Variable Documentation
struct Imu imu
global IMU state
Definition at line 28 of file imu.c.