Paparazzi UAS: sw/airborne/subsystems/imu/imu_b2.c File Reference
imu_b2.c File Reference
#include "subsystems/imu.h"
#include "led.h"
Functions
void imu_impl_init (void)
void imu_periodic (void)
Function Documentation
void imu_impl_init (void)
Definition at line 25 of file imu_b2.c.
References ami601_init(), hmc5843_init(), hmc58xx_init(), max1168_init(), and ms2100_init().
void imu_periodic (void)
Definition at line 41 of file imu_b2.c.
References ami601_read(), Hmc58xxPeriodic, Max1168Periodic, and Ms2100Periodic.