Paparazzi UAS: sw/airborne/subsystems/imu/imu_crista.c File Reference
imu_crista.c File Reference
#include "subsystems/imu.h"
Functions
void imu_impl_init (void)
void imu_periodic (void)
Variables
volatile bool_t ADS8344_available
uint16_t ADS8344_values [ADS8344_NB_CHANNELS]
Function Documentation
void imu_impl_init (void)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Definition at line 27 of file imu_crista.c.
References ADS8344_available, ami601_init(), FALSE, hmc5843_init(), and imu_crista_arch_init().
void imu_periodic (void)
Definition at line 42 of file imu_crista.c.
References ami601_read(), hmc5843_periodic(), and ImuCristaArchPeriodic.
Variable Documentation
volatile bool_t ADS8344_available
Definition at line 24 of file imu_crista.c.
uint16_t ADS8344_values[ADS8344_NB_CHANNELS]
Definition at line 25 of file imu_crista.c.