Paparazzi UAS: sw/airborne/subsystems/imu/imu_aspirin_i2c.h File Reference
imu_aspirin_i2c.h File Reference
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/itg3200.h"
#include "peripherals/hmc58xx.h"
#include "peripherals/adxl345_i2c.h"
#include "subsystems/imu/imu_aspirin_defaults.h"
Data Structures
struct ImuAspirinI2c
Functions
void imu_aspirin_i2c_event (void)
static void ImuEvent (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Variables
struct ImuAspirinI2c imu_aspirin
Function Documentation
void imu_aspirin_i2c_event (void)
Definition at line 129 of file imu_aspirin_i2c.c.
References ImuAspirin::acc_adxl, Imu::accel_unscaled, ImuAspirin::accel_valid, adxl345_i2c_event(), Adxl345_Spi::data, Hmc58xx::data, Itg3200::data, Adxl345_Spi::data_available, Hmc58xx::data_available, Itg3200::data_available, FALSE, ImuAspirin::gyro_itg, Imu::gyro_unscaled, ImuAspirin::gyro_valid, hmc58xx_event(), imu, imu_aspirin, itg3200_event(), ImuAspirin::mag_hmc, Imu::mag_unscaled, ImuAspirin::mag_valid, Itg3200::rates, RATES_COPY, TRUE, Adxl345_Spi::vect, Hmc58xx::vect, VECT3_COPY, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
static void ImuEvent (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) inline static
Definition at line 56 of file imu_aspirin_i2c.h.
References ImuAspirin::accel_valid, FALSE, ImuAspirin::gyro_valid, imu_aspirin, imu_aspirin_i2c_event(), and ImuAspirin::mag_valid.
Variable Documentation
struct ImuAspirinI2c imu_aspirin
Definition at line 63 of file imu_aspirin.c.
Referenced by exti15_10_isr(), imu_aspirin_event(), imu_aspirin_i2c_event(), imu_periodic(), and ImuEvent().