Paparazzi UAS: sw/airborne/subsystems/ins/ins_int.c File Reference
ins_int.c File Reference
#include "subsystems/ins/ins_int.h"
#include "subsystems/imu.h"
#include "subsystems/sensors/baro.h"
#include "subsystems/gps.h"
#include "generated/airframe.h"
#include "math/pprz_geodetic_int.h"
#include "generated/flight_plan.h"
Functions
void ins_init ()
INS initialization.
void ins_periodic (void)
INS periodic call.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
void ins_realign_v (float z)
INS vertical realign.
void ins_propagate ()
Propagation.
void ins_update_baro ()
Update INS state with barometer measurements.
void ins_update_gps (void)
Update INS state with GPS measurements.
void ins_update_sonar ()
Update INS state with sonar measurements.
Variables
struct LtpDef_i ins_ltp_def
Ins implementation state (fixed point)
bool_t ins_ltp_initialised
struct NedCoor_i ins_gps_pos_cm_ned
struct NedCoor_i ins_gps_speed_cm_s_ned
struct NedCoor_i ins_ltp_pos
struct NedCoor_i ins_ltp_speed
struct NedCoor_i ins_ltp_accel
Function Documentation
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 76 of file ins_int.c.
References LlaCoor_i::alt, b2_hff_init(), ecef_of_lla_i(), FALSE, Ins::hf_realign, LtpDef_i::hmsl, ins, ins_baro_initialised, ins_ltp_accel, ins_ltp_def, ins_ltp_initialised, ins_ltp_pos, ins_ltp_speed, INS_RUNNING, ins_update_on_agl, INT32_RAD_OF_DEG, INT32_VECT3_ZERO, LlaCoor_i::lat, LlaCoor_i::lon, ltp_def_from_ecef_i(), stateSetLocalOrigin_i(), Ins::status, TRUE, Ins::vf_realign, and vff_init().
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 117 of file ins_int.c.
void ins_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each INS algorithm.
Definition at line 132 of file ins_int.c.
References Imu::accel, ACCEL_BFP_OF_REAL, ACCEL_FLOAT_OF_BFP, b2_hff_propagate(), baro, Imu::body_to_imu_rmat, BS_RUNNING, imu, ins_baro_initialised, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, INS_NED_TO_STATE, INT32_RMAT_TRANSP_VMULT, POS_BFP_OF_REAL, SPEED_BFP_OF_REAL, stateGetNedToBodyRMat_i(), Baro::status, vff_propagate(), vff_z, vff_zdot, vff_zdotdot, NedCoor_i::x, Int32Vect3::x, NedCoor_i::y, Int32Vect3::y, NedCoor_i::z, and Int32Vect3::z.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
Parameters:
pos new horizontal position to set
speed new horizontal speed to set Needs to be implemented by each INS algorithm.
Definition at line 120 of file ins_int.c.
References b2_hff_realign().
void ins_realign_v (float z)
INS vertical realign.
Parameters:
z new altitude to set Needs to be implemented by each INS algorithm.
Definition at line 126 of file ins_int.c.
References vff_realign(), and EcefCoor_i::z.
void ins_update_baro (void)
Update INS state with barometer measurements.
Reads the global baro data struct. Needs to be implemented by each INS algorithm.
Definition at line 166 of file ins_int.c.
References Baro::absolute, ACCEL_BFP_OF_REAL, baro, BS_RUNNING, FALSE, ins, ins_baro_alt, ins_baro_initialised, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, INS_NED_TO_STATE, ins_qfe, ins_sonar_offset, POS_BFP_OF_REAL, POS_FLOAT_OF_BFP, sonar_meas, SPEED_BFP_OF_REAL, Baro::status, TRUE, Ins::vf_realign, vff_realign(), vff_update(), vff_z, vff_zdot, vff_zdotdot, and NedCoor_i::z.
void ins_update_gps (void)
Update INS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each INS algorithm.
Definition at line 195 of file ins_int.c.
References LlaCoor_i::alt, b2_hff_realign(), b2_hff_update_gps(), GpsState::ecef_pos, GpsState::ecef_vel, FALSE, GpsState::fix, gps, GPS_FIX_3D, Ins::hf_realign, GpsState::hmsl, LtpDef_i::hmsl, ins, ins_gps_pos_cm_ned, ins_gps_speed_cm_s_ned, ins_ltp_def, ins_ltp_initialised, ins_ltp_pos, ins_ltp_speed, INS_NED_TO_STATE, INT32_POS_OF_CM_DEN, INT32_POS_OF_CM_NUM, INT32_SPEED_OF_CM_S_DEN, INT32_SPEED_OF_CM_S_NUM, INT32_VECT2_RSHIFT, INT32_VECT2_SCALE_2, LtpDef_i::lla, GpsState::lla_pos, ltp_def_from_ecef_i(), ned_of_ecef_point_i(), ned_of_ecef_vect_i(), stateSetLocalOrigin_i(), TRUE, VECT2_ADD, VECT2_ASSIGN, VECT2_COPY, VECT2_SDIV, NedCoor_i::x, NedCoor_i::y, and NedCoor_i::z.
void ins_update_sonar (void)
Update INS state with sonar measurements.
Reads the global #sonar data struct. Needs to be implemented by each INS algorithm.
Definition at line 253 of file ins_int.c.
References Baro::absolute, baro, BS_RUNNING, ins_qfe, ins_sonar_offset, ins_update_on_agl, sonar_meas, and Baro::status.
Variable Documentation
struct NedCoor_i ins_gps_pos_cm_ned
Definition at line 51 of file ins_int.c.
Referenced by ins_update_gps().
struct NedCoor_i ins_gps_speed_cm_s_ned
Definition at line 52 of file ins_int.c.
Referenced by ins_update_gps().
struct NedCoor_i ins_ltp_accel
Definition at line 73 of file ins_int.c.
Referenced by b2_hff_propagate(), b2_hff_update_gps(), ins_init(), ins_propagate(), ins_update_baro(), and track_event().
struct LtpDef_i ins_ltp_def
Ins implementation state (fixed point)
global INS state
Definition at line 49 of file ins_int.c.
Referenced by dl_parse_msg(), ins_init(), ins_update_gps(), nav_periodic_task(), and nav_reset_alt().
bool_t ins_ltp_initialised
Definition at line 50 of file ins_int.c.
Referenced by ins_init(), ins_update_gps(), nav_reset_reference(), track_event(), and track_init().
struct NedCoor_i ins_ltp_pos
Definition at line 71 of file ins_int.c.
Referenced by b2_hff_propagate(), b2_hff_update_gps(), booz_fms_impl_periodic(), ins_init(), ins_propagate(), ins_update_baro(), ins_update_gps(), and track_event().
struct NedCoor_i ins_ltp_speed
Definition at line 72 of file ins_int.c.
Referenced by b2_hff_propagate(), b2_hff_update_gps(), ins_init(), ins_propagate(), ins_update_baro(), ins_update_gps(), and track_event().