Paparazzi UAS: sw/airborne/subsystems/ins/ins_int_extended.c File Reference
ins_int_extended.c File Reference
#include "subsystems/ins/ins_int.h"
#include "subsystems/imu.h"
#include "subsystems/sensors/baro.h"
#include "subsystems/gps.h"
#include "generated/airframe.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
#include "state.h"
#include "subsystems/ins/vf_extended_float.h"
#include "math/pprz_geodetic_int.h"
#include "generated/flight_plan.h"
#include "filters/median_filter.h"
Defines
#define INS_SONAR_OFFSET 0
#define VFF_R_SONAR_0 0.1
#define VFF_R_SONAR_OF_M 0.2
Functions
void ins_init ()
INS initialization.
void ins_periodic (void)
INS periodic call.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
void ins_realign_v (float z)
INS vertical realign.
void ins_propagate ()
Propagation.
void ins_update_baro ()
Update INS state with barometer measurements.
void ins_update_gps (void)
Update INS state with GPS measurements.
void ins_update_sonar ()
Update INS state with sonar measurements.
Variables
struct LtpDef_i ins_ltp_def
Ins implementation state (fixed point)
bool_t ins_ltp_initialised
struct NedCoor_i ins_gps_pos_cm_ned
struct NedCoor_i ins_gps_speed_cm_s_ned
int32_t ins_qfe
bool_t ins_baro_initialised
int32_t ins_baro_alt
struct MedianFilterInt baro_median
bool_t ins_update_on_agl
int32_t ins_sonar_alt
int32_t ins_sonar_offset
struct MedianFilterInt sonar_median
struct NedCoor_i ins_ltp_pos
struct NedCoor_i ins_ltp_speed
struct NedCoor_i ins_ltp_accel
Define Documentation
#define INS_SONAR_OFFSET 0
Definition at line 78 of file ins_int_extended.c.
Referenced by ins_init().
#define VFF_R_SONAR_0 0.1
Definition at line 80 of file ins_int_extended.c.
Referenced by ins_update_sonar().
#define VFF_R_SONAR_OF_M 0.2
Definition at line 81 of file ins_int_extended.c.
Referenced by ins_update_sonar().
Function Documentation
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 89 of file ins_int_extended.c.
References LlaCoor_i::alt, b2_hff_init(), baro_median, ecef_of_lla_i(), FALSE, Ins::hf_realign, LtpDef_i::hmsl, init_median_filter(), ins, ins_adof, ins_ador, ins_baro_initialised, ins_baud, ins_init_status, ins_ltp_accel, ins_ltp_def, ins_ltp_initialised, ins_ltp_pos, ins_ltp_speed, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, ins_sonar_offset, INS_SONAR_OFFSET, ins_update_on_agl, INS_VN100_SET_BAUD, ins_yaw_neutral, INS_YAW_NEUTRAL_DEFAULT, INT32_RAD_OF_DEG, INT32_VECT3_ZERO, LlaCoor_i::lat, LlaCoor_i::lon, ltp_def_from_ecef_i(), sonar_median, SpiSetCPHA(), SpiSetCPOL(), TRUE, Ins::vf_realign, and vff_init().
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 125 of file ins_int_extended.c.
References VN100_Req_Packet::CmdID, ins_configure(), last_received_packet, last_send_packet, VN100_Req_Packet::RegID, SpiStart(), VN100_CmdID_ReadRegister, VN100_REG_YMR, and VN100_REG_YMR_SIZE.
void ins_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each INS algorithm.
Definition at line 141 of file ins_int_extended.c.
References Imu::accel, ACCEL_BFP_OF_REAL, ACCEL_FLOAT_OF_BFP, b2_hff_propagate(), baro, Imu::body_to_imu_rmat, BS_RUNNING, imu, ins_baro_initialised, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, INT32_RMAT_TRANSP_VMULT, POS_BFP_OF_REAL, SPEED_BFP_OF_REAL, stateGetNedToBodyRMat_i(), Baro::status, vff_propagate(), vff_z, vff_zdot, vff_zdotdot, NedCoor_i::x, Int32Vect3::x, NedCoor_i::y, Int32Vect3::y, NedCoor_i::z, and Int32Vect3::z.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
Parameters:
pos new horizontal position to set
speed new horizontal speed to set Needs to be implemented by each INS algorithm.
Definition at line 133 of file ins_int_extended.c.
void ins_realign_v (float z)
INS vertical realign.
Parameters:
z new altitude to set Needs to be implemented by each INS algorithm.
Definition at line 137 of file ins_int_extended.c.
References vff_realign().
void ins_update_baro (void)
Update INS state with barometer measurements.
Reads the global baro data struct. Needs to be implemented by each INS algorithm.
Definition at line 170 of file ins_int_extended.c.
References Baro::absolute, ACCEL_BFP_OF_REAL, baro, baro_median, BS_RUNNING, EstimatorSetAlt, FALSE, ins, ins_baro_alt, ins_baro_initialised, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, ins_qfe, POS_BFP_OF_REAL, POS_FLOAT_OF_BFP, SPEED_BFP_OF_REAL, Baro::status, TRUE, update_median_filter(), Ins::vf_realign, vff_realign(), vff_update_baro(), vff_z, vff_zdot, vff_zdotdot, and NedCoor_i::z.
void ins_update_gps (void)
Update INS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each INS algorithm.
Definition at line 194 of file ins_int_extended.c.
References LlaCoor_i::alt, UtmCoor_f::alt, b2_hff_realign(), b2_hff_update_gps(), UtmCoor_f::east, UtmCoor_i::east, GpsState::ecef_pos, GpsState::ecef_vel, estimator_z, EstimatorSetAlt, FALSE, GpsState::fix, gps, GPS_FIX_3D, Ins::hf_realign, GpsState::hmsl, LtpDef_i::hmsl, ins, ins_gps_pos_cm_ned, ins_gps_speed_cm_s_ned, ins_ltp_def, ins_ltp_initialised, ins_ltp_pos, ins_ltp_speed, INT32_POS_OF_CM_DEN, INT32_POS_OF_CM_NUM, INT32_SPEED_OF_CM_S_DEN, INT32_SPEED_OF_CM_S_NUM, INT32_VECT2_SCALE_2, LtpDef_i::lla, GpsState::lla_pos, ltp_def_from_ecef_i(), nav_utm_zone0, ned_of_ecef_point_i(), ned_of_ecef_vect_i(), GpsState::ned_vel, UtmCoor_f::north, UtmCoor_i::north, stateSetPositionUtm_f(), stateSetSpeedNed_f(), TRUE, GpsState::utm_pos, VECT2_ASSIGN, VECT2_COPY, VECT2_SDIV, NedCoor_i::x, NedCoor_i::y, NedCoor_i::z, and UtmCoor_f::zone.
void ins_update_sonar (void)
Update INS state with sonar measurements.
Reads the global #sonar data struct. Needs to be implemented by each INS algorithm.
Definition at line 248 of file ins_int_extended.c.
References baro, BS_RUNNING, DefaultChannel, DefaultDevice, ins_baro_alt, ins_sonar_alt, ins_sonar_offset, ins_update_on_agl, POS_BFP_OF_REAL, POS_FLOAT_OF_BFP, sonar_meas, sonar_median, stabilization_cmd, Baro::status, update_median_filter(), variance_float(), vff_offset, VFF_R_SONAR_0, VFF_R_SONAR_OF_M, vff_update_alt_conf(), and vff_update_offset().
Variable Documentation
struct MedianFilterInt baro_median
Definition at line 70 of file ins_int_extended.c.
Referenced by ins_init(), and ins_update_baro().
int32_t ins_baro_alt
Definition at line 68 of file ins_int_extended.c.
bool_t ins_baro_initialised
Definition at line 67 of file ins_int_extended.c.
struct NedCoor_i ins_gps_pos_cm_ned
Definition at line 57 of file ins_int_extended.c.
struct NedCoor_i ins_gps_speed_cm_s_ned
Definition at line 58 of file ins_int_extended.c.
struct NedCoor_i ins_ltp_accel
Definition at line 86 of file ins_int_extended.c.
struct LtpDef_i ins_ltp_def
Ins implementation state (fixed point)
global INS state
Definition at line 55 of file ins_int_extended.c.
bool_t ins_ltp_initialised
Definition at line 56 of file ins_int_extended.c.
struct NedCoor_i ins_ltp_pos
Definition at line 84 of file ins_int_extended.c.
struct NedCoor_i ins_ltp_speed
Definition at line 85 of file ins_int_extended.c.
int32_t ins_qfe
Definition at line 66 of file ins_int_extended.c.
int32_t ins_sonar_alt
Definition at line 74 of file ins_int_extended.c.
Referenced by ins_update_sonar().
int32_t ins_sonar_offset
Definition at line 75 of file ins_int_extended.c.
Referenced by ins_init(), ins_update_baro(), and ins_update_sonar().
bool_t ins_update_on_agl
Definition at line 73 of file ins_int_extended.c.
Referenced by ins_init(), ins_update_sonar(), and track_init().
struct MedianFilterInt sonar_median
Definition at line 76 of file ins_int_extended.c.
Referenced by ins_init(), and ins_update_sonar().