Paparazzi UAS: sw/airborne/subsystems/ins/ins_gps_passthrough.c File Reference
ins_gps_passthrough.c File Reference
Simply passes GPS position and velocity through to the state interface.
#include "subsystems/ins.h"
#include <inttypes.h>
#include <math.h>
#include "state.h"
#include "subsystems/gps.h"
#include "subsystems/nav.h"
Functions
void ins_init ()
INS initialization.
void ins_periodic (void)
INS periodic call.
void ins_update_gps (void)
Update INS state with GPS measurements.
void ins_propagate ()
Propagation.
void ins_update_baro ()
Update INS state with barometer measurements.
void ins_update_sonar ()
Update INS state with sonar measurements.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
void ins_realign_v (float z)
INS vertical realign.
Detailed Description
Simply passes GPS position and velocity through to the state interface.
Definition in file ins_gps_passthrough.c.
Function Documentation
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 35 of file ins_gps_passthrough.c.
References nav_utm_east0, nav_utm_north0, nav_utm_zone0, stateSetLocalUtmOrigin_f(), and stateSetPositionUtm_f().
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 41 of file ins_gps_passthrough.c.
void ins_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each INS algorithm.
Definition at line 64 of file ins_gps_passthrough.c.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
Parameters:
pos new horizontal position to set
speed new horizontal speed to set Needs to be implemented by each INS algorithm.
Definition at line 73 of file ins_gps_passthrough.c.
void ins_realign_v (float z)
INS vertical realign.
Parameters:
z new altitude to set Needs to be implemented by each INS algorithm.
Definition at line 76 of file ins_gps_passthrough.c.
void ins_update_baro (void)
Update INS state with barometer measurements.
Reads the global baro data struct. Needs to be implemented by each INS algorithm.
Definition at line 67 of file ins_gps_passthrough.c.
void ins_update_gps (void)
Update INS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each INS algorithm.
Definition at line 44 of file ins_gps_passthrough.c.
References UtmCoor_f::alt, UtmCoor_f::east, UtmCoor_i::east, gps, GpsState::hmsl, nav_utm_zone0, GpsState::ned_vel, UtmCoor_f::north, UtmCoor_i::north, stateSetPositionUtm_f(), stateSetSpeedNed_f(), GpsState::utm_pos, NedCoor_i::x, NedCoor_i::y, NedCoor_i::z, and UtmCoor_f::zone.
void ins_update_sonar (void)
Update INS state with sonar measurements.
Reads the global #sonar data struct. Needs to be implemented by each INS algorithm.
Definition at line 70 of file ins_gps_passthrough.c.