Paparazzi UAS: sw/airborne/subsystems/ins/ins_float.c File Reference
ins_float.c File Reference
#include "subsystems/ins/ins_float.h"
#include <inttypes.h>
#include <math.h>
#include "state.h"
#include "mcu_periph/uart.h"
#include "ap_downlink.h"
#include "subsystems/gps.h"
#include "subsystems/nav.h"
Functions
void ins_init ()
INS initialization.
void ins_periodic (void)
INS periodic call.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
void ins_realign_v (float z)
INS vertical realign.
void ins_propagate ()
Propagation.
void ins_update_baro ()
Update INS state with barometer measurements.
void ins_update_gps (void)
Update INS state with GPS measurements.
void ins_update_sonar ()
Update INS state with sonar measurements.
Variables
float estimator_z
altitude above MSL in meters
float estimator_z_dot
bool_t ins_hf_realign
bool_t ins_vf_realign
bool_t alt_kalman_enabled
Function Documentation
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 54 of file ins_float.c.
References EstimatorSetAlt, ins_vf_realign, nav_utm_east0, nav_utm_north0, nav_utm_zone0, stateSetLocalUtmOrigin_f(), and stateSetPositionUtm_f().
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 76 of file ins_float.c.
Referenced by sensors_task().
void ins_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each INS algorithm.
Definition at line 85 of file ins_float.c.
Referenced by on_gyro_accel_event(), and on_gyro_event().
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
Parameters:
pos new horizontal position to set
speed new horizontal speed to set Needs to be implemented by each INS algorithm.
Definition at line 79 of file ins_float.c.
Referenced by track_event().
void ins_realign_v (float z)
INS vertical realign.
Parameters:
z new altitude to set Needs to be implemented by each INS algorithm.
Definition at line 82 of file ins_float.c.
void ins_update_baro (void)
Update INS state with barometer measurements.
Reads the global baro data struct. Needs to be implemented by each INS algorithm.
Definition at line 88 of file ins_float.c.
Referenced by on_baro_abs_event().
void ins_update_gps (void)
Update INS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each INS algorithm.
Definition at line 109 of file ins_float.c.
Referenced by on_gps_event().
void ins_update_sonar (void)
Update INS state with sonar measurements.
Reads the global #sonar data struct. Needs to be implemented by each INS algorithm.
Definition at line 135 of file ins_float.c.
Variable Documentation
bool_t alt_kalman_enabled
Definition at line 138 of file ins_float.c.
float estimator_z
altitude above MSL in meters
Definition at line 41 of file ins_float.c.
Referenced by ins_update_gps().
float estimator_z_dot
Definition at line 42 of file ins_float.c.
bool_t ins_hf_realign
Definition at line 51 of file ins_float.c.
Referenced by ins_init(), ins_update_gps(), nav_reset_reference(), and track_event().
bool_t ins_vf_realign
Definition at line 52 of file ins_float.c.
Referenced by ins_init(), ins_update_baro(), nav_reset_alt(), and nav_reset_reference().