Paparazzi UAS: sw/airborne/modules/ins/ins_chimu_uart.c File Reference
ins_chimu_uart.c File Reference
#include <stdbool.h>
#include "state.h"
#include "subsystems/gps.h"
#include "subsystems/ahrs.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
#include "ins_module.h"
#include "imu_chimu.h"
Defines
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void ins_init (void)
INS initialization.
void parse_ins_msg (void)
void ins_periodic_task (void)
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Variables
CHIMU_PARSER_DATA CHIMU_DATA
INS_FORMAT ins_roll_neutral
INS_FORMAT ins_pitch_neutral
volatile uint8_t new_ins_attitude
Define Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 21 of file ins_chimu_uart.c.
Function Documentation
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 106 of file ins_chimu_uart.c.
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 38 of file ins_chimu_uart.c.
References CHIMU_BROADCAST, CHIMU_Checksum(), CHIMU_Init(), CHIMU_STX, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, InsSend, InsUartSend1, MSG00_PING, MSG09_ESTIMATOR, MSG10_UARTSETTINGS, and new_ins_attitude.
void ins_periodic_task (void)
Definition at line 101 of file ins_chimu_uart.c.
void parse_ins_msg (void)
Definition at line 72 of file ins_chimu_uart.c.
References CHIMU_Parse(), DefaultChannel, DefaultDevice, CHIMU_attitude_data::euler, InsLink, LED_TOGGLE, CHIMU_PARSER_DATA::m_attitude, CHIMU_PARSER_DATA::m_MsgID, new_ins_attitude, CHIMU_Euler::phi, CHIMU_Euler::psi, stateSetNedToBodyEulers_f(), and CHIMU_Euler::theta.
Variable Documentation
CHIMU_PARSER_DATA CHIMU_DATA
Definition at line 31 of file ins_chimu_uart.c.
INS_FORMAT ins_pitch_neutral
Definition at line 34 of file ins_chimu_uart.c.
INS_FORMAT ins_roll_neutral
Todo:
harmonize infrared neutrals with ins_neutrals or get rid of ins neutrals this ins only needed for sim right now
Definition at line 33 of file ins_chimu_uart.c.
volatile uint8_t new_ins_attitude
Definition at line 36 of file ins_chimu_uart.c.