Paparazzi UAS: sw/airborne/arch/sim/jsbsim_hw.h File Reference
jsbsim_hw.h File Reference
#include <inttypes.h>
#include "std.h"
#include "inter_mcu.h"
#include "firmwares/fixedwing/autopilot.h"
#include "subsystems/gps.h"
#include "subsystems/navigation/traffic_info.h"
#include "generated/flight_plan.h"
#include "generated/airframe.h"
#include "generated/settings.h"
#include "subsystems/nav.h"
#include "firmwares/fixedwing/stabilization/stabilization_attitude.h"
#include "firmwares/fixedwing/guidance/guidance_v.h"
#include "subsystems/sensors/infrared.h"
#include "subsystems/commands.h"
#include "firmwares/fixedwing/main_ap.h"
#include "ap_downlink.h"
#include "sim_uart.h"
#include "subsystems/datalink/datalink.h"
Functions
void sim_use_gps_pos (double lat, double lon, double alt, double course, double gspeed, double climb, double time)
From airborne/autopilot/.
void sim_update_sv (void)
Space vehicle info simulation.
void set_ir (double roll, double pitch)
void provide_attitude_and_rates (float phi, float theta, float psi, float p, float q, float r)
void update_bat (double bat)
void parse_dl_ping (char *argv[])
void parse_dl_acinfo (char *argv[])
void parse_dl_setting (char *argv[])
void parse_dl_get_setting (char *argv[])
void parse_dl_block (char *argv[])
void parse_dl_move_wp (char *argv[])
Detailed Description
Definition in file jsbsim_hw.h.
Function Documentation
void parse_dl_acinfo (char * argv[])
Definition at line 15 of file jsbsim_transport.c.
References c, MOfCm, and SetAcInfo.
void parse_dl_block (char * argv[])
Definition at line 42 of file jsbsim_transport.c.
References nav_goto_block().
void parse_dl_get_setting (char * argv[])
Definition at line 36 of file jsbsim_transport.c.
References DefaultChannel, and DefaultDevice.
void parse_dl_move_wp (char * argv[])
Definition at line 47 of file jsbsim_transport.c.
References DefaultChannel, DefaultDevice, dl_buffer, UtmCoor_f::east, LlaCoor_f::lat, LlaCoor_f::lon, MOfCm, nav_move_waypoint(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, utm_of_lla_f(), waypoints, EnuCoor_i::x, EnuCoor_i::y, and UtmCoor_f::zone.
void parse_dl_ping (char * argv[])
Definition at line 11 of file jsbsim_transport.c.
References DefaultChannel, and DefaultDevice.
void parse_dl_setting (char * argv[])
Definition at line 29 of file jsbsim_transport.c.
References DefaultChannel, and DefaultDevice.
void provide_attitude_and_rates (float phi, float theta, float psi, float p, float q, float r)
Definition at line 20 of file jsbsim_ahrs.c.
References ahrs_sim_available, p, sim_p, sim_phi, sim_psi, sim_q, sim_r, sim_theta, and TRUE.
void set_ir (double roll, double pitch)
Definition at line 18 of file jsbsim_ir.c.
References infrared, JSBSIM_IR_PITCH_NEUTRAL, JSBSIM_IR_ROLL_NEUTRAL, Infrared::pitch, Infrared::roll, and Infrared::top.
void sim_update_sv (void)
Space vehicle info simulation.
Definition at line 47 of file jsbsim_gps.c.
References SVinfo::azim, SVinfo::cno, SVinfo::elev, SVinfo::flags, gps, GpsState::nb_channels, GpsState::num_sv, GpsState::pacc, GpsState::pdop, SVinfo::qi, GpsState::sacc, SVinfo::svid, and GpsState::svinfos.
void sim_use_gps_pos (double lat, double lon, double alt, double course, double gspeed, double climb, double time)
From airborne/autopilot/.
Definition at line 19 of file jsbsim_gps.c.
References GpsState::course, UtmCoor_f::east, UtmCoor_i::east, GpsState::fix, gps, gps_available, GpsState::gspeed, GpsState::hmsl, LlaCoor_f::lat, LLA_BFP_OF_REAL, GpsState::lla_pos, LlaCoor_f::lon, nav_utm_zone0, GpsState::ned_vel, UtmCoor_f::north, UtmCoor_i::north, GpsState::tow, TRUE, utm_of_lla_f(), GpsState::utm_pos, GpsState::week, NedCoor_i::z, UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by sim_use_gps_pos_bytecode().
void update_bat (double bat)
Definition at line 30 of file jsbsim_hw.c.
References electrical, and Electrical::vsupply.