Paparazzi UAS: sw/airborne/modules/display/lcd_dogm.c File Reference
lcd_dogm.c File Reference
#include "display/lcd_dogm_hw.h"
#include "lcd_dogm.h"
Functions
void lcd_cmd (uint8_t command)
void lcd_data (uint8_t data)
void lcd_dogm_init (void)
Function Documentation
void lcd_cmd (uint8_t command)
Definition at line 43 of file lcd_dogm.c.
References lcd_spi_tx(), lcddogmCmdMode, and lcddogmSelect.
Referenced by lcd_dogm_init().
void lcd_data (uint8_t data)
Definition at line 51 of file lcd_dogm.c.
References lcd_spi_tx(), lcddogmDataMode, and lcddogmSelect.
Referenced by lcd_dogm_init().
void lcd_dogm_init (void)
Definition at line 59 of file lcd_dogm.c.
References DOGM_BIAS_SET, DOGM_CLEAR, DOGM_CONTRAST, DOGM_DISP_ON, DOGM_ENTRY_MODE, DOGM_FOLLOWER, DOGM_FUN_SET_1, DOGM_PWR_CTRL, lcd_cmd(), lcd_data(), and lcd_dogm_init_hw().