Paparazzi UAS: sw/airborne/link_mcu_spi.h File Reference
link_mcu_spi.h File Reference
#include <inttypes.h>
#include "inter_mcu.h"
#include "mcu_periph/spi.h"
#include "link_mcu_hw.h"
Data Structures
struct link_mcu_msg
Transport for the communication between FBW and AP in a bi-process architecture.
Functions
void link_mcu_init (void)
void link_mcu_event_task (void)
Variables
struct link_mcu_msg link_mcu_from_ap_msg
struct link_mcu_msg link_mcu_from_fbw_msg
struct spi_transaction link_mcu_trans
bool_t link_mcu_received
Function Documentation
void link_mcu_event_task (void)
Definition at line 342 of file link_mcu_usart.c.
Referenced by event_task_ap(), and event_task_fbw().
void link_mcu_init (void)
Definition at line 247 of file link_mcu_usart.c.
Referenced by init_ap(), and init_fbw().
Variable Documentation
struct link_mcu_msg link_mcu_from_ap_msg
Definition at line 29 of file link_mcu_spi.c.
struct link_mcu_msg link_mcu_from_fbw_msg
Definition at line 30 of file link_mcu_spi.c.
bool_t link_mcu_received
Definition at line 34 of file link_mcu_spi.c.
struct spi_transaction link_mcu_trans
Definition at line 32 of file link_mcu_spi.c.