Paparazzi UAS: sw/airborne/lisa/test/lisa_test_adxl345.c File Reference
lisa_test_adxl345.c File Reference
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/spi.h>
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "peripherals/adxl345.h"
#include "my_debug_servo.h"
#include "led.h"
Defines
#define CONFIGURED 6
#define AccUnselect() GPIOB->BSRR = GPIO_Pin_12
#define AccSelect() GPIOB->BRR = GPIO_Pin_12
#define AccToggleSelect() GPIOB->ODR ^= GPIO_Pin_12
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_init_hw (void)
int main (void)
static void write_to_reg (uint8_t addr, uint8_t val)
static uint8_t read_fom_reg (uint8_t addr)
static void read_data (void)
void exti2_irq_handler (void)
Variables
static uint8_t acc_status = 0
static volatile uint8_t acc_ready_for_read = FALSE
static uint8_t values [6]
Define Documentation
#define AccSelect () GPIOB->BRR = GPIO_Pin_12
Definition at line 75 of file lisa_test_adxl345.c.
Referenced by read_data(), read_fom_reg(), and write_to_reg().
#define AccToggleSelect () GPIOB->ODR ^= GPIO_Pin_12
Definition at line 76 of file lisa_test_adxl345.c.
#define AccUnselect () GPIOB->BSRR = GPIO_Pin_12
Definition at line 74 of file lisa_test_adxl345.c.
Referenced by main_init_hw(), read_data(), read_fom_reg(), and write_to_reg().
#define CONFIGURED 6
Definition at line 69 of file lisa_test_adxl345.c.
Referenced by main_event_task(), and main_periodic_task().
Function Documentation
void exti2_irq_handler (void)
Definition at line 281 of file lisa_test_adxl345.c.
References TRUE.
int main (void)
Definition at line 48 of file lisa_test_adxl345.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) [inline, static]
Definition at line 201 of file lisa_test_adxl345.c.
References CONFIGURED, DefaultChannel, DefaultDevice, FALSE, and read_data().
Referenced by main().
static void main_init (void) [inline, static]
static void main_init_hw (void) [inline, static]
Definition at line 214 of file lisa_test_adxl345.c.
References AccUnselect, DEBUG_SERVO2_INIT, IMU_ACC_DRDY_GPIO, IMU_ACC_DRDY_GPIO_PORTSOURCE, and IMU_ACC_DRDY_RCC_GPIO.
static void main_periodic_task (void) [inline, static]
Definition at line 155 of file lisa_test_adxl345.c.
References ADXL345_REG_BW_RATE, ADXL345_REG_DATA_FORMAT, ADXL345_REG_INT_ENABLE, ADXL345_REG_POWER_CTL, CONFIGURED, DefaultChannel, DefaultDevice, LED_PERIODIC, read_data(), and write_to_reg().
Referenced by main().
static void read_data (void) [static]
Definition at line 111 of file lisa_test_adxl345.c.
References AccSelect, AccUnselect, ADXL345_REG_DATA_X0, foo, and RESET.
Referenced by main_event_task(), and main_periodic_task().
static uint8_t read_fom_reg (uint8_t addr) [static]
Definition at line 94 of file lisa_test_adxl345.c.
References AccSelect, AccUnselect, and RESET.
static void write_to_reg (uint8_t addr, uint8_t val) [static]
Definition at line 78 of file lisa_test_adxl345.c.
References AccSelect, AccUnselect, and RESET.
Referenced by main_periodic_task().
Variable Documentation
volatile uint8_t acc_ready_for_read = FALSE [static]
Definition at line 71 of file lisa_test_adxl345.c.
uint8_t acc_status = 0 [static]
Definition at line 70 of file lisa_test_adxl345.c.
uint8_t values[6] [static]
Definition at line 72 of file lisa_test_adxl345.c.