Paparazzi UAS: sw/airborne/lisa/test/lisa_test_hmc5843.c File Reference
lisa_test_hmc5843.c File Reference
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/spi.h>
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "std.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/i2c.h"
#include "peripherals/hmc5843.h"
#include "my_debug_servo.h"
#include "math/pprz_algebra_int.h"
Macros
#define INITIALIZED 6
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_init_hw (void)
static void send_config (void)
int main (void)
void exti9_5_isr (void)
Variables
static struct i2c_transaction i2c_trans
struct i2c_transaction t1
struct i2c_transaction t2
static uint8_t mag_state = 0
static volatile uint8_t mag_ready_for_read = FALSE
static uint8_t reading_mag = FALSE
Macro Definition Documentation
#define INITIALIZED 6
Definition at line 56 of file lisa_test_hmc5843.c.
Referenced by exti9_5_isr(), main_event_task(), and main_periodic_task().
Function Documentation
void exti9_5_isr (void)
Definition at line 265 of file lisa_test_hmc5843.c.
References INITIALIZED, mag_ready_for_read, mag_state, and TRUE.
int main (void)
Definition at line 61 of file lisa_test_hmc5843.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) inline static
Definition at line 155 of file lisa_test_hmc5843.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, FALSE, HMC5843_ADDR, i2c_submit(), i2c_trans, I2CTransFailed, I2CTransRx, I2CTransSuccess, INITIALIZED, i2c_transaction::len_r, mag_ready_for_read, mag_state, reading_mag, i2c_transaction::slave_addr, i2c_transaction::status, TRUE, i2c_transaction::type, VECT3_ASSIGN, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by main().
static void main_init (void) inline static
static void main_init_hw (void) inline static
Definition at line 220 of file lisa_test_hmc5843.c.
References DEBUG_SERVO1_INIT, and DEBUG_SERVO2_INIT.
static void main_periodic_task (void) inline static
Definition at line 79 of file lisa_test_hmc5843.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, HMC5843_ADDR, HMC5843_REG_CFGA, HMC5843_REG_CFGB, HMC5843_REG_MODE, i2c_submit(), i2c_trans, I2CTransTx, INITIALIZED, LED_PERIODIC, i2c_transaction::len_w, mag_state, send_config(), i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by main().
static void send_config (void) static
Definition at line 188 of file lisa_test_hmc5843.c.
References i2c_transaction::buf, HMC5843_ADDR, HMC5843_REG_CFGA, HMC5843_REG_CFGB, HMC5843_REG_MODE, i2c_submit(), i2c_trans, I2CTransTx, i2c_transaction::len_w, i2c_transaction::slave_addr, t1, t2, and i2c_transaction::type.
Referenced by main_periodic_task().
Variable Documentation
struct i2c_transaction i2c_trans static
Definition at line 52 of file lisa_test_hmc5843.c.
Referenced by main_event_task(), main_periodic_task(), and send_config().
volatile uint8_t mag_ready_for_read = FALSE static
Definition at line 58 of file lisa_test_hmc5843.c.
Referenced by exti9_5_isr(), and main_event_task().
uint8_t mag_state = 0 static
Definition at line 57 of file lisa_test_hmc5843.c.
Referenced by exti9_5_isr(), main_event_task(), and main_periodic_task().
uint8_t reading_mag = FALSE static
Definition at line 59 of file lisa_test_hmc5843.c.
Referenced by main_event_task().
struct i2c_transaction t1
Definition at line 53 of file lisa_test_hmc5843.c.
Referenced by send_config().
struct i2c_transaction t2
Definition at line 54 of file lisa_test_hmc5843.c.
Referenced by baro_event(), baro_ms5611_event(), and send_config().