Paparazzi UAS: sw/airborne/lisa/test/lisa_test_itg3200.c File Reference
lisa_test_itg3200.c File Reference
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/spi.h>
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "peripherals/itg3200.h"
#include "my_debug_servo.h"
#include "led.h"
Defines
#define INITIALIZED 6
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_init_hw (void)
int main (void)
void exti15_10_irq_handler (void)
Variables
static struct i2c_transaction i2c_trans
static uint8_t gyro_state = 0
static volatile uint8_t gyro_ready_for_read = FALSE
static uint8_t reading_gyro = FALSE
Define Documentation
#define INITIALIZED 6
Definition at line 53 of file lisa_test_itg3200.c.
Referenced by exti15_10_irq_handler(), main_event_task(), and main_periodic_task().
Function Documentation
void exti15_10_irq_handler (void)
Definition at line 275 of file lisa_test_itg3200.c.
References gyro_ready_for_read, gyro_state, INITIALIZED, and TRUE.
int main (void)
Definition at line 58 of file lisa_test_itg3200.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) [inline, static]
Definition at line 172 of file lisa_test_itg3200.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, FALSE, gyro_ready_for_read, gyro_state, i2c_submit(), i2c_trans, I2CTransFailed, I2CTransSuccess, I2CTransTxRx, INITIALIZED, ITG3200_REG_TEMP_OUT_H, i2c_transaction::len_r, i2c_transaction::len_w, MyByteSwap16, Int32Rates::p, Int32Rates::q, Int32Rates::r, RATES_ASSIGN, reading_gyro, i2c_transaction::status, TRUE, and i2c_transaction::type.
Referenced by main().
static void main_init (void) [inline, static]
static void main_init_hw (void) [inline, static]
Definition at line 226 of file lisa_test_itg3200.c.
References DEBUG_SERVO1_INIT, and DEBUG_SERVO2_INIT.
static void main_periodic_task (void) [inline, static]
Definition at line 76 of file lisa_test_itg3200.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, gyro_state, i2c_submit(), i2c_trans, I2CTransTx, INITIALIZED, ITG3200_ADDR, ITG3200_REG_DLPF_FS, ITG3200_REG_INT_CFG, ITG3200_REG_PWR_MGM, ITG3200_REG_SMPLRT_DIV, ITG3200_REG_TEMP_OUT_H, LED_PERIODIC, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by main().
Variable Documentation
volatile uint8_t gyro_ready_for_read = FALSE [static]
Definition at line 55 of file lisa_test_itg3200.c.
Referenced by exti15_10_irq_handler(), and main_event_task().
uint8_t gyro_state = 0 [static]
Definition at line 54 of file lisa_test_itg3200.c.
Referenced by exti15_10_irq_handler(), main_event_task(), and main_periodic_task().
struct i2c_transaction i2c_trans [static]
Definition at line 52 of file lisa_test_itg3200.c.
Referenced by main_event_task(), and main_periodic_task().
uint8_t reading_gyro = FALSE [static]
Definition at line 56 of file lisa_test_itg3200.c.
Referenced by main_event_task().