Paparazzi UAS: sw/airborne/boards/lisa_m/baro_board.h File Reference
baro_board.h File Reference
Macros
#define BaroEvent(_b_abs_handler, _b_diff_handler) baro_event(_b_abs_handler,_b_diff_handler)
Functions
void baro_event (void(*b_abs_handler)(void), void(*b_diff_handler)(void))
Generic barometer interface, assuming the barometer is read through Aspirin IMU directly.
Macro Definition Documentation
#define BaroEvent (_b_abs_handler, _b_diff_handler) baro_event(_b_abs_handler,_b_diff_handler)
Definition at line 13 of file baro_board.h.
Function Documentation
void baro_event (void(*)(void) b_abs_handler, void(*)(void) b_diff_handler)
Generic barometer interface, assuming the barometer is read through Aspirin IMU directly.
Edit by: Michal Podhradsky, micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu Utah State University, http://aggieair.usu.edu/
Definition at line 21 of file baro_board.c.
References Baro::absolute, baro, baro_init(), baro_ms5611_crc(), BS_RUNNING, i2c_transaction::buf, DefaultChannel, DefaultDevice, dt, fbaroms, ftempms, I2CTransceive, I2CTransDone, I2CTransmit, I2CTransSuccess, LED_TOGGLE, MS5611_ADC_D1, MS5611_ADC_D2, ms5611_c, MS5611_CONV_D2, ms5611_d1, ms5611_d2, MS5611_I2C_DEV, MS5611_IDLE, MS5611_PROM, MS5611_PROM_READ, MS5611_RESET, MS5611_RESET_OK, MS5611_SLAVE_ADDR, MS5611_SPI_DEV, MS5611_START_CONV_D2, ms5611_status, ms5611_trans, prom_cnt, PROM_NB, spi_submit(), SPITransDone, SPITransSuccess, Baro::status, i2c_transaction::status, and t2.