Paparazzi UAS: sw/airborne/arch/lpc21/mcu_periph/uart_arch.c File Reference
uart_arch.c File Reference
LPC21 architecture
Handling of UART hardware for lpc21xx.
#include "mcu_periph/uart.h"
#include "armVIC.h"
Functions
static void uart_disable_interrupts (struct uart_periph *p)
static void uart_enable_interrupts (struct uart_periph *p)
static void uart_set_baudrate (struct uart_periph *p, uint32_t baud)
void uart_periph_set_baudrate (struct uart_periph *p, uint32_t baud, bool_t hw_flow_control)
void uart_transmit (struct uart_periph *p, uint8_t data)
static void uart_ISR (struct uart_periph *p)
Detailed Description
Handling of UART hardware for lpc21xx.
Definition in file uart_arch.c.
Function Documentation
static void uart_disable_interrupts (struct uart_periph * p) inline static
Definition at line 34 of file uart_arch.c.
References uart_periph::reg_addr.
Referenced by uart_periph_set_baudrate().
static void uart_enable_interrupts (struct uart_periph * p) inline static
Definition at line 42 of file uart_arch.c.
References uart_periph::reg_addr, and UIER_ERBFI.
Referenced by uart_periph_set_baudrate().
static void uart_ISR (struct uart_periph * p) inline static
Definition at line 101 of file uart_arch.c.
References uart_periph::reg_addr, uart_periph::rx_buf, uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, UART_RX_BUFFER_SIZE, UART_TX_BUFFER_SIZE, UIIR_CTI_INT, UIIR_ID_MASK, UIIR_NO_INT, UIIR_RDA_INT, UIIR_RLS_INT, UIIR_THRE_INT, ULSR_RDR, and ULSR_THRE.
void uart_periph_set_baudrate (struct uart_periph * p, uint32_t baud, bool_t hw_flow_control)
Definition at line 65 of file uart_arch.c.
static void uart_set_baudrate (struct uart_periph * p, uint32_t baud) inline static
Definition at line 47 of file uart_arch.c.
References PCLK, uart_periph::reg_addr, UART_8N1, UART_FIFO_8, and ULCR_DLAB_ENABLE.
Referenced by uart_periph_set_baudrate().
void uart_transmit (struct uart_periph * p, uint8_t data)
Definition at line 71 of file uart_arch.c.
Referenced by main(), main_event_task(), and test_uart_periodic().