Paparazzi UAS: sw/airborne/arch/lpc21/mcu_periph/i2c_arch.c File Reference
i2c_arch.c File Reference
#include "mcu_periph/i2c.h"
#include "std.h"
#include "interrupt_hw.h"
#include <BOARD_CONFIG>
Functions
static void I2cSendStart (struct i2c_periph *p)
static void I2cSendAck (void *reg)
static void I2cEndOfTransaction (struct i2c_periph *p)
static void I2cSendStop (struct i2c_periph *p, struct i2c_transaction *t)
static void I2cFail (struct i2c_periph *p, struct i2c_transaction *t)
static void I2cSendByte (void *reg, uint8_t b)
static void I2cReceive (void *reg, bool_t ack)
static void I2cClearStart (void *reg)
static void I2cClearIT (void *reg)
static void I2cAutomaton (int32_t state, struct i2c_periph *p)
bool_t i2c_idle (struct i2c_periph *p)
bool_t i2c_submit (struct i2c_periph *p, struct i2c_transaction *t)
void i2c_event (void)
void i2c_setbitrate (struct i2c_periph *p, int bitrate)
Function Documentation
void i2c_event (void)
Definition at line 359 of file i2c_arch.c.
Referenced by event_task_ap(), event_task_fbw(), and main_event().
bool_t i2c_idle (struct i2c_periph * p)
Definition at line 322 of file i2c_arch.c.
Referenced by baro_periodic(), event_i2c_abuse_test(), hmc5843_idle_task(), hmc5843_periodic(), i2c_event(), i2c_setbitrate(), and imu_aspirin_event().
void i2c_setbitrate (struct i2c_periph * p, int bitrate)
Definition at line 361 of file i2c_arch.c.
Referenced by event_i2c_abuse_test().
bool_t i2c_submit (struct i2c_periph * p, struct i2c_transaction * t)
Definition at line 326 of file i2c_arch.c.
Referenced by actuators_asctec_set(), actuators_mkk_set(), actuators_skiron_set(), ami601_read(), baro_board_read_from_current_register(), baro_board_read_from_register(), baro_board_send_reset(), baro_board_set_current_register(), baro_board_write_to_register(), event_i2c_abuse_test(), gyro_read_i2c(), hmc5843_idle_task(), hmc5843_periodic(), i2c_abuse_send_transaction(), imu_impl_init(), imu_periodic(), main_event_task(), main_periodic_task(), send_config(), and send_i2c_msg_with_retry().
static void I2cAutomaton (int32_t state, struct i2c_periph * p) [inline, static]
Definition at line 88 of file i2c_arch.c.
References i2c_transaction::buf, I2C_MR_DATA_ACK, I2C_MR_DATA_NACK, I2C_MR_SLA_ACK, I2C_MR_SLA_NACK, I2C_MT_DATA_ACK, I2C_MT_SLA_ACK, I2C_MT_SLA_NACK, I2C_RESTART, I2C_START, I2cClearStart(), I2cFail(), I2cReceive(), I2cSendByte(), I2cSendStart(), I2cSendStop(), I2CTransRx, I2CTransTx, I2CTransTxRx, i2c_transaction::len_r, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
static void I2cClearIT (void * reg) [inline, static]
Definition at line 84 of file i2c_arch.c.
References SIC.
static void I2cClearStart (void * reg) [inline, static]
Definition at line 80 of file i2c_arch.c.
References STAC.
Referenced by I2cAutomaton().
static void I2cEndOfTransaction (struct i2c_periph * p) [inline, static]
Definition at line 42 of file i2c_arch.c.
References I2C_TRANSACTION_QUEUE_LEN, I2CIdle, and I2cSendStart().
Referenced by I2cFail(), and I2cSendStop().
static void I2cFail (struct i2c_periph * p, struct i2c_transaction * t) [inline, static]
Definition at line 63 of file i2c_arch.c.
References I2cEndOfTransaction(), I2CTransFailed, and STO.
Referenced by I2cAutomaton().
static void I2cReceive (void * reg, bool_t ack) [inline, static]
Definition at line 75 of file i2c_arch.c.
References AA, and AAC.
Referenced by I2cAutomaton().
static void I2cSendAck (void * reg) [inline, static]
Definition at line 38 of file i2c_arch.c.
References AA.
static void I2cSendByte (void * reg, uint8_t b) [inline, static]
Definition at line 71 of file i2c_arch.c.
Referenced by I2cAutomaton().
static void I2cSendStart (struct i2c_periph * p) [inline, static]
Definition at line 33 of file i2c_arch.c.
References I2CStartRequested, and STA.
Referenced by i2c_submit(), I2cAutomaton(), and I2cEndOfTransaction().
static void I2cSendStop (struct i2c_periph * p, struct i2c_transaction * t) [inline, static]
Definition at line 56 of file i2c_arch.c.
References I2cEndOfTransaction(), I2CTransSuccess, and STO.
Referenced by I2cAutomaton().