Paparazzi UAS: sw/airborne/arch/lpc21/mcu_periph/sys_time_arch.h File Reference
sys_time_arch.h File Reference
LPC21 architecture
LPC21xx timing functions.
#include "mcu_periph/sys_time.h"
#include <BOARD_CONFIG>
#include "LPC21xx.h"
#include "armVIC.h"
#include "std.h"
Macros
#define TIMER0_VIC_SLOT 1
#define SysTimeTimerStart(_t) { _t = usec_of_cpu_ticks(T0TC); }
#define SysTimeTimer(_t) (usec_of_cpu_ticks(T0TC) - (_t))
#define SysTimeTimerStop(_t) { _t = (usec_of_cpu_ticks(T0TC) - (_t)); }
#define SysTickTimerStart(_t) { _t = T0TC; }
#define SysTickTimer(_t) ((uint32_t)(T0TC - _t))
#define SysTickTimerStop(_t) { _t = (T0TC - _t); }
Functions
void TIMER0_ISR (void)
static void sys_time_usleep (uint32_t us)
Busy wait, in microseconds.
Detailed Description
LPC21xx timing functions.
Definition in file sys_time_arch.h.
Macro Definition Documentation
#define SysTickTimer (_t) ((uint32_t)(T0TC - _t))
Definition at line 69 of file sys_time_arch.h.
#define SysTickTimerStart (_t) { _t = T0TC; }
Definition at line 68 of file sys_time_arch.h.
#define SysTickTimerStop (_t) { _t = (T0TC - _t); }
Definition at line 70 of file sys_time_arch.h.
#define SysTimeTimer (_t) (usec_of_cpu_ticks(T0TC) - (_t))
Definition at line 65 of file sys_time_arch.h.
Referenced by actuators_asctec_set(), actuators_asctec_v2_set(), actuators_mkk_set(), actuators_mkk_v2_set(), actuators_skiron_set(), event_sysmon(), and periodic_sysmon().
#define SysTimeTimerStart (_t) { _t = usec_of_cpu_ticks(T0TC); }
Definition at line 64 of file sys_time_arch.h.
Referenced by event_sysmon(), gps_mtk_read_message(), and periodic_sysmon().
#define SysTimeTimerStop (_t) { _t = (usec_of_cpu_ticks(T0TC) - (_t)); }
Definition at line 66 of file sys_time_arch.h.
#define TIMER0_VIC_SLOT 1
Definition at line 59 of file sys_time_arch.h.
Referenced by sys_time_arch_init().
Function Documentation
static void sys_time_usleep (uint32_t us) inline static
Busy wait, in microseconds.
Definition at line 73 of file sys_time_arch.h.
References cpu_ticks_of_usec(), and T0TC.
Referenced by pcap01_init(), w5100_init(), xbee_init(), and xbee_try_to_enter_api().
void TIMER0_ISR (void)
Definition at line 170 of file sys_time_arch.c.
References ACTUATORS_IT, AMI601_ISR, AMI601_IT, ISR_ENTRY, ISR_EXIT, LED_TOGGLE, MB_SCALE_IT, MB_TACHO_IT, PPM_ISR, PPM_IT, PWM_INPUT_IT1, PWM_INPUT_IT2, Servos4015Mat_ISR, SERVOS_4017_ISR, ServosPPMMat_ISR, sys_tick_irq_handler(), SYS_TICK_IT, T0IR, TIMER0_IT_MASK, TRIG_ISR(), TRIGGER_IT, and VICVectAddr.
Referenced by sys_time_arch_init().