Paparazzi UAS: sw/airborne/modules/sensors/mag_hmc58xx.c File Reference
mag_hmc58xx.c File Reference
Module wrapper for Honeywell HMC5843 and HMC5883 magnetometers.
#include "modules/sensors/mag_hmc58xx.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
Macros
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void mag_hmc58xx_module_init (void)
void mag_hmc58xx_module_periodic (void)
void mag_hmc58xx_module_event (void)
void mag_hmc58xx_report (void)
Variables
struct Hmc58xx mag_hmc58xx
Detailed Description
Module wrapper for Honeywell HMC5843 and HMC5883 magnetometers.
Definition in file mag_hmc58xx.c.
Macro Definition Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 34 of file mag_hmc58xx.c.
Function Documentation
void mag_hmc58xx_module_event (void)
Definition at line 47 of file mag_hmc58xx.c.
References Hmc58xx::data_available, FALSE, hmc58xx_event(), mag_hmc58xx, and mag_hmc58xx_report().
void mag_hmc58xx_module_init (void)
Definition at line 39 of file mag_hmc58xx.c.
References HMC58XX_ADDR, hmc58xx_init(), and mag_hmc58xx.
void mag_hmc58xx_module_periodic (void)
Definition at line 43 of file mag_hmc58xx.c.
References hmc58xx_periodic(), and mag_hmc58xx.
void mag_hmc58xx_report (void)
Definition at line 57 of file mag_hmc58xx.c.
References Hmc58xx::data, DefaultChannel, DefaultDevice, mag_hmc58xx, Hmc58xx::vect, Int16Vect3::x, Int16Vect3::y, and Int16Vect3::z.
Referenced by mag_hmc58xx_module_event().
Variable Documentation
struct Hmc58xx mag_hmc58xx
Definition at line 37 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), mag_hmc58xx_module_init(), mag_hmc58xx_module_periodic(), and mag_hmc58xx_report().