Paparazzi UAS: sw/airborne/modules/sensors/mag_hmc5843.c File Reference
mag_hmc5843.c File Reference
#include "mcu_periph/i2c.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
#include <math.h>
#include "../../peripherals/hmc5843.h"
Macros
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void hmc5843_module_init (void)
void hmc5843_module_periodic (void)
void hmc5843_module_event (void)
Variables
int32_t mag_x
int32_t mag_y
int32_t mag_z
bool_t mag_valid
Macro Definition Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 34 of file mag_hmc5843.c.
Function Documentation
void hmc5843_module_event (void)
Definition at line 51 of file mag_hmc5843.c.
References hmc5843_idle_task().
void hmc5843_module_init (void)
Definition at line 38 of file mag_hmc5843.c.
References hmc5843_init().
void hmc5843_module_periodic (void)
Definition at line 42 of file mag_hmc5843.c.
References Hmc5843::data, DefaultChannel, DefaultDevice, hmc5843, hmc5843_periodic(), mag_x, mag_y, mag_z, and Hmc5843::value.
Variable Documentation
bool_t mag_valid
Definition at line 30 of file mag_hmc5843.c.
int32_t mag_x
Definition at line 29 of file mag_hmc5843.c.
Referenced by hmc5843_module_periodic().
int32_t mag_y
Definition at line 29 of file mag_hmc5843.c.
Referenced by hmc5843_module_periodic().
int32_t mag_z
Definition at line 29 of file mag_hmc5843.c.
Referenced by hmc5843_module_periodic().