Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_ap.c File Reference
main_ap.c File Reference
AP (AutoPilot) tasks.
#include <math.h>
#include "firmwares/fixedwing/main_ap.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "link_mcu_spi.h"
#include "subsystems/gps.h"
#include "subsystems/imu.h"
#include "subsystems/ahrs.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "subsystems/sensors/baro.h"
#include "subsystems/ins.h"
#include "state.h"
#include "firmwares/fixedwing/autopilot.h"
#include "firmwares/fixedwing/stabilization/stabilization_attitude.h"
#include <CTRL_TYPE_H>
#include "subsystems/nav.h"
#include "generated/flight_plan.h"
#include "subsystems/datalink/datalink.h"
#include "subsystems/settings.h"
#include "subsystems/datalink/xbee.h"
#include "subsystems/datalink/w5100.h"
#include "firmwares/fixedwing/ap_downlink.h"
#include "generated/modules.h"
#include "generated/settings.h"
#include "rc_settings.h"
#include "gpio.h"
#include "led.h"
Defines
#define MODULES_C
#define RC_LOST_MODE PPRZ_MODE_HOME
mode to enter when RC is lost in PPRZ_MODE_MANUAL or PPRZ_MODE_AUTO1
#define LOW_BATTERY_DELAY 5
Maximum time allowed for low battery level before going into kill mode.
#define KILL_MODE_DISTANCE (1.5*MAX_DIST_FROM_HOME)
Maximum distance from HOME waypoint before going into kill mode.
#define MIN_SPEED_FOR_TAKEOFF 5.
Define minimal speed for takeoff in m/s.
Functions
static void on_gyro_event (void)
static void on_accel_event (void)
static void on_mag_event (void)
static void on_gps_solution (void)
static void on_baro_abs_event (void)
static void on_baro_dif_event (void)
void init_ap (void)
void handle_periodic_tasks_ap (void)
static uint8_t pprz_mode_update (void)
Update paparazzi mode.
static uint8_t mcu1_status_update (void)
static void copy_from_to_fbw (void)
Send back uncontrolled channels.
static void telecommand_task (void)
Function to be called when a message from FBW is available.
void reporting_task (void)
Send a series of initialisation messages followed by a stream of periodic ones.
void navigation_task (void)
Compute desired_course.
void attitude_loop (void)
void sensors_task (void)
Run at PERIODIC_FREQUENCY (60Hz if not defined)
void monitor_task (void)
monitor stuff run at 1Hz
void event_task_ap (void)
Variables
volatile uint8_t ahrs_timeout_counter = 0
static const uint16_t version = 1
static uint8_t mcu1_status
static uint8_t mcu1_ppm_cpt
static int32_t current
Supply current in milliAmpere.
tid_t modules_tid
id for modules_periodic_task() timer
tid_t telemetry_tid
id for telemetry_periodic() timer
tid_t sensors_tid
id for sensors_task() timer
tid_t attitude_tid
id for attitude_loop() timer
tid_t navigation_tid
id for navigation_task() timer
tid_t monitor_tid
id for monitor_task() timer
Detailed Description
AP (AutoPilot) tasks.
This process is reponsible for the collecting the different sensors data, fusing them to obtain aircraft attitude and running the different control loops
Definition in file main_ap.c.
Define Documentation
#define KILL_MODE_DISTANCE (1.5*MAX_DIST_FROM_HOME)
Maximum distance from HOME waypoint before going into kill mode.
Definition at line 553 of file main_ap.c.
Referenced by monitor_task().
#define LOW_BATTERY_DELAY 5
Maximum time allowed for low battery level before going into kill mode.
Definition at line 549 of file main_ap.c.
Referenced by monitor_task().
#define MIN_SPEED_FOR_TAKEOFF 5.
Define minimal speed for takeoff in m/s.
Definition at line 557 of file main_ap.c.
Referenced by monitor_task().
#define MODULES_C
Definition at line 31 of file main_ap.c.
#define RC_LOST_MODE PPRZ_MODE_HOME
mode to enter when RC is lost in PPRZ_MODE_MANUAL or PPRZ_MODE_AUTO1
Definition at line 305 of file main_ap.c.
Referenced by telecommand_task().
Function Documentation
void attitude_loop (void)
Definition at line 471 of file main_ap.c.
References ahrs_update_infrared(), ap_state, autopilot_flight_time, h_ctl_aileron_setpoint, h_ctl_attitude_loop(), h_ctl_elevator_setpoint, h_ctl_pitch_setpoint, inter_mcu_received_ap, kill_throttle, launch, link_mcu_send(), MAX_PPRZ, nav_pitch, nav_throttle_setpoint, pprz_mode, PPRZ_MODE_AUTO2, TRIM_PPRZ, TRIM_UPPRZ, TRUE, v_ctl_climb_loop(), v_ctl_mode, V_CTL_MODE_AUTO_CLIMB, V_CTL_MODE_AUTO_THROTTLE, v_ctl_pitch_setpoint, v_ctl_throttle_setpoint, v_ctl_throttle_slew(), v_ctl_throttle_slewed, and vsupply.
Referenced by event_task_ap(), handle_periodic_tasks_ap(), and sim_periodic_task().
static void copy_from_to_fbw (void) [inline, static]
Send back uncontrolled channels.
Definition at line 295 of file main_ap.c.
References ap_state, fbw_state, and RADIO_YAW.
Referenced by telecommand_task().
void event_task_ap (void)
Definition at line 590 of file main_ap.c.
References attitude_loop(), BaroEvent, DatalinkEvent, FALSE, GpsEvent, i2c_event(), ImuEvent, inter_mcu_received_fbw, link_mcu_event_task(), new_ins_attitude, on_accel_event(), on_baro_abs_event(), on_baro_dif_event(), on_gps_solution(), on_gyro_event(), on_mag_event(), and telecommand_task().
Referenced by sim_periodic_task().
void handle_periodic_tasks_ap (void)
Definition at line 215 of file main_ap.c.
References attitude_loop(), attitude_tid, LED_PERIODIC, modules_tid, monitor_task(), monitor_tid, navigation_task(), navigation_tid, reporting_task(), sensors_task(), sensors_tid, sys_time_check_and_ack_timer(), and telemetry_tid.
void init_ap (void)
init done in main_fbw in single MCU
start interrupt task
Definition at line 130 of file main_ap.c.
References ahrs_aligner_init(), ahrs_init(), attitude_tid, audio_telemetry_init(), autopilot_init(), baro_init(), CONTROL_FREQUENCY, GpioInit, gps_init(), h_ctl_init(), imu_init(), ins_init(), IO0DIR, IO0SET, link_mcu_init(), mcu_int_enable, MODULES_FREQUENCY, modules_tid, monitor_tid, nav_init(), NAVIGATION_FREQUENCY, navigation_tid, PERIODIC_FREQUENCY, sensors_tid, settings_init(), stateInit(), sys_time_register_timer(), telemetry_tid, traffic_info_init(), v_ctl_init(), w5100_init(), and xbee_init().
Referenced by sim_init().
static uint8_t mcu1_status_update (void) [inline, static]
Definition at line 282 of file main_ap.c.
References FALSE, fbw_state, and mcu1_status.
Referenced by telecommand_task().
void monitor_task (void)
monitor stuff run at 1Hz
Definition at line 560 of file main_ap.c.
References autopilot_flight_time, datalink_time, DefaultChannel, DefaultDevice, dist2_to_home, GpioUpdate1, KILL_MODE_DISTANCE, kill_throttle, launch, LOW_BATTERY_DELAY, MIN_SPEED_FOR_TAKEOFF, sys_time::nb_sec, Square, stateGetHorizontalSpeedNorm_f(), TRUE, and vsupply.
Referenced by handle_periodic_tasks_ap(), and sim_monitor_task().
void navigation_task (void)
Compute desired_course.
Definition at line 403 of file main_ap.c.
References CallTCAS, common_nav_periodic_task_4Hz(), current, DefaultChannel, DefaultDevice, energy, FALSE, gps_lost, h_ctl_auto1_rate, h_ctl_course_loop(), lateral_mode, LATERAL_MODE_COURSE, launch, nav_home(), nav_periodic_task(), nav_without_gps(), PERIODIC_SEND_PPRZ_MODE, pprz_mode, PPRZ_MODE_AUTO2, PPRZ_MODE_GPS_OUT_OF_ORDER, PPRZ_MODE_HOME, SEND_CAM, SEND_NAVIGATION, TRUE, v_ctl_altitude_loop(), v_ctl_mode, and V_CTL_MODE_AUTO_ALT.
Referenced by handle_periodic_tasks_ap(), and sim_nav_task().
static void on_accel_event (void) [inline, static]
Definition at line 657 of file main_ap.c.
Referenced by event_task_ap().
static void on_baro_abs_event (void) [inline, static]
Definition at line 745 of file main_ap.c.
References ins_update_baro().
Referenced by event_task_ap().
static void on_baro_dif_event (void) [inline, static]
Definition at line 749 of file main_ap.c.
Referenced by event_task_ap().
static void on_gps_solution (void) [inline, static]
Definition at line 643 of file main_ap.c.
References ahrs_update_gps(), and ins_update_gps().
Referenced by event_task_ap().
static void on_gyro_event (void) [inline, static]
Definition at line 660 of file main_ap.c.
References Imu::accel_unscaled, ahrs, ahrs_align(), ahrs_aligner, AHRS_ALIGNER_LOCKED, ahrs_aligner_run(), ahrs_propagate(), AHRS_PROPAGATE_FREQUENCY, ahrs_timeout_counter, AHRS_UNINIT, ahrs_update_accel(), Imu::gyro_unscaled, imu, ImuScaleAccel, ImuScaleGyro, INT_RATES_ZERO, INT_VECT3_ZERO, new_ins_attitude, PERIODIC_FREQUENCY, RATES_ADD, RATES_SDIV, AhrsAligner::status, Ahrs::status, VECT3_ADD, and VECT3_SDIV.
Referenced by event_task_ap().
static void on_mag_event (void) [inline, static]
Definition at line 729 of file main_ap.c.
References ahrs, AHRS_RUNNING, ahrs_update_mag(), imu, ImuScaleMag, and Ahrs::status.
Referenced by event_task_ap().
static uint8_t pprz_mode_update (void) [inline, static]
Update paparazzi mode.
Definition at line 247 of file main_ap.c.
References FALSE, fbw_state, ModeUpdate, pprz_mode, PPRZ_MODE_AUTO1, PPRZ_MODE_AUTO2, PPRZ_MODE_GPS_OUT_OF_ORDER, PPRZ_MODE_HOME, PPRZ_MODE_MANUAL, PPRZ_MODE_OF_PULSE, RADIO_MODE, THRESHOLD2, and TRUE.
Referenced by telecommand_task().
void reporting_task (void)
Send a series of initialisation messages followed by a stream of periodic ones.
Called at 60Hz.
initialisation phase during boot
then report periodicly
Definition at line 381 of file main_ap.c.
References DefaultChannel, DefaultDevice, FALSE, TRUE, and version.
Referenced by handle_periodic_tasks_ap(), and sim_periodic_task().
void sensors_task (void)
Run at PERIODIC_FREQUENCY (60Hz if not defined)
Definition at line 523 of file main_ap.c.
References ahrs_propagate(), ahrs_timeout_counter, baro_periodic(), imu_periodic(), and ins_periodic().
Referenced by handle_periodic_tasks_ap(), and sim_periodic_task().
static void telecommand_task (void) [inline, static]
Function to be called when a message from FBW is available.
In AUTO1 mode, compute roll setpoint and pitch setpoint from RADIO_ROLL and RADIO_PITCH
Roll is bounded between [-AUTO1_MAX_ROLL;AUTO1_MAX_ROLL]
Pitch is bounded between [-AUTO1_MAX_PITCH;AUTO1_MAX_PITCH]
Else asynchronously set by h_ctl_course_loop()
In AUTO1, throttle comes from RADIO_THROTTLE In MANUAL, the value is copied to get it in the telemetry
else asynchronously set by v_ctl_climb_loop();
Definition at line 311 of file main_ap.c.
References autopilot_flight_time, copy_from_to_fbw(), current, DefaultChannel, DefaultDevice, FALSE, fbw_state, FLOAT_OF_PPRZ, h_ctl_pitch_setpoint, h_ctl_roll_setpoint, launch, mcu1_ppm_cpt, mcu1_status_update(), PERIODIC_SEND_PPRZ_MODE, pprz_mode, PPRZ_MODE_AUTO1, PPRZ_MODE_AUTO2, PPRZ_MODE_GPS_OUT_OF_ORDER, PPRZ_MODE_HOME, PPRZ_MODE_MANUAL, pprz_mode_update(), RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, RC_LOST_MODE, rc_settings(), THROTTLE_THRESHOLD_TAKEOFF, too_far_from_home, TRUE, v_ctl_throttle_setpoint, and vsupply.
Referenced by event_task_ap().
Variable Documentation
volatile uint8_t ahrs_timeout_counter = 0
Definition at line 94 of file main_ap.c.
Referenced by on_gyro_event(), and sensors_task().
tid_t attitude_tid
id for attitude_loop() timer
Definition at line 125 of file main_ap.c.
Referenced by handle_periodic_tasks_ap(), and init_ap().
int32_t current [static]
Supply current in milliAmpere.
This the ap copy of the measurement from fbw
Definition at line 119 of file main_ap.c.
Referenced by navigation_task(), and telecommand_task().
uint8_t mcu1_ppm_cpt [static]
Definition at line 113 of file main_ap.c.
Referenced by telecommand_task().
uint8_t mcu1_status [static]
Definition at line 110 of file main_ap.c.
Referenced by mcu1_status_update().
tid_t modules_tid
id for modules_periodic_task() timer
Definition at line 122 of file main_ap.c.
Referenced by handle_periodic_tasks_ap(), and init_ap().
tid_t monitor_tid
id for monitor_task() timer
Definition at line 127 of file main_ap.c.
Referenced by handle_periodic_tasks_ap(), and init_ap().
tid_t navigation_tid
id for navigation_task() timer
Definition at line 126 of file main_ap.c.
Referenced by handle_periodic_tasks_ap(), and init_ap().
tid_t sensors_tid
id for sensors_task() timer
Definition at line 124 of file main_ap.c.
Referenced by handle_periodic_tasks_ap(), and init_ap().
tid_t telemetry_tid
id for telemetry_periodic() timer
Definition at line 123 of file main_ap.c.
Referenced by handle_periodic_tasks(), handle_periodic_tasks_ap(), init_ap(), and main_init().
const uint16_t version = 1 [static]
Definition at line 108 of file main_ap.c.
Referenced by reporting_task().