Paparazzi UAS: sw/airborne/firmwares/rotorcraft/main.h File Reference
main.h File Reference
Rotorcraft main loop.
Defines
#define STATIC_INLINE static inline
Functions
STATIC_INLINE void main_init (void)
STATIC_INLINE void main_event (void)
STATIC_INLINE void handle_periodic_tasks (void)
STATIC_INLINE void main_periodic (void)
STATIC_INLINE void telemetry_periodic (void)
STATIC_INLINE void failsafe_check (void)
Detailed Description
Rotorcraft main loop.
Definition in file main.h.
Define Documentation
#define STATIC_INLINE static inline
Definition at line 34 of file main.h.
Function Documentation
STATIC_INLINE void failsafe_check (void)
Definition at line 194 of file main.c.
References AP_MODE_FAILSAFE, AP_MODE_KILL, AP_MODE_NAV, autopilot_mode, autopilot_set_mode(), GpsIsLost(), radio_control, RC_OK, and RadioControl::status.
Referenced by handle_periodic_tasks().
STATIC_INLINE void handle_periodic_tasks (void)
Definition at line 156 of file main.c.
References baro_periodic(), baro_tid, electrical_periodic(), electrical_tid, failsafe_check(), failsafe_tid, main_periodic(), main_periodic_tid, radio_control_periodic_task(), radio_control_tid, sys_time_check_and_ack_timer(), telemetry_periodic(), and telemetry_tid.
Referenced by main().
STATIC_INLINE void main_event (void) [inline]
Definition at line 214 of file main.c.
References autopilot_on_rc_frame(), autopilot_rc, BaroEvent, DatalinkEvent, DetectGroundEvent(), GpsEvent, i2c_event(), ImuEvent, on_accel_event(), on_baro_abs_event(), on_baro_dif_event(), on_gps_event(), on_gyro_event(), on_mag_event(), and RadioControlEvent.
Referenced by main().
STATIC_INLINE void main_init (void) [inline]
Definition at line 105 of file main.c.
References ahrs_aligner_init(), ahrs_init(), autopilot_init(), baro_init(), BARO_PERIODIC_FREQUENCY, baro_tid, electrical_init(), electrical_tid, failsafe_tid, gps_init(), guidance_h_init(), guidance_v_init(), imu_init(), ins_init(), main_periodic_tid, mcu_init(), mcu_int_enable, motor_mixing_init(), nav_init(), PERIODIC_FREQUENCY, radio_control_init(), radio_control_tid, settings_init(), stabilization_init(), stateInit(), sys_time_register_timer(), telemetry_tid, and xbee_init().
STATIC_INLINE void main_periodic (void) [inline]
Definition at line 171 of file main.c.
STATIC_INLINE void telemetry_periodic (void)
Definition at line 190 of file main.c.
References DefaultChannel, and DefaultDevice.
Referenced by handle_periodic_tasks().