Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_ap.h File Reference
main_ap.h File Reference
AP (AutoPilot) process API.
Functions
void init_ap (void)
void handle_periodic_tasks_ap (void)
void event_task_ap (void)
void sensors_task (void)
Run at PERIODIC_FREQUENCY (60Hz if not defined)
void navigation_task (void)
Compute desired_course.
void monitor_task (void)
monitor stuff run at 1Hz
void reporting_task (void)
Send a series of initialisation messages followed by a stream of periodic ones.
void attitude_loop (void)
Detailed Description
AP (AutoPilot) process API.
Definition in file main_ap.h.
Function Documentation
void attitude_loop (void)
Definition at line 469 of file main_ap.c.
References ahrs_update_infrared(), ap_state, autopilot_flight_time, h_ctl_aileron_setpoint, h_ctl_attitude_loop(), h_ctl_elevator_setpoint, h_ctl_pitch_setpoint, inter_mcu_received_ap, kill_throttle, launch, link_mcu_send(), MAX_PPRZ, nav_pitch, nav_throttle_setpoint, pprz_mode, PPRZ_MODE_AUTO2, TRIM_PPRZ, TRIM_UPPRZ, TRUE, v_ctl_climb_loop(), v_ctl_mode, V_CTL_MODE_AUTO_CLIMB, V_CTL_MODE_AUTO_THROTTLE, v_ctl_pitch_setpoint, v_ctl_throttle_setpoint, v_ctl_throttle_slew(), v_ctl_throttle_slewed, and vsupply.
Referenced by event_task_ap(), handle_periodic_tasks_ap(), and sim_periodic_task().
void event_task_ap (void)
Definition at line 588 of file main_ap.c.
References attitude_loop(), BaroEvent, DatalinkEvent, FALSE, GpsEvent, i2c_event(), ImuEvent, inter_mcu_received_fbw, link_mcu_event_task(), new_ins_attitude, on_accel_event(), on_baro_abs_event(), on_baro_dif_event(), on_gps_solution(), on_gyro_event(), on_mag_event(), and telecommand_task().
Referenced by sim_periodic_task().
void handle_periodic_tasks_ap (void)
Definition at line 213 of file main_ap.c.
References attitude_loop(), attitude_tid, LED_PERIODIC, modules_tid, monitor_task(), monitor_tid, navigation_task(), navigation_tid, reporting_task(), sensors_task(), sensors_tid, sys_time_check_and_ack_timer(), and telemetry_tid.
void init_ap (void)
init done in main_fbw in single MCU
start interrupt task
Definition at line 131 of file main_ap.c.
References ahrs_aligner_init(), ahrs_init(), attitude_tid, audio_telemetry_init(), autopilot_init(), baro_init(), CONTROL_FREQUENCY, GpioInit, gps_init(), h_ctl_init(), imu_init(), ins_init(), IO0DIR, IO0SET, link_mcu_init(), mcu_int_enable, MODULES_FREQUENCY, modules_tid, monitor_tid, nav_init(), NAVIGATION_FREQUENCY, navigation_tid, PERIODIC_FREQUENCY, sensors_tid, settings_init(), stateInit(), sys_time_register_timer(), telemetry_tid, traffic_info_init(), v_ctl_init(), and xbee_init().
Referenced by sim_init().
void monitor_task (void)
monitor stuff run at 1Hz
Definition at line 558 of file main_ap.c.
References autopilot_flight_time, datalink_time, DefaultChannel, DefaultDevice, dist2_to_home, GpioUpdate1, KILL_MODE_DISTANCE, kill_throttle, launch, LOW_BATTERY_DELAY, MIN_SPEED_FOR_TAKEOFF, sys_time::nb_sec, Square, stateGetHorizontalSpeedNorm_f(), TRUE, and vsupply.
Referenced by handle_periodic_tasks_ap(), and sim_monitor_task().
void navigation_task (void)
Compute desired_course.
Definition at line 401 of file main_ap.c.
References CallTCAS, common_nav_periodic_task_4Hz(), current, DefaultChannel, DefaultDevice, energy, FALSE, gps_lost, h_ctl_auto1_rate, h_ctl_course_loop(), lateral_mode, LATERAL_MODE_COURSE, launch, nav_home(), nav_periodic_task(), nav_without_gps(), PERIODIC_SEND_PPRZ_MODE, pprz_mode, PPRZ_MODE_AUTO2, PPRZ_MODE_GPS_OUT_OF_ORDER, PPRZ_MODE_HOME, SEND_CAM, SEND_NAVIGATION, TRUE, v_ctl_altitude_loop(), v_ctl_mode, and V_CTL_MODE_AUTO_ALT.
Referenced by handle_periodic_tasks_ap(), and sim_nav_task().
void reporting_task (void)
Send a series of initialisation messages followed by a stream of periodic ones.
Called at 60Hz.
initialisation phase during boot
then report periodicly
Definition at line 379 of file main_ap.c.
References DefaultChannel, DefaultDevice, FALSE, TRUE, and version.
Referenced by handle_periodic_tasks_ap(), and sim_periodic_task().
void sensors_task (void)
Run at PERIODIC_FREQUENCY (60Hz if not defined)
Definition at line 521 of file main_ap.c.
References ahrs_propagate(), ahrs_timeout_counter, baro_periodic(), imu_periodic(), and ins_periodic().
Referenced by handle_periodic_tasks_ap(), and sim_periodic_task().