Paparazzi UAS: sw/airborne/subsystems/actuators/motor_mixing.h File Reference
motor_mixing.h File Reference
Motor Mixing.
#include "std.h"
#include "paparazzi.h"
#include "generated/airframe.h"
Data Structures
struct MotorMixing
Functions
void motor_mixing_init (void)
void motor_mixing_run (bool_t motors_on, bool_t override_on, pprz_t in_cmd[])
void motor_mixing_run_spinup (uint32_t counter, uint32_t max_counter)
Variables
struct MotorMixing motor_mixing
Detailed Description
Motor Mixing.
Handles the mapping of roll/pitch/yaw commands to actual motor commands.
Definition in file motor_mixing.h.
Function Documentation
void motor_mixing_init (void)
Definition at line 71 of file motor_mixing.c.
References MotorMixing::commands, FALSE, motor_mixing, MOTOR_MIXING_STOP_MOTOR, MotorMixing::nb_failure, MotorMixing::override_enabled, MotorMixing::override_value, pitch_coef, roll_coef, MotorMixing::trim, and yaw_coef.
Referenced by main_init().
void motor_mixing_run (bool_t motors_on, bool_t override_on, pprz_t in_cmd[])
Definition at line 145 of file motor_mixing.c.
References bound_commands(), bound_commands_step(), MotorMixing::commands, INT32_MAX, INT32_MIN, MAX_PPRZ, motor_mixing, MOTOR_MIXING_MAX_MOTOR, MOTOR_MIXING_MIN_MOTOR, MOTOR_MIXING_STOP_MOTOR, MotorMixing::nb_failure, offset_commands(), MotorMixing::override_enabled, MotorMixing::override_value, pitch_coef, roll_coef, thrust_coef, MotorMixing::trim, and yaw_coef.
void motor_mixing_run_spinup (uint32_t counter, uint32_t max_counter)
Definition at line 123 of file motor_mixing.c.
References MotorMixing::commands, motor_mixing, MOTOR_MIXING_MIN_MOTOR, and MOTOR_MIXING_MIN_MOTOR_STARTUP.
Variable Documentation
struct MotorMixing motor_mixing
Definition at line 69 of file motor_mixing.c.
Referenced by bound_commands(), motor_mixing_init(), motor_mixing_run(), motor_mixing_run_spinup(), and offset_commands().