Paparazzi UAS: sw/airborne/subsystems/nav.h File Reference
nav.h File Reference
Fixedwing Navigation library.
#include "std.h"
#include "paparazzi.h"
#include "state.h"
#include "subsystems/navigation/nav_survey_rectangle.h"
#include "subsystems/navigation/common_flight_plan.h"
#include "subsystems/navigation/common_nav.h"
Macros
#define G 9.806
#define Square(_x) ((_x)*(_x))
#define DistanceSquare(p1_x, p1_y, p2_x, p2_y) (Square(p1_x-p2_x)+Square(p1_y-p2_y))
#define NAV_MODE_ROLL 1
#define NAV_MODE_COURSE 2
#define HORIZONTAL_MODE_WAYPOINT 0
#define HORIZONTAL_MODE_ROUTE 1
#define HORIZONTAL_MODE_CIRCLE 2
#define NavGotoWaypoint(_wp)
#define Eight(a, b, c) nav_eight((a), (b), (c))
#define Oval(a, b, c) nav_oval((b), (a), (c))
#define NavCircleWaypoint(wp, radius) nav_circle_XY(waypoints[wp].x, waypoints[wp].y, radius)
#define NormCourse(x)
Normalize a degree angle between 0 and 359.
#define NavCircleCount() (fabs(nav_circle_radians) / (2*M_PI))
#define NavCircleQdr() ({ float qdr = DegOfRad(M_PI_2 - nav_circle_trigo_qdr); NormCourse(qdr); qdr; })
#define CloseDegAngles(_c1, _c2) ({ float _diff = _c1 - _c2; NormCourse(_diff); 350 < _diff || _diff < 10; })
#define NavQdrCloseTo(x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
#define NavCourseCloseTo(x) CloseDegAngles(x, DegOfRad(*stateGetHorizontalSpeedDir_f()))
#define NavSegment(_start, _end) nav_route_xy(waypoints[_start].x, waypoints[_start].y, waypoints[_end].x, waypoints[_end].y)
#define NavApproaching(wp, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, last_x, last_y, time)
#define NavApproachingFrom(wp, from, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, waypoints[from].x, waypoints[from].y, time)
#define NavVerticalAutoThrottleMode(_pitch)
Set the climb control to auto-throttle with the specified pitch pre-command.
#define NavVerticalAutoPitchMode(_throttle)
Set the climb control to auto-pitch with the specified throttle pre-command.
#define NavVerticalAltitudeMode(_alt, _pre_climb)
Set the vertical mode to altitude control with the specified altitude setpoint and climb pre-command.
#define NavVerticalClimbMode(_climb)
Set the vertical mode to climb control with the specified climb setpoint.
#define NavVerticalThrottleMode(_throttle)
Set the vertical mode to fixed throttle with the specified setpoint.
#define NavHeading(_course)
#define NavAttitude(_roll)
#define nav_IncreaseShift(x) { if (x==0) nav_shift = 0; else nav_shift += x; }
#define nav_SetNavRadius(x) { if (x==1) nav_radius = DEFAULT_CIRCLE_RADIUS; else if (x==-1) nav_radius = -DEFAULT_CIRCLE_RADIUS; else nav_radius = x; }
#define NavKillThrottle() { kill_throttle = 1; }
#define GetPosX() (stateGetPositionUtm_f()->north)
#define GetPosY() (stateGetPositionUtm_f()->east)
#define GetPosAlt() (stateGetPositionUtm_f()->alt)
Enumerations
enum oval_status { OR12, OC2, OR21, OC1 }
Functions
void fly_to_xy (float x, float y)
Computes desired_x, desired_y and desired_course.
void nav_eight_init (void)
void nav_eight (uint8_t, uint8_t, float)
Navigation along a figure 8.
void nav_oval_init (void)
void nav_oval (uint8_t, uint8_t, float)
void nav_periodic_task (void)
Navigation main: call to the code generated from the XML flight plan.
void nav_home (void)
Home mode navigation (circle around HOME)
void nav_init (void)
Navigation Initialisation.
void nav_without_gps (void)
Failsafe navigation without position estimation.
void nav_circle_XY (float x, float y, float radius)
Angle from center to mobile.
void nav_route_xy (float last_wp_x, float last_wp_y, float wp_x, float wp_y)
Computes the carrot position along the desired segment.
bool_t nav_approaching_xy (float x, float y, float from_x, float from_y, float approaching_time)
Decide if the UAV is approaching the current waypoint.
Variables
float cur_pos_x
float cur_pos_y
float last_x
float last_y
float desired_x
float desired_y
float nav_altitude
float flight_altitude
Dynamically adjustable, reset to nav_altitude when it is changing.
float nav_glide_pitch_trim
pprz_t nav_throttle_setpoint
float nav_pitch
with INT32_ANGLE_FRAC
float rc_pitch
float fp_pitch
float carrot_x
float carrot_y
float nav_circle_radians
Status on the current circle.
bool_t nav_in_circle
bool_t nav_in_segment
float nav_circle_x
float nav_circle_y
float nav_circle_radius
float nav_segment_x_1
float nav_segment_y_1
float nav_segment_x_2
float nav_segment_y_2
int nav_mode
uint8_t horizontal_mode
uint8_t nav_oval_count
Navigation along a figure O.
float nav_radius
float nav_course
with INT32_ANGLE_FRAC
float nav_climb
float nav_shift
float nav_ground_speed_pgain
float nav_ground_speed_setpoint
float nav_survey_shift
float nav_survey_west
float nav_survey_east
float nav_survey_north
float nav_survey_south
bool_t nav_survey_active
float nav_circle_trigo_qdr
Detailed Description
Fixedwing Navigation library.
This collection of macros and functions is used by the C code generated from the XML flight plan.
Definition in file nav.h.
Macro Definition Documentation
#define CloseDegAngles (_c1, _c2) ({ float _diff = _c1 - _c2; NormCourse(_diff); 350 < _diff || _diff < 10; })
Definition at line 129 of file nav.h.
#define DistanceSquare (p1_x, p1_y, p2_x, p2_y) (Square(p1_x-p2_x)+Square(p1_y-p2_y))
Definition at line 46 of file nav.h.
Referenced by nav_circle_XY().
#define Eight (a, b, c) nav_eight((a), (b), (c))
Definition at line 89 of file nav.h.
#define G 9.806
Definition at line 44 of file nav.h.
Referenced by lla_of_ecef_d(), lla_of_ecef_f(), and nav_circle_XY().
#define GetPosAlt () (stateGetPositionUtm_f()->alt)
Definition at line 199 of file nav.h.
#define GetPosX () (stateGetPositionUtm_f()->north)
Definition at line 197 of file nav.h.
#define GetPosY () (stateGetPositionUtm_f()->east)
Definition at line 198 of file nav.h.
#define HORIZONTAL_MODE_CIRCLE 2
Definition at line 77 of file nav.h.
#define HORIZONTAL_MODE_ROUTE 1
Definition at line 76 of file nav.h.
#define HORIZONTAL_MODE_WAYPOINT 0
Definition at line 75 of file nav.h.
#define nav_IncreaseShift (x) { if (x==0) nav_shift = 0; else nav_shift += x; }
Definition at line 191 of file nav.h.
#define NAV_MODE_COURSE 2
Definition at line 71 of file nav.h.
Referenced by fly_to_xy(), nav_circle_XY(), and nav_init().
#define NAV_MODE_ROLL 1
Definition at line 70 of file nav.h.
#define nav_SetNavRadius (x) { if (x==1) nav_radius = DEFAULT_CIRCLE_RADIUS; else if (x==-1) nav_radius = -DEFAULT_CIRCLE_RADIUS; else nav_radius = x; }
Definition at line 193 of file nav.h.
#define NavApproaching (wp, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, last_x, last_y, time)
Definition at line 142 of file nav.h.
#define NavApproachingFrom (wp, from, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, waypoints[from].x, waypoints[from].y, time)
Definition at line 143 of file nav.h.
#define NavAttitude (_roll)
Value:
{ \
  lateral_mode = LATERAL_MODE_ROLL; \
  if(pprz_mode != PPRZ_MODE_AUTO1)  \
   {h_ctl_roll_setpoint = _roll;} \
}
Definition at line 185 of file nav.h.
#define NavCircleCount () (fabs(nav_circle_radians) / (2*M_PI))
Definition at line 126 of file nav.h.
#define NavCircleQdr () ({ float qdr = DegOfRad(M_PI_2 - nav_circle_trigo_qdr); NormCourse(qdr); qdr; })
Definition at line 127 of file nav.h.
#define NavCircleWaypoint (wp, radius) nav_circle_XY(waypoints[wp].x, waypoints[wp].y, radius)
Definition at line 116 of file nav.h.
#define NavCourseCloseTo (x) CloseDegAngles(x, DegOfRad(*stateGetHorizontalSpeedDir_f()))
Definition at line 134 of file nav.h.
#define NavGotoWaypoint (_wp)
Value:
{ \
  horizontal_mode = HORIZONTAL_MODE_WAYPOINT; \
  fly_to_xy(waypoints[_wp].x, waypoints[_wp].y); \
}
Definition at line 81 of file nav.h.
#define NavHeading (_course)
Value:
{ \
  lateral_mode = LATERAL_MODE_COURSE; \
  h_ctl_course_setpoint = _course; \
}
Definition at line 180 of file nav.h.
#define NavKillThrottle () { kill_throttle = 1; }
Definition at line 195 of file nav.h.
#define NavQdrCloseTo (x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
Definition at line 132 of file nav.h.
#define NavSegment (_start, _end) nav_route_xy(waypoints[_start].x, waypoints[_start].y, waypoints[_end].x, waypoints[_end].y)
Definition at line 138 of file nav.h.
#define NavVerticalAltitudeMode (_alt, _pre_climb)
Value:
{ \
  v_ctl_mode = V_CTL_MODE_AUTO_ALT; \
  nav_altitude = _alt; \
  v_ctl_altitude_pre_climb = _pre_climb; \
}
Set the vertical mode to altitude control with the specified altitude setpoint and climb pre-command.
Definition at line 162 of file nav.h.
#define NavVerticalAutoPitchMode (_throttle)
Value:
{ \
  v_ctl_climb_mode = V_CTL_CLIMB_MODE_AUTO_PITCH; \
  nav_throttle_setpoint = _throttle; \
}
Set the climb control to auto-pitch with the specified throttle pre-command.
Definition at line 155 of file nav.h.
#define NavVerticalAutoThrottleMode (_pitch)
Value:
{ \
  v_ctl_climb_mode = V_CTL_CLIMB_MODE_AUTO_THROTTLE; \
  nav_pitch = _pitch; \
}
Set the climb control to auto-throttle with the specified pitch pre-command.
Definition at line 148 of file nav.h.
#define NavVerticalClimbMode (_climb)
Value:
{ \
  v_ctl_mode = V_CTL_MODE_AUTO_CLIMB; \
  v_ctl_climb_setpoint = _climb; \
}
Set the vertical mode to climb control with the specified climb setpoint.
Definition at line 169 of file nav.h.
#define NavVerticalThrottleMode (_throttle)
Value:
{ \
  v_ctl_mode = V_CTL_MODE_AUTO_THROTTLE; \
  nav_throttle_setpoint = _throttle; \
}
Set the vertical mode to fixed throttle with the specified setpoint.
Definition at line 175 of file nav.h.
#define NormCourse (x)
Value:
{ \
  uint8_t dont_loop_forever = 0;  \
  while (x < 0 && ++dont_loop_forever) x += 360; \
  while (x >= 360 && ++dont_loop_forever) x -= 360; \
}
Normalize a degree angle between 0 and 359.
Definition at line 120 of file nav.h.
#define Oval (a, b, c) nav_oval((b), (a), (c))
Definition at line 94 of file nav.h.
#define Square (_x) ((_x)*(_x))
Definition at line 45 of file nav.h.
Referenced by monitor_task(), and nav_circle_XY().
Enumeration Type Documentation
enum oval_status
Enumerator:
OR12
OC2
OR21
OC1
Definition at line 48 of file nav.h.
Function Documentation
void fly_to_xy (float x, float y)
Computes desired_x, desired_y and desired_course.
Definition at line 335 of file nav.c.
References h_ctl_course_pgain, h_ctl_course_setpoint, h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, lateral_mode, LATERAL_MODE_COURSE, LATERAL_MODE_ROLL, NAV_MODE_COURSE, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), EnuCoor_f::x, and EnuCoor_f::y.
Referenced by formation_flight(), nav_circle_XY(), nav_follow(), nav_route_xy(), and potential_task().
bool_t nav_approaching_xy (float x, float y, float from_x, float from_y, float approaching_time)
Decide if the UAV is approaching the current waypoint.
Computes dist2_to_wp and compare it to square carrot. Return true if it is smaller. Else computes by scalar products if uav has not gone past waypoint. Return true if it is the case.
distance to waypoint in x
distance to waypoint in y
Definition at line 314 of file nav.c.
References dist2_to_wp, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), TRUE, EnuCoor_f::x, and EnuCoor_f::y.
Referenced by disc_survey(), FlightLine(), nav_eight(), nav_oval(), poly_survey_adv(), PolygonSurvey(), snav_route(), and SpiralNav().
void nav_circle_XY (float x, float y, float radius)
Angle from center to mobile.
Angle from center to mobile.
Clockwise iff radius > 0
Computes a prebank. Go straight if inside or outside the circle
Definition at line 107 of file nav.c.
References DistanceSquare, fly_to_xy(), G, HORIZONTAL_MODE_CIRCLE, Max, Min, nav_circle_trigo_qdr, NAV_MODE_COURSE, nav_shift, radius, Square, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), TRUE, EnuCoor_f::x, and EnuCoor_f::y.
Referenced by border_line(), disc_survey(), FlightLine(), FlowerNav(), nav_eight(), nav_line(), nav_oval(), poly_survey_adv(), PolygonSurvey(), SkidLanding(), snav_circle1(), snav_circle2(), snav_on_time(), SpiralNav(), and VerticalRaster().
void nav_eight (uint8_t target, uint8_t c1, float radius)
Navigation along a figure 8.
The cross center is defined by the waypoint [target], the center of one of the circles is defined by [c1]. Altitude is given by [target]. The navigation goes through 6 states: C1 (circle around [c1]), R1T, RT2 (route from circle 1 to circle 2 over [target]), C2 and R2T, RT1. If necessary, the [c1] waypoint is moved in the direction of [target] to be not far than [2*radius].
Definition at line 488 of file nav.c.
References c1, C1, C2, InitStage, Max, nav_approaching_xy(), nav_circle_XY(), nav_route_xy(), NavCircleWaypoint, NavQdrCloseTo, R1T, R2T, RT1, RT2, waypoints, point::x, EnuCoor_i::x, point::y, and EnuCoor_i::y.
void nav_eight_init (void)
Definition at line 476 of file nav.c.
References C1.
void nav_home (void)
Home mode navigation (circle around HOME)
Nominal speed
Definition at line 334 of file navigation.c.
References compute_dist2_to_home(), dist2_to_home, dist2_to_wp, FAILSAFE_HOME_RADIUS, ground_alt, nav_set_altitude(), NavCircleWaypoint, v_ctl_mode, and V_CTL_MODE_AUTO_ALT.
Referenced by navigation_task().
void nav_init (void)
Navigation Initialisation.
Definition at line 84 of file navigation.c.
References DEFAULT_CIRCLE_RADIUS, ground_alt, HORIZONTAL_MODE_WAYPOINT, INT32_VECT3_COPY, nav_altitude, nav_block, NAV_GLIDE_PITCH_TRIM, NAV_MODE_COURSE, nav_stage, navigation_carrot, navigation_target, nb_waypoint, POS_BFP_OF_REAL, VERTICAL_MODE_ALT, waypoints, EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.
Referenced by init_ap(), and main_init().
void nav_oval (uint8_t , uint8_t , float)
Definition at line 609 of file nav.c.
References InitStage, LINE_START_FUNCTION, LINE_STOP_FUNCTION, nav_approaching_xy(), nav_circle_XY(), nav_route_xy(), NavQdrCloseTo, OC1, OC2, OR12, OR21, radius, waypoints, point::x, EnuCoor_i::x, point::y, and EnuCoor_i::y.
void nav_oval_init (void)
Definition at line 604 of file nav.c.
References OC2.
void nav_periodic_task (void)
Navigation main: call to the code generated from the XML flight plan.
Definition at line 286 of file navigation.c.
References block_time, compute_dist2_to_home(), dist2_to_wp, FALSE, h_ctl_course_pre_bank, LtpDef_i::hmsl, ins_ltp_def, nav_run(), nav_set_altitude(), POS_BFP_OF_REAL, stage_time, V_CTL_AUTO_THROTTLE_STANDARD, v_ctl_auto_throttle_submode, v_ctl_mode, and V_CTL_MODE_AUTO_CLIMB.
Referenced by autopilot_periodic(), and navigation_task().
void nav_route_xy (float last_wp_x, float last_wp_y, float wp_x, float wp_y)
Computes the carrot position along the desired segment.
distance of carrot (in meter)
Definition at line 359 of file nav.c.
References fly_to_xy(), HORIZONTAL_MODE_ROUTE, Max, stateGetPositionEnu_f(), TRUE, EnuCoor_f::x, and EnuCoor_f::y.
Referenced by BungeeTakeoff(), disc_survey(), FlightLine(), FlowerNav(), nav_eight(), nav_oval(), nav_points(), nav_survey_losange_carto(), nav_survey_rectangle(), PolygonSurvey(), SkidLanding(), snav_route(), and SpiralNav().
void nav_without_gps (void)
Failsafe navigation without position estimation.
Just set attitude and throttle to FAILSAFE values to prevent the plane from crashing.
Definition at line 454 of file nav.c.
References h_ctl_roll_setpoint, lateral_mode, LATERAL_MODE_ROLL, MAX_PPRZ, TRIM_UPPRZ, v_ctl_mode, and V_CTL_MODE_AUTO_THROTTLE.
Referenced by navigation_task().
Variable Documentation
float carrot_x
Definition at line 49 of file nav.c.
float carrot_y
Definition at line 49 of file nav.c.
float cur_pos_x
float cur_pos_y
float desired_x
Definition at line 302 of file nav.c.
Referenced by cam_segment_periodic(), formation_flight(), and potential_task().
float desired_y
Definition at line 302 of file nav.c.
Referenced by cam_segment_periodic(), formation_flight(), and potential_task().
float flight_altitude
Dynamically adjustable, reset to nav_altitude when it is changing.
Definition at line 76 of file navigation.c.
Referenced by formation_flight(), and nav_set_altitude().
float fp_pitch
Definition at line 305 of file nav.c.
uint8_t horizontal_mode
Definition at line 57 of file navigation.c.
Referenced by guidance_h_run().
float last_x
Definition at line 43 of file nav.c.
Referenced by nav_init_stage(), and poly_survey_adv().
float last_y
Definition at line 43 of file nav.c.
Referenced by nav_init_stage(), and poly_survey_adv().
float nav_altitude
Definition at line 75 of file navigation.c.
Referenced by formation_flight(), nav_init(), nav_set_altitude(), start_formation(), stop_formation(), and tcas_periodic_task_4Hz().
float nav_circle_radians
Status on the current circle.
Definition at line 60 of file navigation.c.
float nav_circle_radius
Definition at line 60 of file navigation.c.
Referenced by flight_benchmark_periodic().
float nav_circle_trigo_qdr
Definition at line 53 of file nav.c.
Referenced by nav_circle_XY().
float nav_circle_x
Definition at line 65 of file nav.c.
Referenced by flight_benchmark_periodic().
float nav_circle_y
Definition at line 65 of file nav.c.
Referenced by flight_benchmark_periodic().
float nav_climb
Definition at line 75 of file navigation.c.
Referenced by guidance_v_run().
float nav_course
with INT32_ANGLE_FRAC
Definition at line 66 of file navigation.c.
float nav_glide_pitch_trim
Definition at line 73 of file nav.c.
float nav_ground_speed_pgain
Definition at line 80 of file nav.c.
float nav_ground_speed_setpoint
Definition at line 80 of file nav.c.
bool_t nav_in_circle
Definition at line 63 of file nav.c.
Referenced by nav_survey_rectangle().
bool_t nav_in_segment
Definition at line 64 of file nav.c.
Referenced by nav_survey_rectangle().
int nav_mode
Definition at line 87 of file nav.c.
uint8_t nav_oval_count
Navigation along a figure O.
One side leg is defined by waypoints [p1] and [p2]. The navigation goes through 4 states: OC1 (half circle next to [p1]), OR21 (route [p2] to [p1], OC2 (half circle next to [p2]) and OR12 (opposite leg).
Initial state is the route along the desired segment (OC2).
Definition at line 602 of file nav.c.
float nav_pitch
with INT32_ANGLE_FRAC
Definition at line 65 of file navigation.c.
Referenced by attitude_loop(), guidance_h_run(), nav_init_stage(), v_ctl_climb_auto_throttle_loop(), v_ctl_climb_loop(), and v_ctl_set_pitch().
float nav_radius
Definition at line 67 of file navigation.c.
Referenced by FlowerNav(), and nav_compute_baseleg().
float nav_segment_x_1
Definition at line 66 of file nav.c.
Referenced by flight_benchmark_periodic().
float nav_segment_x_2
Definition at line 66 of file nav.c.
Referenced by flight_benchmark_periodic().
float nav_segment_y_1
Definition at line 66 of file nav.c.
Referenced by flight_benchmark_periodic().
float nav_segment_y_2
Definition at line 66 of file nav.c.
Referenced by flight_benchmark_periodic().
float nav_shift
Definition at line 54 of file nav.c.
Referenced by nav_circle_XY().
bool_t nav_survey_active
Definition at line 85 of file nav.c.
Referenced by nav_survey_rectangle().
float nav_survey_east
Definition at line 84 of file nav.c.
Referenced by nav_survey_rectangle(), and nav_survey_rectangle_init().
float nav_survey_north
Definition at line 84 of file nav.c.
Referenced by nav_survey_rectangle(), and nav_survey_rectangle_init().
float nav_survey_shift
Definition at line 83 of file nav.c.
Referenced by disc_survey(), disc_survey_init(), nav_survey_rectangle(), and nav_survey_rectangle_init().
float nav_survey_south
Definition at line 84 of file nav.c.
Referenced by nav_survey_rectangle(), and nav_survey_rectangle_init().
float nav_survey_west
Definition at line 84 of file nav.c.
Referenced by nav_survey_rectangle(), and nav_survey_rectangle_init().
pprz_t nav_throttle_setpoint
Definition at line 303 of file nav.c.
Referenced by attitude_loop().
float rc_pitch
Definition at line 48 of file nav.c.