Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/quat_setpoint_int.c File Reference
quat_setpoint_int.c File Reference
Quaternion setpoint generation.
#include "state.h"
#include "stabilization/stabilization_attitude_ref_quat_int.h"
#include "stabilization/quat_setpoint_int.h"
#include "stabilization.h"
#include "messages.h"
#include "mcu_periph/uart.h"
#include "subsystems/datalink/downlink.h"
Defines
#define QUAT_SETPOINT_HOVER_PITCH RadOfDeg(90)
#define ROLL_COEF (STABILIZATION_ATTITUDE_SP_MAX_PHI / MAX_PPRZ)
#define PITCH_COEF (STABILIZATION_ATTITUDE_SP_MAX_THETA / MAX_PPRZ)
#define YAW_COEF (STABILIZATION_ATTITUDE_SP_MAX_PSI / MAX_PPRZ)
#define DEADBAND_EXCEEDED(VARIABLE, VALUE) ((VARIABLE > VALUE) || (VARIABLE < -VALUE))
#define APPLY_DEADBAND(VARIABLE, VALUE) (DEADBAND_EXCEEDED(VARIABLE, VALUE) ? VARIABLE : 0.0)
Functions
static void reset_sp_quat (int32_t _psi, int32_t _theta, struct Int32Quat *initial)
void stabilization_attitude_read_rc_absolute (bool_t in_flight)
void stabilization_attitude_sp_enter (void)
Detailed Description
Quaternion setpoint generation.
Definition in file quat_setpoint_int.c.
Define Documentation
#define APPLY_DEADBAND (VARIABLE, VALUE) (DEADBAND_EXCEEDED(VARIABLE, VALUE) ? VARIABLE : 0.0)
Definition at line 29 of file quat_setpoint_int.c.
Referenced by stabilization_attitude_read_rc_absolute().
#define DEADBAND_EXCEEDED (VARIABLE, VALUE) ((VARIABLE > VALUE) || (VARIABLE < -VALUE))
Definition at line 28 of file quat_setpoint_int.c.
#define PITCH_COEF (STABILIZATION_ATTITUDE_SP_MAX_THETA / MAX_PPRZ)
Definition at line 25 of file quat_setpoint_int.c.
Referenced by stabilization_attitude_read_rc_absolute().
#define QUAT_SETPOINT_HOVER_PITCH RadOfDeg(90)
Definition at line 22 of file quat_setpoint_int.c.
Referenced by reset_sp_quat().
#define ROLL_COEF (STABILIZATION_ATTITUDE_SP_MAX_PHI / MAX_PPRZ)
Definition at line 24 of file quat_setpoint_int.c.
Referenced by stabilization_attitude_read_rc_absolute().
#define YAW_COEF (STABILIZATION_ATTITUDE_SP_MAX_PSI / MAX_PPRZ)
Definition at line 26 of file quat_setpoint_int.c.
Referenced by stabilization_attitude_read_rc_absolute().
Function Documentation
static void reset_sp_quat (int32_t _psi, int32_t _theta, struct Int32Quat * initial) [static]
Definition at line 32 of file quat_setpoint_int.c.
References ANGLE_BFP_OF_REAL, INT32_EULERS_OF_QUAT, INT32_QUAT_COMP_NORM_SHORTEST, INT32_QUAT_OF_AXIS_ANGLE, INT32_QUAT_OF_EULERS, Int32Eulers::phi, QUAT_COPY, QUAT_SETPOINT_HOVER_PITCH, stab_att_sp_quat, and Int32Eulers::theta.
Referenced by stabilization_attitude_read_rc_absolute(), and stabilization_attitude_sp_enter().
void stabilization_attitude_read_rc_absolute (bool_t in_flight)
Definition at line 65 of file quat_setpoint_int.c.
References APPLY_DEADBAND, INT32_EULERS_OF_QUAT, INT32_QUAT_COMP_NORM_SHORTEST, INT32_QUAT_OF_EULERS, Int32Eulers::phi, PITCH_COEF, Int32Eulers::psi, QUAT_COPY, radio_control, RADIO_PITCH, RADIO_ROLL, RADIO_YAW, RATE_BFP_OF_REAL, RC_UPDATE_FREQ, reset_sp_quat(), ROLL_COEF, stab_att_sp_euler, stab_att_sp_quat, stateGetNedToBodyQuat_i(), Int32Eulers::theta, RadioControl::values, and YAW_COEF.
Referenced by stabilization_attitude_read_rc().
void stabilization_attitude_sp_enter (void)
Definition at line 104 of file quat_setpoint_int.c.
References reset_sp_quat(), and stateGetNedToBodyQuat_i().
Referenced by stabilization_attitude_ref_enter().