Paparazzi UAS: sw/airborne/peripherals/sc18i600.h File Reference
sc18i600.h File Reference
#include "std.h"
#include "peripherals/sc18is600_arch.h"
Data Structures
struct Sc18Is600
Defines
#define Sc18Is600_IOConfig 0x00
#define Sc18Is600_IOState 0x01
#define Sc18Is600_I2CClock 0x02
#define Sc18Is600_I2CTO 0x03
#define Sc18Is600_I2CStat 0x04
#define Sc18Is600_I2CAdr 0x05
#define SC18IS600_BUF_LEN 96
Enumerations
enum Sc18Is600Status {
Sc18Is600Idle, Sc18Is600SendingRequest, Sc18Is600WaitingForI2C, Sc18Is600ReadingI2CStat,
Sc18Is600ReadingBuffer, Sc18Is600TransactionComplete
}
enum Sc18Is600Transaction {
Sc18Is600Transmit, Sc18Is600Receive, Sc18Is600Transcieve, Sc18Is600ReadRegister,
Sc18Is600WriteRegister
}
Functions
void sc18is600_init (void)
void sc18is600_transmit (uint8_t addr, uint8_t len)
void sc18is600_receive (uint8_t addr, uint8_t len)
void sc18is600_tranceive (uint8_t addr, uint8_t len_tx, uint8_t len_rx)
void sc18is600_write_to_register (uint8_t addr, uint8_t value)
void sc18is600_read_from_register (uint8_t addr)
void sc18is600_arch_init (void)
Variables
struct Sc18Is600 sc18is600
Define Documentation
#define SC18IS600_BUF_LEN 96
Definition at line 31 of file sc18i600.h.
#define Sc18Is600_I2CAdr 0x05
Definition at line 12 of file sc18i600.h.
#define Sc18Is600_I2CClock 0x02
Definition at line 9 of file sc18i600.h.
Referenced by main_periodic_task().
#define Sc18Is600_I2CStat 0x04
Definition at line 11 of file sc18i600.h.
#define Sc18Is600_I2CTO 0x03
Definition at line 10 of file sc18i600.h.
#define Sc18Is600_IOConfig 0x00
Definition at line 7 of file sc18i600.h.
#define Sc18Is600_IOState 0x01
Definition at line 8 of file sc18i600.h.
Enumeration Type Documentation
enum Sc18Is600Status
Enumerator:
Sc18Is600Idle
Sc18Is600SendingRequest
Sc18Is600WaitingForI2C
Sc18Is600ReadingI2CStat
Sc18Is600ReadingBuffer
Sc18Is600TransactionComplete
Definition at line 15 of file sc18i600.h.
enum Sc18Is600Transaction
Enumerator:
Sc18Is600Transmit
Sc18Is600Receive
Sc18Is600Transcieve
Sc18Is600ReadRegister
Sc18Is600WriteRegister
Definition at line 24 of file sc18i600.h.
Function Documentation
void sc18is600_arch_init (void)
Definition at line 25 of file sc18is600_arch.c.
References Sc18Is600Unselect.
Referenced by sc18is600_init().
void sc18is600_init (void)
Definition at line 5 of file sc18i600.c.
References sc18is600, sc18is600_arch_init(), Sc18Is600Idle, and Sc18Is600::status.
void sc18is600_read_from_register (uint8_t addr)
Definition at line 189 of file sc18is600_arch.c.
References Sc18Is600::priv_tx_buf, sc18is600, Sc18Is600_Cmd_Read_From_Reg, sc18is600_setup_SPI_DMA(), Sc18Is600ReadRegister, Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600::status, and Sc18Is600::transaction.
Referenced by main_periodic_task().
void sc18is600_receive (uint8_t addr, uint8_t len)
Definition at line 161 of file sc18is600_arch.c.
void sc18is600_tranceive (uint8_t addr, uint8_t len_tx, uint8_t len_rx)
Definition at line 165 of file sc18is600_arch.c.
References Sc18Is600::priv_tx_buf, Sc18Is600::rx_len, sc18is600, Sc18Is600_Cmd_Read_After_Write, sc18is600_setup_SPI_DMA(), Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600Transcieve, Sc18Is600::status, and Sc18Is600::transaction.
Referenced by main_periodic_task().
void sc18is600_transmit (uint8_t addr, uint8_t len)
Definition at line 149 of file sc18is600_arch.c.
References Sc18Is600::priv_tx_buf, sc18is600, Sc18Is600_Cmd_Write, sc18is600_setup_SPI_DMA(), Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600Transmit, Sc18Is600::status, and Sc18Is600::transaction.
Referenced by main_periodic_task().
void sc18is600_write_to_register (uint8_t addr, uint8_t value)
Definition at line 178 of file sc18is600_arch.c.
References Sc18Is600::priv_tx_buf, sc18is600, Sc18Is600_Cmd_Write_To_Reg, sc18is600_setup_SPI_DMA(), Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600WriteRegister, Sc18Is600::status, and Sc18Is600::transaction.
Referenced by main_periodic_task().
Variable Documentation
struct Sc18Is600 sc18is600
Definition at line 3 of file sc18i600.c.
Referenced by main_periodic_task(), sc18is600_init(), sc18is600_read_from_register(), sc18is600_setup_SPI_DMA(), sc18is600_tranceive(), sc18is600_transmit(), and sc18is600_write_to_register().