Paparazzi UAS: sw/airborne/sd_card/main.c File Reference
main.c File Reference
#include "std.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
#include "subsystems/datalink/datalink.h"
#include "generated/settings.h"
#include "dl_protocol.h"
#include "mcu_periph/spi.h"
#include "sd_card.h"
Defines
#define IdOfMsg(x) (x[1])
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
int main (void)
void dl_parse_msg (void)
Variables
uint8_t dl_buffer [MSG_SIZE]
bool_t dl_msg_available
uint16_t datalink_time
Define Documentation
#define IdOfMsg (x) (x[1])
Definition at line 66 of file main.c.
Referenced by dl_parse_msg().
Function Documentation
void dl_parse_msg (void)
NAV
WIND_INFO
Else there is no dl_settings section in the flight plan
Definition at line 68 of file main.c.
References c, datalink_time, DefaultChannel, DefaultDevice, dl_buffer, UtmCoor_f::east, gps_nb_ovrn, IdOfMsg, infrared, JoystickHandeDatalink, LlaCoor_f::lat, LED_TOGGLE, LlaCoor_f::lon, MOfCm, nav_goto_block(), nav_move_waypoint(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, parse_rc_3ch_datalink(), parse_rc_4ch_datalink(), Infrared::pitch, tcas_ac_status::resolve, Infrared::roll, SEND_NAVIGATION, SenderIdOfMsg, SetAcInfo, stateGetAirspeed_f(), stateSetAirspeed_f(), stateSetHorizontalWindspeed_f(), tcas_acs_status, the_acs_id, Infrared::top, TRUE, utm_of_lla_f(), val, waypoints, FloatVect2::x, EnuCoor_i::x, FloatVect2::y, EnuCoor_i::y, and UtmCoor_f::zone.
int main (void)
Definition at line 26 of file main.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) [inline, static]
Definition at line 53 of file main.c.
References DatalinkEvent, FALSE, sd_card_event(), and spi_message_received.
Referenced by main().
static void main_init (void) [inline, static]
static void main_periodic_task (void) [inline, static]
Definition at line 48 of file main.c.
References LED_TOGGLE.
Referenced by main().
Variable Documentation
uint16_t datalink_time
Definition at line 24 of file main.c.
uint8_t dl_buffer[MSG_SIZE]
Definition at line 22 of file main.c.
bool_t dl_msg_available
Definition at line 23 of file main.c.