Paparazzi UAS: sw/airborne/sd_card/sd_card.h File Reference
sd_card.h File Reference
#include "std.h"
Functions
void sd_card_init (void)
void sd_card_periodic (void)
void sd_card_event (void)
Variables
uint8_t buf_input [3]
uint8_t buf_output [3]
bool_t sd_card_available
Detailed Description
Definition in file sd_card.h.
Function Documentation
void sd_card_event (void)
Definition at line 97 of file sd_card.c.
References status_read_data.
Referenced by main_event_task().
void sd_card_init (void)
Definition at line 58 of file sd_card.c.
References CMD_INIT_1, CMD_INIT_2, CMD_INIT_3, CMD_INIT_4, CMD_INIT_5, CMD_INIT_6, FALSE, sd_card_available, send1_on_spi(), and status_read_data.
void sd_card_periodic (void)
Definition at line 72 of file sd_card.c.
References buf_input, buf_output, CMD_MEASUREMENT, SpiStart(), and status_read_data.
Variable Documentation
uint8_t buf_input[3]
Definition at line 44 of file sd_card.c.
uint8_t buf_output[3]
Definition at line 45 of file sd_card.c.
bool_t sd_card_available
Definition at line 31 of file sd_card.c.
Referenced by sd_card_init().