Paparazzi UAS: sw/airborne/arch/sim/sim_ap.c File Reference
sim_ap.c File Reference
#include <stdio.h>
#include <assert.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <time.h>
#include <string.h>
#include "std.h"
#include "inter_mcu.h"
#include "autopilot.h"
#include "subsystems/gps.h"
#include "subsystems/navigation/traffic_info.h"
#include "generated/settings.h"
#include "subsystems/nav.h"
#include "firmwares/fixedwing/stabilization/stabilization_attitude.h"
#include "firmwares/fixedwing/guidance/guidance_v.h"
#include "subsystems/commands.h"
#include "firmwares/fixedwing/main_ap.h"
#include "ap_downlink.h"
#include "sim_uart.h"
#include "subsystems/datalink/datalink.h"
#include "generated/flight_plan.h"
#include "generated/modules.h"
#include <caml/mlvalues.h>
#include <caml/memory.h>
Macros
#define MODULES_C
Functions
value sim_periodic_task (value unit)
value sim_monitor_task (value unit)
value sim_nav_task (value unit)
float ftimeofday (void)
value sim_init (value unit)
value update_bat (value bat)
value get_commands (value val_commands)
value set_datalink_message (value s)
void adc_buf_channel (void *a, void *b, void *c)
Required by electrical.
Variables
uint8_t ir_estim_mode
uint8_t vertical_mode
uint8_t inflight_calib_mode
bool_t rc_event_1
bool_t rc_event_2
bool_t launch
uint8_t gps_nb_ovrn
uint8_t link_fbw_fbw_nb_err
uint8_t link_fbw_nb_err
float alt_roll_pgain
float roll_rate_pgain
bool_t gpio1_status
uint16_t datalink_time = 0
uint8_t ac_id
Macro Definition Documentation
#define MODULES_C
Definition at line 4 of file sim_ap.c.
Function Documentation
void adc_buf_channel (void * a, void * b, void * c)
Required by electrical.
Definition at line 137 of file sim_ap.c.
float ftimeofday (void)
Definition at line 74 of file sim_ap.c.
value get_commands (value val_commands)
Definition at line 114 of file sim_ap.c.
References commands.
value set_datalink_message (value s)
Definition at line 123 of file sim_ap.c.
References dl_buffer, dl_parse_msg(), and MSG_SIZE.
value sim_init (value unit)
Definition at line 81 of file sim_ap.c.
References init_ap(), init_fbw(), pipe_stream, and unit.
value sim_monitor_task (value unit)
Definition at line 63 of file sim_ap.c.
References monitor_task(), and unit.
value sim_nav_task (value unit)
Definition at line 68 of file sim_ap.c.
References navigation_task(), and unit.
value sim_periodic_task (value unit)
Definition at line 51 of file sim_ap.c.
References attitude_loop(), electrical_periodic(), event_task_ap(), event_task_fbw(), periodic_task_fbw(), reporting_task(), sensors_task(), and unit.
value update_bat (value bat)
Definition at line 108 of file sim_ap.c.
References electrical, and Electrical::vsupply.
Variable Documentation
uint8_t ac_id
Definition at line 49 of file sim_ap.c.
float alt_roll_pgain
Definition at line 42 of file sim_ap.c.
uint16_t datalink_time = 0
Definition at line 45 of file sim_ap.c.
Referenced by dl_parse_msg(), main_periodic(), monitor_task(), and xtend_rssi_periodic().
bool_t gpio1_status
Definition at line 44 of file sim_ap.c.
uint8_t gps_nb_ovrn
Definition at line 41 of file sim_ap.c.
uint8_t inflight_calib_mode
Definition at line 38 of file sim_ap.c.
uint8_t ir_estim_mode
Definition at line 36 of file sim_ap.c.
bool_t launch
Definition at line 40 of file sim_ap.c.
Referenced by attitude_loop(), autopilot_init(), Drift_correction(), h_ctl_course_loop(), h_ctl_pitch_loop(), h_ctl_roll_loop(), monitor_task(), nav_catapult_highrate_module(), navigation_task(), telecommand_task(), v_ctl_climb_loop(), v_ctl_set_pitch(), and v_ctl_set_throttle().
uint8_t link_fbw_fbw_nb_err
Definition at line 41 of file sim_ap.c.
uint8_t link_fbw_nb_err
Definition at line 41 of file sim_ap.c.
bool_t rc_event_1
Definition at line 39 of file sim_ap.c.
bool_t rc_event_2
Definition at line 39 of file sim_ap.c.
float roll_rate_pgain
Definition at line 43 of file sim_ap.c.
uint8_t vertical_mode
Definition at line 37 of file sim_ap.c.
Referenced by guidance_v_run().