Paparazzi UAS: sw/airborne/arch/sim/mcu_periph/spi_arch.c File Reference
spi_arch.c File Reference
#include "mcu_periph/spi.h"
Functions
bool_t spi_submit (struct spi_periph *p, struct spi_transaction *t)
void spi_init_slaves (void)
void spi_slave_select (uint8_t slave)
void spi_slave_unselect (uint8_t slave)
bool_t spi_lock (struct spi_periph *p, uint8_t slave)
bool_t spi_resume (struct spi_periph *p, uint8_t slave)
Function Documentation
void spi_init_slaves (void)
Definition at line 27 of file spi_arch.c.
Referenced by mcu_init().
bool_t spi_lock (struct spi_periph * p, uint8_t slave)
Definition at line 33 of file spi_arch.c.
Referenced by max1168_lock_cb().
bool_t spi_resume (struct spi_periph * p, uint8_t slave)
Definition at line 35 of file spi_arch.c.
Referenced by max1168_event().
void spi_slave_select (uint8_t slave)
Definition at line 29 of file spi_arch.c.
void spi_slave_unselect (uint8_t slave)
Definition at line 31 of file spi_arch.c.
Referenced by max1168_event().
bool_t spi_submit (struct spi_periph * p, struct spi_transaction * t)
Definition at line 25 of file spi_arch.c.
Referenced by imu_periodic(), ins_configure(), max1168_read(), mcp355x_read(), mpu_configure(), mpu_set(), mpu_wait_slave4_ready(), ms2100_event(), ms2100_read(), read_data(), vn100_periodic_task(), w5100_get(), w5100_set(), and write_to_reg().