Paparazzi UAS: sw/airborne/modules/MPPT/sim_MPPT.c File Reference
sim_MPPT.c File Reference
#include "MPPT.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
Macros
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void MPPT_init (void)
void MPPT_periodic (void)
Variables
uint8_t MPPT_mode
static int16_t MPPT_data [NB_DATA]
Macro Definition Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 26 of file sim_MPPT.c.
Function Documentation
void MPPT_init (void)
Definition at line 37 of file sim_MPPT.c.
References MPPT_data, MPPT_mode, MPPT_status, MPPT_STATUS_IDLE, and NB_DATA.
void MPPT_periodic (void)
Definition at line 44 of file sim_MPPT.c.
References i2c_transaction::buf, data_index, DefaultChannel, DefaultDevice, i2c_receive(), i2c_transmit(), I2CTransSuccess, MPPT_ask(), MPPT_data, MPPT_IBAT_INDEX, MPPT_ICONV_INDEX, MPPT_ITOTAL_INDEX, MPPT_mode, MPPT_MODE_ADDR, MPPT_SLAVE_ADDR, MPPT_status, MPPT_STATUS_ASKING, MPPT_STATUS_IDLE, MPPT_STATUS_READING, MPPT_STATUS_WRITING, mppt_trans, NB_DATA, NB_I2C_DATA, and i2c_transaction::status.
Variable Documentation
int16_t MPPT_data[NB_DATA] static
Definition at line 35 of file sim_MPPT.c.
Referenced by MPPT_init(), and MPPT_periodic().
uint8_t MPPT_mode
Definition at line 33 of file sim_MPPT.c.