Paparazzi UAS: sw/airborne/subsystems/navigation/snav.h File Reference
snav.h File Reference
Smooth navigation to wp_a along an arc (around wp_cd), a segment (from wp_rd to wp_ta) and a second arc (around wp_ca).
#include "std.h"
Functions
bool_t snav_init (uint8_t wp_a, float desired_course_rad, float radius)
bool_t snav_circle1 (void)
bool_t snav_route (void)
bool_t snav_circle2 (void)
bool_t snav_on_time (float radius)
Variables
float snav_desired_tow
Detailed Description
Smooth navigation to wp_a along an arc (around wp_cd), a segment (from wp_rd to wp_ta) and a second arc (around wp_ca).
Definition in file snav.h.
Function Documentation
bool_t snav_circle1 (void)
Definition at line 120 of file snav.c.
References d_radius, nav_circle_XY(), NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, and qdr_td.
bool_t snav_circle2 (void)
Definition at line 137 of file snav.c.
References a_radius, nav_circle_XY(), NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, and qdr_a.
bool_t snav_init (uint8_t wp_a, float desired_course_rad, float radius)
Definition at line 49 of file snav.c.
References point::a, a_radius, d_radius, FALSE, ground_speed_timer, qdr_a, qdr_td, radius, Sign, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), u_a_ca_x, u_a_ca_y, WaypointAlt, WaypointX, WaypointY, wp_a, wp_ta, point::x, EnuCoor_f::x, point::y, and EnuCoor_f::y.
bool_t snav_on_time (float radius)
Definition at line 173 of file snav.c.
References point::a, a_radius, ANGLE_STEP, compute_ground_speed(), gps, ground_speed_of_course(), ground_speed_timer, nav_circle_XY(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, Norm2Pi, qdr_a, radius, Sign, snav_desired_tow, stateGetAirspeed_f(), stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), GpsState::tow, u_a_ca_x, u_a_ca_y, WaypointX, WaypointY, wp_a, point::x, and point::y.
bool_t snav_route (void)
Definition at line 128 of file snav.c.
References nav_approaching_xy(), nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, wp_ta, point::x, and point::y.
Variable Documentation
float snav_desired_tow
Definition at line 44 of file snav.c.
Referenced by snav_on_time().