Paparazzi UAS: sw/airborne/arch/stm32/subsystems/imu/imu_b2_arch.c File Reference
imu_b2_arch.c File Reference
#include "subsystems/imu.h"
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/f1/rcc.h>
#include <libopencm3/stm32/spi.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/f1/dma.h>
#include <libopencm3/stm32/nvic.h>
Defines
#define IMU_SSP_STA_IDLE 0
#define IMU_SSP_STA_BUSY_MAX1168 1
#define IMU_SSP_STA_BUSY_MS2100 2
Functions
void dma1_channel4_isr (void)
void spi2_isr (void)
void imu_b2_arch_init (void)
void imu_periodic (void)
Variables
volatile uint8_t imu_ssp_status
Define Documentation
#define IMU_SSP_STA_BUSY_MAX1168 1
Definition at line 34 of file imu_b2_arch.c.
Referenced by imu_periodic().
#define IMU_SSP_STA_BUSY_MS2100 2
Definition at line 35 of file imu_b2_arch.c.
#define IMU_SSP_STA_IDLE 0
Definition at line 33 of file imu_b2_arch.c.
Referenced by imu_b2_arch_init().
Function Documentation
void dma1_channel4_isr (void)
void imu_b2_arch_init (void)
Definition at line 42 of file imu_b2_arch.c.
References IMU_SSP_STA_IDLE, and imu_ssp_status.
Referenced by imu_impl_init().
void imu_periodic (void)
Definition at line 65 of file imu_b2_arch.c.
References hmc5843_periodic(), IMU_SSP_STA_BUSY_MAX1168, imu_ssp_status, max1168_read(), and Max1168ConfigureSPI.
void spi2_isr (void)
Definition at line 108 of file imu_b2_arch.c.
References Ms2100OnSpiIrq.
Variable Documentation
volatile uint8_t imu_ssp_status
Definition at line 37 of file imu_b2_arch.c.