Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/adc_arch.c File Reference
adc_arch.c File Reference
STM32 architecture
Driver for the analog to digital converters on STM32.
#include "mcu_periph/adc.h"
#include <libopencm3/stm32/f1/rcc.h>
#include <libopencm3/stm32/f1/adc.h>
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/timer.h>
#include <libopencm3/stm32/f1/nvic.h>
#include <string.h>
#include "std.h"
#include "led.h"
#include <BOARD_CONFIG>
Functions
static void adc_init_single (uint32_t adc, uint8_t chan1, uint8_t chan2, uint8_t chan3, uint8_t chan4)
Enable selected channels on specified ADC.
static void adc_push_sample (struct adc_buf *buf, uint16_t sample)
static void adc_init_rcc (void)
static void adc_init_irq (void)
void adc_buf_channel (uint8_t adc_channel, struct adc_buf *s, uint8_t av_nb_sample)
Registers a buffer to be used to store the specified converted channel Usage:
void adc_init (void)
Starts conversions.
void adc1_2_isr (void)
ADC1+2 interrupt hander.
Variables
volatile uint8_t adc_new_data_trigger
volatile uint32_t * adc_injected_channels [4]
Maps integer value x to ADC_InjectedChannel_x.
static uint8_t adc_channel_map [4]
Maps integer value x to ADC_Channel_y.
Detailed Description
Driver for the analog to digital converters on STM32.
Usage: Define flags for ADCs to use and their channels:
-DUSE_AD1 -DUSE_AD1_1 -DUSE_AD1_3
would enable ADC1 and it's channels 1 and 3.
Definition in file adc_arch.c.
Function Documentation
void adc1_2_isr (void)
ADC1+2 interrupt hander.
Definition at line 505 of file adc_arch.c.
References ADC1, adc_injected_channels, adc_new_data_trigger, adc_push_sample(), channel, NB_ADC1_CHANNELS, and NB_ADC2_CHANNELS.
void adc_buf_channel (uint8_t adc_channel, struct adc_buf * s, uint8_t av_nb_sample)
Registers a buffer to be used to store the specified converted channel Usage:
struct adc_buf channel_buf;
adc_buf_channel(1, &channel_buf, 12);
Registers channel_buf as buffer for ADC channel 1, with max index 12 (12 samples).
Definition at line 205 of file adc_arch.c.
References adc_buf::av_nb_sample.
void adc_init (void)
Starts conversions.
Definition at line 402 of file adc_arch.c.
References _VIC_ADDR, _VIC_CNTL, AD0CR, AD1CR, ADC1, ADC_AD0CR_SEL_HW_SCAN, ADC_AD1CR_SEL_HW_SCAN, adc_channel_map, adc_init_irq(), adc_init_rcc(), adc_init_single(), adc_injected_channels, adc_new_data_trigger, ADC_PINSEL0_ONES, ADC_PINSEL1_ONES, adcISR0(), adcISR1(), BOARD_ADC_CHANNEL_1, BOARD_ADC_CHANNEL_2, BOARD_ADC_CHANNEL_3, BOARD_ADC_CHANNEL_4, channel, FALSE, NB_ADC1_CHANNELS, NB_ADC2_CHANNELS, PINSEL0, PINSEL1, USE_AD1_2, USE_AD1_4, VIC_AD0, VIC_AD1, VIC_BIT, VIC_ENABLE, VICIntEnable, and VICIntSelect.
static void adc_init_irq (void) inline static
Definition at line 276 of file adc_arch.c.
Referenced by adc_init().
static void adc_init_rcc (void) inline static
Definition at line 215 of file adc_arch.c.
Referenced by adc_init().
static void adc_init_single (uint32_t adc, uint8_t chan1, uint8_t chan2, uint8_t chan3, uint8_t chan4) inline static
Enable selected channels on specified ADC.
Usage:
adc_init_single(ADC1, 1, 1, 0, 0);
... would enable ADC1, enabling channels 1 and 2, but not 3 and 4.
Definition at line 291 of file adc_arch.c.
References ADC1, adc_channel_map, NB_ADC1_CHANNELS, and NB_ADC2_CHANNELS.
Referenced by adc_init().
static void adc_push_sample (struct adc_buf * buf, uint16_t sample) inline static
Definition at line 490 of file adc_arch.c.
References adc_buf::av_nb_sample, adc_buf::head, adc_buf::sum, and adc_buf::values.
Referenced by adc1_2_isr().
Variable Documentation
uint8_t adc_channel_map[4] static
Maps integer value x to ADC_Channel_y.
like e.g.
0 –> ADC_Channel_5
1 –> ADC_Channel_8
2 –> ADC_Channel_13
so they can be iterated incrementally.
Definition at line 199 of file adc_arch.c.
Referenced by adc_init(), and adc_init_single().
volatile uint32_t* adc_injected_channels[4]
Maps integer value x to ADC_InjectedChannel_x.
so they can be iterated safely
Definition at line 188 of file adc_arch.c.
Referenced by adc1_2_isr(), and adc_init().
volatile uint8_t adc_new_data_trigger
Definition at line 97 of file adc_arch.c.
Referenced by adc1_2_isr(), adc_init(), and main_event_task().