Paparazzi UAS: sw/airborne/arch/stm32/subsystems/imu/imu_crista_arch.h File Reference
imu_crista_arch.h File Reference
Macros
#define ImuCristaArchPeriodic()
Functions
void ADS8344_start (void)
Macro Definition Documentation
#define ImuCristaArchPeriodic ()
Value:
{   \
    ADS8344_start();        \
  }
Definition at line 26 of file imu_crista_arch.h.
Function Documentation
void ADS8344_start (void)
Definition at line 123 of file ADS8344.c.
References ADS8344_read_channel(), ADS8344Select, channel, send_request(), SpiClearRti(), SpiEnable, SpiEnableRti(), SSP_ClearRti, SSP_Enable, and SSP_EnableRti.