Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/uart_arch.c File Reference
uart_arch.c File Reference
STM32 architecture
Handling of UART hardware for STM32.
#include "mcu_periph/uart.h"
#include <libopencm3/stm32/f1/nvic.h>
#include <libopencm3/stm32/f1/rcc.h>
#include <libopencm3/stm32/usart.h>
#include <libopencm3/stm32/f1/gpio.h>
#include "std.h"
Functions
void uart_periph_set_baudrate (struct uart_periph *p, uint32_t baud, bool_t hw_flow_control)
void uart_transmit (struct uart_periph *p, uint8_t data)
static void usart_isr (struct uart_periph *p)
static void usart_enable_irq (u8 IRQn)
Detailed Description
Handling of UART hardware for STM32.
Definition in file uart_arch.c.
Function Documentation
void uart_periph_set_baudrate (struct uart_periph * p, uint32_t baud, bool_t hw_flow_control)
Definition at line 37 of file uart_arch.c.
References uart_periph::reg_addr, uart_disable_interrupts(), uart_enable_interrupts(), and uart_set_baudrate().
void uart_transmit (struct uart_periph * p, uint8_t data)
Definition at line 62 of file uart_arch.c.
References disableIRQ(), uart_periph::reg_addr, restoreIRQ(), TRUE, uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, UART_TX_BUFFER_SIZE, and UIER_ETBEI.
static void usart_enable_irq (u8 IRQn) inline static
Definition at line 112 of file uart_arch.c.
static void usart_isr (struct uart_periph * p) inline static
Definition at line 85 of file uart_arch.c.
References FALSE, uart_periph::reg_addr, uart_periph::rx_buf, uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, UART_RX_BUFFER_SIZE, and UART_TX_BUFFER_SIZE.