Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/i2c_arch.c File Reference
i2c_arch.c File Reference
#include "mcu_periph/i2c.h"
#include <libopencm3/stm32/f1/rcc.h>
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/f1/scb.h>
#include <libopencm3/stm32/nvic.h>
Defines
#define I2C1_CLOCK_SPEED 40000
#define I2C2_CLOCK_SPEED 300000
#define I2C_SR1_ERR_MASK
#define BIT_X_IS_SET_IN_REG(X, REG) (((REG) & (X)) == (X))
#define __I2C_REG_CRITICAL_ZONE_START __disable_irq();
#define __I2C_REG_CRITICAL_ZONE_STOP __enable_irq();
Enumerations
enum STMI2CSubTransactionStatus {
STMI2C_SubTra_Busy, STMI2C_SubTra_Ready_StopRequested, STMI2C_SubTra_Ready, STMI2C_SubTra_Error,
STMI2C_SubTra_Busy, STMI2C_SubTra_Ready_StopRequested, STMI2C_SubTra_Ready, STMI2C_SubTra_Busy,
STMI2C_SubTra_Ready_StopRequested, STMI2C_SubTra_Ready, STMI2C_SubTra_Busy, STMI2C_SubTra_Ready_StopRequested,
STMI2C_SubTra_Ready, STMI2C_SubTra_Error
}
Functions
static void __disable_irq (void)
static void __enable_irq (void)
void i2c1_ev_isr (void)
void i2c1_er_isr (void)
void i2c2_ev_isr (void)
void i2c2_er_isr (void)
static void PPRZ_I2C_SEND_STOP (u32 i2c)
static void PPRZ_I2C_SEND_START (struct i2c_periph *periph)
static enum
STMI2CSubTransactionStatus stmi2c_send (u32 i2c, struct i2c_periph *periph, struct i2c_transaction *trans)
static enum
STMI2CSubTransactionStatus stmi2c_read1 (u32 i2c, struct i2c_periph *periph, struct i2c_transaction *trans)
static enum
STMI2CSubTransactionStatus stmi2c_read2 (u32 i2c, struct i2c_periph *periph, struct i2c_transaction *trans)
static enum
STMI2CSubTransactionStatus stmi2c_readmany (u32 i2c, struct i2c_periph *periph, struct i2c_transaction *trans)
static void i2c_error (struct i2c_periph *periph)
static void stmi2c_clear_pending_interrupts (u32 i2c)
static void i2c_irq (struct i2c_periph *periph)
void i2c_setbitrate (struct i2c_periph *periph, int bitrate)
void i2c_event (void)
bool_t i2c_submit (struct i2c_periph *periph, struct i2c_transaction *t)
bool_t i2c_idle (struct i2c_periph *periph)
Define Documentation
#define __I2C_REG_CRITICAL_ZONE_START __disable_irq();
Definition at line 172 of file i2c_arch.c.
Referenced by stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
#define __I2C_REG_CRITICAL_ZONE_STOP __enable_irq();
Definition at line 173 of file i2c_arch.c.
Referenced by stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
#define BIT_X_IS_SET_IN_REG (X, REG) (((REG) & (X)) == (X))
Definition at line 163 of file i2c_arch.c.
Referenced by i2c_idle(), stmi2c_clear_pending_interrupts(), stmi2c_read1(), stmi2c_read2(), stmi2c_readmany(), and stmi2c_send().
#define I2C1_CLOCK_SPEED 40000
Definition at line 98 of file i2c_arch.c.
#define I2C2_CLOCK_SPEED 300000
Definition at line 99 of file i2c_arch.c.
#define I2C_SR1_ERR_MASK
Value:
(I2C_SR1_SMBALERT | \
                                     I2C_SR1_TIMEOUT |  \
                     I2C_SR1_PECERR |   \
                     I2C_SR1_OVR |      \
                     I2C_SR1_AF |       \
                     I2C_SR1_ARLO |     \
                     I2C_SR1_BERR)
Definition at line 153 of file i2c_arch.c.
Referenced by i2c_irq().
Enumeration Type Documentation
enum STMI2CSubTransactionStatus
Enumerator:
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Error
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Error
Definition at line 361 of file i2c_arch.c.
Function Documentation
static void __disable_irq (void) [inline, static]
Definition at line 167 of file i2c_arch.c.
Referenced by i2c_event(), i2c_setbitrate(), i2c_submit(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
static void __enable_irq (void) [inline, static]
Definition at line 168 of file i2c_arch.c.
Referenced by i2c_event(), i2c_setbitrate(), i2c_submit(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
void i2c1_er_isr (void)
void i2c1_ev_isr (void)
void i2c2_er_isr (void)
Referenced by imu_aspirin_event().
void i2c2_ev_isr (void)
static void i2c_error (struct i2c_periph * periph) [inline, static]
Definition at line 703 of file i2c_arch.c.
References i2c_errors::ack_fail_cnt, i2c_errors::arb_lost_cnt, i2c_errors::er_irq_cnt, i2c_periph::errors, LED_ERROR(), i2c_errors::miss_start_stop_cnt, i2c_errors::over_under_cnt, i2c_errors::pec_recep_cnt, i2c_periph::reg_addr, i2c_errors::smbus_alert_cnt, and i2c_errors::timeout_tlow_cnt.
Referenced by i2c_irq().
void i2c_event (void)
Todo:
Watchdog timer
Definition at line 1355 of file i2c_arch.c.
References __disable_irq(), __enable_irq(), I2CIdle, I2CStartRequested, LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
bool_t i2c_idle (struct i2c_periph * periph)
Definition at line 1473 of file i2c_arch.c.
References BIT_X_IS_SET_IN_REG, I2C_DEBUG_LED, I2CIdle, i2c_periph::reg_addr, and i2c_periph::status.
static void i2c_irq (struct i2c_periph * periph) [inline, static]
Definition at line 807 of file i2c_arch.c.
References i2c_periph::errors, i2c_error(), I2C_SR1_ERR_MASK, I2C_TRANSACTION_QUEUE_LEN, I2CFailed, I2CIdle, I2CStartRequested, I2CTransFailed, I2CTransRx, I2CTransTxRx, i2c_errors::last_unexpected_event, LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), LED_SHOW_ACTIVE_BITS(), i2c_transaction::len_r, PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), i2c_periph::reg_addr, i2c_transaction::status, i2c_periph::status, stmi2c_clear_pending_interrupts(), stmi2c_read1(), stmi2c_read2(), stmi2c_readmany(), stmi2c_send(), STMI2C_SubTra_Busy, STMI2C_SubTra_Error, STMI2C_SubTra_Ready, i2c_periph::trans, i2c_periph::trans_extract_idx, i2c_periph::trans_insert_idx, i2c_transaction::type, and i2c_errors::unexpected_event_cnt.
void i2c_setbitrate (struct i2c_periph * periph, int bitrate)
Definition at line 1264 of file i2c_arch.c.
References __disable_irq(), __enable_irq(), i2c_idle(), LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), and i2c_periph::reg_addr.
bool_t i2c_submit (struct i2c_periph * periph, struct i2c_transaction * t)
Definition at line 1428 of file i2c_arch.c.
References __disable_irq(), __enable_irq(), I2C_TRANSACTION_QUEUE_LEN, I2CIdle, I2CTransPending, LED2_OFF(), LED2_ON(), PPRZ_I2C_SEND_START(), i2c_transaction::status, i2c_periph::status, i2c_periph::trans, i2c_periph::trans_extract_idx, and i2c_periph::trans_insert_idx.
static void PPRZ_I2C_SEND_START (struct i2c_periph * periph) [inline, static]
Definition at line 321 of file i2c_arch.c.
References I2C_DEBUG_LED, I2CStartRequested, i2c_periph::idx_buf, LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), LED_SHOW_ACTIVE_BITS(), i2c_periph::reg_addr, and i2c_periph::status.
Referenced by i2c_irq(), and i2c_submit().
static void PPRZ_I2C_SEND_STOP (u32 i2c) [inline, static]
Definition at line 306 of file i2c_arch.c.
References LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
Referenced by i2c_irq(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
static void stmi2c_clear_pending_interrupts (u32 i2c) [inline, static]
Definition at line 767 of file i2c_arch.c.
References BIT_X_IS_SET_IN_REG.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_read1 (u32 i2c, struct i2c_periph * periph, struct i2c_transaction * trans) [inline, static]
Definition at line 451 of file i2c_arch.c.
References __I2C_REG_CRITICAL_ZONE_START, __I2C_REG_CRITICAL_ZONE_STOP, BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2CAddrRdSent, I2CReadingLastByte, I2CStopRequested, I2CTransSuccess, PPRZ_I2C_SEND_STOP(), i2c_transaction::slave_addr, i2c_transaction::status, i2c_periph::status, STMI2C_SubTra_Busy, STMI2C_SubTra_Error, and STMI2C_SubTra_Ready_StopRequested.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_read2 (u32 i2c, struct i2c_periph * periph, struct i2c_transaction * trans) [inline, static]
Definition at line 514 of file i2c_arch.c.
References __I2C_REG_CRITICAL_ZONE_START, __I2C_REG_CRITICAL_ZONE_STOP, BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2CAddrRdSent, I2CReadingByte, I2CStopRequested, I2CTransSuccess, PPRZ_I2C_SEND_STOP(), i2c_transaction::slave_addr, i2c_transaction::status, i2c_periph::status, STMI2C_SubTra_Busy, STMI2C_SubTra_Error, and STMI2C_SubTra_Ready_StopRequested.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_readmany (u32 i2c, struct i2c_periph * periph, struct i2c_transaction * trans) [inline, static]
Definition at line 584 of file i2c_arch.c.
References __I2C_REG_CRITICAL_ZONE_START, __I2C_REG_CRITICAL_ZONE_STOP, BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2CAddrRdSent, I2CReadingByte, I2CStopRequested, I2CTransSuccess, i2c_periph::idx_buf, i2c_transaction::len_r, PPRZ_I2C_SEND_STOP(), i2c_transaction::slave_addr, i2c_transaction::status, i2c_periph::status, STMI2C_SubTra_Busy, STMI2C_SubTra_Error, and STMI2C_SubTra_Ready_StopRequested.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_send (u32 i2c, struct i2c_periph * periph, struct i2c_transaction * trans) [inline, static]
Definition at line 370 of file i2c_arch.c.
References BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2CAddrWrSent, I2CSendingByte, I2CTransSuccess, I2CTransTx, i2c_periph::idx_buf, i2c_transaction::len_w, i2c_transaction::slave_addr, i2c_transaction::status, i2c_periph::status, STMI2C_SubTra_Busy, STMI2C_SubTra_Error, STMI2C_SubTra_Ready, and i2c_transaction::type.
Referenced by i2c_irq().