Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/sys_time_arch.h File Reference
sys_time_arch.h File Reference
STM32 architecture
STM32 timing functions.
#include "mcu_periph/sys_time.h"
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/f1/rcc.h>
#include <libopencm3/cm3/systick.h>
#include "std.h"
Macros
#define SysTimeTimerStart(_t) { _t = get_sys_time_usec(); }
#define SysTimeTimer(_t) (get_sys_time_usec() - (_t))
#define SysTimeTimerStop(_t) { _t = (get_sys_time_usec() - (_t)); }
Functions
void sys_tick_handler (void)
static uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
static void sys_time_usleep (uint32_t us)
Busy wait in microseconds.
Detailed Description
STM32 timing functions.
Definition in file sys_time_arch.h.
Macro Definition Documentation
#define SysTimeTimer (_t) (get_sys_time_usec() - (_t))
Definition at line 57 of file sys_time_arch.h.
#define SysTimeTimerStart (_t) { _t = get_sys_time_usec(); }
Definition at line 56 of file sys_time_arch.h.
#define SysTimeTimerStop (_t) { _t = (get_sys_time_usec() - (_t)); }
Definition at line 58 of file sys_time_arch.h.
Function Documentation
static uint32_t get_sys_time_usec (void) inline static
Get the time in microseconds since startup.
WARNING: overflows after 70min!
Returns
current system time as uint32_t
Definition at line 49 of file sys_time_arch.h.
References sys_time::nb_sec, sys_time::nb_sec_rem, and usec_of_cpu_ticks().
void sys_tick_handler (void)
Definition at line 37 of file sys_time_arch.c.
References sys_time_timer::cb, sys_time::cpu_ticks_per_sec, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, sys_time_timer::in_use, LED_TOGGLE, sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, sys_time::resolution_cpu_ticks, SYS_TIME_NB_TIMER, sys_time::timer, and TRUE.
static void sys_time_usleep (uint32_t us) inline static
Busy wait in microseconds.
Todo:
: doesn't handle wrap-around at 2^32 / 1000000 = 4294s = ~72min
Definition at line 64 of file sys_time_arch.h.
References cpu_ticks_of_usec(), sys_time::nb_tick, sys_time::resolution_cpu_ticks, and sys_time_ticks_of_usec().