Paparazzi UAS: sw/airborne/arch/stm32/subsystems/imu/imu_crista_arch.c File Reference
imu_crista_arch.c File Reference
#include "subsystems/imu.h"
#include <stm32/gpio.h>
#include <stm32/rcc.h>
#include <stm32/spi.h>
#include <stm32/misc.h>
#include <stm32/dma.h>
Defines
#define POWER_MODE (1 << 1 | 1)
#define SGL_DIF 1
#define ADS8344Unselect() GPIOB->BSRR = GPIO_Pin_12
#define ADS8344Select() GPIOB->BRR = GPIO_Pin_12
Functions
void dma1_c4_irq_handler (void)
static void ADS8344_read_channel (void)
void imu_crista_arch_init (void)
void ADS8344_start (void)
Variables
static volatile uint8_t channel
static uint8_t buf_in [4]
static uint8_t buf_out [4]
Define Documentation
#define ADS8344Select () GPIOB->BRR = GPIO_Pin_12
Definition at line 38 of file imu_crista_arch.c.
Referenced by ADS8344_start().
#define ADS8344Unselect () GPIOB->BSRR = GPIO_Pin_12
Definition at line 37 of file imu_crista_arch.c.
Referenced by ADS8344_read_channel(), and imu_crista_arch_init().
#define POWER_MODE (1 << 1 | 1)
Definition at line 34 of file imu_crista_arch.c.
Referenced by ADS8344_read_channel().
#define SGL_DIF 1
Definition at line 35 of file imu_crista_arch.c.
Referenced by ADS8344_read_channel().
Function Documentation
static void ADS8344_read_channel (void) [static]
Definition at line 98 of file imu_crista_arch.c.
References ADS8344_available, ADS8344_values, ADS8344Unselect, buf_in, buf_out, channel, dma1_c4_irq_handler(), POWER_MODE, SGL_DIF, and TRUE.
Referenced by ADS8344_start().
void ADS8344_start (void)
Definition at line 90 of file imu_crista_arch.c.
References ADS8344_read_channel(), ADS8344Select, channel, send_request(), SpiClearRti(), SpiEnable, and SpiEnableRti().
void dma1_c4_irq_handler (void)
void imu_crista_arch_init (void)
Definition at line 43 of file imu_crista_arch.c.
References ADS8344_SS_IODIR, ADS8344_SS_PIN, ADS8344Unselect, channel, PINSEL1, SPI1_ISR(), SSP_CPHA, SSP_CPOL, SSP_DSS, SSP_FRF, SSP_LBM, SSP_MS, SSP_SCR, SSP_SOD, SSPCPSR, SSPCR0, SSPCR1, VIC_BIT, VIC_ENABLE, VIC_SPI1, VICIntEnable, VICIntSelect, VICVectAddr7, and VICVectCntl7.
Variable Documentation
uint8_t buf_in[4] [static]
Definition at line 31 of file imu_crista_arch.c.
Referenced by ADS8344_read_channel().
uint8_t buf_out[4] [static]
Definition at line 32 of file imu_crista_arch.c.
Referenced by ADS8344_read_channel().
volatile uint8_t channel [static]
Definition at line 30 of file imu_crista_arch.c.
Referenced by ADS8344_read_channel(), ADS8344_start(), and imu_crista_arch_init().