Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/spi_arch.c File Reference
spi_arch.c File Reference
STM32 architecture
Handling of SPI hardware for STM32.
#include <libopencm3/stm32/f1/nvic.h>
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/f1/rcc.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/spi.h>
#include <libopencm3/stm32/f1/dma.h>
#include "mcu_periph/spi.h"
Data Structures
struct locm3_spi_comm
Libopencm3 specifc communication parameters for a SPI peripheral in master mode.
struct spi_periph_dma
This structure keeps track of specific config for each SPI bus, which allows for more code reuse.
Macros
#define SPI_SELECT_SLAVE0_PERIPH RCC_APB2ENR_IOPAEN
#define SPI_SELECT_SLAVE0_PORT GPIOA
#define SPI_SELECT_SLAVE0_PIN GPIO15
#define SPI_SELECT_SLAVE1_PERIPH RCC_APB2ENR_IOPAEN
#define SPI_SELECT_SLAVE1_PORT GPIOA
#define SPI_SELECT_SLAVE1_PIN GPIO4
#define SPI_SELECT_SLAVE2_PERIPH RCC_APB2ENR_IOPBEN
#define SPI_SELECT_SLAVE2_PORT GPIOB
#define SPI_SELECT_SLAVE2_PIN GPIO12
#define SPI_SELECT_SLAVE3_PERIPH RCC_APB2ENR_IOPCEN
#define SPI_SELECT_SLAVE3_PORT GPIOC
#define SPI_SELECT_SLAVE3_PIN GPIO13
#define SPI_SELECT_SLAVE4_PERIPH RCC_APB2ENR_IOPCEN
#define SPI_SELECT_SLAVE4_PORT GPIOC
#define SPI_SELECT_SLAVE4_PIN GPIO12
#define SPI_SELECT_SLAVE5_PERIPH RCC_APB2ENR_IOPCEN
#define SPI_SELECT_SLAVE5_PORT GPIOC
#define SPI_SELECT_SLAVE5_PIN GPIO4
Functions
static void spi_start_dma_transaction (struct spi_periph *periph, struct spi_transaction *trans)
Start a new transaction with DMA.
static void spi_next_transaction (struct spi_periph *periph)
start next transaction if there is one in the queue
static void spi_configure_dma (u32 dma, u8 chan, u32 periph_addr, u32 buf_addr, u16 len, enum SPIDataSizeSelect dss, bool_t increment)
static void process_rx_dma_interrupt (struct spi_periph *periph)
Processing done after rx completes.
static void process_tx_dma_interrupt (struct spi_periph *periph)
Processing done after tx completes.
static void spi_arch_int_enable (struct spi_periph *spi)
Enable DMA channel interrupts.
static void spi_arch_int_disable (struct spi_periph *spi)
Disable DMA channel interrupts.
static void SpiSlaveUnselect (uint8_t slave)
static void SpiSlaveSelect (uint8_t slave)
void spi_slave_select (uint8_t slave)
Select a slave.
void spi_slave_unselect (uint8_t slave)
Unselect a slave.
void spi_init_slaves (void)
Initialize all used slaves and uselect them.
bool_t spi_submit (struct spi_periph *p, struct spi_transaction *t)
Submit a spi transaction.
bool_t spi_lock (struct spi_periph *p, uint8_t slave)
Lock the SPI fifo.
bool_t spi_resume (struct spi_periph *p, uint8_t slave)
Resume the SPI fifo.
static void set_default_comm_config (struct locm3_spi_comm *c)
static uint8_t get_transaction_signature (struct spi_transaction *t)
static uint8_t get_comm_signature (struct locm3_spi_comm *c)
static void set_comm_from_transaction (struct locm3_spi_comm *c, struct spi_transaction *t)
Update SPI communication conf from generic paparazzi SPI transaction.
void spi1_arch_init (void)
Architecture dependant SPI1 initialization.
void spi2_arch_init (void)
Architecture dependant SPI2 initialization.
void dma1_channel2_isr (void)
receive transferred over DMA
void dma1_channel3_isr (void)
transmit transferred over DMA
void dma1_channel4_isr (void)
receive transferred over DMA
void dma1_channel5_isr (void)
transmit transferred over DMA
Variables
static struct spi_periph_dma spi1_dma
static struct spi_periph_dma spi2_dma
Detailed Description
Handling of SPI hardware for STM32.
SPI Master code.
When a transaction is submitted:
The transaction is added to the queue if there is space, otherwise it returns false
The pending state is set
SPI Interrupts (in this case the DMA interrupts) are disabled to prevent race conditions
The slave is selected if required, then the before_cb callback is run
The spi and dma registers are set up for the specific transaction
Spi, DMA and interrupts are enabled and the transaction starts
Obviously output_length and input_length will never both be 0 at the same time. In this case, spi_submit will just return false.
For the DMA and interrupts:
If the output_len != input_len, a dummy DMA transfer is triggered for the remainder so the same amount of data is moved in and out. This simplifies keeping the clock going if output_len is greater and allows the rx dma interrupt to represent that the transaction has fully completed.
The dummy DMA transfer is initiated at the transaction setup if length is 0, otherwise after the first dma interrupt completes in the ISR directly.
The rx DMA transfer completed interrupt marks the end of a complete transaction.
The after_cb callback happens BEFORE the slave is unselected as configured.
Definition in file spi_arch.c.
Macro Definition Documentation
#define SPI_SELECT_SLAVE0_PERIPH RCC_APB2ENR_IOPAEN
Todo:
move the SS gpio defines to the board files
Definition at line 126 of file spi_arch.c.
Referenced by spi_init_slaves().
#define SPI_SELECT_SLAVE0_PIN GPIO15
Definition at line 128 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE0_PORT GPIOA
Definition at line 127 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE1_PERIPH RCC_APB2ENR_IOPAEN
Definition at line 130 of file spi_arch.c.
Referenced by spi_init_slaves().
#define SPI_SELECT_SLAVE1_PIN GPIO4
Definition at line 132 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE1_PORT GPIOA
Definition at line 131 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE2_PERIPH RCC_APB2ENR_IOPBEN
Definition at line 134 of file spi_arch.c.
Referenced by spi_init_slaves().
#define SPI_SELECT_SLAVE2_PIN GPIO12
Definition at line 136 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE2_PORT GPIOB
Definition at line 135 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE3_PERIPH RCC_APB2ENR_IOPCEN
Definition at line 138 of file spi_arch.c.
Referenced by spi_init_slaves().
#define SPI_SELECT_SLAVE3_PIN GPIO13
Definition at line 140 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE3_PORT GPIOC
Definition at line 139 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE4_PERIPH RCC_APB2ENR_IOPCEN
Definition at line 142 of file spi_arch.c.
Referenced by spi_init_slaves().
#define SPI_SELECT_SLAVE4_PIN GPIO12
Definition at line 144 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE4_PORT GPIOC
Definition at line 143 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE5_PERIPH RCC_APB2ENR_IOPCEN
Definition at line 146 of file spi_arch.c.
Referenced by spi_init_slaves().
#define SPI_SELECT_SLAVE5_PIN GPIO4
Definition at line 148 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
#define SPI_SELECT_SLAVE5_PORT GPIOC
Definition at line 147 of file spi_arch.c.
Referenced by spi_init_slaves(), SpiSlaveSelect(), and SpiSlaveUnselect().
Function Documentation
void dma1_channel2_isr (void)
receive transferred over DMA
Definition at line 886 of file spi_arch.c.
References process_rx_dma_interrupt(), and spi1.
void dma1_channel3_isr (void)
transmit transferred over DMA
Definition at line 896 of file spi_arch.c.
References process_tx_dma_interrupt(), and spi1.
void dma1_channel4_isr (void)
receive transferred over DMA
Definition at line 909 of file spi_arch.c.
References process_rx_dma_interrupt(), and spi2.
void dma1_channel5_isr (void)
transmit transferred over DMA
Definition at line 919 of file spi_arch.c.
References process_tx_dma_interrupt(), and spi2.
static uint8_t get_comm_signature (struct locm3_spi_comm * c) static
Definition at line 370 of file spi_arch.c.
References locm3_spi_comm::br, locm3_spi_comm::cpha, locm3_spi_comm::cpol, locm3_spi_comm::dff, locm3_spi_comm::lsbfirst, SPICphaEdge1, SPICphaEdge2, SPICpolIdleHigh, SPICpolIdleLow, SPIDiv128, SPIDiv16, SPIDiv2, SPIDiv256, SPIDiv32, SPIDiv4, SPIDiv64, SPIDiv8, SPIDss16bit, SPIDss8bit, SPILSBFirst, and SPIMSBFirst.
Referenced by spi1_arch_init(), and spi2_arch_init().
static uint8_t get_transaction_signature (struct spi_transaction * t) inline static
Definition at line 365 of file spi_arch.c.
References spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, and spi_transaction::dss.
Referenced by spi_start_dma_transaction().
void process_rx_dma_interrupt (struct spi_periph * periph) static
Processing done after rx completes.
Definition at line 954 of file spi_arch.c.
References spi_transaction::after_cb, spi_periph_dma::dma, spi_transaction::dss, FALSE, spi_periph::init_struct, spi_transaction::input_length, spi_transaction::output_length, spi_periph::reg_addr, spi_periph_dma::rx_chan, spi_periph_dma::rx_dummy_buf, spi_periph_dma::rx_extra_dummy_dma, spi_transaction::select, spi_transaction::slave_idx, spi_configure_dma(), spi_next_transaction(), spi_periph_dma::spidr, SPISelectUnselect, SpiSlaveUnselect(), SPITransSuccess, SPIUnselect, spi_transaction::status, spi_periph::trans, and spi_periph::trans_extract_idx.
Referenced by dma1_channel2_isr(), and dma1_channel4_isr().
void process_tx_dma_interrupt (struct spi_periph * periph) static
Processing done after tx completes.
Definition at line 1016 of file spi_arch.c.
References spi_periph_dma::dma, spi_transaction::dss, FALSE, spi_periph::init_struct, spi_transaction::input_length, spi_transaction::output_length, spi_periph::reg_addr, spi_configure_dma(), spi_periph_dma::spidr, spi_periph::trans, spi_periph::trans_extract_idx, spi_periph_dma::tx_chan, spi_periph_dma::tx_dummy_buf, and spi_periph_dma::tx_extra_dummy_dma.
Referenced by dma1_channel3_isr(), and dma1_channel5_isr().
static void set_comm_from_transaction (struct locm3_spi_comm * c, struct spi_transaction * t) static
Update SPI communication conf from generic paparazzi SPI transaction.
Definition at line 426 of file spi_arch.c.
References spi_transaction::bitorder, locm3_spi_comm::br, spi_transaction::cdiv, locm3_spi_comm::cpha, spi_transaction::cpha, locm3_spi_comm::cpol, spi_transaction::cpol, locm3_spi_comm::dff, spi_transaction::dss, locm3_spi_comm::lsbfirst, SPICphaEdge1, SPICpolIdleLow, SPIDiv128, SPIDiv16, SPIDiv2, SPIDiv256, SPIDiv32, SPIDiv4, SPIDiv64, SPIDiv8, SPIDss8bit, and SPIMSBFirst.
Referenced by spi_start_dma_transaction().
static void set_default_comm_config (struct locm3_spi_comm * c) static
Definition at line 357 of file spi_arch.c.
References locm3_spi_comm::br, locm3_spi_comm::cpha, locm3_spi_comm::cpol, locm3_spi_comm::dff, and locm3_spi_comm::lsbfirst.
Referenced by spi1_arch_init(), and spi2_arch_init().
static void spi_arch_int_disable (struct spi_periph * spi) static
Disable DMA channel interrupts.
Definition at line 519 of file spi_arch.c.
References spi_periph::init_struct.
Referenced by spi_lock(), spi_resume(), and spi_submit().
static void spi_arch_int_enable (struct spi_periph * spi) static
Enable DMA channel interrupts.
Todo:
fix priority levels if necessary
Definition at line 508 of file spi_arch.c.
References spi_periph::init_struct.
Referenced by spi1_arch_init(), spi2_arch_init(), spi_lock(), spi_resume(), and spi_submit().
static void spi_configure_dma (u32 dma, u8 chan, u32 periph_addr, u32 buf_addr, u16 len, enum SPIDataSizeSelect dss, bool_t increment) static
Definition at line 484 of file spi_arch.c.
References SPIDss8bit.
Referenced by process_rx_dma_interrupt(), process_tx_dma_interrupt(), and spi_start_dma_transaction().
static void spi_next_transaction (struct spi_periph * periph) static
start next transaction if there is one in the queue
Definition at line 525 of file spi_arch.c.
References spi_start_dma_transaction(), SPI_TRANSACTION_QUEUE_LEN, SPIIdle, spi_periph::status, spi_periph::suspend, spi_periph::trans, spi_periph::trans_extract_idx, and spi_periph::trans_insert_idx.
Referenced by process_rx_dma_interrupt().
static void spi_start_dma_transaction (struct spi_periph * periph, struct spi_transaction * _trans) static
Start a new transaction with DMA.
Definition at line 544 of file spi_arch.c.
References spi_transaction::before_cb, locm3_spi_comm::br, spi_periph_dma::comm, spi_periph_dma::comm_sig, locm3_spi_comm::cpha, locm3_spi_comm::cpol, locm3_spi_comm::dff, spi_periph_dma::dma, spi_transaction::dss, FALSE, get_transaction_signature(), spi_periph::init_struct, spi_transaction::input_buf, spi_transaction::input_length, locm3_spi_comm::lsbfirst, spi_transaction::output_buf, spi_transaction::output_length, spi_periph::reg_addr, spi_periph_dma::rx_chan, spi_periph_dma::rx_dummy_buf, spi_periph_dma::rx_extra_dummy_dma, spi_transaction::select, set_comm_from_transaction(), spi_transaction::slave_idx, spi_configure_dma(), spi_periph_dma::spidr, SPIRunning, SPISelect, SPISelectUnselect, SpiSlaveSelect(), SPITransRunning, spi_transaction::status, spi_periph::status, TRUE, spi_periph_dma::tx_chan, spi_periph_dma::tx_dummy_buf, and spi_periph_dma::tx_extra_dummy_dma.
Referenced by spi_next_transaction(), spi_resume(), and spi_submit().
static void SpiSlaveSelect (uint8_t slave) inline static
Definition at line 187 of file spi_arch.c.
References SPI_SELECT_SLAVE0_PIN, SPI_SELECT_SLAVE0_PORT, SPI_SELECT_SLAVE1_PIN, SPI_SELECT_SLAVE1_PORT, SPI_SELECT_SLAVE2_PIN, SPI_SELECT_SLAVE2_PORT, SPI_SELECT_SLAVE3_PIN, SPI_SELECT_SLAVE3_PORT, SPI_SELECT_SLAVE4_PIN, SPI_SELECT_SLAVE4_PORT, SPI_SELECT_SLAVE5_PIN, and SPI_SELECT_SLAVE5_PORT.
Referenced by spi_slave_select(), and spi_start_dma_transaction().
static void SpiSlaveUnselect (uint8_t slave) inline static
Definition at line 150 of file spi_arch.c.
References SPI_SELECT_SLAVE0_PIN, SPI_SELECT_SLAVE0_PORT, SPI_SELECT_SLAVE1_PIN, SPI_SELECT_SLAVE1_PORT, SPI_SELECT_SLAVE2_PIN, SPI_SELECT_SLAVE2_PORT, SPI_SELECT_SLAVE3_PIN, SPI_SELECT_SLAVE3_PORT, SPI_SELECT_SLAVE4_PIN, SPI_SELECT_SLAVE4_PORT, SPI_SELECT_SLAVE5_PIN, and SPI_SELECT_SLAVE5_PORT.
Referenced by process_rx_dma_interrupt(), spi_init_slaves(), and spi_slave_unselect().
Variable Documentation
struct spi_periph_dma spi1_dma static
Definition at line 101 of file spi_arch.c.
Referenced by spi1_arch_init().
struct spi_periph_dma spi2_dma static
Definition at line 104 of file spi_arch.c.
Referenced by spi2_arch_init().