Paparazzi UAS: sw/airborne/subsystems/imu/imu_aspirin2.c File Reference
imu_aspirin2.c File Reference
#include "subsystems/imu.h"
#include "led.h"
#include "mcu_periph/spi.h"
#include "peripherals/mpu60X0.h"
#include "peripherals/hmc58xx_regs.h"
#include "peripherals/ms5611.h"
Macros
#define MPU6000_SLAVE_IDX SPI_SLAVE2
#define MPU6000_SPI_DEV spi2
#define HMC58XX_DO 0x6
#define HMC58XX_MS 0x0
#define HMC58XX_GN 0x1
#define HMC58XX_MD 0x0
#define HMC58XX_CRA ((HMC58XX_DO<<2)|(HMC58XX_MS))
#define HMC58XX_CRB (HMC58XX_GN<<5)
Functions
static void mpu_configure (void)
static void trans_cb (struct spi_transaction *trans)
void imu_impl_init (void)
void imu_periodic (void)
static void mpu_set (uint8_t _reg, uint8_t _val)
static void mpu_wait_slave4_ready (void)
Variables
struct ImuAspirin2 imu_aspirin2
struct spi_transaction aspirin2_mpu60x0
Macro Definition Documentation
#define HMC58XX_CRA ((HMC58XX_DO<<2)|(HMC58XX_MS))
Definition at line 53 of file imu_aspirin2.c.
Referenced by mpu_configure().
#define HMC58XX_CRB (HMC58XX_GN<<5)
Definition at line 54 of file imu_aspirin2.c.
Referenced by mpu_configure().
#define HMC58XX_DO 0x6
Definition at line 41 of file imu_aspirin2.c.
#define HMC58XX_GN 0x1
Definition at line 47 of file imu_aspirin2.c.
#define HMC58XX_MD 0x0
Definition at line 50 of file imu_aspirin2.c.
Referenced by mpu_configure().
#define HMC58XX_MS 0x0
Definition at line 44 of file imu_aspirin2.c.
#define MPU6000_SLAVE_IDX SPI_SLAVE2
Definition at line 32 of file imu_aspirin2.c.
Referenced by imu_impl_init().
#define MPU6000_SPI_DEV spi2
Definition at line 36 of file imu_aspirin2.c.
Referenced by imu_periodic(), mpu_configure(), mpu_set(), and mpu_wait_slave4_ready().
Function Documentation
void imu_impl_init (void)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Definition at line 64 of file imu_aspirin2.c.
References aspirin2_mpu60x0, Aspirin2StatusUninit, FALSE, imu_aspirin2, IMU_ASPIRIN_BUFFER_LEN, ImuAspirin2::imu_available, ImuAspirin2::input_buf_p, MPU6000_SLAVE_IDX, ImuAspirin2::output_buf_p, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, ImuAspirin2::status, and trans_cb().
void imu_periodic (void)
Definition at line 83 of file imu_aspirin2.c.
References aspirin2_mpu60x0, Aspirin2StatusIdle, Aspirin2StatusUninit, imu_aspirin2, MPU6000_SPI_DEV, MPU60X0_REG_INT_STATUS, MPU60X0_SPI_READ, mpu_configure(), spi_submit(), and ImuAspirin2::status.
static void mpu_configure (void) static
Definition at line 134 of file imu_aspirin2.c.
References aspirin2_mpu60x0, HMC58XX_ADDR, HMC58XX_CRA, HMC58XX_CRB, HMC58XX_MD, HMC58XX_REG_CFGA, HMC58XX_REG_CFGB, HMC58XX_REG_DATXM, HMC58XX_REG_MODE, MPU6000_SPI_DEV, MPU60X0_REG_ACCEL_CONFIG, MPU60X0_REG_CONFIG, MPU60X0_REG_GYRO_CONFIG, MPU60X0_REG_I2C_MST_CTRL, MPU60X0_REG_I2C_MST_DELAY, MPU60X0_REG_I2C_SLV0_ADDR, MPU60X0_REG_I2C_SLV0_CTRL, MPU60X0_REG_I2C_SLV0_REG, MPU60X0_REG_I2C_SLV1_ADDR, MPU60X0_REG_I2C_SLV1_CTRL, MPU60X0_REG_I2C_SLV1_REG, MPU60X0_REG_I2C_SLV2_ADDR, MPU60X0_REG_I2C_SLV2_CTRL, MPU60X0_REG_I2C_SLV2_DO, MPU60X0_REG_I2C_SLV3_ADDR, MPU60X0_REG_I2C_SLV3_CTRL, MPU60X0_REG_I2C_SLV3_DO, MPU60X0_REG_I2C_SLV4_ADDR, MPU60X0_REG_I2C_SLV4_CTRL, MPU60X0_REG_I2C_SLV4_DO, MPU60X0_REG_I2C_SLV4_REG, MPU60X0_REG_PWR_MGMT_1, MPU60X0_REG_SMPLRT_DIV, MPU60X0_REG_USER_CTRL, MPU60X0_SPI_READ, mpu_set(), mpu_wait_slave4_ready(), MS5611_ADDR0, MS5611_REG_ADCREAD, MS5611_REG_RESET, and spi_submit().
Referenced by imu_periodic().
static void mpu_set (uint8_t _reg, uint8_t _val) inline static
Definition at line 108 of file imu_aspirin2.c.
References aspirin2_mpu60x0, MPU6000_SPI_DEV, spi_submit(), SPITransSuccess, and i2c_transaction::status.
Referenced by mpu_configure().
static void mpu_wait_slave4_ready (void) inline static
Definition at line 118 of file imu_aspirin2.c.
References aspirin2_mpu60x0, MPU6000_SPI_DEV, MPU60X0_REG_I2C_SLV4_CTRL, MPU60X0_SPI_READ, spi_submit(), SPITransSuccess, and i2c_transaction::status.
Referenced by mpu_configure().
static void trans_cb (struct spi_transaction * trans) static
Definition at line 102 of file imu_aspirin2.c.
References Aspirin2StatusUninit, imu_aspirin2, ImuAspirin2::imu_available, ImuAspirin2::status, and TRUE.
Referenced by imu_impl_init().
Variable Documentation
struct spi_transaction aspirin2_mpu60x0
Definition at line 58 of file imu_aspirin2.c.
struct ImuAspirin2 imu_aspirin2
Definition at line 56 of file imu_aspirin2.c.
Referenced by imu_aspirin2_event(), imu_impl_init(), imu_periodic(), and trans_cb().