Paparazzi UAS: sw/airborne/mcu_periph/sys_time.h File Reference
sys_time.h File Reference
Architecture independent timing functions.
#include <inttypes.h>
#include <stdlib.h>
#include "std.h"
#include <BOARD_CONFIG>
#include "mcu_periph/sys_time_arch.h"
Data Structures
struct sys_time_timer
struct sys_time
Macros
#define SYS_TIME_NB_TIMER 8
#define SYS_TIME_FREQUENCY 1000
(Default) sys_time timer frequency in Hz.
#define USEC_OF_SEC(sec) ((sec) * 1e6)
Typedefs
typedef uint8_t tid_t
sys_time timer id type
typedef void(* sys_time_cb)(uint8_t id)
Functions
void sys_time_init (void)
int sys_time_register_timer (float duration, sys_time_cb cb)
Register a new system timer.
void sys_time_cancel_timer (tid_t id)
Cancel a system timer by id.
void sys_time_update_timer (tid_t id, float duration)
Update the duration until a timer elapses.
static bool_t sys_time_check_and_ack_timer (tid_t id)
Check if timer has elapsed.
static float get_sys_time_float (void)
Get the time in seconds since startup.
static uint32_t sys_time_ticks_of_sec (float seconds)
static uint32_t sys_time_ticks_of_msec (uint32_t msec)
static uint32_t sys_time_ticks_of_usec (uint32_t usec)
static float sec_of_sys_time_ticks (uint32_t ticks)
static uint32_t msec_of_sys_time_ticks (uint32_t ticks)
static uint32_t usec_of_sys_time_ticks (uint32_t ticks)
static uint32_t cpu_ticks_of_sec (float seconds)
static uint32_t cpu_ticks_of_usec (uint32_t usec)
static int32_t signed_cpu_ticks_of_usec (int32_t usec)
static uint32_t cpu_ticks_of_nsec (uint32_t nsec)
static uint32_t msec_of_cpu_ticks (uint32_t cpu_ticks)
static uint32_t usec_of_cpu_ticks (uint32_t cpu_ticks)
static uint32_t nsec_of_cpu_ticks (uint32_t cpu_ticks)
void sys_time_arch_init (void)
Initialize SysTick.
Variables
struct sys_time sys_time
Detailed Description
Architecture independent timing functions.
Definition in file sys_time.h.
Macro Definition Documentation
#define SYS_TIME_FREQUENCY 1000
(Default) sys_time timer frequency in Hz.
sys_time.resolution is set from this define.
Definition at line 52 of file sys_time.h.
Referenced by sys_time_init().
#define SYS_TIME_NB_TIMER 8
Definition at line 40 of file sys_time.h.
Referenced by sys_tick_handler(), sys_tick_irq_handler(), sys_time_init(), and sys_time_register_timer().
#define USEC_OF_SEC (sec) ((sec) * 1e6)
Definition at line 190 of file sys_time.h.
Referenced by actuators_asctec_set(), actuators_asctec_v2_set(), actuators_mkk_set(), actuators_mkk_v2_set(), and actuators_skiron_set().
Typedef Documentation
typedef void(* sys_time_cb)(uint8_t id)
Definition at line 58 of file sys_time.h.
typedef uint8_t tid_t
sys_time timer id type
Definition at line 57 of file sys_time.h.
Function Documentation
static uint32_t cpu_ticks_of_nsec (uint32_t nsec) inline static
Definition at line 172 of file sys_time.h.
References sys_time::cpu_ticks_per_sec.
Referenced by ms2100_reset_cb().
static uint32_t cpu_ticks_of_sec (float seconds) inline static
Definition at line 160 of file sys_time.h.
References sys_time::cpu_ticks_per_sec.
static uint32_t cpu_ticks_of_usec (uint32_t usec) inline static
Definition at line 164 of file sys_time.h.
References sys_time::cpu_ticks_per_sec.
Referenced by sys_time_usleep(), and xtend_rssi_periodic().
static float get_sys_time_float (void) inline static
Get the time in seconds since startup.
Returns
current system time as float
Definition at line 123 of file sys_time.h.
References sys_time::nb_sec, sys_time::nb_sec_rem, and sys_time::resolution_cpu_ticks.
static uint32_t msec_of_cpu_ticks (uint32_t cpu_ticks) inline static
Definition at line 176 of file sys_time.h.
References sys_time::cpu_ticks_per_sec.
Referenced by TRIG_ISR().
static uint32_t msec_of_sys_time_ticks (uint32_t ticks) inline static
Definition at line 147 of file sys_time.h.
References sys_time::ticks_per_sec.
Referenced by gps_tow_from_sys_ticks(), trigger_ext_periodic(), and windturbine_periodic().
static uint32_t nsec_of_cpu_ticks (uint32_t cpu_ticks) inline static
Definition at line 184 of file sys_time.h.
References sys_time::cpu_ticks_per_sec.
static float sec_of_sys_time_ticks (uint32_t ticks) inline static
Definition at line 143 of file sys_time.h.
References sys_time::resolution.
static int32_t signed_cpu_ticks_of_usec (int32_t usec) inline static
Definition at line 168 of file sys_time.h.
References sys_time::cpu_ticks_per_sec.
void sys_time_arch_init (void)
Initialize SysTick.
Generate SysTick interrupt every sys_time.resolution_cpu_ticks
Definition at line 105 of file sys_time_arch.c.
References _VIC_ADDR, _VIC_CNTL, AHB_CLK, sys_time::cpu_ticks_per_sec, PCLK, sys_time::resolution, sys_time::resolution_cpu_ticks, T0CCR, T0EMR, T0MCR, T0MR0, T0PR, T0TCR, TCR_ENABLE, TCR_RESET, TIMER0_ISR(), TIMER0_VIC_SLOT, TMCR_MR0_I, VIC_BIT, VIC_ENABLE, VIC_TIMER0, VICIntEnable, and VICIntSelect.
Referenced by sys_time_init().
void sys_time_cancel_timer (tid_t id)
Cancel a system timer by id.
Parameters
id Timer id.
Definition at line 54 of file sys_time.c.
References sys_time_timer::cb, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, FALSE, sys_time_timer::in_use, and sys_time::timer.
static bool_t sys_time_check_and_ack_timer (tid_t id) inline static
Check if timer has elapsed.
Parameters
id Timer id
Returns
TRUE if timer has elapsed
Definition at line 111 of file sys_time.h.
References sys_time_timer::elapsed, FALSE, sys_time::timer, and TRUE.
Referenced by handle_periodic_tasks(), handle_periodic_tasks_ap(), handle_periodic_tasks_fbw(), and main().
void sys_time_init (void)
Definition at line 70 of file sys_time.c.
References sys_time_timer::cb, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, FALSE, sys_time_timer::in_use, sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, sys_time::resolution, sys_time_arch_init(), SYS_TIME_FREQUENCY, SYS_TIME_NB_TIMER, sys_time::ticks_per_sec, and sys_time::timer.
Referenced by main(), and mcu_init().
int sys_time_register_timer (float duration, sys_time_cb cb)
Register a new system timer.
Parameters
duration Duration in seconds until the timer elapses.
cb Callback function that is called from the ISR when timer elapses, or NULL
Returns
-1 if it failed, the timer id otherwise
Definition at line 37 of file sys_time.c.
References sys_time_timer::cb, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, FALSE, sys_time_timer::in_use, sys_time::nb_tick, SYS_TIME_NB_TIMER, sys_time_ticks_of_sec(), sys_time::timer, and TRUE.
Referenced by init_ap(), init_fbw(), main(), and main_init().
static uint32_t sys_time_ticks_of_msec (uint32_t msec) inline static
Definition at line 135 of file sys_time.h.
References sys_time::ticks_per_sec.
static uint32_t sys_time_ticks_of_sec (float seconds) inline static
Definition at line 131 of file sys_time.h.
References sys_time::ticks_per_sec.
Referenced by sys_time_register_timer(), and sys_time_update_timer().
static uint32_t sys_time_ticks_of_usec (uint32_t usec) inline static
Definition at line 139 of file sys_time.h.
References sys_time::ticks_per_sec.
Referenced by sys_time_usleep().
void sys_time_update_timer (tid_t id, float duration)
Update the duration until a timer elapses.
Parameters
id Timer id
duration Duration in seconds until the timer elapses.
Definition at line 63 of file sys_time.c.
References sys_time_timer::duration, sys_time_timer::end_time, mcu_int_disable, mcu_int_enable, sys_time_ticks_of_sec(), and sys_time::timer.
static uint32_t usec_of_cpu_ticks (uint32_t cpu_ticks) inline static
Definition at line 180 of file sys_time.h.
References sys_time::cpu_ticks_per_sec.
Referenced by get_sys_time_usec().
static uint32_t usec_of_sys_time_ticks (uint32_t ticks) inline static
Definition at line 151 of file sys_time.h.
References sys_time::ticks_per_sec.
Variable Documentation
struct sys_time sys_time
Definition at line 35 of file sys_time.c.