Paparazzi UAS: sw/airborne/lisa/test_spi_slave2.c File Reference
test_spi_slave2.c File Reference
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/spi.h>
#include <stm32/dma.h>
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "fms/fms_autopilot_msg.h"
#include "led.h"
Defines
#define USE_DMA 1
#define BufferSize sizeof(struct AutopilotMessageFoo)
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_spi_slave_init (void)
static void main_setup_dma (void)
static void main_enable_dma (void)
int main (void)
void spi1_dma_irq_handler (void)
Variables
uint8_t SPI_SLAVE_Buffer_Rx [BufferSize]
uint8_t SPI_SLAVE_Buffer_Tx [BufferSize]
Define Documentation
#define BufferSize sizeof(struct AutopilotMessageFoo)
Definition at line 42 of file test_spi_slave2.c.
Referenced by main_event_task(), and main_setup_dma().
#define USE_DMA 1
Definition at line 40 of file test_spi_slave2.c.
Function Documentation
int main (void)
Definition at line 49 of file test_spi_slave2.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_enable_dma (void) [static]
Definition at line 163 of file test_spi_slave2.c.
References SPI1.
Referenced by main_event_task(), and main_spi_slave_init().
static void main_event_task (void) [inline, static]
Definition at line 77 of file test_spi_slave2.c.
References BufferSize, DefaultChannel, DefaultDevice, LED_TOGGLE, main_enable_dma(), main_setup_dma(), SPI_SLAVE_Buffer_Rx, and SPI_SLAVE_Buffer_Tx.
Referenced by main().
static void main_init (void) [inline, static]
static void main_periodic_task (void) [inline, static]
Definition at line 68 of file test_spi_slave2.c.
References DefaultChannel, DefaultDevice, LED_PERIODIC, and sys_time::nb_sec.
Referenced by main().
static void main_setup_dma (void) [static]
Definition at line 138 of file test_spi_slave2.c.
References BufferSize, SPI_SLAVE_Buffer_Rx, and SPI_SLAVE_Buffer_Tx.
Referenced by main_event_task(), and main_spi_slave_init().
static void main_spi_slave_init (void) [inline, static]
Definition at line 93 of file test_spi_slave2.c.
References main_enable_dma(), main_setup_dma(), and SPI1.
void spi1_dma_irq_handler (void)
Definition at line 187 of file test_spi_slave2.c.
References LED_TOGGLE.
Variable Documentation
uint8_t SPI_SLAVE_Buffer_Rx[BufferSize]
Definition at line 43 of file test_spi_slave2.c.
Referenced by main_event_task(), and main_setup_dma().
uint8_t SPI_SLAVE_Buffer_Tx[BufferSize]
Definition at line 44 of file test_spi_slave2.c.
Referenced by main_event_task(), and main_setup_dma().