Paparazzi UAS: sw/airborne/lisa/test_can.c File Reference
test_can.c File Reference
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "subsystems/datalink/downlink.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/can.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
void main_on_can_msg (uint32_t id, uint8_t *data, int len)
int main (void)
Variables
uint8_t tx_data [8]
uint8_t rx_data [8]
bool new_can_data = false
Function Documentation
int main (void)
Definition at line 41 of file test_can.c.
References main_event_task(), main_init(), main_periodic_task(), new_can_data, sys_time_check_and_ack_timer(), and tx_data.
static void main_event_task (void) inline static
Definition at line 81 of file test_can.c.
References LED_OFF, LED_ON, new_can_data, and rx_data.
Referenced by main().
static void main_init (void) inline static
void main_on_can_msg (uint32_t id, uint8_t * data, int len)
Definition at line 117 of file test_can.c.
References new_can_data, and rx_data.
static void main_periodic_task (void) inline static
Definition at line 70 of file test_can.c.
References DefaultChannel, DefaultDevice, LED_PERIODIC, ppz_can_transmit(), and tx_data.
Referenced by main().
Variable Documentation
bool new_can_data = false
Definition at line 39 of file test_can.c.
Referenced by main(), main_event_task(), and main_on_can_msg().
uint8_t rx_data[8]
Definition at line 38 of file test_can.c.
Referenced by main_event_task(), and main_on_can_msg().
uint8_t tx_data[8]
Definition at line 37 of file test_can.c.
Referenced by main(), and main_periodic_task().