Paparazzi UAS: sw/airborne/lisa/test_mc.c File Reference
test_mc.c File Reference
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/i2c.h>
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_i2c_init (void)
static void main_test_send (void)
static void test_gpios (void)
int main (void)
Function Documentation
int main (void)
Definition at line 43 of file test_mc.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) inline static
Definition at line 69 of file test_mc.c.
Referenced by main().
static void main_i2c_init (void) inline static
Definition at line 91 of file test_mc.c.
References I2C1.
static void main_init (void) inline static
static void main_periodic_task (void) inline static
Definition at line 63 of file test_mc.c.
References LED_PERIODIC, and main_test_send().
Referenced by main().
static void main_test_send (void) inline static
Definition at line 125 of file test_mc.c.
References I2C1.
Referenced by main_periodic_task().
static void test_gpios (void) static
Definition at line 74 of file test_mc.c.