Paparazzi UAS: sw/airborne/lisa/test/test_mc_asctec_v1_simple.c File Reference
test_mc_asctec_v1_simple.c File Reference
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "led.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
int main (void)
Variables
static uint8_t i2c_done
Function Documentation
int main (void)
Definition at line 42 of file test_mc_asctec_v1_simple.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) [inline, static]
Definition at line 103 of file test_mc_asctec_v1_simple.c.
Referenced by main().
static void main_init (void) [inline, static]
static void main_periodic_task (void) [inline, static]
Definition at line 61 of file test_mc_asctec_v1_simple.c.
References DefaultChannel, DefaultDevice, i2c_done, and LED_PERIODIC.
Referenced by main().
Variable Documentation
uint8_t i2c_done [static]
Definition at line 40 of file test_mc_asctec_v1_simple.c.
Referenced by main_periodic_task().