Paparazzi UAS: sw/airborne/lisa/tunnel_hw.c File Reference
tunnel_hw.c File Reference
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/f1/rcc.h>
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
Macros
#define A_PERIPH RCC_APB2ENR_IOPAEN
#define A_PORT GPIOA
#define A_RX_PIN GPIO10
#define A_RX_PORT A_PORT
#define A_TX_PIN GPIO9
#define A_TX_PORT A_PORT
#define B_PERIPH RCC_APB2ENR_IOPAEN
#define B_PORT GPIOA
#define B_RX_PIN GPIO3
#define B_RX_PORT B_PORT
#define B_TX_PIN GPIO2
#define B_TX_PORT B_PORT
Functions
static void main_periodic (void)
static void main_event (void)
void Delay (volatile uint32_t nCount)
int main (void)
Macro Definition Documentation
#define A_PERIPH RCC_APB2ENR_IOPAEN
Definition at line 30 of file tunnel_hw.c.
Referenced by main().
#define A_PORT GPIOA
Definition at line 31 of file tunnel_hw.c.
#define A_RX_PIN GPIO10
Definition at line 32 of file tunnel_hw.c.
Referenced by main().
#define A_RX_PORT A_PORT
Definition at line 33 of file tunnel_hw.c.
Referenced by main().
#define A_TX_PIN GPIO9
Definition at line 34 of file tunnel_hw.c.
Referenced by main().
#define A_TX_PORT A_PORT
Definition at line 35 of file tunnel_hw.c.
Referenced by main().
#define B_PERIPH RCC_APB2ENR_IOPAEN
Definition at line 37 of file tunnel_hw.c.
#define B_PORT GPIOA
Definition at line 38 of file tunnel_hw.c.
#define B_RX_PIN GPIO3
Definition at line 39 of file tunnel_hw.c.
Referenced by main().
#define B_RX_PORT B_PORT
Definition at line 40 of file tunnel_hw.c.
Referenced by main().
#define B_TX_PIN GPIO2
Definition at line 41 of file tunnel_hw.c.
Referenced by main().
#define B_TX_PORT B_PORT
Definition at line 42 of file tunnel_hw.c.
Function Documentation
void Delay (volatile uint32_t nCount)
int main (void)
Definition at line 52 of file tunnel_hw.c.
References A_PERIPH, A_RX_PIN, A_RX_PORT, A_TX_PIN, A_TX_PORT, B_RX_PIN, B_RX_PORT, B_TX_PIN, main_event(), main_periodic(), mcu_init(), PERIODIC_FREQUENCY, sys_time_check_and_ack_timer(), and sys_time_register_timer().
static void main_event (void) inline static
static void main_periodic (void) inline static