Paparazzi UAS: sw/airborne/arch/lpc21/usb_tunnel.c File Reference
usb_tunnel.c File Reference
USB tunnel application.
#include "std.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/usb_serial.h"
Macros
#define BLINK_MIN 10
Functions
int main (void)
Detailed Description
USB tunnel application.
This creates a USB serial port that connects to UART0 or UART1 port of the LPC processor. This enables you to configure the gps receiver or the modem without removing it.
Definition in file usb_tunnel.c.
Macro Definition Documentation
#define BLINK_MIN 10
Definition at line 39 of file usb_tunnel.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 41 of file usb_tunnel.c.
References BLINK_MIN, led_init(), LED_OFF, LED_ON, mcu_init(), mcu_int_enable, PCLK, sys_time_init(), T0TC, uart_char_available(), uart_check_free_space(), uart_getch(), uart_transmit(), VCOM_allow_linecoding(), VCOM_check_available(), VCOM_check_free_space(), VCOM_getchar(), VCOM_init(), and VCOM_putchar().