Paparazzi UAS: sw/airborne/subsystems/ins/vf_extended_float.h File Reference
vf_extended_float.h File Reference
Macros
#define VFF_STATE_SIZE 4
Functions
void vff_init (float z, float zdot, float accel_bias, float baro_offset)
void vff_propagate (float accel)
void vff_update_baro (float z_meas)
void vff_update_alt (float z_meas)
void vff_update_offset (float offset)
void vff_update_baro_conf (float z_meas, float conf)
void vff_update_alt_conf (float z_meas, float conf)
void vff_realign (float z_meas)
Variables
float vff_z
float vff_zdot
float vff_bias
float vff_offset
float vff_P [VFF_STATE_SIZE][VFF_STATE_SIZE]
float vff_zdotdot
float vff_z_meas
float vff_z_meas_baro
Macro Definition Documentation
#define VFF_STATE_SIZE 4
Definition at line 26 of file vf_extended_float.h.
Referenced by vff_init().
Function Documentation
void vff_init (float z, float zdot, float accel_bias, float baro_offset)
Definition at line 65 of file vf_extended_float.c.
References INIT_PXX, vff_bias, vff_offset, vff_P, VFF_STATE_SIZE, vff_z, and vff_zdot.
Referenced by ins_init(), and vff_realign().
void vff_propagate (float accel)
Definition at line 99 of file vf_extended_float.c.
void vff_realign (float z_meas)
Definition at line 309 of file vf_extended_float.c.
void vff_update_alt (float z_meas)
Definition at line 245 of file vf_extended_float.c.
References R_ALT, and update_alt_conf().
void vff_update_alt_conf (float z_meas, float conf)
Definition at line 249 of file vf_extended_float.c.
References update_alt_conf().
Referenced by ins_update_sonar().
void vff_update_baro (float z_meas)
Definition at line 185 of file vf_extended_float.c.
References R_BARO, and update_baro_conf().
Referenced by ins_update_baro().
void vff_update_baro_conf (float z_meas, float conf)
Definition at line 189 of file vf_extended_float.c.
References update_baro_conf().
void vff_update_offset (float offset)
Definition at line 304 of file vf_extended_float.c.
References R_OFFSET, and update_offset_conf().
Referenced by ins_update_sonar().
Variable Documentation
float vff_bias
Definition at line 56 of file vf_extended_float.c.
float vff_offset
Definition at line 57 of file vf_extended_float.c.
Referenced by ins_update_sonar(), update_alt_conf(), update_baro_conf(), update_offset_conf(), vff_init(), and vff_propagate().
float vff_P[VFF_STATE_SIZE][VFF_STATE_SIZE]
Definition at line 60 of file vf_extended_float.c.
float vff_z
Definition at line 54 of file vf_extended_float.c.
float vff_z_meas
Definition at line 62 of file vf_extended_float.c.
float vff_z_meas_baro
Definition at line 63 of file vf_extended_float.c.
Referenced by update_baro_conf(), and vff_propagate().
float vff_zdot
Definition at line 55 of file vf_extended_float.c.
float vff_zdotdot
Definition at line 58 of file vf_extended_float.c.