Paparazzi UAS: sw/airborne/subsystems/datalink/w5100.h File Reference
w5100.h File Reference
#include "subsystems/datalink/datalink.h"
#include "generated/airframe.h"
#include "subsystems/datalink/transport.h"
Data Structures
struct w5100_periph
struct w5100_transport
Macros
#define W5100_RX_BUFFER_SIZE 80
#define W5100_TX_BUFFER_SIZE 80
#define W5100_BUFFER_NUM 2
#define STX 0x99
#define W5100Init() w5100_init()
#define W5100CheckFreeSpace(_x) (TRUE)
#define W5100Transmit(_x) w5100_transmit(_x)
#define W5100SendMessage() w5100_send()
#define W5100ChAvailable() w5100_ch_available()
#define W5100Getch() w5100_getch()
#define W5100TxRunning chip0.tx_running
#define W5100SetBaudrate(_b) w5100_set_baudrate(_b)
#define W5100TransportSizeOf(_dev, _x) (_x+4)
#define W5100TransportCheckFreeSpace(_dev, x) TransportLink(_dev, CheckFreeSpace(x))
#define W5100TransportPut1Byte(_dev, x) TransportLink(_dev, Transmit(x))
#define W5100TransportSendMessage(_dev) TransportLink(_dev, SendMessage())
#define W5100TransportPutUint8(_dev, _byte)
#define W5100TransportPut1ByteByAddr(_dev, _byte)
#define W5100TransportPut2Bytes(_dev, _x)
#define W5100TransportPut2ByteByAddr(_dev, _byte)
#define W5100TransportPut4ByteByAddr(_dev, _byte)
#define W5100TransportPutDoubleByAddr(_dev, _byte)
#define W5100TransportPutInt8ByAddr(_dev, _x) W5100TransportPut1ByteByAddr(_dev, _x)
#define W5100TransportPutUint8ByAddr(_dev, _x) W5100TransportPut1ByteByAddr(_dev, (const uint8_t*)_x)
#define W5100TransportPutInt16ByAddr(_dev, _x) W5100TransportPut2ByteByAddr(_dev, (const uint8_t*)_x)
#define W5100TransportPutUint16ByAddr(_dev, _x) W5100TransportPut2ByteByAddr(_dev, (const uint8_t*)_x)
#define W5100TransportPutInt32ByAddr(_dev, _x) W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_x)
#define W5100TransportPutUint32ByAddr(_dev, _x) W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_x)
#define W5100TransportPutFloatByAddr(_dev, _x) W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_x)
#define W5100TransportPutNamedUint8(_dev, _name, _byte) W5100TransportPutUint8(_dev, _byte)
#define W5100TransportPutArray(_dev, _put, _n, _x)
#define W5100TransportPutInt16Array(_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutInt16ByAddr, _n, _x)
#define W5100TransportPutUint16Array(_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutUint16ByAddr, _n, _x)
#define W5100TransportPutUint8Array(_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutUint8ByAddr, _n, _x)
#define W5100TransportPutFloatArray(_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutFloatByAddr, _n, _x)
#define W5100TransportPutDoubleArray(_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutDoubleByAddr, _n, _x)
#define W5100TransportHeader(_dev, payload_len)
#define W5100TransportTrailer(_dev)
#define UNINIT 0
Receiving pprz messages.
#define GOT_STX 1
#define GOT_LENGTH 2
#define GOT_PAYLOAD 3
#define GOT_CRC1 4
#define W5100Buffer(_dev) TransportLink(_dev,ChAvailable())
#define W5100CheckAndParse(_dev, _trans)
Enumerations
enum W5100Status { W5100StatusUninit, W5100StatusIdle, W5100StatusReading }
Functions
void w5100_init (void)
void w5100_transmit (uint8_t data)
uint16_t w5100_receive (uint8_t *buf, uint16_t len)
void w5100_send (void)
uint16_t w5100_rx_size (uint8_t _s)
bool_t w5100_ch_available (void)
static void parse_w5100 (struct w5100_transport *t, uint8_t c)
static void w5100_parse_payload (struct w5100_transport *t)
static void w5100_read_buffer (struct w5100_transport *t)
Variables
uint8_t rx_buf [W5100_RX_BUFFER_SIZE]
struct w5100_periph chip0
struct w5100_transport w5100_tp
Macro Definition Documentation
#define GOT_CRC1 4
Definition at line 175 of file w5100.h.
Referenced by parse_w5100().
#define GOT_LENGTH 2
Definition at line 173 of file w5100.h.
Referenced by parse_w5100().
#define GOT_PAYLOAD 3
Definition at line 174 of file w5100.h.
Referenced by parse_w5100().
#define GOT_STX 1
Definition at line 172 of file w5100.h.
Referenced by parse_w5100().
#define STX 0x99
Definition at line 36 of file w5100.h.
Referenced by parse_w5100().
#define UNINIT 0
Receiving pprz messages.
Definition at line 171 of file w5100.h.
Referenced by parse_w5100(), and w5100_read_buffer().
#define W5100_BUFFER_NUM 2
Definition at line 35 of file w5100.h.
Referenced by w5100_send().
#define W5100_RX_BUFFER_SIZE 80
Definition at line 33 of file w5100.h.
Referenced by w5100_read_buffer().
#define W5100_TX_BUFFER_SIZE 80
Definition at line 34 of file w5100.h.
Referenced by w5100_transmit().
#define W5100Buffer (_dev) TransportLink(_dev,ChAvailable())
Definition at line 249 of file w5100.h.
#define W5100ChAvailable () w5100_ch_available()
Definition at line 79 of file w5100.h.
#define W5100CheckAndParse (_dev, _trans)
Value:
{       \
    if (W5100Buffer(_dev)) {                    \
      w5100_read_buffer( &(_trans) );           \
      if (_trans.trans.msg_received) {          \
        w5100_parse_payload(&(_trans));         \
        _trans.trans.msg_received = FALSE;      \
      }                                         \
    }                                           \
  }
Definition at line 251 of file w5100.h.
#define W5100CheckFreeSpace (_x) (TRUE)
Definition at line 76 of file w5100.h.
#define W5100Getch () w5100_getch()
Definition at line 80 of file w5100.h.
#define W5100Init () w5100_init()
Definition at line 75 of file w5100.h.
#define W5100SendMessage () w5100_send()
Definition at line 78 of file w5100.h.
#define W5100SetBaudrate (_b) w5100_set_baudrate(_b)
Definition at line 82 of file w5100.h.
#define W5100Transmit (_x) w5100_transmit(_x)
Definition at line 77 of file w5100.h.
#define W5100TransportCheckFreeSpace (_dev, x) TransportLink(_dev, CheckFreeSpace(x))
Definition at line 85 of file w5100.h.
#define W5100TransportHeader (_dev, payload_len)
Value:
{ \
W5100TransportPut1Byte(_dev, STX); \
uint8_t msg_len = W5100TransportSizeOf(_dev, payload_len); \
W5100TransportPut1Byte(_dev, msg_len); \
ck_a = msg_len; ck_b = msg_len; \
}
Definition at line 154 of file w5100.h.
#define W5100TransportPut1Byte (_dev, x) TransportLink(_dev, Transmit(x))
Definition at line 86 of file w5100.h.
#define W5100TransportPut1ByteByAddr (_dev, _byte)
Value:
{ \
    uint8_t _x = *(_byte);                          \
    W5100TransportPutUint8(_dev, _x);               \
  }
Definition at line 95 of file w5100.h.
#define W5100TransportPut2ByteByAddr (_dev, _byte)
Value:
{                 \
    W5100TransportPut1ByteByAddr(_dev, _byte);                      \
    W5100TransportPut1ByteByAddr(_dev, (const uint8_t*)_byte+1);    \
  }
Definition at line 106 of file w5100.h.
#define W5100TransportPut2Bytes (_dev, _x)
Value:
{     \
    uint16_t x16 = _x;                          \
    W5100TransportPut1Byte(_dev, x16>>8);       \
    W5100TransportPut1Byte(_dev, x16 & 0xff);   \
  }
Definition at line 100 of file w5100.h.
#define W5100TransportPut4ByteByAddr (_dev, _byte)
Value:
{                 \
    W5100TransportPut2ByteByAddr(_dev, _byte);                      \
    W5100TransportPut2ByteByAddr(_dev, (const uint8_t*)_byte+2);    \
  }
Definition at line 111 of file w5100.h.
#define W5100TransportPutArray (_dev, _put, _n, _x)
Value:
{ \
uint8_t _i; \
W5100TransportPutUint8(_dev, _n); \
for(_i = 0; _i < _n; _i++) { \
_put(_dev, &_x[_i]); \
} \
}
Definition at line 138 of file w5100.h.
#define W5100TransportPutDoubleArray (_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutDoubleByAddr, _n, _x)
Definition at line 151 of file w5100.h.
#define W5100TransportPutDoubleByAddr (_dev, _byte)
Value:
{                \
    W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_byte);      \
    W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_byte+4);    \
  }
Definition at line 122 of file w5100.h.
#define W5100TransportPutFloatArray (_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutFloatByAddr, _n, _x)
Definition at line 150 of file w5100.h.
#define W5100TransportPutFloatByAddr (_dev, _x) W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_x)
Definition at line 135 of file w5100.h.
#define W5100TransportPutInt16Array (_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutInt16ByAddr, _n, _x)
Definition at line 146 of file w5100.h.
#define W5100TransportPutInt16ByAddr (_dev, _x) W5100TransportPut2ByteByAddr(_dev, (const uint8_t*)_x)
Definition at line 131 of file w5100.h.
#define W5100TransportPutInt32ByAddr (_dev, _x) W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_x)
Definition at line 133 of file w5100.h.
#define W5100TransportPutInt8ByAddr (_dev, _x) W5100TransportPut1ByteByAddr(_dev, _x)
Definition at line 129 of file w5100.h.
#define W5100TransportPutNamedUint8 (_dev, _name, _byte) W5100TransportPutUint8(_dev, _byte)
Definition at line 136 of file w5100.h.
#define W5100TransportPutUint16Array (_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutUint16ByAddr, _n, _x)
Definition at line 148 of file w5100.h.
#define W5100TransportPutUint16ByAddr (_dev, _x) W5100TransportPut2ByteByAddr(_dev, (const uint8_t*)_x)
Definition at line 132 of file w5100.h.
#define W5100TransportPutUint32ByAddr (_dev, _x) W5100TransportPut4ByteByAddr(_dev, (const uint8_t*)_x)
Definition at line 134 of file w5100.h.
#define W5100TransportPutUint8 (_dev, _byte)
Value:
{   \
    ck_a += _byte;                              \
    ck_b += ck_a;                               \
    W5100TransportPut1Byte(_dev, _byte);        \
  }
Definition at line 89 of file w5100.h.
#define W5100TransportPutUint8Array (_dev, _n, _x) W5100TransportPutArray(_dev, W5100TransportPutUint8ByAddr, _n, _x)
Definition at line 149 of file w5100.h.
#define W5100TransportPutUint8ByAddr (_dev, _x) W5100TransportPut1ByteByAddr(_dev, (const uint8_t*)_x)
Definition at line 130 of file w5100.h.
#define W5100TransportSendMessage (_dev) TransportLink(_dev, SendMessage())
Definition at line 87 of file w5100.h.
#define W5100TransportSizeOf (_dev, _x) (_x+4)
Definition at line 84 of file w5100.h.
#define W5100TransportTrailer (_dev)
Value:
{ \
W5100TransportPut1Byte(_dev, ck_a); \
W5100TransportPut1Byte(_dev, ck_b); \
W5100TransportSendMessage(_dev); \
}
Definition at line 161 of file w5100.h.
#define W5100TxRunning chip0.tx_running
Definition at line 81 of file w5100.h.
Enumeration Type Documentation
enum W5100Status
Enumerator:
W5100StatusUninit
W5100StatusIdle
W5100StatusReading
Definition at line 38 of file w5100.h.
Function Documentation
static void parse_w5100 (struct w5100_transport * t, uint8_t c) inline static
Definition at line 188 of file w5100.h.
References c, w5100_transport::ck_a, w5100_transport::ck_b, transport::error, GOT_CRC1, GOT_LENGTH, GOT_PAYLOAD, GOT_STX, transport::msg_received, transport::ovrn, transport::payload, w5100_transport::payload_idx, transport::payload_len, w5100_transport::status, STX, w5100_transport::trans, TRUE, and UNINIT.
Referenced by w5100_read_buffer().
bool_t w5100_ch_available (void)
Definition at line 324 of file w5100.c.
References CMD_SOCKET, FALSE, TRUE, and w5100_rx_size().
Referenced by w5100_read_buffer().
void w5100_init (void)
Definition at line 155 of file w5100.c.
References spi_transaction::bitorder, spi_transaction::cdiv, chip0, CMD_SOCKET, configure_socket(), spi_transaction::cpha, spi_transaction::cpol, w5100_periph::curbuf, dest, dport, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, ip, mac, spi_transaction::output_buf, spi_transaction::output_length, RBASE, REG_GAR, REG_MR, REG_RX_MEM, REG_SHAR, REG_SIPR, REG_SUBR, REG_TX_MEM, RSIZE, RST, RXBUF_BASE, SBASE, spi_transaction::select, spi_transaction::slave_idx, SNMR_MULTI, SOCKETS, SPICphaEdge1, SPICpolIdleLow, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, SSIZE, w5100_periph::status, subnet, sys_time_usleep(), TELEM_SOCKET, TXBUF_BASE, w5100_set(), w5100_set_buffer(), W5100_SLAVE_IDX, w5100_spi, W5100StatusUninit, w5100_periph::work_rx, and w5100_periph::work_tx.
Referenced by init_ap().
static void w5100_parse_payload (struct w5100_transport * t) inline static
Definition at line 232 of file w5100.h.
References dl_buffer, dl_msg_available, transport::payload, transport::payload_len, w5100_transport::trans, and TRUE.
static void w5100_read_buffer (struct w5100_transport * t) inline static
Definition at line 239 of file w5100.h.
References c, transport::msg_received, parse_w5100(), rx_buf, w5100_transport::status, w5100_transport::trans, UNINIT, w5100_ch_available(), w5100_receive(), and W5100_RX_BUFFER_SIZE.
uint16_t w5100_receive (uint8_t * buf, uint16_t len)
Definition at line 331 of file w5100.c.
References CMD_SOCKET, SOCK_CR, SOCK_RECV, SOCK_RXRD, w5100_read_data(), w5100_sock_get16(), and w5100_sock_set().
Referenced by w5100_read_buffer().
uint16_t w5100_rx_size (uint8_t _s)
Definition at line 280 of file w5100.c.
References SOCK_RSR, val, and w5100_sock_get16().
Referenced by w5100_ch_available().
void w5100_send (void)
Definition at line 238 of file w5100.c.
References chip0, w5100_periph::curbuf, SBASE, SMASK, SOCK_CR, SOCK_SEND, SOCK_TX_WR, SSIZE, TELEM_SOCKET, w5100_periph::tx_buf, w5100_periph::tx_extract_idx, w5100_periph::tx_insert_idx, W5100_BUFFER_NUM, w5100_set_buffer(), w5100_sock_get(), w5100_sock_get16(), and w5100_sock_set().
void w5100_transmit (uint8_t data)
Definition at line 224 of file w5100.c.
References chip0, w5100_periph::curbuf, w5100_periph::tx_buf, w5100_periph::tx_extract_idx, w5100_periph::tx_insert_idx, and W5100_TX_BUFFER_SIZE.
Variable Documentation
struct w5100_periph chip0
Definition at line 75 of file w5100.c.
Referenced by w5100_init(), w5100_send(), and w5100_transmit().
uint8_t rx_buf[W5100_RX_BUFFER_SIZE]
Definition at line 77 of file w5100.c.
Referenced by w5100_read_buffer().
struct w5100_transport w5100_tp
Definition at line 95 of file w5100.c.