Paparazzi UAS: sw/airborne/subsystems/ahrs.h File Reference
ahrs.h File Reference
Attitude and Heading Reference System interface.
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct Ahrs
Attitude and Heading Reference System state (fixed point version)
struct AhrsFloat
Attitude and Heading Reference System state (floating point version)
Defines
#define AHRS_UNINIT 0
#define AHRS_RUNNING 1
#define AHRS_FLOAT_OF_INT32()
#define AHRS_INT_OF_FLOAT()
#define AHRS_IMU_INT_OF_FLOAT()
Functions
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_gps (void)
Variables
struct Ahrs ahrs
global AHRS state (fixed point version)
struct AhrsFloat ahrs_float
global AHRS state (floating point version)
float ahrs_mag_offset
Detailed Description
Attitude and Heading Reference System interface.
Definition in file ahrs.h.
Define Documentation
#define AHRS_FLOAT_OF_INT32 ()
Value:
{                  \
    QUAT_FLOAT_OF_BFP(ahrs_float.ltp_to_body_quat, ahrs.ltp_to_body_quat);     \
    EULERS_FLOAT_OF_BFP(ahrs_float.ltp_to_body_euler, ahrs.ltp_to_body_euler); \
    RATES_FLOAT_OF_BFP(ahrs_float.body_rate, ahrs.body_rate);          \
  }
Definition at line 83 of file ahrs.h.
#define AHRS_IMU_INT_OF_FLOAT ()
Value:
{                                       \
    QUAT_BFP_OF_REAL(ahrs.ltp_to_imu_quat, ahrs_float.ltp_to_imu_quat); \
    EULERS_BFP_OF_REAL(ahrs.ltp_to_imu_euler, ahrs_float.ltp_to_imu_euler); \
    RMAT_BFP_OF_REAL(ahrs.ltp_to_imu_rmat, ahrs_float.ltp_to_imu_rmat); \
    RATES_BFP_OF_REAL(ahrs.imu_rate, ahrs_float.imu_rate);            \
  }
Definition at line 96 of file ahrs.h.
Referenced by ahrs_align(), ahrs_propagate(), and ahrs_realign_heading().
#define AHRS_INT_OF_FLOAT ()
Value:
{                                                  \
    QUAT_BFP_OF_REAL(ahrs.ltp_to_body_quat, ahrs_float.ltp_to_body_quat);      \
    EULERS_BFP_OF_REAL(ahrs.ltp_to_body_euler, ahrs_float.ltp_to_body_euler);  \
    RMAT_BFP_OF_REAL(ahrs.ltp_to_body_rmat, ahrs_float.ltp_to_body_rmat);      \
    RATES_BFP_OF_REAL(ahrs.body_rate, ahrs_float.body_rate);                   \
  }
Definition at line 89 of file ahrs.h.
Referenced by ahrs_align(), ahrs_propagate(), and ahrs_realign_heading().
#define AHRS_RUNNING 1
Definition at line 34 of file ahrs.h.
Referenced by ahrs_align(), ahrs_init(), ahrs_is_aligned(), and on_mag_event().
#define AHRS_UNINIT 0
Definition at line 33 of file ahrs.h.
Referenced by ahrs_init(), on_accel_event(), on_gyro_accel_event(), and on_gyro_event().
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 100 of file ahrs_float_cmpl.c.
References ACCELS_FLOAT_OF_BFP, ahrs, ahrs_aligner, ahrs_float, ahrs_float_get_euler_from_accel_mag(), ahrs_float_get_quat_from_accel(), ahrs_float_get_quat_from_accel_mag(), ahrs_impl, AHRS_IMU_INT_OF_FLOAT, ahrs_int_get_quat_from_accel(), ahrs_int_get_quat_from_accel_mag(), AHRS_INT_OF_FLOAT, AHRS_RUNNING, bafl_accel_measure, bafl_bias, compute_body_orientation(), compute_body_orientation_and_rates(), compute_imu_euler_and_rmat_from_quat(), compute_imu_quat_and_rmat_from_euler(), compute_imu_rmat_and_euler_from_quat(), EULERS_COPY, EULERS_SDIV, F_UPDATE, FLOAT_QUAT_OF_EULERS, FLOAT_RMAT_OF_QUAT, get_phi_theta_measurement_fom_accel(), get_psi_measurement_from_mag(), AhrsFloatCmplRmat::gyro_bias, AhrsFloatCmplRmat::heading_aligned, INT_RATES_LSHIFT, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, Ahrs::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_euler, Ahrs::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, RATES_COPY, RATES_FLOAT_OF_BFP, set_dcm_matrix_from_rmat(), Ahrs::status, and update_ahrs_from_sim().
Referenced by on_gyro_accel_event(), and on_gyro_event().
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 75 of file ins_xsens.c.
References ahrs, ahrs_float, ahrs_float_lkf_SetRaccel, ahrs_float_lkf_SetRmag, ahrs_impl, ahrs_mag_offset, AHRS_RUNNING, ahrs_sim_available, AHRS_UNINIT, bafl_h, BAFL_hx, BAFL_hy, BAFL_hz, bafl_P, BAFL_Q_ATT, bafl_Q_att, BAFL_Q_GYRO, bafl_Q_gyro, bafl_quat, BAFL_SIGMA_ACCEL, BAFL_SIGMA_MAG, BAFL_SSIZE, bafl_T, Ahrs::body_rate, AhrsFloat::body_rate, AhrsFloatCmplRmat::body_to_imu_quat, Imu::body_to_imu_quat, AhrsFloatCmplRmat::body_to_imu_rmat, Imu::body_to_imu_rmat, AhrsFloatCmplRmat::correct_gravity, EULERS_COPY, FACE_REINJ_1, FLOAT_EULERS_ZERO, FLOAT_QUAT_OF_EULERS, FLOAT_QUAT_ZERO, FLOAT_RATES_ZERO, FLOAT_RMAT_OF_EULERS, FLOAT_RMAT_ZERO, FLOAT_VECT3_ASSIGN, AhrsFloatCmplRmat::gyro_bias, AhrsFloatCmplRmat::heading_aligned, high_accel_done, high_accel_flag, imu, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, Ahrs::imu_rate, AhrsFloat::imu_rate, ins_init(), INT32_EULERS_OF_RMAT, INT32_QUAT_ZERO, INT32_RMAT_ZERO, INT_EULERS_ZERO, INT_RATES_ZERO, Ahrs::ltp_to_body_euler, AhrsFloat::ltp_to_body_euler, Ahrs::ltp_to_body_quat, AhrsFloat::ltp_to_body_quat, Ahrs::ltp_to_body_rmat, AhrsFloat::ltp_to_body_rmat, Ahrs::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_euler, Ahrs::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_quat, Ahrs::ltp_to_imu_rmat, AhrsFloat::ltp_to_imu_rmat, AhrsFloatCmplRmat::ltp_vel_norm_valid, QUAT_COPY, AhrsFloatCmplRmat::rate_correction, RATES_COPY, RMAT_COPY, set_dcm_matrix_from_rmat(), and Ahrs::status.
Referenced by init_ap(), and main_init().
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 131 of file ahrs_float_cmpl.c.
References ahrs, ahrs_float, ahrs_impl, AHRS_IMU_INT_OF_FLOAT, AHRS_INT_OF_FLOAT, ahrs_lowpass_accel(), AHRS_LTP_TO_BODY, AHRS_PROPAGATE_FREQUENCY, AHRS_TO_BFP, bafe_bias, BAFE_DT, bafe_F, bafe_qdot, bafe_quat, bafe_rates, bafl_bias, bafl_dcm, BAFL_DT, bafl_eulers, bafl_P, bafl_Q_att, bafl_Q_gyro, bafl_qnorm, bafl_qr, bafl_qtemp, bafl_quat, bafl_rates, BAFL_SSIZE, bafl_T, bafl_tempP, AhrsFloat::body_rate, compute_ahrs_representations(), compute_body_orientation(), compute_body_orientation_and_rates(), compute_imu_euler_and_rmat_from_quat(), compute_imu_quat_and_euler_from_rmat(), compute_imu_quat_and_rmat_from_euler(), compute_imu_rmat_and_euler_from_quat(), EULERS_ADD, EULERS_DIFF, EULERS_SDIV, F_UPDATE, FLOAT_EULERS_OF_RMAT, FLOAT_QUAT_COMP, FLOAT_QUAT_COPY, FLOAT_QUAT_INTEGRATE, FLOAT_QUAT_NORM, FLOAT_QUAT_NORMALIZE, FLOAT_QUAT_SMUL, FLOAT_RATES_LIN_CMB, FLOAT_RATES_ZERO, FLOAT_RMAT_INTEGRATE_FI, FLOAT_RMAT_OF_QUAT, float_rmat_reorthogonalize(), Imu::gyro, AhrsFloatCmplRmat::gyro_bias, Imu::gyro_prev, imu, Ahrs::imu_rate, AhrsFloat::imu_rate, INT32_EULERS_DOT_OF_RATES, INT32_QUAT_INTEGRATE_FI, INT32_QUAT_NORMALIZE, INT_RATES_ZERO, INTEG_EULER_NORMALIZE, Ahrs::ltp_to_imu_euler, Ahrs::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, Matrix_update(), NOISE_FILTER_GAIN, Normalize(), FloatRates::p, Int32Rates::p, FloatRates::q, Int32Rates::q, FloatQuat::qi, QUAT_ASSIGN, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatRates::r, Int32Rates::r, AhrsFloatCmplRmat::rate_correction, RATE_FLOAT_OF_BFP, RATES_ADD, RATES_COPY, RATES_DIFF, RATES_FLOAT_OF_BFP, RATES_SDIV, RATES_SMUL, RATES_SUB, RATES_SUM, RATES_SUM_SCALED, and RMAT_ELMT.
Referenced by on_gyro_accel_event(), and on_gyro_event().
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 170 of file ahrs_float_cmpl.c.
References Imu::accel, ACCEL_BFP_OF_REAL, ACCELS_FLOAT_OF_BFP, ahrs, ahrs_do_update_accel(), ahrs_float, ahrs_impl, Ahrs::body_rate, AhrsFloat::body_rate, AhrsFloatCmplRmat::body_to_imu_rmat, Imu::body_to_imu_rmat, AhrsFloatCmplRmat::correct_gravity, Drift_correction(), GpsState::fix, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, FLOAT_VECT3_CROSS_PRODUCT, FLOAT_VECT3_NORM, get_phi_theta_measurement_fom_accel(), gps, GPS_FIX_3D, AhrsFloatCmplRmat::gyro_bias, imu, INT32_ACCEL_FRAC, INT32_RATE_FRAC, INT32_RMAT_VMULT, INT32_SPEED_FRAC, INT32_VECT3_CROSS_PRODUCT, INT32_VECT3_DIFF, INT32_VECT3_NORM, INT32_VECT3_RSHIFT, INT_RATES_RSHIFT, Ahrs::ltp_to_imu_rmat, AhrsFloat::ltp_to_imu_rmat, AhrsFloatCmplRmat::ltp_vel_norm, AhrsFloatCmplRmat::ltp_vel_norm_valid, NOISE_FILTER_GAIN, Omega, FloatRates::p, FloatRates::q, FloatRates::r, AhrsFloatCmplRmat::rate_correction, RMAT_ELMT, GpsState::speed_3d, VECT3_COPY, VECT3_DIFF, VECT3_RATES_CROSS_VECT3, VECT3_SDIV, VECT3_SUM_SCALED, FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, FloatVect3::z, and Int32Vect3::z.
Referenced by ahrs_update(), on_accel_event(), and on_gyro_accel_event().
void ahrs_update_gps (void)
Definition at line 97 of file ins_chimu_spi.c.
References ahrs_float, ahrs_impl, ahrs_realign_heading(), ahrs_update_fw_estimator(), ahrs_update_heading(), GpsState::cacc, CHIMU_Checksum(), GpsState::course, GpsState::fix, FloatSwap, gps, GPS_FIX_3D, GpsState::gspeed, AhrsFloatCmplRmat::heading_aligned, InsSend, INT32_ANGLE_FRAC, AhrsFloat::ltp_to_body_euler, AhrsFloatCmplRmat::ltp_vel_norm, AhrsFloatCmplRmat::ltp_vel_norm_valid, FloatEulers::psi, GpsState::speed_3d, SPEED_BFP_OF_REAL, wind_east, and wind_north.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 228 of file ahrs_float_cmpl.c.
References ahrs, ahrs_do_update_mag(), ahrs_float, ahrs_impl, ahrs_update_mag_2d(), ahrs_update_mag_full(), DefaultChannel, DefaultDevice, get_psi_measurement_from_mag(), imu, Ahrs::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_euler, Imu::mag, FloatEulers::phi, Int32Eulers::phi, FloatEulers::theta, Int32Eulers::theta, FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, FloatVect3::z, and Int32Vect3::z.
Referenced by ahrs_update(), and on_mag_event().
Variable Documentation
struct Ahrs ahrs
global AHRS state (fixed point version)
Definition at line 24 of file ahrs.c.
Referenced by __attribute__(), ahrs_align(), ahrs_init(), ahrs_is_aligned(), ahrs_propagate(), ahrs_realign_heading(), ahrs_update_accel(), ahrs_update_heading(), ahrs_update_mag(), b2_hff_propagate(), booz_cam_periodic(), guidance_h_hover_enter(), guidance_h_nav_enter(), guidance_h_run(), guidance_h_traj_run(), ins_propagate(), on_accel_event(), on_gyro_accel_event(), on_gyro_event(), on_mag_event(), reset_psi_ref_from_body(), stabilization_attitude_enter(), stabilization_attitude_read_rc_absolute(), stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_run(), stabilization_attitude_sp_enter(), stabilization_rate_run(), and track_periodic_task().
struct AhrsFloat ahrs_float
global AHRS state (floating point version)
Definition at line 25 of file ahrs.c.
Referenced by ahrs_align(), ahrs_init(), ahrs_propagate(), ahrs_realign_heading(), ahrs_update_accel(), ahrs_update_fw_estimator(), ahrs_update_gps(), ahrs_update_heading(), ahrs_update_infrared(), ahrs_update_mag(), ahrs_update_mag_2d(), ahrs_update_mag_2d_dumb(), ahrs_update_mag_full(), compute_ahrs_representations(), compute_body_orientation_and_rates(), compute_imu_quat_and_euler_from_rmat(), compute_imu_rmat_and_euler_from_quat(), Matrix_update(), reset_psi_ref_from_body(), stabilization_attitude_run(), and update_ahrs_from_sim().
float ahrs_mag_offset
Definition at line 27 of file ahrs.c.
Referenced by ahrs_init().