Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_sim.c File Reference
ahrs_sim.c File Reference
#include "subsystems/ahrs.h"
#include "subsystems/ahrs/ahrs_sim.h"
#include "math/pprz_algebra_float.h"
#include "generated/airframe.h"
#include <inttypes.h>
#include <caml/mlvalues.h>
Functions
void compute_body_orientation_and_rates (void)
void update_ahrs_from_sim (void)
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_gps (void)
Variables
float sim_phi
in radians
float sim_theta
in radians
float sim_psi
in radians
float sim_p
in radians/s
float sim_q
in radians/s
float sim_r
in radians/s
bool_t ahrs_sim_available
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 79 of file ahrs_sim.c.
References ahrs, ahrs_aligner, ahrs_float, ahrs_float_get_quat_from_accel(), ahrs_float_get_quat_from_accel_mag(), ahrs_impl, AHRS_IMU_INT_OF_FLOAT, AHRS_INT_OF_FLOAT, AHRS_RUNNING, compute_body_orientation_and_rates(), compute_imu_rmat_and_euler_from_quat(), AhrsFloatCmplRmat::gyro_bias, AhrsFloatCmplRmat::heading_aligned, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, AhrsFloat::ltp_to_imu_quat, RATES_COPY, RATES_FLOAT_OF_BFP, Ahrs::status, and update_ahrs_from_sim().
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 59 of file ahrs_sim.c.
References ahrs, ahrs_float, AHRS_RUNNING, ahrs_sim_available, AhrsFloat::body_rate, EULERS_COPY, FLOAT_EULERS_ZERO, FLOAT_QUAT_ZERO, FLOAT_RATES_ZERO, FLOAT_RMAT_ZERO, AhrsFloat::imu_rate, ins_init(), AhrsFloat::ltp_to_body_euler, AhrsFloat::ltp_to_body_quat, AhrsFloat::ltp_to_body_rmat, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, QUAT_COPY, RATES_COPY, RMAT_COPY, and Ahrs::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 94 of file ahrs_sim.c.
References ahrs_float, ahrs_impl, AHRS_IMU_INT_OF_FLOAT, AHRS_INT_OF_FLOAT, AHRS_PROPAGATE_FREQUENCY, compute_body_orientation_and_rates(), compute_imu_quat_and_euler_from_rmat(), compute_imu_rmat_and_euler_from_quat(), FLOAT_QUAT_INTEGRATE, FLOAT_QUAT_NORMALIZE, FLOAT_RATES_LIN_CMB, FLOAT_RATES_ZERO, FLOAT_RMAT_INTEGRATE_FI, float_rmat_reorthogonalize(), AhrsFloatCmplRmat::gyro_bias, Imu::gyro_prev, imu, AhrsFloat::imu_rate, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, AhrsFloatCmplRmat::rate_correction, RATES_COPY, RATES_FLOAT_OF_BFP, RATES_SUB, and RATES_SUM.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 97 of file ahrs_sim.c.
References Imu::accel, ACCELS_FLOAT_OF_BFP, ahrs_float, ahrs_impl, AhrsFloat::body_rate, AhrsFloatCmplRmat::body_to_imu_rmat, AhrsFloatCmplRmat::correct_gravity, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, FLOAT_VECT3_CROSS_PRODUCT, FLOAT_VECT3_NORM, AhrsFloatCmplRmat::gyro_bias, imu, AhrsFloat::ltp_to_imu_rmat, AhrsFloatCmplRmat::ltp_vel_norm, AhrsFloatCmplRmat::ltp_vel_norm_valid, AhrsFloatCmplRmat::rate_correction, RMAT_ELMT, VECT3_DIFF, and VECT3_RATES_CROSS_VECT3.
void ahrs_update_gps (void)
Definition at line 103 of file ahrs_sim.c.
References CHIMU_Checksum(), GpsState::fix, FloatSwap, gps, GPS_FIX_3D, InsSend, and GpsState::speed_3d.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 100 of file ahrs_sim.c.
References ahrs_update_mag_2d(), and ahrs_update_mag_full().
void compute_body_orientation_and_rates (void)
Definition at line 111 of file ahrs_sim.c.
References ahrs_float, AhrsFloat::body_rate, EULERS_COPY, AhrsFloat::imu_rate, AhrsFloat::ltp_to_body_euler, AhrsFloat::ltp_to_body_quat, AhrsFloat::ltp_to_body_rmat, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, QUAT_COPY, RATES_COPY, and RMAT_COPY.
Referenced by ahrs_align(), and update_ahrs_from_sim().
void update_ahrs_from_sim (void)
Definition at line 42 of file ahrs_sim.c.
References ahrs_float, compute_body_orientation_and_rates(), FLOAT_QUAT_OF_EULERS, FLOAT_RMAT_OF_EULERS, AhrsFloat::imu_rate, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, sim_p, sim_phi, sim_psi, sim_q, sim_r, sim_theta, and FloatEulers::theta.
Referenced by ahrs_align().
Variable Documentation
bool_t ahrs_sim_available
Definition at line 17 of file jsbsim_ahrs.c.
float sim_p
in radians/s
Definition at line 14 of file jsbsim_ahrs.c.
Referenced by ArduIMU_periodic(), provide_attitude_and_rates(), provide_rates(), and update_ahrs_from_sim().
float sim_phi
in radians
Definition at line 11 of file jsbsim_ahrs.c.
Referenced by ArduIMU_periodic(), provide_attitude(), provide_attitude_and_rates(), and update_ahrs_from_sim().
float sim_psi
in radians
Definition at line 13 of file jsbsim_ahrs.c.
Referenced by provide_attitude(), provide_attitude_and_rates(), and update_ahrs_from_sim().
float sim_q
in radians/s
Definition at line 15 of file jsbsim_ahrs.c.
Referenced by ArduIMU_periodic(), provide_attitude_and_rates(), provide_rates(), and update_ahrs_from_sim().
float sim_r
in radians/s
Definition at line 16 of file jsbsim_ahrs.c.
Referenced by ArduIMU_periodic(), provide_attitude_and_rates(), provide_rates(), and update_ahrs_from_sim().
float sim_theta
in radians
Definition at line 12 of file jsbsim_ahrs.c.
Referenced by ArduIMU_periodic(), provide_attitude(), provide_attitude_and_rates(), and update_ahrs_from_sim().