Paparazzi UAS: sw/airborne/boards/lisa_l/test_baro.c File Reference
test_baro.c File Reference
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/i2c.h"
#include "led.h"
#include "subsystems/datalink/downlink.h"
#include "subsystems/sensors/baro.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_on_baro_diff (void)
static void main_on_baro_abs (void)
int main (void)
Function Documentation
int main (void)
Definition at line 49 of file test_baro.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
static void main_event_task (void) [inline, static]
Definition at line 107 of file test_baro.c.
References BaroEvent, main_on_baro_abs(), and main_on_baro_diff().
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 61 of file test_baro.c.
References baro_init(), mcu_init(), PERIODIC_FREQUENCY, and sys_time_register_timer().
static void main_on_baro_abs (void) [inline, static]
Definition at line 117 of file test_baro.c.
References Baro::absolute, baro, DefaultChannel, DefaultDevice, and Baro::differential.
Referenced by main_event_task().
static void main_on_baro_diff (void) [inline, static]
Definition at line 113 of file test_baro.c.
Referenced by main_event_task().
static void main_periodic_task (void) [inline, static]
Definition at line 74 of file test_baro.c.
References baro_periodic(), DefaultChannel, DefaultDevice, and LED_PERIODIC.
Referenced by main().