Paparazzi UAS: sw/airborne/lisa/test_led.c File Reference
test_led.c File Reference
#include <stm32/flash.h>
#include <stm32/misc.h>
#include "mcu.h"
#include "led.h"
Functions
void Delay (__IO uint32_t nCount)
void led_on (int i)
void led_off (int i)
int main (void)
Function Documentation
void Delay (__IO uint32_t nCount)
Definition at line 106 of file test_led.c.
Referenced by main().
void led_off (int i)
Definition at line 69 of file test_led.c.
References LED_OFF.
Referenced by main().
void led_on (int i)
Definition at line 49 of file test_led.c.
References LED_ON.
Referenced by main().
int main (void)
Definition at line 89 of file test_led.c.
References Delay(), led_off(), led_on(), LED_PERIODIC, and mcu_init().