Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_int_cmpl_quat.c File Reference
ahrs_int_cmpl_quat.c File Reference
#include "subsystems/ahrs/ahrs_int_cmpl_quat.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "subsystems/ahrs/ahrs_int_utils.h"
#include "subsystems/imu.h"
#include "math/pprz_trig_int.h"
#include "math/pprz_algebra_int.h"
#include "generated/airframe.h"
Defines
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
Functions
static void ahrs_update_mag_full (void)
static void ahrs_update_mag_2d (void)
static void compute_imu_euler_and_rmat_from_quat (void)
static void compute_body_euler_and_rmat_from_quat (void)
static void compute_imu_orientation (void)
static void compute_body_orientation (void)
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_gps (void)
void ahrs_update_heading (int32_t heading)
Update yaw based on a heading measurement.
void ahrs_realign_heading (int32_t heading)
Hard reset yaw to a heading.
__attribute__ ((always_inline))
Variables
struct AhrsIntCmpl ahrs_impl
Define Documentation
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
Definition at line 50 of file ahrs_int_cmpl_quat.c.
Referenced by ahrs_propagate().
Function Documentation
__attribute__ ((always_inline))
Definition at line 439 of file ahrs_int_cmpl_quat.c.
References ahrs, INT32_EULERS_OF_QUAT, INT32_RMAT_OF_QUAT, Ahrs::ltp_to_imu_euler, Ahrs::ltp_to_imu_quat, and Ahrs::ltp_to_imu_rmat.
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 96 of file ahrs_int_cmpl_quat.c.
References ahrs, ahrs_aligner, ahrs_impl, ahrs_int_get_quat_from_accel(), ahrs_int_get_quat_from_accel_mag(), AHRS_RUNNING, compute_body_orientation(), compute_imu_euler_and_rmat_from_quat(), AhrsFloatCmplRmat::gyro_bias, AhrsFloatCmplRmat::heading_aligned, INT_RATES_LSHIFT, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, Ahrs::ltp_to_imu_quat, RATES_COPY, and Ahrs::status.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 60 of file ahrs_int_cmpl_quat.c.
References ahrs, ahrs_impl, AHRS_UNINIT, Ahrs::body_rate, Imu::body_to_imu_quat, Imu::body_to_imu_rmat, AhrsFloatCmplRmat::correct_gravity, AhrsFloatCmplRmat::gyro_bias, AhrsFloatCmplRmat::heading_aligned, imu, Ahrs::imu_rate, INT32_EULERS_OF_RMAT, INT32_QUAT_ZERO, INT32_RMAT_ZERO, INT_EULERS_ZERO, INT_RATES_ZERO, Ahrs::ltp_to_body_euler, Ahrs::ltp_to_body_quat, Ahrs::ltp_to_body_rmat, Ahrs::ltp_to_imu_euler, Ahrs::ltp_to_imu_quat, Ahrs::ltp_to_imu_rmat, AhrsFloatCmplRmat::ltp_vel_norm_valid, QUAT_COPY, AhrsFloatCmplRmat::rate_correction, RMAT_COPY, and Ahrs::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 128 of file ahrs_int_cmpl_quat.c.
References ahrs, ahrs_impl, AHRS_PROPAGATE_FREQUENCY, compute_body_orientation(), compute_imu_euler_and_rmat_from_quat(), AhrsFloatCmplRmat::gyro_bias, Imu::gyro_prev, imu, Ahrs::imu_rate, INT32_QUAT_INTEGRATE_FI, INT32_QUAT_NORMALIZE, INT_RATES_ZERO, Ahrs::ltp_to_imu_quat, AhrsFloatCmplRmat::rate_correction, RATES_ADD, RATES_COPY, RATES_DIFF, RATES_SDIV, and RATES_SMUL.
void ahrs_realign_heading (int32_t heading)
Hard reset yaw to a heading.
Doesn't affect the bias. Sets ahrs_impl.heading_aligned to TRUE.
Parameters:
heading Heading in body frame, radians (CW/north) with INT32_ANGLE_FRAC
Definition at line 402 of file ahrs_int_cmpl_quat.c.
References ahrs, ahrs_impl, compute_body_euler_and_rmat_from_quat(), compute_imu_orientation(), AhrsFloatCmplRmat::heading_aligned, INT32_QUAT_COMP_NORM_SHORTEST, INT32_QUAT_INV_COMP_NORM_SHORTEST, INT32_QUAT_NORMALIZE, Ahrs::ltp_to_body_quat, PPRZ_ITRIG_COS, PPRZ_ITRIG_SIN, Int32Quat::qi, QUAT_COPY, Int32Quat::qx, Int32Quat::qy, and Int32Quat::qz.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 161 of file ahrs_int_cmpl_quat.c.
References Imu::accel, ACCEL_BFP_OF_REAL, ahrs, ahrs_impl, Ahrs::body_rate, Imu::body_to_imu_rmat, AhrsFloatCmplRmat::correct_gravity, AhrsFloatCmplRmat::gyro_bias, imu, INT32_ACCEL_FRAC, INT32_RATE_FRAC, INT32_RMAT_VMULT, INT32_SPEED_FRAC, INT32_VECT3_CROSS_PRODUCT, INT32_VECT3_DIFF, INT32_VECT3_NORM, INT32_VECT3_RSHIFT, INT_RATES_RSHIFT, Ahrs::ltp_to_imu_rmat, AhrsFloatCmplRmat::ltp_vel_norm, AhrsFloatCmplRmat::ltp_vel_norm_valid, FloatRates::p, FloatRates::q, FloatRates::r, AhrsFloatCmplRmat::rate_correction, RMAT_ELMT, VECT3_RATES_CROSS_VECT3, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void ahrs_update_gps (void)
Definition at line 316 of file ahrs_int_cmpl_quat.c.
References ahrs_impl, ahrs_realign_heading(), ahrs_update_heading(), GpsState::cacc, GpsState::course, GpsState::fix, gps, GPS_FIX_3D, GpsState::gspeed, AhrsFloatCmplRmat::heading_aligned, INT32_ANGLE_FRAC, AhrsFloatCmplRmat::ltp_vel_norm, AhrsFloatCmplRmat::ltp_vel_norm_valid, GpsState::speed_3d, and SPEED_BFP_OF_REAL.
void ahrs_update_heading (int32_t heading)
Update yaw based on a heading measurement.
e.g. from GPS course
Parameters:
heading Heading in body frame, radians (CW/north) with INT32_ANGLE_FRAC
Definition at line 349 of file ahrs_int_cmpl_quat.c.
References ahrs, ahrs_impl, AhrsFloatCmplRmat::gyro_bias, INT32_ANGLE_FRAC, INT32_ANGLE_NORMALIZE, INT32_RMAT_VMULT, INT_RATES_RSHIFT, Ahrs::ltp_to_body_rmat, Ahrs::ltp_to_imu_rmat, FloatRates::p, PPRZ_ITRIG_COS, PPRZ_ITRIG_SIN, FloatRates::q, FloatRates::r, AhrsFloatCmplRmat::rate_correction, RMAT_ELMT, TRIG_BFP_OF_REAL, Int32Vect2::x, Int32Vect3::x, Int32Vect2::y, Int32Vect3::y, and Int32Vect3::z.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 236 of file ahrs_int_cmpl_quat.c.
References ahrs_update_mag_2d(), and ahrs_update_mag_full().
static void ahrs_update_mag_2d (void) [inline, static]
static void ahrs_update_mag_full (void) [inline, static]
static void compute_body_euler_and_rmat_from_quat (void) [inline, static]
Referenced by ahrs_realign_heading().
static void compute_body_orientation (void) [inline, static]
Referenced by ahrs_align(), and ahrs_propagate().
static void compute_imu_euler_and_rmat_from_quat (void) [inline, static]
Referenced by ahrs_align(), and ahrs_propagate().
static void compute_imu_orientation (void) [inline, static]
Referenced by ahrs_realign_heading().
Variable Documentation
struct AhrsIntCmpl ahrs_impl
Definition at line 53 of file ahrs_int_cmpl_quat.c.