Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/obsolete/i2c_attempt3_subtra.c File Reference
i2c_attempt3_subtra.c File Reference
#include "mcu_periph/i2c.h"
#include <stm32/rcc.h>
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
Defines
#define I2C_DEBUG_LED
#define I2C_SR1_BIT_SB (1<<0)
#define I2C_SR1_BIT_ADDR (1<<1)
#define I2C_SR1_BIT_BTF (1<<2)
#define I2C_SR1_BIT_RXNE (1<<6)
#define I2C_SR1_BIT_TXE (1<<7)
#define I2C_SR1_BIT_ERR_BUS (1<<8)
#define I2C_SR1_BIT_ERR_ARLO (1<<9)
#define I2C_SR1_BIT_ERR_AF (1<<10)
#define I2C_SR1_BIT_ERR_OVR (1<<11)
#define I2C_SR1_BITS_ERR ((1<<8)|(1<<9)|(1<<10)|(1<<11)|(1<<12)|(1<<14)|(1<<15))
#define I2C_SR2_BIT_TRA (1<<2)
#define I2C_SR2_BIT_BUSY (1<<1)
#define I2C_SR2_BIT_MSL (1<<0)
#define I2C_CR1_BIT_PE (1<<0)
#define I2C_CR1_BIT_START (1<<8)
#define I2C_CR1_BIT_STOP (1<<9)
#define I2C_CR1_BIT_ACK (1<<10)
#define I2C_CR1_BIT_POS (1<<11)
#define I2C_CR1_BIT_SWRST (1<<15)
#define I2C_CR2_BIT_ITERREN (1<<8)
#define I2C_CR2_BIT_ITEVTEN (1<<9)
#define I2C_CR2_BIT_ITBUFEN (1<<10)
#define BIT_X_IS_SET_IN_REG(X, REG) (((REG) & (X)) == (X))
Enumerations
enum STMI2CSubTransactionStatus {
STMI2C_SubTra_Busy, STMI2C_SubTra_Ready_StopRequested, STMI2C_SubTra_Ready, STMI2C_SubTra_Error,
STMI2C_SubTra_Busy, STMI2C_SubTra_Ready_StopRequested, STMI2C_SubTra_Ready, STMI2C_SubTra_Busy,
STMI2C_SubTra_Ready_StopRequested, STMI2C_SubTra_Ready, STMI2C_SubTra_Busy, STMI2C_SubTra_Ready_StopRequested,
STMI2C_SubTra_Ready, STMI2C_SubTra_Error
}
Functions
static void LED1_ON (void)
static void LED1_OFF (void)
static void LED2_ON (void)
static void LED2_OFF (void)
static void LED_INIT (void)
static void LED_ERROR (uint8_t base, uint8_t nr)
static void LED_SHOW_ACTIVE_BITS (I2C_TypeDef *regs)
static void PPRZ_I2C_SEND_STOP (I2C_TypeDef *regs)
static void PPRZ_I2C_SEND_START (struct i2c_periph *periph)
static enum
STMI2CSubTransactionStatus stmi2c_send (I2C_TypeDef *regs, struct i2c_periph *periph, struct i2c_transaction *trans)
static enum
STMI2CSubTransactionStatus stmi2c_read1 (I2C_TypeDef *regs, struct i2c_transaction *trans)
static enum
STMI2CSubTransactionStatus stmi2c_read2 (I2C_TypeDef *regs, struct i2c_transaction *trans)
static enum
STMI2CSubTransactionStatus stmi2c_readmany (I2C_TypeDef *regs, struct i2c_periph *periph, struct i2c_transaction *trans)
static void stmi2c_clear_pending_interrupts (I2C_TypeDef *regs)
static void i2c_error (struct i2c_periph *periph)
static void i2c_irq (struct i2c_periph *periph)
void i2c_setbitrate (struct i2c_periph *periph, int bitrate)
void i2c_event (void)
bool_t i2c_submit (struct i2c_periph *periph, struct i2c_transaction *t)
bool_t i2c_idle (struct i2c_periph *periph)
Define Documentation
#define BIT_X_IS_SET_IN_REG (X, REG) (((REG) & (X)) == (X))
Definition at line 136 of file i2c_attempt3_subtra.c.
Referenced by i2c_idle(), LED_SHOW_ACTIVE_BITS(), stmi2c_clear_pending_interrupts(), stmi2c_read1(), stmi2c_read2(), stmi2c_readmany(), and stmi2c_send().
#define I2C_CR1_BIT_ACK (1<<10)
Definition at line 123 of file i2c_attempt3_subtra.c.
Referenced by stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
#define I2C_CR1_BIT_PE (1<<0)
Definition at line 120 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS(), and PPRZ_I2C_SEND_START().
#define I2C_CR1_BIT_POS (1<<11)
Definition at line 124 of file i2c_attempt3_subtra.c.
Referenced by stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
#define I2C_CR1_BIT_START (1<<8)
Definition at line 121 of file i2c_attempt3_subtra.c.
Referenced by i2c_irq(), LED_SHOW_ACTIVE_BITS(), and PPRZ_I2C_SEND_START().
#define I2C_CR1_BIT_STOP (1<<9)
Definition at line 122 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS(), and PPRZ_I2C_SEND_STOP().
#define I2C_CR1_BIT_SWRST (1<<15)
Definition at line 125 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS().
#define I2C_CR2_BIT_ITBUFEN (1<<10)
Definition at line 131 of file i2c_attempt3_subtra.c.
Referenced by PPRZ_I2C_SEND_START(), stmi2c_clear_pending_interrupts(), stmi2c_read1(), stmi2c_read2(), stmi2c_readmany(), and stmi2c_send().
#define I2C_CR2_BIT_ITERREN (1<<8)
Definition at line 129 of file i2c_attempt3_subtra.c.
Referenced by PPRZ_I2C_SEND_START().
#define I2C_CR2_BIT_ITEVTEN (1<<9)
Definition at line 130 of file i2c_attempt3_subtra.c.
Referenced by PPRZ_I2C_SEND_START().
#define I2C_DEBUG_LED
Definition at line 8 of file i2c_attempt3_subtra.c.
Referenced by i2c_event(), i2c_idle(), i2c_irq(), and PPRZ_I2C_SEND_START().
#define I2C_SR1_BIT_ADDR (1<<1)
Definition at line 100 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS(), stmi2c_clear_pending_interrupts(), stmi2c_read1(), stmi2c_read2(), stmi2c_readmany(), and stmi2c_send().
#define I2C_SR1_BIT_BTF (1<<2)
Definition at line 101 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS(), stmi2c_clear_pending_interrupts(), stmi2c_read2(), stmi2c_readmany(), and stmi2c_send().
#define I2C_SR1_BIT_ERR_AF (1<<10)
Definition at line 107 of file i2c_attempt3_subtra.c.
#define I2C_SR1_BIT_ERR_ARLO (1<<9)
Definition at line 106 of file i2c_attempt3_subtra.c.
#define I2C_SR1_BIT_ERR_BUS (1<<8)
Definition at line 105 of file i2c_attempt3_subtra.c.
#define I2C_SR1_BIT_ERR_OVR (1<<11)
Definition at line 108 of file i2c_attempt3_subtra.c.
#define I2C_SR1_BIT_RXNE (1<<6)
Definition at line 102 of file i2c_attempt3_subtra.c.
Referenced by stmi2c_read1(), and stmi2c_readmany().
#define I2C_SR1_BIT_SB (1<<0)
Definition at line 99 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS(), stmi2c_clear_pending_interrupts(), stmi2c_read1(), stmi2c_read2(), stmi2c_readmany(), and stmi2c_send().
#define I2C_SR1_BIT_TXE (1<<7)
Definition at line 103 of file i2c_attempt3_subtra.c.
Referenced by stmi2c_send().
#define I2C_SR1_BITS_ERR ((1<<8)|(1<<9)|(1<<10)|(1<<11)|(1<<12)|(1<<14)|(1<<15))
Definition at line 110 of file i2c_attempt3_subtra.c.
Referenced by i2c_irq(), and LED_SHOW_ACTIVE_BITS().
#define I2C_SR2_BIT_BUSY (1<<1)
Definition at line 115 of file i2c_attempt3_subtra.c.
Referenced by i2c_idle(), and LED_SHOW_ACTIVE_BITS().
#define I2C_SR2_BIT_MSL (1<<0)
Definition at line 116 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS().
#define I2C_SR2_BIT_TRA (1<<2)
Definition at line 114 of file i2c_attempt3_subtra.c.
Referenced by LED_SHOW_ACTIVE_BITS().
Enumeration Type Documentation
enum STMI2CSubTransactionStatus
Enumerator:
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Error
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Busy
STMI2C_SubTra_Ready_StopRequested
STMI2C_SubTra_Ready
STMI2C_SubTra_Error
Definition at line 321 of file i2c_attempt3_subtra.c.
Function Documentation
static void i2c_error (struct i2c_periph * periph) [inline, static]
Definition at line 907 of file i2c_attempt3_subtra.c.
References i2c_errors::ack_fail_cnt, i2c_errors::arb_lost_cnt, i2c_errors::er_irq_cnt, i2c_periph::errors, LED_ERROR(), i2c_errors::miss_start_stop_cnt, i2c_errors::over_under_cnt, i2c_errors::pec_recep_cnt, i2c_periph::reg_addr, i2c_errors::smbus_alert_cnt, and i2c_errors::timeout_tlow_cnt.
Referenced by i2c_irq().
void i2c_event (void)
Definition at line 1146 of file i2c_attempt3_subtra.c.
References i2c_idle(), I2CIdle, I2CStartRequested, LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), and PPRZ_I2C_SEND_START().
bool_t i2c_idle (struct i2c_periph * periph)
Definition at line 1270 of file i2c_attempt3_subtra.c.
References BIT_X_IS_SET_IN_REG, I2C_DEBUG_LED, I2C_SR2_BIT_BUSY, I2CIdle, i2c_periph::reg_addr, and i2c_periph::status.
static void i2c_irq (struct i2c_periph * periph) [inline, static]
Definition at line 636 of file i2c_attempt3_subtra.c.
References i2c_periph::errors, I2C_CR1_BIT_START, I2C_DEBUG_LED, i2c_error(), I2C_SR1_BITS_ERR, I2C_TRANSACTION_QUEUE_LEN, I2CIdle, I2CStartRequested, I2CTransFailed, I2CTransRx, I2CTransTxRx, LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), LED_SHOW_ACTIVE_BITS(), i2c_transaction::len_r, PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), i2c_periph::reg_addr, i2c_transaction::status, i2c_periph::status, stmi2c_clear_pending_interrupts(), stmi2c_read1(), stmi2c_read2(), stmi2c_readmany(), stmi2c_send(), STMI2C_SubTra_Busy, STMI2C_SubTra_Ready, i2c_periph::trans, i2c_periph::trans_extract_idx, i2c_periph::trans_insert_idx, i2c_transaction::type, and i2c_errors::unexpected_event_cnt.
void i2c_setbitrate (struct i2c_periph * periph, int bitrate)
Definition at line 1117 of file i2c_attempt3_subtra.c.
References i2c_idle(), LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
bool_t i2c_submit (struct i2c_periph * periph, struct i2c_transaction * t)
Definition at line 1231 of file i2c_attempt3_subtra.c.
References I2C_TRANSACTION_QUEUE_LEN, I2CIdle, I2CTransPending, PPRZ_I2C_SEND_START(), i2c_transaction::status, i2c_periph::status, i2c_periph::trans, i2c_periph::trans_extract_idx, and i2c_periph::trans_insert_idx.
static void LED1_OFF (void) [inline, static]
Definition at line 21 of file i2c_attempt3_subtra.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_INIT(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), and stmi2c_readmany().
static void LED1_ON (void) [inline, static]
Definition at line 16 of file i2c_attempt3_subtra.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), and stmi2c_readmany().
static void LED2_OFF (void) [inline, static]
Definition at line 31 of file i2c_attempt3_subtra.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_INIT(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), and stmi2c_readmany().
static void LED2_ON (void) [inline, static]
Definition at line 26 of file i2c_attempt3_subtra.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), and stmi2c_readmany().
static void LED_ERROR (uint8_t base, uint8_t nr) [inline, static]
Definition at line 50 of file i2c_attempt3_subtra.c.
References LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
Referenced by i2c_error().
static void LED_INIT (void) [inline, static]
Definition at line 36 of file i2c_attempt3_subtra.c.
References LED1_OFF(), and LED2_OFF().
static void LED_SHOW_ACTIVE_BITS (I2C_TypeDef * regs) [inline, static]
Definition at line 144 of file i2c_attempt3_subtra.c.
References BIT_X_IS_SET_IN_REG, I2C_CR1_BIT_PE, I2C_CR1_BIT_START, I2C_CR1_BIT_STOP, I2C_CR1_BIT_SWRST, I2C_SR1_BIT_ADDR, I2C_SR1_BIT_BTF, I2C_SR1_BIT_SB, I2C_SR1_BITS_ERR, I2C_SR2_BIT_BUSY, I2C_SR2_BIT_MSL, I2C_SR2_BIT_TRA, LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
Referenced by i2c_event(), i2c_irq(), and PPRZ_I2C_SEND_START().
static void PPRZ_I2C_SEND_START (struct i2c_periph * periph) [inline, static]
Definition at line 272 of file i2c_attempt3_subtra.c.
References I2C_CR1_BIT_PE, I2C_CR1_BIT_START, I2C_CR2_BIT_ITBUFEN, I2C_CR2_BIT_ITERREN, I2C_CR2_BIT_ITEVTEN, I2C_DEBUG_LED, I2CStartRequested, i2c_periph::idx_buf, LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), LED_SHOW_ACTIVE_BITS(), i2c_periph::reg_addr, and i2c_periph::status.
Referenced by i2c_event(), i2c_irq(), and i2c_submit().
static void PPRZ_I2C_SEND_STOP (I2C_TypeDef * regs) [inline, static]
Definition at line 257 of file i2c_attempt3_subtra.c.
References I2C_CR1_BIT_STOP, LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
Referenced by i2c_irq(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
static void stmi2c_clear_pending_interrupts (I2C_TypeDef * regs) [inline, static]
Definition at line 605 of file i2c_attempt3_subtra.c.
References __attribute__(), BIT_X_IS_SET_IN_REG, I2C_CR2_BIT_ITBUFEN, I2C_SR1_BIT_ADDR, I2C_SR1_BIT_BTF, and I2C_SR1_BIT_SB.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_read1 (I2C_TypeDef * regs, struct i2c_transaction * trans) [inline, static]
Definition at line 395 of file i2c_attempt3_subtra.c.
References __attribute__(), BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2C_CR1_BIT_ACK, I2C_CR1_BIT_POS, I2C_CR2_BIT_ITBUFEN, I2C_SR1_BIT_ADDR, I2C_SR1_BIT_RXNE, I2C_SR1_BIT_SB, I2CTransSuccess, PPRZ_I2C_SEND_STOP(), i2c_transaction::slave_addr, i2c_transaction::status, STMI2C_SubTra_Busy, and STMI2C_SubTra_Ready_StopRequested.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_read2 (I2C_TypeDef * regs, struct i2c_transaction * trans) [inline, static]
Definition at line 441 of file i2c_attempt3_subtra.c.
References __attribute__(), BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2C_CR1_BIT_ACK, I2C_CR1_BIT_POS, I2C_CR2_BIT_ITBUFEN, I2C_SR1_BIT_ADDR, I2C_SR1_BIT_BTF, I2C_SR1_BIT_SB, I2CTransSuccess, PPRZ_I2C_SEND_STOP(), i2c_transaction::slave_addr, i2c_transaction::status, STMI2C_SubTra_Busy, and STMI2C_SubTra_Ready_StopRequested.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_readmany (I2C_TypeDef * regs, struct i2c_periph * periph, struct i2c_transaction * trans) [inline, static]
Definition at line 491 of file i2c_attempt3_subtra.c.
References __attribute__(), BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2C_CR1_BIT_ACK, I2C_CR1_BIT_POS, I2C_CR2_BIT_ITBUFEN, I2C_SR1_BIT_ADDR, I2C_SR1_BIT_BTF, I2C_SR1_BIT_RXNE, I2C_SR1_BIT_SB, I2CTransSuccess, i2c_periph::idx_buf, LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), i2c_transaction::len_r, PPRZ_I2C_SEND_STOP(), i2c_transaction::slave_addr, i2c_transaction::status, STMI2C_SubTra_Busy, and STMI2C_SubTra_Ready_StopRequested.
Referenced by i2c_irq().
static enum STMI2CSubTransactionStatus stmi2c_send (I2C_TypeDef * regs, struct i2c_periph * periph, struct i2c_transaction * trans) [inline, static]
Definition at line 327 of file i2c_attempt3_subtra.c.
References __attribute__(), BIT_X_IS_SET_IN_REG, i2c_transaction::buf, I2C_CR2_BIT_ITBUFEN, I2C_SR1_BIT_ADDR, I2C_SR1_BIT_BTF, I2C_SR1_BIT_SB, I2C_SR1_BIT_TXE, I2CTransSuccess, I2CTransTx, i2c_periph::idx_buf, i2c_transaction::len_w, i2c_transaction::slave_addr, i2c_transaction::status, STMI2C_SubTra_Busy, STMI2C_SubTra_Ready, and i2c_transaction::type.
Referenced by i2c_irq().