Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/obsolete/i2c_attempt1.c File Reference
i2c_attempt1.c File Reference
#include "mcu_periph/i2c.h"
#include <stm32/rcc.h>
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
Defines
#define SPURIOUS_INTERRUPT(_periph, _status, _event) { }
#define OUT_OF_SYNC_STATE_MACHINE(_periph, _status, _event) { }
Functions
static void LED1_ON (void)
static void LED1_OFF (void)
static void LED2_ON ()
static void LED2_OFF (void)
static void LED_INIT (void)
static void LED_ERROR (uint8_t nr)
static void LED_STROBE2 (void)
bool_t i2c_submit (struct i2c_periph *periph, struct i2c_transaction *t)
bool_t i2c_idle (struct i2c_periph *periph)
Define Documentation
#define OUT_OF_SYNC_STATE_MACHINE (_periph, _status, _event) { }
Definition at line 83 of file i2c_attempt1.c.
#define SPURIOUS_INTERRUPT (_periph, _status, _event) { }
Definition at line 82 of file i2c_attempt1.c.
Function Documentation
bool_t i2c_idle (struct i2c_periph * periph)
Definition at line 653 of file i2c_attempt1.c.
bool_t i2c_submit (struct i2c_periph * periph, struct i2c_transaction * t)
Definition at line 628 of file i2c_attempt1.c.
References I2C_TRANSACTION_QUEUE_LEN, I2CIdle, I2CTransPending, i2c_transaction::status, i2c_periph::status, i2c_periph::trans, i2c_periph::trans_extract_idx, and i2c_periph::trans_insert_idx.
static void LED1_OFF (void) [inline, static]
Definition at line 17 of file i2c_attempt1.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_INIT(), LED_STROBE2(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
static void LED1_ON (void) [inline, static]
Definition at line 12 of file i2c_attempt1.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_STROBE2(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
static void LED2_OFF (void) [inline, static]
Definition at line 27 of file i2c_attempt1.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), i2c_submit(), LED_ERROR(), LED_INIT(), LED_STROBE2(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
static void LED2_ON (void) [inline, static]
Definition at line 22 of file i2c_attempt1.c.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), i2c_submit(), LED_ERROR(), LED_STROBE2(), PPRZ_I2C_SEND_START(), PPRZ_I2C_SEND_STOP(), stmi2c_read1(), stmi2c_read2(), and stmi2c_readmany().
static void LED_ERROR (uint8_t nr) [inline, static]
Definition at line 46 of file i2c_attempt1.c.
References LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
Referenced by i2c_error().
static void LED_INIT (void) [inline, static]
Definition at line 32 of file i2c_attempt1.c.
References LED1_OFF(), and LED2_OFF().
static void LED_STROBE2 (void) [inline, static]
Definition at line 60 of file i2c_attempt1.c.
References LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().