Paparazzi UAS: sw/airborne/modules/ins/ins_chimu_spi.c File Reference
ins_chimu_spi.c File Reference
#include <stdbool.h>
#include "mcu_periph/spi.h"
#include "mcu_periph/spi_slave_hs_arch.h"
#include "estimator.h"
#include "subsystems/gps.h"
#include "subsystems/ahrs.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
#include "ins_module.h"
#include "imu_chimu.h"
Defines
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void ins_init (void)
void parse_ins_msg (void)
void ahrs_update_gps (void)
void ins_periodic_task (void)
Variables
CHIMU_PARSER_DATA CHIMU_DATA
INS_FORMAT ins_roll_neutral
INS_FORMAT ins_pitch_neutral
volatile uint8_t new_ins_attitude
Define Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 21 of file ins_chimu_spi.c.
Function Documentation
void ahrs_update_gps (void)
Definition at line 97 of file ins_chimu_spi.c.
References CHIMU_Checksum(), GpsState::fix, FloatSwap, gps, GPS_FIX_3D, InsSend, and GpsState::speed_3d.
void ins_init (void)
Definition at line 39 of file ins_chimu_spi.c.
References CHIMU_BROADCAST, CHIMU_Checksum(), CHIMU_Init(), CHIMU_STX, ins_pitch_neutral, ins_roll_neutral, InsSend, InsSend1, MSG09_ESTIMATOR, MSG10_UARTSETTINGS, and new_ins_attitude.
void ins_periodic_task (void)
Definition at line 120 of file ins_chimu_spi.c.
void parse_ins_msg (void)
Definition at line 71 of file ins_chimu_spi.c.
Referenced by ins_event_task().
Variable Documentation
CHIMU_PARSER_DATA CHIMU_DATA
Definition at line 32 of file ins_chimu_spi.c.
INS_FORMAT ins_pitch_neutral
Definition at line 35 of file ins_chimu_spi.c.
INS_FORMAT ins_roll_neutral
Definition at line 34 of file ins_chimu_spi.c.
volatile uint8_t new_ins_attitude
Definition at line 37 of file ins_chimu_spi.c.
Referenced by ins_init(), and parse_ins_msg().