Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/quat_setpoint_int.h File Reference
quat_setpoint_int.h File Reference
#include "stabilization.h"
#include "subsystems/radio_control.h"
#include "math/pprz_algebra.h"
#include "stabilization/stabilization_attitude_ref_int.h"
Functions
void stabilization_attitude_sp_enter (void)
void stabilization_attitude_read_rc_absolute (bool_t in_flight)
Function Documentation
void stabilization_attitude_read_rc_absolute (bool_t in_flight)
Definition at line 65 of file quat_setpoint_int.c.
References ahrs, APPLY_DEADBAND, INT32_EULERS_OF_QUAT, INT32_QUAT_COMP_NORM_SHORTEST, INT32_QUAT_OF_EULERS, Ahrs::ltp_to_body_quat, Int32Eulers::phi, PITCH_COEF, Int32Eulers::psi, QUAT_COPY, radio_control, RADIO_PITCH, RADIO_ROLL, RADIO_YAW, RATE_BFP_OF_REAL, RC_UPDATE_FREQ, reset_sp_quat(), ROLL_COEF, stab_att_sp_euler, stab_att_sp_quat, Int32Eulers::theta, and YAW_COEF.
Referenced by stabilization_attitude_read_rc().
void stabilization_attitude_sp_enter (void)
Definition at line 104 of file quat_setpoint_int.c.
References ahrs, Ahrs::ltp_to_body_quat, and reset_sp_quat().
Referenced by stabilization_attitude_ref_enter().