Paparazzi UAS: sw/airborne/firmwares/rotorcraft/actuators/arch/sim/actuators_pwm_arch.c File Reference
actuators_pwm_arch.c File Reference
dummy servos handling for sim
#include "firmwares/rotorcraft/actuators/actuators_pwm.h"
Functions
void actuators_pwm_arch_init (void)
void actuators_pwm_commit (void)
Detailed Description
dummy servos handling for sim
Definition in file actuators_pwm_arch.c.
Function Documentation
void actuators_pwm_arch_init (void)
Definition at line 28 of file actuators_pwm_arch.c.
Referenced by actuators_init().
void actuators_pwm_commit (void)
Definition at line 32 of file actuators_pwm_arch.c.
Referenced by actuators_set(), on_overo_link_msg_received(), and test_srvo_periodic().