Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/spi_arch.h File Reference
spi_arch.h File Reference
#include "mcu_periph/spi.h"
#include <stm32/gpio.h>
Functions
void spi_arch_int_enable (void)
handling of stm32 SPI hardware
void spi_arch_int_disable (void)
void spi_clear_rx_buf (void)
void spi_rw (struct spi_transaction *_trans)
Function Documentation
void spi_arch_int_disable (void)
Definition at line 32 of file spi_arch.c.
void spi_arch_int_enable (void)
handling of stm32 SPI hardware
Definition at line 20 of file spi_arch.c.
Referenced by spi_init().
void spi_clear_rx_buf (void)
void spi_rw (struct spi_transaction * _trans)
Definition at line 106 of file spi_arch.c.
References slave0, and Spi2Slave0Select.
Referenced by imu_periodic(), mpu_set(), and mpu_wait_slave4_ready().