Paparazzi UAS: sw/airborne/arch/stm32/stm32_exceptions.h File Reference
stm32_exceptions.h File Reference
Functions
void nmi_exception (void)
void hard_fault_exception (void)
void mem_manage_exception (void)
void bus_fault_exception (void)
void usage_fault_exception (void)
Function Documentation
void bus_fault_exception (void)
Definition at line 37 of file stm32_exceptions.c.
Referenced by reset_handler_stage1().
void hard_fault_exception (void)
Definition at line 29 of file stm32_exceptions.c.
Referenced by reset_handler_stage1().
void mem_manage_exception (void)
Definition at line 33 of file stm32_exceptions.c.
Referenced by reset_handler_stage1().
void nmi_exception (void)
Definition at line 26 of file stm32_exceptions.c.
Referenced by reset_handler_stage1().
void usage_fault_exception (void)
Definition at line 41 of file stm32_exceptions.c.
Referenced by reset_handler_stage1().