Paparazzi UAS: sw/airborne/firmwares/rotorcraft/actuators/actuators_mkk.c File Reference
actuators_mkk.c File Reference
Actuators driver for Mikrokopter motor controllers.
#include "firmwares/rotorcraft/actuators.h"
#include "firmwares/rotorcraft/actuators/actuators_mkk.h"
#include "firmwares/rotorcraft/commands.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/sys_time.h"
Functions
void actuators_init (void)
void actuators_set (bool_t motors_on)
Variables
struct ActuatorsMkk actuators_mkk
uint32_t actuators_delay_time
bool_t actuators_delay_done
Detailed Description
Actuators driver for Mikrokopter motor controllers.
Definition in file actuators_mkk.c.
Function Documentation
void actuators_init (void)
Definition at line 40 of file actuators_mkk.c.
References actuators_delay_done, actuators_delay_time, actuators_mkk, FALSE, I2CTransSuccess, I2CTransTx, i2c_transaction::len_w, i2c_transaction::slave_addr, i2c_transaction::status, supervision_init(), SysTimeTimerStart, ActuatorsMkk::trans, TRUE, and i2c_transaction::type.
void actuators_set (bool_t motors_on)
Definition at line 62 of file actuators_mkk.c.
References actuators_delay_done, actuators_delay_time, actuators_mkk, i2c_transaction::buf, Supervision::commands, commands, FALSE, i2c_submit(), supervision, supervision_run(), SysTimeTimer, ActuatorsMkk::trans, TRUE, and USEC_OF_SEC.
Variable Documentation
bool_t actuators_delay_done
Definition at line 38 of file actuators_mkk.c.
uint32_t actuators_delay_time
Definition at line 37 of file actuators_mkk.c.
struct ActuatorsMkk actuators_mkk
Definition at line 34 of file actuators_mkk.c.
Referenced by actuators_init(), and actuators_set().