Paparazzi UAS: sw/airborne/firmwares/rotorcraft/actuators/actuators_skiron.c File Reference
actuators_skiron.c File Reference
Skiron motor speed controller by Michel.
#include "firmwares/rotorcraft/actuators.h"
#include "firmwares/rotorcraft/actuators/actuators_skiron.h"
#include "firmwares/rotorcraft/commands.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/sys_time.h"
Functions
void actuators_init (void)
void actuators_set (bool_t motors_on)
Variables
struct ActuatorsSkiron actuators_skiron
uint32_t actuators_delay_time
bool_t actuators_delay_done
Detailed Description
Skiron motor speed controller by Michel.
Definition in file actuators_skiron.c.
Function Documentation
void actuators_init (void)
Definition at line 40 of file actuators_skiron.c.
References _4015_NB_CHANNELS, actuators_delay_done, actuators_delay_time, ActuatorsSkiron::actuators_idx, actuators_skiron, ACTUATORS_SKIRON_I2C_ADDR, FALSE, I2CTransDone, I2CTransTx, IO0DIR, IO1DIR, i2c_transaction::len_w, PWM_ISR(), PWMLER, PWMLER_LATCH0, PWMLER_LATCH_SERV1, PWMMCR, PWMMCR_MR0R, PWMMCR_MRI_SERV1, PWMMR0, PWMMR_SERV1, PWMPCR, PWMPCR_ENA_SERV1, PWMPR, PWMTCR, PWMTCR_COUNTER_ENABLE, PWMTCR_PWM_ENABLE, SERV1_CLOCK_PIN, SERV1_CLOCK_PINSEL, SERV1_CLOCK_PINSEL_BIT, SERV1_CLOCK_PINSEL_VAL, SERV1_DATA_PIN, SERV1_RESET_PIN, SERVOS_TICS_OF_USEC, servos_values, i2c_transaction::slave_addr, i2c_transaction::status, supervision_init(), SysTimeTimerStart, ActuatorsSkiron::trans, TRUE, i2c_transaction::type, VIC_BIT, VIC_ENABLE, VIC_PWM, VICIntEnable, VICIntSelect, VICVectAddr3, and VICVectCntl3.
void actuators_set (bool_t motors_on)
Definition at line 62 of file actuators_skiron.c.
References actuators_asctec, actuators_delay_done, actuators_delay_time, ActuatorsSkiron::actuators_idx, actuators_skiron, ASCTEC_MAX_CMD, ASCTEC_MAX_THROTTLE, ASCTEC_MIN_CMD, ASCTEC_MIN_THROTTLE, i2c_transaction::buf, ActuatorsAsctec::cmd, ActuatorsAsctec::cmds, Supervision::commands, commands, ActuatorsAsctec::cur_addr, FALSE, i2c_submit(), ActuatorsAsctec::i2c_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, MAX_PPRZ, ActuatorsAsctec::nb_err, ActuatorsAsctec::new_addr, NONE, PITCH, REVERSE, ROLL, SET_ADDR, i2c_transaction::status, supervision, supervision_run(), SysTimeTimer, TEST, THRUST, ActuatorsSkiron::trans, TRUE, USEC_OF_SEC, and YAW.
Variable Documentation
bool_t actuators_delay_done
Definition at line 38 of file actuators_skiron.c.
uint32_t actuators_delay_time
Definition at line 37 of file actuators_skiron.c.
struct ActuatorsSkiron actuators_skiron
Definition at line 34 of file actuators_skiron.c.
Referenced by actuators_init(), and actuators_set().