Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/can_arch.c File Reference
can_arch.c File Reference
#include <stdint.h>
#include <string.h>
#include "mcu_periph/can_arch.h"
#include "mcu_periph/can.h"
#include <stm32/rcc.h>
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/can.h>
#include "led.h"
Macros
#define RCC_APB2Periph_GPIO_CAN RCC_APB2Periph_GPIOA
#define GPIO_CAN GPIOA
#define GPIO_Pin_CAN_RX GPIO_Pin_11
#define GPIO_Pin_CAN_TX GPIO_Pin_12
Functions
void _can_run_rx_callback (uint32_t id, uint8_t *buf, uint8_t len)
void can_hw_init (void)
int can_hw_transmit (uint32_t id, const uint8_t *buf, uint8_t len)
void usb_lp_can1_rx0_irq_handler (void)
Variables
CanTxMsg can_tx_msg
CanRxMsg can_rx_msg
Macro Definition Documentation
#define GPIO_CAN GPIOA
Definition at line 40 of file can_arch.c.
#define GPIO_Pin_CAN_RX GPIO_Pin_11
Definition at line 41 of file can_arch.c.
#define GPIO_Pin_CAN_TX GPIO_Pin_12
Definition at line 42 of file can_arch.c.
#define RCC_APB2Periph_GPIO_CAN RCC_APB2Periph_GPIOA
Definition at line 39 of file can_arch.c.
Function Documentation
void _can_run_rx_callback (uint32_t id, uint8_t * buf, uint8_t len)
Definition at line 45 of file can.c.
References can_rx_callback.
Referenced by usb_lp_can1_rx0_irq_handler().
void can_hw_init (void)
Definition at line 49 of file can_arch.c.
References CAN1, and can_tx_msg.
Referenced by can_init().
int can_hw_transmit (uint32_t id, const uint8_t * buf, uint8_t len)
Definition at line 126 of file can_arch.c.
References CAN1, and can_tx_msg.
Referenced by can_transmit().
void usb_lp_can1_rx0_irq_handler (void)
Definition at line 146 of file can_arch.c.
References _can_run_rx_callback(), CAN1, and can_rx_msg.
Variable Documentation
CanRxMsg can_rx_msg
Definition at line 45 of file can_arch.c.
Referenced by usb_lp_can1_rx0_irq_handler().
CanTxMsg can_tx_msg
Definition at line 44 of file can_arch.c.
Referenced by can_hw_init(), and can_hw_transmit().