Paparazzi UAS: sw/airborne/mcu_periph/i2c.h File Reference
i2c.h File Reference
#include "std.h"
#include "mcu_periph/i2c_arch.h"
#include <string.h>
Data Structures
struct i2c_transaction
struct i2c_periph
struct i2c_errors
Macros
#define I2C_BUF_LEN 32
#define I2C_TRANSACTION_QUEUE_LEN 8
#define I2C_ZERO_EVENTS(_err)
#define ZEROS_ERR_COUNTER(_i2c_err)
#define I2CReceive(_p, _t, _s_addr, _len)
#define I2CTransmit(_p, _t, _s_addr, _len)
#define I2CTransceive(_p, _t, _s_addr, _len_w, _len_r)
Enumerations
enum I2CTransactionType { I2CTransTx, I2CTransRx, I2CTransTxRx }
enum I2CTransactionStatus {
I2CTransPending, I2CTransRunning, I2CTransSuccess, I2CTransFailed,
I2CTransDone
}
enum I2CStatus {
I2CIdle, I2CStartRequested, I2CAddrWrSent, I2CAddrRdSent,
I2CSendingByte, I2CReadingByte, I2CReadingLastByte, I2CStopRequested,
I2CRestartRequested, I2CComplete, I2CFailed
}
Functions
void i2c_init (struct i2c_periph *p)
bool_t i2c_idle (struct i2c_periph *p)
bool_t i2c_submit (struct i2c_periph *p, struct i2c_transaction *t)
void i2c_setbitrate (struct i2c_periph *p, int bitrate)
void i2c_event (void)
Macro Definition Documentation
#define I2C_BUF_LEN 32
Definition at line 38 of file i2c.h.
#define I2C_TRANSACTION_QUEUE_LEN 8
Definition at line 51 of file i2c.h.
Referenced by end_of_transaction(), i2c_event(), i2c_irq(), and i2c_submit().
#define I2C_ZERO_EVENTS (_err)
Value:
{                     \
    _err.irq_cnt = 0;                           \
    memset((void*)_err.event_chain, 0, sizeof(_err.event_chain));   \
    memset((void*)_err.status_chain, 0, sizeof(_err.status_chain)); \
  }
Definition at line 88 of file i2c.h.
#define I2CReceive (_p, _t, _s_addr, _len)
Value:
{ \
  _t.type = I2CTransRx;                     \
  _t.slave_addr = _s_addr;                  \
  _t.len_r = _len;                          \
  _t.len_w = 0;                             \
  i2c_submit(&(_p),&(_t));                  \
}
Definition at line 140 of file i2c.h.
Referenced by airspeed_amsys_read_periodic(), airspeed_ets_read_periodic(), ArduIMU_periodic(), baro_amsys_read_periodic(), baro_ets_read_periodic(), charge_sens_periodic(), dpicco_periodic(), dust_gp2y_periodic(), ezcurrent_read_periodic(), geiger_counter_periodic(), humid_htm_read(), humid_sht_p_humid(), humid_sht_p_temp(), infrared_i2c_hor_event(), infrared_i2c_update(), MPPT_periodic(), srf08_read(), temod_periodic(), and wind_gfi_event().
#define I2CTransceive (_p, _t, _s_addr, _len_w, _len_r)
Value:
{  \
  _t.type = I2CTransTxRx;                                 \
  _t.slave_addr = _s_addr;                                \
  _t.len_r = _len_r;                                      \
  _t.len_w = _len_w;                                      \
  i2c_submit(&(_p),&(_t));                                \
}
Definition at line 156 of file i2c.h.
Referenced by ads1114_read(), adxl345_read(), atmega_i2c_cam_ctrl_send(), baro_bmp_init(), baro_bmp_periodic(), baro_ms5611_d1(), baro_ms5611_d2(), baro_ms5611_event(), baro_ms5611_periodic(), baro_scp_event(), baro_scp_periodic(), hmc58xx_read(), humid_sht_event_i2c(), humid_sht_periodic_i2c(), ir_mlx_event(), ir_mlx_periodic(), itg3200_read(), lm75_periodic(), pbn_periodic(), pcap01readRegister(), readPCAP01_SRAM(), srf08_read_register(), and tmp102_periodic().
#define I2CTransmit (_p, _t, _s_addr, _len)
Value:
{ \
  _t.type = I2CTransTx;                       \
  _t.slave_addr = _s_addr;                    \
  _t.len_r = 0;                               \
  _t.len_w = _len;                            \
  i2c_submit(&(_p),&(_t));                    \
}
Definition at line 148 of file i2c.h.
Referenced by ads1114_init(), adxl345_send_config(), ArduIMU_periodicGPS(), baro_bmp_event(), baro_bmp_periodic(), baro_ms5611_event(), baro_ms5611_periodic(), baro_scp_start_high_res_measurement(), generic_com_periodic(), hmc58xx_send_config(), humid_htm_start(), humid_sht_event_i2c(), humid_sht_periodic_i2c(), infrared_i2c_hor_event(), infrared_i2c_update(), itg3200_send_config(), MPPT_ask(), MPPT_periodic(), PCAP01_Control(), pcap01writeRegister(), srf08_init(), srf08_initiate_ranging(), srf08_receive(), stop_com(), tmp102_init(), wind_gfi_event(), wind_gfi_periodic(), and writePCAP01_SRAM().
#define ZEROS_ERR_COUNTER (_i2c_err)
Value:
{     \
    _i2c_err.ack_fail_cnt = 0;        \
    _i2c_err.miss_start_stop_cnt = 0;     \
    _i2c_err.arb_lost_cnt = 0;        \
    _i2c_err.over_under_cnt = 0;      \
    _i2c_err.pec_recep_cnt = 0;       \
    _i2c_err.timeout_tlow_cnt = 0;      \
    _i2c_err.smbus_alert_cnt = 0;     \
    _i2c_err.unexpected_event_cnt = 0;      \
    _i2c_err.last_unexpected_event = 0;     \
    _i2c_err.er_irq_cnt = 0;        \
  }
Definition at line 94 of file i2c.h.
Enumeration Type Documentation
enum I2CStatus
Enumerator:
I2CIdle
I2CStartRequested
I2CAddrWrSent
I2CAddrRdSent
I2CSendingByte
I2CReadingByte
I2CReadingLastByte
I2CStopRequested
I2CRestartRequested
I2CComplete
I2CFailed
Definition at line 22 of file i2c.h.
enum I2CTransactionStatus
Enumerator:
I2CTransPending
I2CTransRunning
I2CTransSuccess
I2CTransFailed
I2CTransDone
Definition at line 14 of file i2c.h.
enum I2CTransactionType
Enumerator:
I2CTransTx
I2CTransRx
I2CTransTxRx
Definition at line 8 of file i2c.h.
Function Documentation
void i2c_event (void)
Definition at line 344 of file i2c_arch.c.
References i2c_idle(), I2CIdle, I2CStartRequested, LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), and PPRZ_I2C_SEND_START().
Referenced by event_task_ap(), event_task_fbw(), and main_event().
bool_t i2c_idle (struct i2c_periph * p)
Definition at line 317 of file i2c_arch.c.
References BIT_X_IS_SET_IN_REG, FALSE, I2C_DEBUG_LED, I2C_SR2_BIT_BUSY, I2CIdle, i2c_periph::reg_addr, RESET, i2c_periph::status, and TRUE.
Referenced by baro_periodic(), event_i2c_abuse_test(), hmc5843_idle_task(), hmc5843_periodic(), i2c_event(), i2c_setbitrate(), and imu_aspirin_event().
void i2c_init (struct i2c_periph * p)
Definition at line 38 of file i2c.c.
References I2CIdle, i2c_periph::status, i2c_periph::trans_extract_idx, and i2c_periph::trans_insert_idx.
void i2c_setbitrate (struct i2c_periph * p, int bitrate)
Definition at line 346 of file i2c_arch.c.
References I2C_CR1_BIT_PE, i2c_idle(), LED1_OFF(), LED1_ON(), LED2_OFF(), LED2_ON(), and i2c_periph::reg_addr.
Referenced by event_i2c_abuse_test().
bool_t i2c_submit (struct i2c_periph * p, struct i2c_transaction * t)
Definition at line 321 of file i2c_arch.c.
References FALSE, I2C_TRANSACTION_QUEUE_LEN, I2CIdle, I2cSendStart, I2CTransFailed, I2CTransPending, int_disable, int_enable, LED2_OFF(), LED2_ON(), PPRZ_I2C_SEND_START(), start_transaction(), i2c_transaction::status, i2c_periph::status, i2c_periph::trans, i2c_periph::trans_extract_idx, i2c_periph::trans_insert_idx, and TRUE.
Referenced by actuators_set(), ami601_read(), baro_board_read_from_current_register(), baro_board_read_from_register(), baro_board_send_reset(), baro_board_set_current_register(), baro_board_write_to_register(), bmp085_read_reg16(), bmp085_read_reg24(), bmp085_write_reg(), event_i2c_abuse_test(), gyro_read_i2c(), hmc5843_idle_task(), hmc5843_periodic(), i2c_abuse_send_transaction(), imu_impl_init(), imu_periodic(), main_event_task(), main_periodic_task(), send_config(), and send_i2c_msg_with_retry().