Paparazzi UAS: sw/airborne/boards/lisa_l/baro_board.h File Reference
baro_board.h File Reference
#include "std.h"
#include "mcu_periph/i2c.h"
Data Structures
struct BaroBoard
Macros
#define BaroEvent(_b_abs_handler, _b_diff_handler)
Enumerations
enum LisaBaroStatus {
LBS_UNINITIALIZED, LBS_RESETED, LBS_INITIALIZING_ABS, LBS_INITIALIZING_ABS_1,
LBS_INITIALIZING_DIFF, LBS_INITIALIZING_DIFF_1, LBS_IDLE, LBS_READING_ABS,
LBS_READ_ABS, LBS_READING_DIFF, LBS_READ_DIFF, LBS_UNINITIALIZED,
LBS_REQUEST, LBS_READING, LBS_READ, LBS_REQUEST_TEMP,
LBS_READING_TEMP, LBS_READ_TEMP
}
Functions
void baro_board_send_reset (void)
void baro_board_send_config_abs (void)
void baro_board_send_config_diff (void)
Variables
struct BaroBoard baro_board
struct i2c_transaction baro_trans
Macro Definition Documentation
#define BaroEvent (_b_abs_handler, _b_diff_handler)
Value:
{     \
    if (baro_board.status == LBS_READING_ABS &&                 \
        baro_trans.status != I2CTransPending) {                 \
      baro_board.status = LBS_READ_ABS;                         \
      if (baro_trans.status == I2CTransSuccess) {               \
        int16_t tmp = baro_trans.buf[0]<<8 | baro_trans.buf[1]; \
        baro.absolute = tmp;                                    \
        _b_abs_handler();                                       \
      }                                                         \
    }                                                           \
    else  if (baro_board.status == LBS_READING_DIFF &&      \
              baro_trans.status != I2CTransPending) {     \
      baro_board.status = LBS_READ_DIFF;                        \
      if (baro_trans.status == I2CTransSuccess) {               \
          int16_t tmp = baro_trans.buf[0]<<8 | baro_trans.buf[1]; \
        baro.differential = tmp;                                \
        _b_diff_handler();                                      \
      }                                                         \
    }                                                           \
  }
Definition at line 38 of file baro_board.h.
Enumeration Type Documentation
enum LisaBaroStatus
Enumerator:
LBS_UNINITIALIZED
LBS_RESETED
LBS_INITIALIZING_ABS
LBS_INITIALIZING_ABS_1
LBS_INITIALIZING_DIFF
LBS_INITIALIZING_DIFF_1
LBS_IDLE
LBS_READING_ABS
LBS_READ_ABS
LBS_READING_DIFF
LBS_READ_DIFF
LBS_UNINITIALIZED
LBS_REQUEST
LBS_READING
LBS_READ
LBS_REQUEST_TEMP
LBS_READING_TEMP
LBS_READ_TEMP
Definition at line 13 of file baro_board.h.
Function Documentation
void baro_board_send_config_abs (void)
Definition at line 69 of file baro_board.c.
References BARO_ABS_ADDR, and baro_board_write_to_register().
Referenced by baro_periodic().
void baro_board_send_config_diff (void)
Definition at line 80 of file baro_board.c.
References baro_board_write_to_register(), and BARO_DIFF_ADDR.
Referenced by baro_periodic().
void baro_board_send_reset (void)
Definition at line 84 of file baro_board.c.
Variable Documentation
struct BaroBoard baro_board
Definition at line 35 of file baro_board.c.
struct i2c_transaction baro_trans
Definition at line 6 of file baro_board.c.