Paparazzi UAS: sw/airborne/firmwares/rotorcraft/actuators.h File Reference
actuators.h File Reference
#include "std.h"
Functions
void actuators_init (void)
void actuators_set (bool_t motors_on)
Function Documentation
void actuators_init (void)
Definition at line 22 of file servos_4015_hw.c.
References _4015_NB_CHANNELS, _4017_NB_CHANNELS, _PPM_NB_CHANNELS, actuators_asctec, actuators_delay_done, actuators_delay_time, ActuatorsSkiron::actuators_idx, actuators_mkk, actuators_pwm_arch_init(), actuators_skiron, ACTUATORS_SKIRON_I2C_ADDR, ActuatorsAsctec::cmd, ActuatorsAsctec::cur_addr, FALSE, FRONT, ActuatorsAsctec::i2c_trans, I2CTransDone, I2CTransSuccess, I2CTransTx, IO0DIR, IO1DIR, IO1SET, i2c_transaction::len_w, ActuatorsAsctec::nb_err, ActuatorsAsctec::new_addr, NONE, PINSEL2, PWM_ISR(), PWM_SERVO_0_ENA, PWM_SERVO_0_PINSEL, PWM_SERVO_0_PINSEL_BIT, PWM_SERVO_0_PINSEL_MASK, PWM_SERVO_0_PINSEL_VAL, PWM_SERVO_1_ENA, PWM_SERVO_1_PINSEL, PWM_SERVO_1_PINSEL_BIT, PWM_SERVO_1_PINSEL_MASK, PWM_SERVO_1_PINSEL_VAL, PWM_SERVO_2_ENA, PWM_SERVO_2_PINSEL, PWM_SERVO_2_PINSEL_BIT, PWM_SERVO_2_PINSEL_MASK, PWM_SERVO_2_PINSEL_VAL, PWM_SERVO_3_ENA, PWM_SERVO_3_PINSEL, PWM_SERVO_3_PINSEL_BIT, PWM_SERVO_3_PINSEL_MASK, PWM_SERVO_3_PINSEL_VAL, PWM_SERVO_4_ENA, PWM_SERVO_4_PINSEL, PWM_SERVO_4_PINSEL_BIT, PWM_SERVO_4_PINSEL_MASK, PWM_SERVO_4_PINSEL_VAL, PWM_SERVO_5_ENA, PWM_SERVO_5_PINSEL, PWM_SERVO_5_PINSEL_BIT, PWM_SERVO_5_PINSEL_MASK, PWM_SERVO_5_PINSEL_VAL, PWMLER, PWMLER_LATCH0, PWMLER_LATCH_SERV0, PWMLER_LATCH_SERV1, PWMMCR, PWMMCR_MR0R, PWMMCR_MRI_SERV1, PWMMR0, PWMMR_SERV0, PWMMR_SERV1, PWMPCR, PWMPCR_ENA_SERV0, PWMPCR_ENA_SERV1, PWMPR, PWMTCR, PWMTCR_COUNTER_ENABLE, PWMTCR_PWM_ENABLE, SERV0_CLOCK_PIN, SERV0_CLOCK_PINSEL, SERV0_CLOCK_PINSEL_BIT, SERV0_CLOCK_PINSEL_VAL, SERV0_DATA_PIN, SERV0_RESET_PIN, SERV1_CLOCK_PIN, SERV1_CLOCK_PINSEL, SERV1_CLOCK_PINSEL_BIT, SERV1_CLOCK_PINSEL_VAL, SERV1_DATA_PIN, SERV1_RESET_PIN, SERVO_CLOCK_PIN, SERVO_CLOCK_PINSEL, SERVO_CLOCK_PINSEL_BIT, SERVO_CLOCK_PINSEL_VAL, SERVO_DATA_PIN, SERVO_RESET_PIN, servos_4015_idx, servos_4017_idx, SERVOS_PERIOD, servos_PPM_idx, SERVOS_TICS_OF_USEC, servos_values, i2c_transaction::slave_addr, START_TIMEOUT, i2c_transaction::status, supervision_init(), SysTimeTimerStart, T0EMR, T0MCR, T0MR1, TEMR_EM1, TEMR_EMC1_1, TEMR_EMC1_2, TMCR_MR1_I, ActuatorsMkk::trans, ActuatorsSkiron::trans, TRUE, i2c_transaction::type, VIC_BIT, VIC_ENABLE, VIC_PWM, VICIntEnable, VICIntSelect, VICVectAddr3, and VICVectCntl3.
Referenced by init_fbw(), and main_init().
void actuators_set (bool_t motors_on)
Definition at line 77 of file actuators_asctec.c.
References actuators_asctec, actuators_delay_done, actuators_delay_time, ActuatorsSkiron::actuators_idx, actuators_mkk, actuators_pwm_commit(), actuators_pwm_values, actuators_skiron, ASCTEC_MAX_CMD, ASCTEC_MAX_THROTTLE, ASCTEC_MIN_CMD, ASCTEC_MIN_THROTTLE, i2c_transaction::buf, ActuatorsAsctec::cmd, ActuatorsAsctec::cmds, Supervision::commands, commands, ActuatorsAsctec::cur_addr, FALSE, i2c_submit(), ActuatorsAsctec::i2c_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, MAX_PPRZ, ActuatorsAsctec::nb_err, ActuatorsAsctec::new_addr, NONE, PITCH, REVERSE, ROLL, SET_ADDR, i2c_transaction::status, supervision, supervision_run(), SysTimeTimer, TEST, THRUST, ActuatorsMkk::trans, ActuatorsSkiron::trans, TRUE, USEC_OF_SEC, and YAW.
Referenced by main_periodic(), and main_periodic_task().