Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization.h File Reference
stabilization.h File Reference
General stabilization interface for rotorcrafts.
#include "std.h"
#include "generated/airframe.h"
#include "firmwares/rotorcraft/stabilization/stabilization_none.h"
#include "firmwares/rotorcraft/stabilization/stabilization_rate.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
Functions
void stabilization_init (void)
Variables
int32_t stabilization_cmd [COMMANDS_NB]
Stabilization commands.
Detailed Description
General stabilization interface for rotorcrafts.
Definition in file stabilization.h.
Function Documentation
void stabilization_init (void)
Definition at line 30 of file stabilization.c.
References stabilization_attitude_init(), stabilization_none_init(), and stabilization_rate_init().
Referenced by main_init().
Variable Documentation
int32_t stabilization_cmd[COMMANDS_NB]
Stabilization commands.
Contains the resulting stabilization commands, regardless of whether rate or attitude is currently used. Range -MAX_PPRZ:MAX_PPRZ
Definition at line 28 of file stabilization.c.
Referenced by autopilot_periodic(), guidance_v_run(), stabilization_attitude_run(), stabilization_none_run(), and stabilization_rate_run().