Paparazzi UAS: sw/airborne/firmwares/fixedwing/stabilization/stabilization_attitude.c File Reference
stabilization_attitude.c File Reference
#include "firmwares/fixedwing/stabilization/stabilization_attitude.h"
#include "std.h"
#include "led.h"
#include "estimator.h"
#include "subsystems/nav.h"
#include "generated/airframe.h"
#include "firmwares/fixedwing/autopilot.h"
Macros
#define H_CTL_COURSE_PRE_BANK_CORRECTION 1.
#define H_CTL_COURSE_DGAIN 0.
#define H_CTL_ROLL_RATE_GAIN 0.
Functions
static void h_ctl_roll_loop (void)
Computes h_ctl_aileron_setpoint from h_ctl_roll_setpoint.
static void h_ctl_pitch_loop (void)
void h_ctl_init (void)
void h_ctl_course_loop (void)
void h_ctl_attitude_loop (void)
Variables
float h_ctl_course_setpoint
fixed wing horizontal control
float h_ctl_course_pre_bank
float h_ctl_course_pre_bank_correction
float h_ctl_course_pgain
float h_ctl_course_dgain
float h_ctl_roll_max_setpoint
bool_t h_ctl_disabled
bool_t h_ctl_auto1_rate
float h_ctl_roll_setpoint
float h_ctl_roll_pgain
pprz_t h_ctl_aileron_setpoint
float h_ctl_roll_slew
float h_ctl_pitch_setpoint
float h_ctl_pitch_loop_setpoint
float h_ctl_pitch_pgain
float h_ctl_pitch_dgain
pprz_t h_ctl_elevator_setpoint
float h_ctl_aileron_of_throttle
float h_ctl_elevator_of_roll
float h_ctl_roll_attitude_gain
float h_ctl_roll_rate_gain
Macro Definition Documentation
#define H_CTL_COURSE_DGAIN 0.
Definition at line 105 of file stabilization_attitude.c.
Referenced by h_ctl_init().
#define H_CTL_COURSE_PRE_BANK_CORRECTION 1.
Definition at line 101 of file stabilization_attitude.c.
Referenced by h_ctl_init().
#define H_CTL_ROLL_RATE_GAIN 0.
Definition at line 109 of file stabilization_attitude.c.
Referenced by h_ctl_init().
Function Documentation
void h_ctl_attitude_loop (void)
Definition at line 309 of file stabilization_attitude.c.
References h_ctl_disabled, h_ctl_pitch_loop(), and h_ctl_roll_loop().
void h_ctl_course_loop (void)
Definition at line 180 of file stabilization_attitude.c.
References estimator_hspeed_dir, estimator_hspeed_mod, estimator_psi, h_ctl_course_dgain, h_ctl_course_pgain, h_ctl_course_pre_bank, h_ctl_course_pre_bank_correction, h_ctl_course_setpoint, h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, h_ctl_roll_slew, launch, Max, Min, v_ctl_altitude_error, V_CTL_AUTO_THROTTLE_AGRESSIVE, V_CTL_AUTO_THROTTLE_BLENDED, and v_ctl_auto_throttle_submode.
void h_ctl_init (void)
Definition at line 119 of file stabilization_attitude.c.
References airspeed_ratio2, FALSE, h_ctl_aileron_of_throttle, h_ctl_aileron_setpoint, h_ctl_course_dgain, H_CTL_COURSE_DGAIN, h_ctl_course_pgain, h_ctl_course_pre_bank, h_ctl_course_pre_bank_correction, H_CTL_COURSE_PRE_BANK_CORRECTION, h_ctl_course_setpoint, h_ctl_disabled, h_ctl_elevator_of_roll, h_ctl_elevator_setpoint, h_ctl_pitch_dgain, H_CTL_PITCH_DGAIN, h_ctl_pitch_igain, H_CTL_PITCH_IGAIN, h_ctl_pitch_Kffa, H_CTL_PITCH_KFFA, h_ctl_pitch_Kffd, H_CTL_PITCH_KFFD, h_ctl_pitch_loop_setpoint, h_ctl_pitch_of_roll, h_ctl_pitch_pgain, h_ctl_pitch_setpoint, h_ctl_pitch_sum_err, h_ctl_roll_attitude_gain, h_ctl_roll_igain, H_CTL_ROLL_IGAIN, h_ctl_roll_Kffa, H_CTL_ROLL_KFFA, h_ctl_roll_Kffd, H_CTL_ROLL_KFFD, h_ctl_roll_max_setpoint, h_ctl_roll_pgain, h_ctl_roll_rate_gain, H_CTL_ROLL_RATE_GAIN, h_ctl_roll_setpoint, h_ctl_roll_slew, h_ctl_roll_sum_err, use_airspeed_ratio, v_ctl_pitch_dash_trim, and v_ctl_pitch_loiter_trim.
static void h_ctl_pitch_loop (void) inline static
Definition at line 420 of file stabilization_attitude.c.
References estimator_AOA, estimator_phi, estimator_theta, h_ctl_elevator_of_roll, h_ctl_elevator_setpoint, h_ctl_pitch_dgain, h_ctl_pitch_loop_setpoint, h_ctl_pitch_pgain, h_ctl_pitch_setpoint, and TRIM_PPRZ.
Referenced by h_ctl_attitude_loop().
static void h_ctl_roll_loop (void) inline static
Computes h_ctl_aileron_setpoint from h_ctl_roll_setpoint.
Definition at line 335 of file stabilization_attitude.c.
References estimator_phi, h_ctl_aileron_of_throttle, h_ctl_aileron_setpoint, h_ctl_auto1_rate, h_ctl_roll_pgain, h_ctl_roll_setpoint, TRIM_PPRZ, and v_ctl_throttle_setpoint.
Referenced by h_ctl_attitude_loop().
Variable Documentation
float h_ctl_aileron_of_throttle
Definition at line 75 of file stabilization_attitude.c.
pprz_t h_ctl_aileron_setpoint
Definition at line 60 of file stabilization_attitude.c.
bool_t h_ctl_auto1_rate
Definition at line 54 of file stabilization_attitude.c.
float h_ctl_course_dgain
Definition at line 47 of file stabilization_attitude.c.
float h_ctl_course_pgain
Definition at line 46 of file stabilization_attitude.c.
float h_ctl_course_pre_bank
Definition at line 44 of file stabilization_attitude.c.
float h_ctl_course_pre_bank_correction
Definition at line 45 of file stabilization_attitude.c.
float h_ctl_course_setpoint
fixed wing horizontal control
Definition at line 43 of file stabilization_attitude.c.
bool_t h_ctl_disabled
Definition at line 51 of file stabilization_attitude.c.
float h_ctl_elevator_of_roll
Definition at line 76 of file stabilization_attitude.c.
pprz_t h_ctl_elevator_setpoint
Definition at line 68 of file stabilization_attitude.c.
float h_ctl_pitch_dgain
Definition at line 67 of file stabilization_attitude.c.
float h_ctl_pitch_loop_setpoint
Definition at line 65 of file stabilization_attitude.c.
float h_ctl_pitch_pgain
Definition at line 66 of file stabilization_attitude.c.
float h_ctl_pitch_setpoint
Definition at line 64 of file stabilization_attitude.c.
float h_ctl_roll_attitude_gain
Definition at line 112 of file stabilization_attitude.c.
float h_ctl_roll_max_setpoint
Definition at line 48 of file stabilization_attitude.c.
float h_ctl_roll_pgain
Definition at line 59 of file stabilization_attitude.c.
float h_ctl_roll_rate_gain
Definition at line 113 of file stabilization_attitude.c.
float h_ctl_roll_setpoint
Definition at line 58 of file stabilization_attitude.c.
float h_ctl_roll_slew
Definition at line 61 of file stabilization_attitude.c.