Paparazzi UAS: sw/airborne/arch/stm32/stm32_vector_table.c File Reference
stm32_vector_table.c File Reference
#include "stm32_vector_table.h"
#include <cmsis/stm32.h>
#include "stm32_exceptions.h"
Macros
#define SYS_TICK_IRQ_HANDLER null_handler
#define USART1_IRQ_HANDLER null_handler
#define USART2_IRQ_HANDLER null_handler
#define USART3_IRQ_HANDLER null_handler
#define USART5_IRQ_HANDLER null_handler
#define I2C1_EV_IRQ_HANDLER null_handler
#define I2C1_ER_IRQ_HANDLER null_handler
#define I2C2_EV_IRQ_HANDLER null_handler
#define I2C2_ER_IRQ_HANDLER null_handler
#define SPI1_IRQ_HANDLER null_handler
#define SPI2_IRQ_HANDLER null_handler
#define EXTI0_IRQ_HANDLER null_handler
#define EXTI2_IRQ_HANDLER null_handler
#define EXTI3_IRQ_HANDLER null_handler
#define EXTI4_IRQ_HANDLER null_handler
#define EXTI9_5_IRQ_HANDLER null_handler
#define EXTI15_10_IRQ_HANDLER null_handler
#define DMA1_C2_IRQ_HANDLER null_handler
#define DMA1_C4_IRQ_HANDLER null_handler
#define ADC1_2_IRQ_HANDLER null_handler
#define TIM1_UP_IRQ_HANDLER null_handler
#define TIM1_CC_IRQ_HANDLER null_handler
#define TIM2_IRQ_HANDLER null_handler
#define TIM6_IRQ_HANDLER null_handler
#define USB_HP_CAN1_TX_IRQ_HANDLER null_handler
#define USB_LP_CAN1_RX0_IRQ_HANDLER null_handler
Functions
void reset_handler_stage1 (void)
void main (void)
void reset_handler_stage2 (void)
void null_handler (void)
void assert_param (void)
Variables
unsigned long _etext
unsigned long _sidata
unsigned long _sdata
unsigned long _edata
unsigned long _sbss
unsigned long _ebss
void _estack
Macro Definition Documentation
#define ADC1_2_IRQ_HANDLER null_handler
Definition at line 159 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define DMA1_C2_IRQ_HANDLER null_handler
Definition at line 145 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define DMA1_C4_IRQ_HANDLER null_handler
Definition at line 152 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define EXTI0_IRQ_HANDLER null_handler
Definition at line 102 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define EXTI15_10_IRQ_HANDLER null_handler
Definition at line 137 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define EXTI2_IRQ_HANDLER null_handler
Definition at line 109 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define EXTI3_IRQ_HANDLER null_handler
Definition at line 116 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define EXTI4_IRQ_HANDLER null_handler
Definition at line 123 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define EXTI9_5_IRQ_HANDLER null_handler
Definition at line 130 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define I2C1_ER_IRQ_HANDLER null_handler
Definition at line 72 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define I2C1_EV_IRQ_HANDLER null_handler
Definition at line 71 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define I2C2_ER_IRQ_HANDLER null_handler
Definition at line 81 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define I2C2_EV_IRQ_HANDLER null_handler
Definition at line 80 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define SPI1_IRQ_HANDLER null_handler
Definition at line 88 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define SPI2_IRQ_HANDLER null_handler
Definition at line 95 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define SYS_TICK_IRQ_HANDLER null_handler
Definition at line 34 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define TIM1_CC_IRQ_HANDLER null_handler
Definition at line 169 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define TIM1_UP_IRQ_HANDLER null_handler
Definition at line 168 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define TIM2_IRQ_HANDLER null_handler
Definition at line 176 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define TIM6_IRQ_HANDLER null_handler
Definition at line 183 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define USART1_IRQ_HANDLER null_handler
Definition at line 41 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define USART2_IRQ_HANDLER null_handler
Definition at line 48 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define USART3_IRQ_HANDLER null_handler
Definition at line 55 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define USART5_IRQ_HANDLER null_handler
Definition at line 62 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define USB_HP_CAN1_TX_IRQ_HANDLER null_handler
Definition at line 190 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
#define USB_LP_CAN1_RX0_IRQ_HANDLER null_handler
Definition at line 197 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
Function Documentation
void assert_param (void)
Definition at line 328 of file stm32_vector_table.c.
void main (void)
Definition at line 43 of file usb_tunnel.c.
References A_PERIPH, A_RX_PIN, A_RX_PORT, A_TX_PIN, A_TX_PORT, Ap, B_RX_PIN, B_RX_PORT, B_TX_PIN, B_TX_PORT, BLINK_MIN, DEBUG_SERVO1_INIT, Delay(), Fbw, foo, handle_periodic_tasks(), init, led_init(), LED_OFF, led_off(), LED_ON, led_on(), LED_PERIODIC, main_event(), main_event_task(), main_init(), main_periodic(), main_periodic_task(), mcu_init(), mcu_int_enable, MyByteSwap16, MyByteSwap16_1, MyByteSwap32, MyByteSwap32_1, overo_link_init(), PCLK, PERIODIC_FREQUENCY, servos, sys_time_check_and_ack_timer(), sys_time_init(), sys_time_register_timer(), T0TC, VCOM_allow_linecoding(), VCOM_check_available(), VCOM_check_free_space(), VCOM_getchar(), VCOM_init(), and VCOM_putchar().
void null_handler (void)
Definition at line 319 of file stm32_vector_table.c.
Referenced by reset_handler_stage1().
void reset_handler_stage1 (void)
Definition at line 209 of file stm32_vector_table.c.
References _estack, ADC1_2_IRQ_HANDLER, bus_fault_exception(), DMA1_C2_IRQ_HANDLER, DMA1_C4_IRQ_HANDLER, EXTI0_IRQ_HANDLER, EXTI15_10_IRQ_HANDLER, EXTI2_IRQ_HANDLER, EXTI3_IRQ_HANDLER, EXTI4_IRQ_HANDLER, EXTI9_5_IRQ_HANDLER, hard_fault_exception(), I2C1_ER_IRQ_HANDLER, I2C1_EV_IRQ_HANDLER, I2C2_ER_IRQ_HANDLER, I2C2_EV_IRQ_HANDLER, mem_manage_exception(), nmi_exception(), null_handler(), SPI1_IRQ_HANDLER, SPI2_IRQ_HANDLER, SYS_TICK_IRQ_HANDLER, TIM1_CC_IRQ_HANDLER, TIM1_UP_IRQ_HANDLER, TIM2_IRQ_HANDLER, TIM6_IRQ_HANDLER, usage_fault_exception(), USART1_IRQ_HANDLER, USART2_IRQ_HANDLER, USART3_IRQ_HANDLER, USART5_IRQ_HANDLER, USB_HP_CAN1_TX_IRQ_HANDLER, and USB_LP_CAN1_RX0_IRQ_HANDLER.
void reset_handler_stage2 (void)
Definition at line 302 of file stm32_vector_table.c.
References _ebss, _edata, _sbss, _sdata, _sidata, and main().
Variable Documentation
unsigned long _ebss
Referenced by reset_handler_stage2().
unsigned long _edata
Referenced by reset_handler_stage2().
void _estack
Referenced by reset_handler_stage1().
unsigned long _etext
unsigned long _sbss
Referenced by reset_handler_stage2().
unsigned long _sdata
Referenced by reset_handler_stage2().
unsigned long _sidata
Referenced by reset_handler_stage2().