Paparazzi UAS: sw/airborne/arch/stm32/subsystems/imu/imu_aspirin_arch.h File Reference
imu_aspirin_arch.h File Reference
#include "subsystems/imu.h"
#include <stm32/gpio.h>
Functions
void imu_aspirin_arch_int_enable (void)
void imu_aspirin_arch_int_disable (void)
void adxl345_write_to_reg (uint8_t addr, uint8_t val)
void adxl345_clear_rx_buf (void)
void adxl345_start_reading_data (void)
static int imu_aspirin_eoc (void)
Function Documentation
void adxl345_clear_rx_buf (void)
Definition at line 32 of file imu_aspirin_arch.c.
References __attribute__().
Referenced by configure_accel().
void adxl345_start_reading_data (void)
Definition at line 188 of file imu_aspirin_arch.c.
References ImuAspirin::accel_rx_buf, ImuAspirin::accel_tx_buf, ADXL345_REG_DATA_X0, Adxl345Select, and imu_aspirin.
void adxl345_write_to_reg (uint8_t addr, uint8_t val)
Definition at line 20 of file imu_aspirin_arch.c.
References Adxl345Select, Adxl345Unselect, and RESET.
Referenced by configure_accel().
void imu_aspirin_arch_int_disable (void)
Definition at line 11 of file imu_aspirin_arch.c.
Referenced by imu_aspirin_event().
void imu_aspirin_arch_int_enable (void)
Definition at line 7 of file imu_aspirin_arch.c.
Referenced by imu_aspirin_event(), and imu_periodic().
static int imu_aspirin_eoc (void) inline static
Definition at line 13 of file imu_aspirin_arch.h.
Referenced by imu_aspirin_event().