Paparazzi UAS: sw/airborne/peripherals/ads1114.c File Reference
ads1114.c File Reference
#include "peripherals/ads1114.h"
Functions
void ads1114_init (void)
void ads1114_read (struct ads1114_periph *p)
Function Documentation
void ads1114_init (void)
Definition at line 37 of file ads1114.c.
References ADS1114_1_CONFIG_LSB, ADS1114_1_CONFIG_MSB, ADS1114_1_I2C_ADDR, ADS1114_2_CONFIG_LSB, ADS1114_2_CONFIG_MSB, ADS1114_2_I2C_ADDR, ADS1114_I2C_DEVICE, ADS1114_POINTER_CONFIG_REG, and I2CTransmit.
Referenced by baro_init().
void ads1114_read (struct ads1114_periph * p)
Definition at line 62 of file ads1114.c.
References ADS1114_I2C_DEVICE, ADS1114_POINTER_CONV_REG, i2c_transaction::buf, ads1114_periph::config_done, ads1114_periph::i2c_addr, I2CTransceive, I2CTransDone, i2c_transaction::status, and ads1114_periph::trans.
Referenced by airspeed_periodic(), and baro_periodic().