Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_infrared.c File Reference
ahrs_infrared.c File Reference
#include "subsystems/ahrs/ahrs_infrared.h"
#include "subsystems/sensors/infrared.h"
#include "subsystems/gps.h"
#include "estimator.h"
Functions
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_gps (void)
void ahrs_update_infrared (void)
void ahrs_update_fw_estimator (void)
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 47 of file ahrs_infrared.c.
References ahrs, AHRS_RUNNING, and Ahrs::status.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 31 of file ahrs_infrared.c.
References ahrs, ahrs_float, AHRS_UNINIT, AhrsFloat::body_rate, FLOAT_EULERS_ZERO, FLOAT_QUAT_ZERO, FLOAT_RATES_ZERO, FLOAT_RMAT_ZERO, AhrsFloat::imu_rate, AhrsFloat::ltp_to_body_euler, AhrsFloat::ltp_to_body_quat, AhrsFloat::ltp_to_body_rmat, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, and Ahrs::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 54 of file ahrs_infrared.c.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 57 of file ahrs_infrared.c.
void ahrs_update_fw_estimator (void)
Definition at line 104 of file ahrs_infrared.c.
References ahrs_float, AhrsFloat::body_rate, compute_body_orientation_and_rates(), DCM_Matrix, estimator_p, estimator_phi, estimator_psi, estimator_q, estimator_theta, FLOAT_QUAT_OF_EULERS, FLOAT_RMAT_OF_EULERS, GRAVITY, ins_pitch_neutral, ins_roll_neutral, AhrsFloat::ltp_to_body_euler, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_quat, AhrsFloat::ltp_to_imu_rmat, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatEulers::theta, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
void ahrs_update_gps (void)
Definition at line 63 of file ahrs_infrared.c.
References ahrs_float, ahrs_update_fw_estimator(), GpsState::course, gps, GpsState::gspeed, AhrsFloat::ltp_to_body_euler, FloatEulers::psi, wind_east, and wind_north.
void ahrs_update_infrared (void)
Definition at line 79 of file ahrs_infrared.c.
References ahrs_float, ahrs_update_fw_estimator(), Infrared::correction_down, Infrared::correction_left, Infrared::correction_right, Infrared::correction_up, infrared, AhrsFloat::ltp_to_body_euler, FloatEulers::phi, Infrared::pitch, Infrared::pitch_neutral, Infrared::roll, Infrared::roll_neutral, FloatEulers::theta, and Infrared::top.
Referenced by attitude_loop().
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 60 of file ahrs_infrared.c.