Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_int_cmpl.c File Reference
ahrs_int_cmpl.c File Reference
#include "subsystems/ahrs/ahrs_int_cmpl.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "subsystems/ahrs/ahrs_int_utils.h"
#include "subsystems/imu.h"
#include "math/pprz_trig_int.h"
#include "math/pprz_algebra_int.h"
#include "generated/airframe.h"
Defines
#define INT32_QUAT_INTEGRATE_FI(_q, _hr, _omega, _f)
Functions
static void ahrs_update_mag_full (void)
static void ahrs_update_mag_2d (void)
static void compute_imu_quat_and_rmat_from_euler (void)
static void compute_imu_euler_and_rmat_from_quat (void)
static void compute_body_orientation (void)
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
__attribute__ ((always_inline))
Variables
struct AhrsIntCmpl ahrs_impl
Define Documentation
#define INT32_QUAT_INTEGRATE_FI (_q, _hr, _omega, _f)
Value:
{     \
    _hr.qi += -_omega.p*_q.qx - _omega.q*_q.qy - _omega.r*_q.qz;  \
    _hr.qx +=  _omega.p*_q.qi + _omega.r*_q.qy - _omega.q*_q.qz;  \
    _hr.qy +=  _omega.q*_q.qi - _omega.r*_q.qx + _omega.p*_q.qz;  \
    _hr.qz +=  _omega.r*_q.qi + _omega.q*_q.qx - _omega.p*_q.qy;  \
                  \
    ldiv_t _div = ldiv(_hr.qi, ((1<<INT32_RATE_FRAC)*_f*2));    \
    _q.qi+= _div.quot;              \
    _hr.qi = _div.rem;              \
                  \
    _div = ldiv(_hr.qx, ((1<<INT32_RATE_FRAC)*_f*2));     \
    _q.qx+= _div.quot;              \
    _hr.qx = _div.rem;              \
                  \
    _div = ldiv(_hr.qy, ((1<<INT32_RATE_FRAC)*_f*2));     \
    _q.qy+= _div.quot;              \
    _hr.qy = _div.rem;              \
                  \
    _div = ldiv(_hr.qz, ((1<<INT32_RATE_FRAC)*_f*2));     \
    _q.qz+= _div.quot;              \
    _hr.qz = _div.rem;              \
                  \
  }
Definition at line 48 of file ahrs_int_cmpl.c.
Referenced by ahrs_propagate().
Function Documentation
__attribute__ ((always_inline))
Definition at line 291 of file ahrs_int_cmpl.c.
References ahrs, INT32_QUAT_OF_EULERS, INT32_RMAT_OF_EULERS, Ahrs::ltp_to_imu_euler, Ahrs::ltp_to_imu_quat, and Ahrs::ltp_to_imu_rmat.
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 102 of file ahrs_int_cmpl.c.
References ahrs, ahrs_aligner, ahrs_impl, ahrs_int_get_euler_from_accel_mag(), AHRS_RUNNING, compute_body_orientation(), compute_imu_quat_and_rmat_from_euler(), AhrsFloatCmplRmat::gyro_bias, INT_RATES_LSHIFT, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, Ahrs::ltp_to_imu_euler, RATES_COPY, and Ahrs::status.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 80 of file ahrs_int_cmpl.c.
References ahrs, ahrs_impl, AHRS_UNINIT, Ahrs::body_rate, Imu::body_to_imu_quat, Imu::body_to_imu_rmat, AhrsFloatCmplRmat::gyro_bias, imu, Ahrs::imu_rate, INT32_EULERS_OF_RMAT, INT32_QUAT_ZERO, INT32_RMAT_ZERO, INT_EULERS_ZERO, INT_RATES_ZERO, Ahrs::ltp_to_body_euler, Ahrs::ltp_to_body_quat, Ahrs::ltp_to_body_rmat, Ahrs::ltp_to_imu_euler, Ahrs::ltp_to_imu_quat, Ahrs::ltp_to_imu_rmat, QUAT_COPY, AhrsFloatCmplRmat::rate_correction, RMAT_COPY, and Ahrs::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 127 of file ahrs_int_cmpl.c.
References ahrs, ahrs_impl, compute_body_orientation(), compute_imu_euler_and_rmat_from_quat(), AhrsFloatCmplRmat::gyro_bias, Imu::gyro_prev, imu, Ahrs::imu_rate, INT32_QUAT_INTEGRATE_FI, INT32_QUAT_NORMALIZE, INT_RATES_ZERO, Ahrs::ltp_to_imu_quat, AhrsFloatCmplRmat::rate_correction, RATES_ADD, RATES_COPY, RATES_DIFF, RATES_SDIV, and RATES_SMUL.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 160 of file ahrs_int_cmpl.c.
References Imu::accel, ahrs, ahrs_impl, AhrsFloatCmplRmat::gyro_bias, imu, Ahrs::imu_rate, INT32_ACCEL_FRAC, INT32_RATE_FRAC, INT32_SPEED_FRAC, INT32_VECT3_CROSS_PRODUCT, INT_RATES_RSHIFT, Ahrs::ltp_to_imu_rmat, FloatRates::p, FloatRates::q, Int32Rates::q, FloatRates::r, Int32Rates::r, AhrsFloatCmplRmat::rate_correction, RMAT_ELMT, VECT3_DIFF, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 208 of file ahrs_int_cmpl.c.
References ahrs_update_mag_2d(), and ahrs_update_mag_full().
static void ahrs_update_mag_2d (void) [inline, static]
static void ahrs_update_mag_full (void) [inline, static]
static void compute_body_orientation (void) [inline, static]
Referenced by ahrs_align(), and ahrs_propagate().
static void compute_imu_euler_and_rmat_from_quat (void) [inline, static]
Referenced by ahrs_propagate().
static void compute_imu_quat_and_rmat_from_euler (void) [inline, static]
Referenced by ahrs_align().
Variable Documentation
struct AhrsIntCmpl ahrs_impl
Definition at line 74 of file ahrs_int_cmpl.c.