Paparazzi UAS: sw/airborne/firmwares/fixedwing/datalink.c File Reference
datalink.c File Reference
#include <inttypes.h>
#include <string.h>
#include "datalink.h"
#include "generated/modules.h"
#include "subsystems/navigation/common_nav.h"
#include "generated/settings.h"
#include "math/pprz_geodetic_float.h"
#include "mcu_periph/uart.h"
#include "downlink.h"
#include "ap_downlink.h"
Defines
#define DATALINK_C
#define MODULES_DATALINK_C
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
#define MOfCm(_x) (((float)(_x))/100.)
#define SenderIdOfMsg(x) (x[0])
#define IdOfMsg(x) (x[1])
Functions
void dl_parse_msg (void)
Define Documentation
#define DATALINK_C
Definition at line 28 of file datalink.c.
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 61 of file datalink.c.
#define IdOfMsg (x) (x[1])
Definition at line 70 of file datalink.c.
Referenced by dl_parse_msg().
#define MODULES_DATALINK_C
Definition at line 30 of file datalink.c.
#define MOfCm (_x) (((float)(_x))/100.)
Definition at line 67 of file datalink.c.
Referenced by dl_parse_msg().
#define SenderIdOfMsg (x) (x[0])
Definition at line 69 of file datalink.c.
Referenced by dl_parse_msg().
Function Documentation
void dl_parse_msg (void)
NAV
WIND_INFO
Else there is no dl_settings section in the flight plan
Definition at line 72 of file datalink.c.
References c, datalink_time, UtmCoor_f::east, estimator_airspeed, gps_nb_ovrn, IdOfMsg, infrared, JoystickHandeDatalink, LlaCoor_f::lat, LED_TOGGLE, LlaCoor_f::lon, MOfCm, nav_goto_block(), nav_move_waypoint(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, parse_rc_3ch_datalink(), parse_rc_4ch_datalink(), Infrared::pitch, tcas_ac_status::resolve, Infrared::roll, SEND_NAVIGATION, SenderIdOfMsg, SetAcInfo, tcas_acs_status, the_acs_id, Infrared::top, utm_of_lla_f(), val, waypoints, wind_east, wind_north, EnuCoor_i::x, EnuCoor_i::y, and UtmCoor_f::zone.