Paparazzi UAS: sw/airborne/subsystems/ins_extended.c File Reference
ins_extended.c File Reference
#include "subsystems/ins.h"
#include "subsystems/imu.h"
#include "subsystems/sensors/baro.h"
#include "subsystems/gps.h"
#include "generated/airframe.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
#include "subsystems/ahrs.h"
#include "math/pprz_geodetic_int.h"
#include "generated/flight_plan.h"
Functions
void ins_init ()
void ins_periodic (void)
void ins_realign_h (struct FloatVect2 pos __attribute__((unused)), struct FloatVect2 speed __attribute__((unused)))
void ins_realign_v (float z)
void ins_propagate ()
void ins_update_baro ()
void ins_update_gps (void)
void ins_update_sonar ()
Variables
struct LtpDef_i ins_ltp_def
bool_t ins_ltp_initialised
struct NedCoor_i ins_gps_pos_cm_ned
struct NedCoor_i ins_gps_speed_cm_s_ned
bool_t ins_hf_realign
bool_t ins_vf_realign
struct NedCoor_i ins_ltp_pos
struct NedCoor_i ins_ltp_speed
struct NedCoor_i ins_ltp_accel
struct EnuCoor_i ins_enu_pos
struct EnuCoor_i ins_enu_speed
struct EnuCoor_i ins_enu_accel
Function Documentation
void ins_init (void)
Definition at line 97 of file ins_extended.c.
References LlaCoor_i::alt, b2_hff_init(), ecef_of_lla_i(), LtpDef_i::hmsl, init_median_filter(), ins_adof, ins_ador, ins_baud, ins_enu_accel, ins_enu_pos, ins_enu_speed, ins_hf_realign, ins_init_status, ins_ltp_accel, ins_ltp_def, ins_ltp_initialised, ins_ltp_pos, ins_ltp_speed, ins_pitch_neutral, ins_roll_neutral, ins_vf_realign, INS_VN100_SET_BAUD, ins_yaw_neutral, INS_YAW_NEUTRAL_DEFAULT, INT32_RAD_OF_DEG, INT32_VECT3_ZERO, LlaCoor_i::lat, LlaCoor_i::lon, ltp_def_from_ecef_i(), SpiSetCPHA, SpiSetCPOL, and vff_init().
void ins_periodic (void)
Definition at line 139 of file ins_extended.c.
void ins_propagate (void)
Definition at line 157 of file ins_extended.c.
References Imu::accel, ACCEL_BFP_OF_REAL, ACCEL_FLOAT_OF_BFP, ahrs, b2_hff_propagate(), baro, Imu::body_to_imu_rmat, BS_RUNNING, imu, ins_enu_accel, ins_enu_pos, ins_enu_speed, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, INT32_RMAT_TRANSP_VMULT, INT32_VECT3_ENU_OF_NED, Ahrs::ltp_to_body_rmat, POS_BFP_OF_REAL, SPEED_BFP_OF_REAL, Baro::status, vff_propagate(), vff_update_offset(), vff_z, vff_zdot, vff_zdotdot, NedCoor_i::x, Int32Vect3::x, NedCoor_i::y, Int32Vect3::y, NedCoor_i::z, and Int32Vect3::z.
void ins_realign_h (struct FloatVect2 pos __attribute__(unused), struct FloatVect2 speed __attribute__(unused))
Definition at line 147 of file ins_extended.c.
void ins_realign_v (float z)
Definition at line 151 of file ins_extended.c.
References vff_realign().
void ins_update_baro (void)
Definition at line 196 of file ins_extended.c.
References Baro::absolute, ACCEL_BFP_OF_REAL, baro, BS_RUNNING, ins_enu_accel, ins_enu_pos, ins_enu_speed, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, ins_vf_realign, POS_BFP_OF_REAL, POS_FLOAT_OF_BFP, sonar_meas, SPEED_BFP_OF_REAL, Baro::status, update_median_filter(), vff_realign(), vff_update(), vff_update_baro(), vff_z, vff_zdot, vff_zdotdot, NedCoor_i::z, and EnuCoor_i::z.
void ins_update_gps (void)
Definition at line 229 of file ins_extended.c.
References LlaCoor_i::alt, b2_hff_realign(), b2_hff_update_gps(), GpsState::ecef_pos, GpsState::ecef_vel, GpsState::fix, gps, GPS_FIX_3D, GpsState::hmsl, LtpDef_i::hmsl, ins_enu_accel, ins_enu_pos, ins_enu_speed, ins_gps_pos_cm_ned, ins_gps_speed_cm_s_ned, ins_hf_realign, ins_ltp_accel, ins_ltp_def, ins_ltp_initialised, ins_ltp_pos, ins_ltp_speed, INT32_POS_OF_CM_DEN, INT32_POS_OF_CM_NUM, INT32_SPEED_OF_CM_S_DEN, INT32_SPEED_OF_CM_S_NUM, INT32_VECT2_RSHIFT, INT32_VECT2_SCALE_2, INT32_VECT3_ENU_OF_NED, LtpDef_i::lla, GpsState::lla_pos, ltp_def_from_ecef_i(), ned_of_ecef_point_i(), ned_of_ecef_vect_i(), VECT2_ADD, VECT2_ASSIGN, VECT2_COPY, VECT2_SDIV, NedCoor_i::x, NedCoor_i::y, and NedCoor_i::z.
void ins_update_sonar (void)
Definition at line 288 of file ins_extended.c.
References Baro::absolute, baro, BS_RUNNING, POS_BFP_OF_REAL, sonar_meas, stabilization_cmd, Baro::status, update_median_filter(), vff_offset, vff_update_alt_conf(), and vff_update_offset().
Variable Documentation
struct EnuCoor_i ins_enu_accel
Definition at line 94 of file ins_extended.c.
struct EnuCoor_i ins_enu_pos
Definition at line 92 of file ins_extended.c.
struct EnuCoor_i ins_enu_speed
Definition at line 93 of file ins_extended.c.
struct NedCoor_i ins_gps_pos_cm_ned
Definition at line 59 of file ins_extended.c.
struct NedCoor_i ins_gps_speed_cm_s_ned
Definition at line 60 of file ins_extended.c.
bool_t ins_hf_realign
Definition at line 66 of file ins_extended.c.
struct NedCoor_i ins_ltp_accel
Definition at line 91 of file ins_extended.c.
struct LtpDef_i ins_ltp_def
Definition at line 57 of file ins_extended.c.
bool_t ins_ltp_initialised
Definition at line 58 of file ins_extended.c.
struct NedCoor_i ins_ltp_pos
Definition at line 89 of file ins_extended.c.
struct NedCoor_i ins_ltp_speed
Definition at line 90 of file ins_extended.c.
bool_t ins_vf_realign
Definition at line 86 of file ins_extended.c.