Paparazzi UAS: sw/airborne/arch/sim/jsbsim_transport.c File Reference
jsbsim_transport.c File Reference
#include "jsbsim_hw.h"
#include "math/pprz_geodetic_float.h"
#include <stdlib.h>
Defines
#define MOfCm(_x) (((float)(_x))/100.)
Functions
void parse_dl_ping (char *argv[] __attribute__((unused)))
void parse_dl_acinfo (char *argv[] __attribute__((unused)))
void parse_dl_setting (char *argv[])
void parse_dl_get_setting (char *argv[])
void parse_dl_block (char *argv[])
void parse_dl_move_wp (char *argv[])
Define Documentation
#define MOfCm (_x) (((float)(_x))/100.)
Definition at line 9 of file jsbsim_transport.c.
Referenced by parse_dl_acinfo(), and parse_dl_move_wp().
Function Documentation
void parse_dl_acinfo (char *argv[] __attribute__(unused))
Definition at line 15 of file jsbsim_transport.c.
References c, MOfCm, and SetAcInfo.
void parse_dl_block (char * argv[])
Definition at line 42 of file jsbsim_transport.c.
References nav_goto_block().
void parse_dl_get_setting (char * argv[])
Definition at line 36 of file jsbsim_transport.c.
References DefaultChannel, and DefaultDevice.
void parse_dl_move_wp (char * argv[])
Definition at line 47 of file jsbsim_transport.c.
References DefaultChannel, DefaultDevice, UtmCoor_f::east, LlaCoor_f::lat, LlaCoor_f::lon, MOfCm, nav_move_waypoint(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, utm_of_lla_f(), waypoints, EnuCoor_i::x, EnuCoor_i::y, and UtmCoor_f::zone.
void parse_dl_ping (char *argv[] __attribute__(unused))
Definition at line 11 of file jsbsim_transport.c.
References DefaultChannel, and DefaultDevice.
void parse_dl_setting (char * argv[])
Definition at line 29 of file jsbsim_transport.c.
References DefaultChannel, and DefaultDevice.