Paparazzi UAS: sw/airborne/arch/sim/jsbsim_ir.c File Reference
jsbsim_ir.c File Reference
#include "jsbsim_hw.h"
#include <math.h>
#include "estimator.h"
Defines
#define JSBSIM_IR_ROLL_NEUTRAL 0.
Regroup functions to simulate autopilot/infrared.c.
#define JSBSIM_IR_PITCH_NEUTRAL 0.
Functions
void set_ir (double roll __attribute__((unused)), double pitch __attribute__((unused)))
void ir_gain_calib (void)
void adc_buf_channel (uint8_t adc_channel __attribute__((unused)), struct adc_buf *s __attribute__((unused)), uint8_t av_nb_sample __attribute__((unused)))
Required by infrared.c:ir_init()
Define Documentation
#define JSBSIM_IR_PITCH_NEUTRAL 0.
Definition at line 16 of file jsbsim_ir.c.
Referenced by set_ir().
#define JSBSIM_IR_ROLL_NEUTRAL 0.
Regroup functions to simulate autopilot/infrared.c.
Infrared soft simulation.
Definition at line 13 of file jsbsim_ir.c.
Referenced by set_ir().
Function Documentation
void adc_buf_channel (uint8_t adc_channel __attribute__(unused), struct adc_buf *s __attribute__(unused), uint8_t av_nb_sample __attribute__(unused))
Required by infrared.c:ir_init()
Definition at line 35 of file jsbsim_ir.c.
Referenced by adc_generic_init(), agl_vf_init(), airspeed_adc_init(), AOA_adc_init(), baro_init(), electrical_init(), enose_init(), gyro_init(), humid_hih_init(), imu_impl_init(), infrared_adc_init(), light_solar_init(), light_temt_init(), maxbotix_init(), and temp_tcouple_adc_init().
void ir_gain_calib (void)
Definition at line 32 of file jsbsim_ir.c.
void set_ir (double roll __attribute__(unused), double pitch __attribute__(unused))
Definition at line 19 of file jsbsim_ir.c.
References infrared, JSBSIM_IR_PITCH_NEUTRAL, JSBSIM_IR_ROLL_NEUTRAL, Infrared::pitch, Infrared::roll, and Infrared::top.