Paparazzi UAS: sw/airborne/lisa/lisa_overo_link.h File Reference
lisa_overo_link.h File Reference
#include <inttypes.h>
#include "fms/fms_autopilot_msg.h"
#include "lisa_overo_link_arch.h"
Data Structures
struct LisaOveroLink
Defines
#define OVERO_LINK_TIMEOUT 10
#define OveroLinkPeriodic(_timeout_handler)
Enumerations
enum LisaOveroLinkStatus { IDLE, BUSY, DATA_AVAILABLE, LOST }
Functions
void overo_link_init (void)
void overo_link_periodic (void)
void overo_link_arch_init (void)
void overo_link_arch_prepare_next_transfert (void)
Variables
struct LisaOveroLink overo_link
Define Documentation
#define OVERO_LINK_TIMEOUT 10
Definition at line 10 of file lisa_overo_link.h.
Referenced by overo_link_init().
#define OveroLinkPeriodic (_timeout_handler)
Value:
{       \
    if (overo_link.timeout_cnt < OVERO_LINK_TIMEOUT)      \
      overo_link.timeout_cnt++;           \
    else {                \
      __disable_irq();              \
      if (overo_link.status != LOST && overo_link.status != DATA_AVAILABLE ) { \
  overo_link.status = LOST;         \
  __enable_irq();             \
  LED_OFF(OVERO_LINK_LED_OK);         \
  LED_ON(OVERO_LINK_LED_KO);          \
  _timeout_handler();           \
      }                 \
      __enable_irq();             \
    }                 \
  }
Definition at line 59 of file lisa_overo_link.h.
Referenced by vi_impl_periodic().
Enumeration Type Documentation
enum LisaOveroLinkStatus
Enumerator:
IDLE
BUSY
DATA_AVAILABLE
LOST
Definition at line 8 of file lisa_overo_link.h.
Function Documentation
void overo_link_arch_init (void)
Definition at line 12 of file lisa_overo_link_arch.c.
References overo_link_arch_prepare_next_transfert(), and SPI1.
Referenced by overo_link_init().
void overo_link_arch_prepare_next_transfert (void)
Definition at line 57 of file lisa_overo_link_arch.c.
References __attribute__(), LisaOveroLink::array, LisaOveroLink::down, foo, overo_link, SPI1, and LisaOveroLink::up.
Referenced by overo_link_arch_init().
void overo_link_init (void)
Definition at line 5 of file lisa_overo_link.c.
References LisaOveroLink::crc_err_cnt, LisaOveroLink::crc_error, IDLE, LisaOveroLink::msg_cnt, overo_link, overo_link_arch_init(), OVERO_LINK_TIMEOUT, LisaOveroLink::status, LisaOveroLink::timeout, and LisaOveroLink::timeout_cnt.
Referenced by main(), and vi_impl_init().
void overo_link_periodic (void)
Variable Documentation
struct LisaOveroLink overo_link
Definition at line 3 of file lisa_overo_link.c.
Referenced by dma1_c2_irq_handler(), on_gyro_accel_event(), on_overo_link_msg_received(), overo_link_arch_prepare_next_transfert(), overo_link_init(), and vi_overo_link_on_msg_received().