Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_fbw.c File Reference
main_fbw.c File Reference
FBW (FlyByWire) process.
#include "generated/airframe.h"
#include "firmwares/fixedwing/main_fbw.h"
#include "mcu.h"
#include "sys_time.h"
#include "commands.h"
#include "firmwares/fixedwing/actuators.h"
#include "subsystems/electrical.h"
#include "subsystems/radio_control.h"
#include "firmwares/fixedwing/autopilot.h"
#include "fbw_downlink.h"
#include "paparazzi.h"
#include "inter_mcu.h"
Functions
void init_fbw (void)
static void set_failsafe_mode (void)
void event_task_fbw (void)
void periodic_task_fbw (void)
Variables
uint8_t fbw_mode
volatile uint8_t fbw_new_actuators = 0
Detailed Description
FBW (FlyByWire) process.
This process is responsible for decoding radio control, generating actuators signals either from the radio control or from the commands provided by the AP (autopilot) process. It also performs a telemetry task and a low level monitoring (for parameters like the supply)
Definition in file main_fbw.c.
Function Documentation
void event_task_fbw (void)
Definition at line 111 of file main_fbw.c.
Referenced by sim_periodic_task().
void init_fbw (void)
Definition at line 60 of file main_fbw.c.
Referenced by sim_init().
void periodic_task_fbw (void)
Definition at line 180 of file main_fbw.c.
Referenced by sim_periodic_task().
static void set_failsafe_mode (void) [inline, static]
Definition at line 90 of file main_fbw.c.
References commands_failsafe, fbw_mode, FBW_MODE_FAILSAFE, fbw_new_actuators, and SetCommands.
Referenced by periodic_task_fbw().
Variable Documentation
uint8_t fbw_mode
Definition at line 51 of file main_fbw.c.
Referenced by event_task_fbw(), init_fbw(), periodic_task_fbw(), and set_failsafe_mode().
volatile uint8_t fbw_new_actuators = 0
Definition at line 56 of file main_fbw.c.
Referenced by event_task_fbw(), init_fbw(), and set_failsafe_mode().