Paparazzi UAS: sw/airborne/mcu.c File Reference
mcu.c File Reference
#include "mcu.h"
Functions
void mcu_init (void)
Function Documentation
void mcu_init (void)
Definition at line 57 of file mcu.c.
References adc_init(), dac_init(), led_init(), mcu_arch_init(), spi_init(), sys_time_init(), and VCOM_init().
Referenced by init_fbw(), main(), and main_init().