Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/quat_setpoint.c File Reference
quat_setpoint.c File Reference
Quaternion setpoint generation.
#include "subsystems/ahrs.h"
#include "stabilization/stabilization_attitude_ref_quat_int.h"
#include "stabilization/quat_setpoint.h"
#include "stabilization.h"
#include "messages.h"
#include "mcu_periph/uart.h"
#include "downlink.h"
Defines
#define QUAT_SETPOINT_HOVER_PITCH RadOfDeg(90)
Functions
static void reset_sp_quat (int32_t _psi, int32_t _theta, struct Int32Quat *initial)
static void update_sp_quat_from_eulers (void)
void stabilization_attitude_read_rc_absolute (struct Int32Eulers sp, bool_t in_flight)
void stabilization_attitude_sp_enter ()
void quat_setpoint_enter_absolute ()
Detailed Description
Quaternion setpoint generation.
Definition in file quat_setpoint.c.
Define Documentation
#define QUAT_SETPOINT_HOVER_PITCH RadOfDeg(90)
Definition at line 22 of file quat_setpoint.c.
Referenced by reset_sp_quat().
Function Documentation
void quat_setpoint_enter_absolute (void)
Definition at line 155 of file quat_setpoint.c.
References ahrs, Ahrs::ltp_to_body_quat, and reset_sp_quat().
Referenced by stabilization_attitude_sp_enter().
static void reset_sp_quat (int32_t _psi, int32_t _theta, struct Int32Quat * initial) [static]
Definition at line 25 of file quat_setpoint.c.
References ANGLE_BFP_OF_REAL, INT32_EULERS_OF_QUAT, INT32_QUAT_COMP_NORM_SHORTEST, INT32_QUAT_OF_AXIS_ANGLE, INT32_QUAT_OF_EULERS, Int32Eulers::phi, QUAT_COPY, QUAT_SETPOINT_HOVER_PITCH, stab_att_sp_quat, and Int32Eulers::theta.
Referenced by quat_setpoint_enter_absolute(), and stabilization_attitude_read_rc_absolute().
void stabilization_attitude_read_rc_absolute (struct Int32Eulers sp, bool_t in_flight)
Definition at line 111 of file quat_setpoint.c.
References ahrs, APPLY_DEADBAND, INT32_EULERS_OF_QUAT, INT32_QUAT_COMP_NORM_SHORTEST, INT32_QUAT_OF_EULERS, Ahrs::ltp_to_body_quat, Int32Eulers::phi, PITCH_COEF, Int32Eulers::psi, QUAT_COPY, radio_control, RADIO_PITCH, RADIO_ROLL, RADIO_YAW, RATE_BFP_OF_REAL, RC_UPDATE_FREQ, reset_sp_quat(), ROLL_COEF, stab_att_sp_euler, stab_att_sp_quat, Int32Eulers::theta, and YAW_COEF.
void stabilization_attitude_sp_enter (void)
Definition at line 149 of file quat_setpoint.c.
References quat_setpoint_enter_absolute().
Referenced by stabilization_attitude_ref_enter().
static void update_sp_quat_from_eulers (void) [static]
Definition at line 58 of file quat_setpoint.c.
References INT32_QUAT_OF_RMAT, INT32_QUAT_WRAP_SHORTEST, INT32_RMAT_OF_EULERS_312, INT32_RMAT_OF_EULERS_321, stab_att_sp_euler, and stab_att_sp_quat.