Paparazzi UAS: sw/airborne/subsystems/settings.h File Reference
settings.h File Reference
#include "std.h"
#include "generated/settings.h"
Defines
#define settings_StoreSettings(_v) { settings_store_now = _v; settings_store(); }
Functions
void settings_init (void)
void settings_store (void)
int32_t persistent_write (uint32_t ptr, uint32_t size)
int32_t persistent_read (uint32_t ptr, uint32_t size)
Variables
bool_t settings_store_now
Define Documentation
#define settings_StoreSettings (_v) { settings_store_now = _v; settings_store(); }
Definition at line 11 of file settings.h.
Function Documentation
int32_t persistent_read (uint32_t ptr, uint32_t size)
Definition at line 255 of file settings_arch.c.
References FlashInfo::addr, FCHK, flash_detect(), FSIZ, FlashInfo::page_size, and pflash_checksum().
Referenced by settings_init().
int32_t persistent_write (uint32_t ptr, uint32_t size)
Definition at line 243 of file settings_arch.c.
References flash_detect(), FSIZ, FlashInfo::page_size, pflash_checksum(), and pflash_program_bytes().
Referenced by settings_store().
void settings_init (void)
Definition at line 8 of file settings.c.
References pers_settings, and persistent_read().
Referenced by init_ap(), and main_init().
void settings_store (void)
Definition at line 17 of file settings.c.
References pers_settings, and persistent_write().
Variable Documentation
bool_t settings_store_now
Definition at line 5 of file settings.c.