Paparazzi UAS: sw/airborne/subsystems/settings.c File Reference
settings.c File Reference
#include "subsystems/settings.h"
Functions
void settings_init (void)
void settings_store (void)
Variables
struct PersistentSettings pers_settings
bool_t settings_store_now
Function Documentation
void settings_init (void)
Definition at line 8 of file settings.c.
References pers_settings, and persistent_read().
Referenced by init_ap(), and main_init().
void settings_store (void)
Definition at line 17 of file settings.c.
References pers_settings, and persistent_write().
Variable Documentation
struct PersistentSettings pers_settings
Definition at line 4 of file settings.c.
Referenced by settings_init(), and settings_store().
bool_t settings_store_now
Definition at line 5 of file settings.c.