Paparazzi UAS: sw/airborne/modules/digital_cam/sim_i2c_cam_ctrl.c File Reference
sim_i2c_cam_ctrl.c File Reference
Simulated Interface with digital camera.
#include "atmega_i2c_cam_ctrl.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
#include "estimator.h"
Defines
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void atmega_i2c_cam_ctrl_init (void)
void atmega_i2c_cam_ctrl_periodic (void)
void atmega_i2c_cam_ctrl_send (uint8_t cmd)
void atmega_i2c_cam_ctrl_event (void)
Detailed Description
Simulated Interface with digital camera.
Definition in file sim_i2c_cam_ctrl.c.
Define Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 34 of file sim_i2c_cam_ctrl.c.
Function Documentation
void atmega_i2c_cam_ctrl_event (void)
Definition at line 87 of file sim_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_trans, i2c_transaction::buf, DefaultChannel, DefaultDevice, I2CTransDone, I2CTransSuccess, and i2c_transaction::status.
void atmega_i2c_cam_ctrl_init (void)
Definition at line 42 of file sim_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_trans, dc_init(), I2CTransDone, and i2c_transaction::status.
void atmega_i2c_cam_ctrl_periodic (void)
Definition at line 47 of file sim_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_just_sent_command, atmega_i2c_cam_ctrl_send(), DC_GET_STATUS, dc_periodic_4Hz(), and dc_send_command().
void atmega_i2c_cam_ctrl_send (uint8_t cmd)
Definition at line 57 of file sim_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_just_sent_command, atmega_i2c_cam_ctrl_trans, ATMEGA_I2C_DEV, ATMEGA_SLAVE_ADDR, i2c_transaction::buf, DC_GET_STATUS, dc_send_shot_position, DC_SHOOT, DC_TALLER, DC_WIDER, DefaultChannel, DefaultDevice, and I2CTransceive.