Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_none.c File Reference
stabilization_none.c File Reference
Dummy stabilization for rotorcrafts.
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/stabilization/stabilization_none.h"
#include "subsystems/radio_control.h"
#include "generated/airframe.h"
Functions
void stabilization_none_init (void)
void stabilization_none_read_rc (void)
void stabilization_none_enter (void)
void stabilization_none_run (bool_t in_flight __attribute__((unused)))
Variables
struct Int32Rates stabilization_none_rc_cmd
Detailed Description
Dummy stabilization for rotorcrafts.
Doesn't actually do any stabilization, just directly passes the RC commands along.
Definition in file stabilization_none.c.
Function Documentation
void stabilization_none_enter (void)
Definition at line 48 of file stabilization_none.c.
References INT_RATES_ZERO, and stabilization_none_rc_cmd.
Referenced by guidance_h_mode_changed().
void stabilization_none_init (void)
Definition at line 37 of file stabilization_none.c.
References INT_RATES_ZERO, and stabilization_none_rc_cmd.
Referenced by stabilization_init().
void stabilization_none_read_rc (void)
Definition at line 41 of file stabilization_none.c.
References Int32Rates::p, Int32Rates::q, Int32Rates::r, radio_control, RADIO_PITCH, RADIO_ROLL, RADIO_YAW, and stabilization_none_rc_cmd.
Referenced by guidance_h_read_rc().
void stabilization_none_run (bool_t in_flight __attribute__(unused))
Definition at line 52 of file stabilization_none.c.
References Int32Rates::p, Int32Rates::q, Int32Rates::r, stabilization_cmd, and stabilization_none_rc_cmd.
Referenced by guidance_h_run().
Variable Documentation
struct Int32Rates stabilization_none_rc_cmd
Definition at line 35 of file stabilization_none.c.
Referenced by stabilization_none_enter(), stabilization_none_init(), stabilization_none_read_rc(), and stabilization_none_run().