Paparazzi UAS: sw/airborne/arch/stm32/subsystems/imu/imu_aspirin_arch.c File Reference
imu_aspirin_arch.c File Reference
#include "subsystems/imu.h"
#include <libopencm3/stm32/f1/gpio.h>
#include <libopencm3/stm32/f1/rcc.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/spi.h>
#include <libopencm3/stm32/f1/dma.h>
#include <libopencm3/stm32/nvic.h>
#include "mcu_periph/i2c.h"
Defines
#define Adxl345Unselect() GPIOB_BSRR = GPIO12
#define Adxl345Select() GPIOB_BRR = GPIO12
Functions
void exti15_10_isr (void)
void exti9_5_isr (void)
void exti2_isr (void)
void dma1_channel4_isr (void)
void dma1_c4_irq_handler (void)
void imu_aspirin_arch_int_enable (void)
void imu_aspirin_arch_int_disable (void)
void imu_aspirin_arch_init (void)
void adxl345_write_to_reg (uint8_t addr, uint8_t val)
void adxl345_clear_rx_buf (void)
void adxl345_start_reading_data (void)
Define Documentation
#define Adxl345Select () GPIOB_BRR = GPIO12
Definition at line 22 of file imu_aspirin_arch.c.
Referenced by adxl345_start_reading_data(), and adxl345_write_to_reg().
#define Adxl345Unselect () GPIOB_BSRR = GPIO12
Definition at line 21 of file imu_aspirin_arch.c.
Referenced by adxl345_write_to_reg(), and imu_aspirin_arch_init().
Function Documentation
void adxl345_clear_rx_buf (void)
Definition at line 144 of file imu_aspirin_arch.c.
References __attribute__().
void adxl345_start_reading_data (void)
Definition at line 148 of file imu_aspirin_arch.c.
References ImuAspirin::accel_rx_buf, ImuAspirin::accel_tx_buf, ADXL345_REG_DATA_X0, Adxl345Select, and imu_aspirin.
Referenced by configure_accel().
void adxl345_write_to_reg (uint8_t addr, uint8_t val)
Definition at line 132 of file imu_aspirin_arch.c.
References Adxl345Select, Adxl345Unselect, and val.
void dma1_c4_irq_handler (void)
Definition at line 75 of file imu_aspirin_arch.c.
References ImuAspirin::accel_available, and imu_aspirin.
Referenced by ADS8344_read_channel().
void dma1_channel4_isr (void)
void exti15_10_isr (void)
Definition at line 199 of file imu_aspirin_arch.c.
References AspirinStatusReadingGyro, imu_aspirin, and ImuAspirin::status.
void exti2_isr (void)
Definition at line 81 of file max1168_arch.c.
void exti9_5_isr (void)
Definition at line 55 of file hmc5843_arch.c.
void imu_aspirin_arch_init (void)
Definition at line 54 of file imu_aspirin_arch.c.
References Adxl345Unselect.
void imu_aspirin_arch_int_disable (void)
Definition at line 42 of file imu_aspirin_arch.c.
void imu_aspirin_arch_int_enable (void)
Definition at line 26 of file imu_aspirin_arch.c.