Paparazzi UAS: sw/airborne/arch/stm32/subsystems/settings_arch.c File Reference
settings_arch.c File Reference
#include "subsystems/settings.h"
#include <libopencm3/stm32/f1/flash.h>
#include <libopencm3/stm32/crc.h>
#include <libopencm3/stm32/dbgmcu.h>
Data Structures
struct FlashInfo
Defines
#define FLASH_SIZE_ MMIO16(0x1FFFF7E0)
#define FLASH_BEGIN 0x08000000
#define FSIZ 8
#define FCHK 4
Functions
static uint32_t pflash_checksum (uint32_t ptr, uint32_t size)
static int32_t flash_detect (struct FlashInfo *flash)
static int32_t pflash_program_bytes (struct FlashInfo *flash, uint32_t src, uint32_t size, uint32_t chksum)
int32_t persistent_write (uint32_t ptr, uint32_t size)
int32_t persistent_read (uint32_t ptr, uint32_t size)
Define Documentation
#define FCHK 4
Definition at line 62 of file settings_arch.c.
Referenced by persistent_read(), and pflash_program_bytes().
#define FLASH_BEGIN 0x08000000
Definition at line 60 of file settings_arch.c.
Referenced by flash_detect().
#define FLASH_SIZE_ MMIO16(0x1FFFF7E0)
Definition at line 58 of file settings_arch.c.
Referenced by flash_detect().
#define FSIZ 8
Definition at line 61 of file settings_arch.c.
Referenced by persistent_read(), persistent_write(), and pflash_program_bytes().
Function Documentation
static int32_t flash_detect (struct FlashInfo * flash) [static]
Definition at line 107 of file settings_arch.c.
References FlashInfo::addr, FLASH_BEGIN, FLASH_SIZE_, FlashInfo::page_nr, FlashInfo::page_size, and FlashInfo::total_size.
Referenced by persistent_read(), and persistent_write().
int32_t persistent_read (uint32_t ptr, uint32_t size)
Definition at line 250 of file settings_arch.c.
References FlashInfo::addr, FCHK, flash_detect(), FSIZ, FlashInfo::page_size, and pflash_checksum().
int32_t persistent_write (uint32_t ptr, uint32_t size)
Definition at line 239 of file settings_arch.c.
References flash_detect(), FSIZ, FlashInfo::page_size, pflash_checksum(), and pflash_program_bytes().
static uint32_t pflash_checksum (uint32_t ptr, uint32_t size) [static]
Definition at line 65 of file settings_arch.c.
Referenced by persistent_read(), and persistent_write().
static int32_t pflash_program_bytes (struct FlashInfo * flash, uint32_t src, uint32_t size, uint32_t chksum) [static]
Definition at line 191 of file settings_arch.c.
References FlashInfo::addr, FCHK, FSIZ, and FlashInfo::page_size.
Referenced by persistent_write().