Paparazzi UAS: sw/airborne/subsystems/navigation/traffic_info.c File Reference
traffic_info.c File Reference
Informations relative to the other aircrafts.
#include <inttypes.h>
#include "subsystems/navigation/traffic_info.h"
#include "generated/airframe.h"
Functions
void traffic_info_init (void)
struct ac_info_ * get_ac_info (uint8_t id)
Variables
uint8_t acs_idx
uint8_t the_acs_id [NB_ACS_ID]
struct ac_info_ the_acs [NB_ACS]
Detailed Description
Informations relative to the other aircrafts.
Definition in file traffic_info.c.
Function Documentation
struct ac_info_* get_ac_info (uint8_t id) [read]
Definition at line 44 of file traffic_info.c.
References the_acs, and the_acs_id.
Referenced by cam_ac_target(), formation_flight(), nav_follow(), potential_task(), tcas_periodic_task_4Hz(), and tcas_test_direction().
void traffic_info_init (void)
Definition at line 37 of file traffic_info.c.
References ac_info_::ac_id, acs_idx, the_acs, and the_acs_id.
Referenced by init_ap().
Variable Documentation
uint8_t acs_idx
Definition at line 33 of file traffic_info.c.
Referenced by traffic_info_init().
struct ac_info_ the_acs[NB_ACS]
Definition at line 35 of file traffic_info.c.
Referenced by formation_flight(), get_ac_info(), potential_task(), tcas_periodic_task_1Hz(), and traffic_info_init().
uint8_t the_acs_id[NB_ACS_ID]
Definition at line 34 of file traffic_info.c.
Referenced by add_slot(), dl_parse_msg(), formation_flight(), formation_pre_call(), get_ac_info(), tcas_periodic_task_1Hz(), and traffic_info_init().