Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_float_cmpl.h File Reference
ahrs_float_cmpl.h File Reference
#include "std.h"
Data Structures
struct AhrsFloatCmplRmat
Functions
void ahrs_update_heading (float heading)
Update yaw based on a heading measurement.
void ahrs_realign_heading (float heading)
Hard reset yaw to a heading.
Variables
struct AhrsFloatCmplRmat ahrs_impl
Function Documentation
void ahrs_realign_heading (float heading)
Hard reset yaw to a heading.
Doesn't affect the bias. Sets ahrs_impl.heading_aligned to TRUE.
Parameters:
heading Heading in body frame, radians (CW/north)
Definition at line 375 of file ahrs_float_cmpl.c.
References ahrs_float, ahrs_impl, AHRS_IMU_INT_OF_FLOAT, AHRS_INT_OF_FLOAT, AhrsFloatCmplRmat::body_to_imu_quat, compute_imu_rmat_and_euler_from_quat(), FLOAT_ANGLE_NORMALIZE, FLOAT_EULERS_OF_RMAT, FLOAT_QUAT_COMP, FLOAT_QUAT_COMP_NORM_SHORTEST, FLOAT_QUAT_INV_COMP_NORM_SHORTEST, FLOAT_QUAT_NORMALIZE, FLOAT_RMAT_OF_QUAT, AhrsFloatCmplRmat::heading_aligned, AhrsFloat::ltp_to_body_euler, AhrsFloat::ltp_to_body_quat, AhrsFloat::ltp_to_body_rmat, AhrsFloat::ltp_to_imu_quat, FloatQuat::qi, QUAT_COPY, FloatQuat::qx, FloatQuat::qy, and FloatQuat::qz.
Referenced by ahrs_update_gps().
void ahrs_update_heading (float heading)
Update yaw based on a heading measurement.
e.g. from GPS course
Parameters:
heading Heading in body frame, radians (CW/north)
Definition at line 338 of file ahrs_float_cmpl.c.
References ahrs_float, ahrs_impl, FLOAT_ANGLE_NORMALIZE, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, AhrsFloatCmplRmat::gyro_bias, AhrsFloat::ltp_to_body_rmat, AhrsFloat::ltp_to_imu_rmat, AhrsFloatCmplRmat::rate_correction, RMAT_ELMT, FloatVect2::x, FloatVect2::y, and FloatVect3::z.
Referenced by ahrs_update_gps().
Variable Documentation
struct AhrsFloatCmplRmat ahrs_impl
Definition at line 62 of file ahrs_float_cmpl.c.