Paparazzi UAS: sw/airborne/peripherals/hmc5843.c File Reference
hmc5843.c File Reference
#include "peripherals/hmc5843.h"
#include "mcu_periph/i2c.h"
#include "led.h"
Defines
#define HMC5843_TIMEOUT 100
#define bswap_16(x) ((((x) & 0xFF00) >> 8) | (((x) & 0x00FF) << 8))
#define HMC5843_I2C_DEVICE i2c2
Functions
void exti9_5_irq_handler (void)
void hmc5843_init (void)
static void send_config (void)
void hmc5843_idle_task (void)
void hmc5843_periodic (void)
Variables
struct Hmc5843 hmc5843
Define Documentation
#define bswap_16 (x) ((((x) & 0xFF00) >> 8) | (((x) & 0x00FF) << 8))
Definition at line 7 of file hmc5843.c.
Referenced by hmc5843_idle_task().
#define HMC5843_I2C_DEVICE i2c2
Definition at line 13 of file hmc5843.c.
Referenced by hmc5843_idle_task(), hmc5843_periodic(), and send_config().
#define HMC5843_TIMEOUT 100
Definition at line 5 of file hmc5843.c.
Referenced by hmc5843_periodic().
Function Documentation
void exti9_5_irq_handler (void)
Definition at line 66 of file hmc5843_arch.c.
References RESET.
void hmc5843_idle_task (void)
Definition at line 60 of file hmc5843.c.
References bswap_16, Hmc5843::buf, i2c_transaction::buf, Hmc5843::data, Hmc5843::data_available, hmc5843, HMC5843_I2C_DEVICE, i2c_idle(), i2c_submit(), Hmc5843::i2c_trans, I2CIdle, I2CTransFailed, I2CTransPending, I2CTransRunning, I2CTransRx, I2CTransSuccess, I2CTransTx, Hmc5843::initialized, i2c_transaction::len_r, i2c_transaction::len_w, mag_eoc(), Hmc5843::sent_rx, Hmc5843::sent_tx, i2c_transaction::status, Hmc5843::timeout, i2c_transaction::type, and Hmc5843::value.
Referenced by hmc5843_module_event().
void hmc5843_init (void)
Definition at line 16 of file hmc5843.c.
References hmc5843, HMC5843_ADDR, hmc5843_arch_init(), Hmc5843::i2c_trans, I2CTransSuccess, i2c_transaction::slave_addr, and i2c_transaction::status.
Referenced by hmc5843_module_init(), and imu_impl_init().
void hmc5843_periodic (void)
Definition at line 103 of file hmc5843.c.
References i2c_transaction::buf, hmc5843, hmc5843_arch_reset(), HMC5843_I2C_DEVICE, HMC5843_TIMEOUT, i2c_idle(), i2c_submit(), Hmc5843::i2c_trans, I2CIdle, I2CTransPending, I2CTransRunning, I2CTransRx, I2CTransTx, Hmc5843::initialized, i2c_transaction::len_r, i2c_transaction::len_w, send_config(), i2c_transaction::status, Hmc5843::timeout, and i2c_transaction::type.
Referenced by hmc5843_module_periodic(), and imu_periodic().
static void send_config (void) [static]
Definition at line 27 of file hmc5843.c.
References i2c_transaction::buf, hmc5843, HMC5843_I2C_DEVICE, HMC5843_REG_CFGA, HMC5843_REG_CFGB, HMC5843_REG_MODE, i2c_submit(), Hmc5843::i2c_trans, I2CTransPending, I2CTransTx, i2c_transaction::len_w, i2c_transaction::status, and i2c_transaction::type.
Referenced by hmc5843_periodic().
Variable Documentation
struct Hmc5843 hmc5843
Definition at line 9 of file hmc5843.c.
Referenced by hmc5843_idle_task(), hmc5843_init(), hmc5843_module_periodic(), hmc5843_periodic(), and send_config().