Paparazzi UAS: sw/airborne/subsystems/imu/imu_aspirin.h File Reference
imu_aspirin.h File Reference
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "mcu_periph/i2c.h"
#include "peripherals/itg3200.h"
#include "peripherals/hmc5843.h"
#include "peripherals/adxl345.h"
#include "subsystems/imu/imu_aspirin_arch.h"
Data Structures
struct ImuAspirin
Defines
#define IMU_GYRO_P_SIGN 1
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN 1
#define IMU_ACCEL_X_SIGN 1
#define IMU_ACCEL_Y_SIGN 1
#define IMU_ACCEL_Z_SIGN 1
#define IMU_GYRO_P_SENS 4.359
default gyro sensitivy and neutral from the datasheet IMU-3000 has 16.4 LSB/(deg/s) at 2000deg/s range sens = 1/16.4 * pi/180 * 2^INT32_RATE_FRAC sens = 1/16.4 * pi/180 * 4096 = 4.359066229
#define IMU_GYRO_P_SENS_NUM 4359
#define IMU_GYRO_P_SENS_DEN 1000
#define IMU_GYRO_Q_SENS 4.359
#define IMU_GYRO_Q_SENS_NUM 4359
#define IMU_GYRO_Q_SENS_DEN 1000
#define IMU_GYRO_R_SENS 4.359
#define IMU_GYRO_R_SENS_NUM 4359
#define IMU_GYRO_R_SENS_DEN 1000
#define IMU_ACCEL_X_SENS 37.91
default accel sensitivy from the ADXL345 datasheet sensitivity of x & y axes depends on supply voltage:
#define IMU_ACCEL_X_SENS_NUM 3791
#define IMU_ACCEL_X_SENS_DEN 100
#define IMU_ACCEL_Y_SENS 37.91
#define IMU_ACCEL_Y_SENS_NUM 3791
#define IMU_ACCEL_Y_SENS_DEN 100
#define IMU_ACCEL_Z_SENS 39.24
#define IMU_ACCEL_Z_SENS_NUM 3924
#define IMU_ACCEL_Z_SENS_DEN 100
#define ASPIRIN_GYRO_TIMEOUT 3
#define ASPIRIN_ACCEL_TIMEOUT 3
#define foo_handler() {}
#define ImuMagEvent(_mag_handler)
#define ImuEvent(_gyro_handler, _accel_handler, _mag_handler)
Enumerations
enum AspirinStatus { AspirinStatusUninit, AspirinStatusIdle, AspirinStatusReadingGyro, AspirinStatusReadingMag }
Functions
void imu_aspirin_arch_init (void)
static void gyro_read_i2c (void)
static void gyro_copy_i2c (void)
static void accel_copy_spi (void)
static void imu_aspirin_event (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Variables
struct ImuAspirin imu_aspirin
Define Documentation
#define ASPIRIN_ACCEL_TIMEOUT 3
Definition at line 133 of file imu_aspirin.h.
Referenced by imu_periodic().
#define ASPIRIN_GYRO_TIMEOUT 3
Definition at line 132 of file imu_aspirin.h.
Referenced by imu_aspirin_event().
#define foo_handler () {}
Definition at line 135 of file imu_aspirin.h.
#define IMU_ACCEL_X_SENS 37.91
default accel sensitivy from the ADXL345 datasheet sensitivity of x & y axes depends on supply voltage:
256 LSB/g @ 2.5V
265 LSB/g @ 3.3V z sensitivity stays at 256 LSB/g fixed point sens: 9.81 [m/s^2] / 256 [LSB/g] * 2^INT32_ACCEL_FRAC x/y sens = 9.81 / 265 * 1024 = 37.91 z sens = 9.81 / 256 * 1024 = 39.24
what about the offset at 3.3V?
Definition at line 98 of file imu_aspirin.h.
#define IMU_ACCEL_X_SENS_DEN 100
Definition at line 100 of file imu_aspirin.h.
#define IMU_ACCEL_X_SENS_NUM 3791
Definition at line 99 of file imu_aspirin.h.
#define IMU_ACCEL_X_SIGN 1
Definition at line 63 of file imu_aspirin.h.
#define IMU_ACCEL_Y_SENS 37.91
Definition at line 101 of file imu_aspirin.h.
#define IMU_ACCEL_Y_SENS_DEN 100
Definition at line 103 of file imu_aspirin.h.
#define IMU_ACCEL_Y_SENS_NUM 3791
Definition at line 102 of file imu_aspirin.h.
#define IMU_ACCEL_Y_SIGN 1
Definition at line 64 of file imu_aspirin.h.
#define IMU_ACCEL_Z_SENS 39.24
Definition at line 104 of file imu_aspirin.h.
#define IMU_ACCEL_Z_SENS_DEN 100
Definition at line 106 of file imu_aspirin.h.
#define IMU_ACCEL_Z_SENS_NUM 3924
Definition at line 105 of file imu_aspirin.h.
#define IMU_ACCEL_Z_SIGN 1
Definition at line 65 of file imu_aspirin.h.
#define IMU_GYRO_P_SENS 4.359
default gyro sensitivy and neutral from the datasheet IMU-3000 has 16.4 LSB/(deg/s) at 2000deg/s range sens = 1/16.4 * pi/180 * 2^INT32_RATE_FRAC sens = 1/16.4 * pi/180 * 4096 = 4.359066229
Definition at line 74 of file imu_aspirin.h.
#define IMU_GYRO_P_SENS_DEN 1000
Definition at line 76 of file imu_aspirin.h.
#define IMU_GYRO_P_SENS_NUM 4359
Definition at line 75 of file imu_aspirin.h.
#define IMU_GYRO_P_SIGN 1
Definition at line 58 of file imu_aspirin.h.
#define IMU_GYRO_Q_SENS 4.359
Definition at line 77 of file imu_aspirin.h.
#define IMU_GYRO_Q_SENS_DEN 1000
Definition at line 79 of file imu_aspirin.h.
#define IMU_GYRO_Q_SENS_NUM 4359
Definition at line 78 of file imu_aspirin.h.
#define IMU_GYRO_Q_SIGN 1
Definition at line 59 of file imu_aspirin.h.
#define IMU_GYRO_R_SENS 4.359
Definition at line 80 of file imu_aspirin.h.
#define IMU_GYRO_R_SENS_DEN 1000
Definition at line 82 of file imu_aspirin.h.
#define IMU_GYRO_R_SENS_NUM 4359
Definition at line 81 of file imu_aspirin.h.
#define IMU_GYRO_R_SIGN 1
Definition at line 60 of file imu_aspirin.h.
#define ImuEvent (_gyro_handler, _accel_handler, _mag_handler)
Value:
do {    \
  imu_aspirin_event(_gyro_handler, _accel_handler, _mag_handler); \
} while(0);
Definition at line 237 of file imu_aspirin.h.
#define ImuMagEvent (_mag_handler)
Value:
{         \
      MagEvent(foo_handler); \
    if (hmc5843.data_available) {     \
      imu.mag_unscaled.x = hmc5843.data.value[IMU_MAG_X_CHAN];    \
      imu.mag_unscaled.y = hmc5843.data.value[IMU_MAG_Y_CHAN];    \
      imu.mag_unscaled.z = hmc5843.data.value[IMU_MAG_Z_CHAN];    \
      _mag_handler();             \
      hmc5843.data_available = FALSE;   \
    }                 \
}
Definition at line 136 of file imu_aspirin.h.
Referenced by imu_aspirin_event().
Enumeration Type Documentation
enum AspirinStatus
Enumerator:
AspirinStatusUninit
AspirinStatusIdle
AspirinStatusReadingGyro
AspirinStatusReadingMag
Definition at line 110 of file imu_aspirin.h.
Function Documentation
static void accel_copy_spi (void) [inline, static]
Definition at line 170 of file imu_aspirin.h.
References ImuAspirin::accel_rx_buf, Imu::accel_unscaled, imu, imu_aspirin, and VECT3_ASSIGN.
Referenced by imu_aspirin_event().
static void gyro_copy_i2c (void) [inline, static]
Definition at line 162 of file imu_aspirin.h.
References i2c_transaction::buf, Imu::gyro_unscaled, ImuAspirin::i2c_trans_gyro, imu, imu_aspirin, and RATES_ASSIGN.
Referenced by imu_aspirin_event().
static void gyro_read_i2c (void) [inline, static]
Definition at line 152 of file imu_aspirin.h.
References i2c_transaction::buf, i2c_submit(), ImuAspirin::i2c_trans_gyro, I2CTransTxRx, imu_aspirin, ITG3200_REG_GYRO_XOUT_H, i2c_transaction::len_r, i2c_transaction::len_w, ImuAspirin::reading_gyro, and i2c_transaction::type.
Referenced by imu_aspirin_event().
void imu_aspirin_arch_init (void)
Definition at line 15 of file imu_aspirin_arch.c.
References Adxl345Unselect.
Referenced by imu_impl_init().
static void imu_aspirin_event (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) [inline, static]
Definition at line 179 of file imu_aspirin.h.
References ImuAspirin::accel_available, accel_copy_spi(), ASPIRIN_GYRO_TIMEOUT, AspirinStatusUninit, ImuAspirin::gyro_available_blaaa, gyro_copy_i2c(), gyro_read_i2c(), i2c2_er_irq_handler, i2c_idle(), ImuAspirin::i2c_trans_gyro, I2CIdle, I2CTransPending, I2CTransRunning, I2CTransSuccess, imu_aspirin, imu_aspirin_arch_int_disable, imu_aspirin_arch_int_enable, imu_aspirin_eoc(), ImuMagEvent, ImuAspirin::reading_gyro, i2c_transaction::status, ImuAspirin::status, ImuAspirin::time_since_last_accel_reading, and ImuAspirin::time_since_last_reading.
Variable Documentation
struct ImuAspirin imu_aspirin
Definition at line 6 of file imu_aspirin.c.
Referenced by accel_copy_spi(), adxl345_start_reading_data(), dma1_c4_irq_handler(), exti15_10_irq_handler(), gyro_copy_i2c(), gyro_read_i2c(), imu_aspirin_event(), imu_impl_init(), and imu_periodic().