Paparazzi UAS: sw/airborne/subsystems/radio_control/joby.c File Reference
joby.c File Reference
#include "stdio.h"
#include "subsystems/radio_control.h"
Functions
static void handle_channel (void(*callback)(void))
static void handle_tuple (void(*callback)(void))
void rc_joby_parse (int8_t c, void(*callback)(void))
void radio_control_impl_init (void)
Variables
static struct rc_joby_parser_state parser
static const int16_t rc_joby_signs [RADIO_CONTROL_NB_CHANNEL] = RC_JOBY_SIGNS
Function Documentation
static void handle_channel (void(*)(void) callback) [static]
Definition at line 31 of file joby.c.
References rc_joby_parser_state::current_byte, rc_joby_parser_state::current_channel, rc_joby_parser_state::current_inverted, parser, rc_joby_parser_state::parser_normal_buf, radio_control, RADIO_CONTROL_NB_CHANNEL, RC_JOBY_MAGIC_START, rc_joby_signs, READING_HIGH_BYTE, and READING_NORMAL.
Referenced by handle_tuple().
static void handle_tuple (void(*)(void) callback) [static]
Definition at line 56 of file joby.c.
References rc_joby_parser_state::current_byte, rc_joby_parser_state::current_channel, rc_joby_parser_state::current_inverted, rc_joby_parser_state::error_counter, handle_channel(), rc_joby_parser_state::high_byte_buf, rc_joby_parser_state::low_byte_buf, parser, rc_joby_parser_state::parser_inverted_buf, rc_joby_parser_state::parser_normal_buf, READING_HIGH_BYTE, READING_INVERTED, and READING_NORMAL.
Referenced by rc_joby_parse().
void radio_control_impl_init (void)
Definition at line 91 of file joby.c.
References rc_joby_parser_state::current_byte, rc_joby_parser_state::current_channel, rc_joby_parser_state::current_inverted, parser, READING_HIGH_BYTE, and READING_NORMAL.
void rc_joby_parse (int8_t c, void(*)(void) callback)
Definition at line 76 of file joby.c.
References c, rc_joby_parser_state::current_byte, rc_joby_parser_state::current_channel, rc_joby_parser_state::current_inverted, handle_tuple(), rc_joby_parser_state::high_byte_buf, rc_joby_parser_state::low_byte_buf, parser, RC_JOBY_MAGIC_START, READING_HIGH_BYTE, READING_INVERTED, and READING_LOW_BYTE.
Variable Documentation
struct rc_joby_parser_state parser [static]
Definition at line 27 of file joby.c.
Referenced by handle_channel(), handle_tuple(), radio_control_impl_init(), and rc_joby_parse().
const int16_t rc_joby_signs[RADIO_CONTROL_NB_CHANNEL] = RC_JOBY_SIGNS [static]
Definition at line 28 of file joby.c.
Referenced by handle_channel().