Paparazzi UAS: sw/airborne/lisa/arch/stm32/lisa_overo_link_arch.c File Reference
lisa_overo_link_arch.c File Reference
#include "lisa/lisa_overo_link.h"
#include <stm32/rcc.h>
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/spi.h>
#include <stm32/dma.h>
Functions
void dma1_c2_irq_handler (void)
void overo_link_arch_init (void)
void overo_link_arch_prepare_next_transfert (void)
Function Documentation
void dma1_c2_irq_handler (void)
Definition at line 123 of file lisa_overo_link_arch.c.
References DATA_AVAILABLE, overo_link, and LisaOveroLink::status.
void overo_link_arch_init (void)
Definition at line 12 of file lisa_overo_link_arch.c.
References overo_link_arch_prepare_next_transfert(), and SPI1.
Referenced by overo_link_init().
void overo_link_arch_prepare_next_transfert (void)
Definition at line 57 of file lisa_overo_link_arch.c.
References __attribute__(), LisaOveroLink::array, LisaOveroLink::down, foo, overo_link, SPI1, and LisaOveroLink::up.
Referenced by overo_link_arch_init().