Paparazzi UAS: sw/airborne/lisa/test_servos.c File Reference
test_servos.c File Reference
#include <inttypes.h>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "firmwares/rotorcraft/actuators/actuators_pwm.h"
#include "led.h"
Functions
static void main_init (void)
static void main_periodic (void)
int main (void)
Function Documentation
int main (void)
Definition at line 34 of file test_servos.c.
References main_init(), main_periodic(), and sys_time_check_and_ack_timer().
static void main_init (void) [inline, static]
static void main_periodic (void) [inline, static]