Paparazzi UAS: sw/airborne/lisa/test/test_board.c File Reference
test_board.c File Reference
#include <inttypes.h>
#include <string.h>
#include "test_board.h"
#include "std.h"
#include "mcu.h"
#include "mcu_periph/uart.h"
#include "sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "led.h"
#include "subsystems/datalink/datalink.h"
#include "generated/settings.h"
#include "lisa/lisa_baro.h"
#include "actuators/actuators_pwm.h"
Data Structures
struct TestFuns
Defines
#define DATALINK_C
#define IdOfMsg(x) (x[1])
Enumerations
enum UartTestType { OneToThree, ThreeToOne }
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void test_none_start (void)
static void test_none_periodic (void)
static void test_none_event (void)
static void test_baro_start (void)
static void test_baro_periodic (void)
static void test_baro_event (void)
static void test_bldc_start (void)
static void test_bldc_periodic (void)
static void test_bldc_event (void)
static void test_srvo_start (void)
static void test_srvo_periodic (void)
static void test_srvo_event (void)
static void test_uart_start (void)
static void test_uart_periodic (void)
static void test_uart_event (void)
static void all_led_green (void)
static void all_led_red (void)
static void all_led_off (void)
int main (void)
void start_test (void)
static void test_baro_on_baro_diff (void)
static void test_baro_on_baro_abs (void)
void dl_parse_msg (void)
Variables
struct TestFuns tests []
enum TestType cur_test
static const uint8_t buf_src [] = { 42, 43, 44, 45, 46, 122, 126, 128 }
static uint8_t buf_dest [sizeof(buf_src)]
static uint8_t idx_tx
static uint8_t idx_rx
static enum UartTestType direction
Define Documentation
#define DATALINK_C
Definition at line 27 of file test_board.c.
#define IdOfMsg (x) (x[1])
Definition at line 324 of file test_board.c.
Referenced by dl_parse_msg().
Enumeration Type Documentation
enum UartTestType
Enumerator:
OneToThree
ThreeToOne
Definition at line 232 of file test_board.c.
Function Documentation
static void all_led_green (void) [static]
Definition at line 303 of file test_board.c.
References LED_OFF, and LED_ON.
Referenced by test_baro_start(), and test_uart_event().
static void all_led_off (void) [static]
Definition at line 313 of file test_board.c.
References LED_OFF.
Referenced by start_test().
static void all_led_red (void) [static]
Definition at line 308 of file test_board.c.
References LED_OFF, and LED_ON.
Referenced by test_uart_event().
void dl_parse_msg (void)
NAV
WIND_INFO
Else there is no dl_settings section in the flight plan
Definition at line 326 of file test_board.c.
References DefaultChannel, DefaultDevice, and IdOfMsg.
int main (void)
Definition at line 89 of file test_board.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 122 of file test_board.c.
References TestFuns::_event, cur_test, and DatalinkEvent.
Referenced by main().
static void main_init (void) [inline, static]
static void main_periodic_task (void) [inline, static]
Definition at line 113 of file test_board.c.
References TestFuns::_periodic, cur_test, DefaultChannel, DefaultDevice, and LED_PERIODIC.
Referenced by main().
void start_test (void)
Definition at line 130 of file test_board.c.
References TestFuns::_start, all_led_off(), and cur_test.
static void test_baro_event (void) [static]
Definition at line 171 of file test_board.c.
References BaroEvent, test_baro_on_baro_abs(), and test_baro_on_baro_diff().
static void test_baro_on_baro_abs (void) [inline, static]
Definition at line 172 of file test_board.c.
References baro, DefaultChannel, and DefaultDevice.
Referenced by test_baro_event().
static void test_baro_on_baro_diff (void) [inline, static]
Definition at line 175 of file test_board.c.
References baro, DefaultChannel, and DefaultDevice.
Referenced by test_baro_event().
static void test_baro_periodic (void) [static]
Definition at line 156 of file test_board.c.
References baro_periodic(), DefaultChannel, and DefaultDevice.
static void test_baro_start (void) [static]
Definition at line 155 of file test_board.c.
References all_led_green().
static void test_bldc_event (void) [static]
Definition at line 206 of file test_board.c.
static void test_bldc_periodic (void) [static]
Definition at line 187 of file test_board.c.
References DefaultChannel, and DefaultDevice.
static void test_bldc_start (void) [static]
Definition at line 186 of file test_board.c.
static void test_none_event (void) [static]
Definition at line 145 of file test_board.c.
static void test_none_periodic (void) [static]
Definition at line 144 of file test_board.c.
static void test_none_start (void) [static]
Definition at line 143 of file test_board.c.
static void test_srvo_event (void) [static]
Definition at line 223 of file test_board.c.
static void test_srvo_periodic (void) [static]
Definition at line 215 of file test_board.c.
References actuators_pwm_commit(), actuators_pwm_values, and foo.
static void test_srvo_start (void) [static]
Definition at line 214 of file test_board.c.
static void test_uart_event (void) [static]
Definition at line 258 of file test_board.c.
References all_led_green(), all_led_red(), buf_dest, buf_src, DefaultChannel, DefaultDevice, direction, idx_rx, idx_tx, and ThreeToOne.
static void test_uart_periodic (void) [static]
Definition at line 245 of file test_board.c.
References buf_src, direction, idx_tx, OneToThree, and ThreeToOne.
static void test_uart_start (void) [static]
Definition at line 239 of file test_board.c.
References direction, idx_rx, idx_tx, and OneToThree.
Variable Documentation
uint8_t buf_dest[sizeof(buf_src)] [static]
Definition at line 234 of file test_board.c.
Referenced by test_uart_event().
const uint8_t buf_src[] = { 42, 43, 44, 45, 46, 122, 126, 128 } [static]
Definition at line 233 of file test_board.c.
Referenced by test_uart_event(), and test_uart_periodic().
enum TestType cur_test
Definition at line 86 of file test_board.c.
Referenced by main_event_task(), main_periodic_task(), and start_test().
enum UartTestType direction [static]
Definition at line 237 of file test_board.c.
Referenced by test_uart_event(), test_uart_periodic(), and test_uart_start().
uint8_t idx_rx [static]
Definition at line 236 of file test_board.c.
Referenced by test_uart_event(), and test_uart_start().
uint8_t idx_tx [static]
Definition at line 235 of file test_board.c.
Referenced by test_uart_event(), test_uart_periodic(), and test_uart_start().
struct TestFuns tests[]
Initial value:
 {
  {._start=test_none_start, ._periodic=test_none_periodic, ._event=test_none_event},
  {._start=test_baro_start, ._periodic=test_baro_periodic, ._event=test_baro_event},
  {._start=test_bldc_start, ._periodic=test_bldc_periodic, ._event=test_bldc_event},
  {._start=test_srvo_start, ._periodic=test_srvo_periodic, ._event=test_srvo_event},
  {._start=test_uart_start, ._periodic=test_uart_periodic, ._event=test_uart_event}
}
Definition at line 78 of file test_board.c.