Paparazzi UAS: sw/airborne/lisa/test_uart_lisam.c File Reference
test_uart_lisam.c File Reference
#include <stm32/rcc.h>
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include "mcu.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
Functions
static void main_init (void)
static void main_periodic (void)
int main (void)
Function Documentation
int main (void)
Definition at line 39 of file test_uart_lisam.c.
References main_init(), main_periodic(), and sys_time_check_and_ack_timer().
static void main_init (void) [inline, static]
static void main_periodic (void) [inline, static]