Paparazzi UAS: sw/airborne/modules/vehicle_interface/vi_overo_link.c File Reference
vi_overo_link.c File Reference
#include "modules/vehicle_interface/vi_overo_link.h"
#include "lisa/lisa_overo_link.h"
#include "subsystems/imu.h"
#include "subsystems/gps.h"
#include "subsystems/sensors/baro.h"
#include <string.h>
Functions
static void on_overo_link_lost (void)
void vi_impl_init (void)
void vi_impl_periodic (void)
void vi_impl_set_enabled (bool_t enabled __attribute__((unused)))
void vi_overo_link_on_msg_received (void)
void vi_overo_link_on_crc_err (void)
void vi_notify_imu_available (void)
void vi_notify_gps_available (void)
void vi_notify_mag_available (void)
void vi_notify_baro_abs_available (void)
Function Documentation
static void on_overo_link_lost (void) [inline, static]
Definition at line 49 of file vi_overo_link.c.
Referenced by vi_impl_periodic().
void vi_impl_init (void)
Definition at line 36 of file vi_overo_link.c.
References VehicleInterface::available_sensors, overo_link_init(), and vi.
Referenced by vi_init().
void vi_impl_periodic (void)
Definition at line 41 of file vi_overo_link.c.
References on_overo_link_lost(), and OveroLinkPeriodic.
Referenced by vi_periodic().
void vi_impl_set_enabled (bool_t enabled __attribute__(unused))
Definition at line 45 of file vi_overo_link.c.
void vi_notify_baro_abs_available (void)
Definition at line 97 of file vi_overo_link.c.
References VehicleInterface::available_sensors, and vi.
Referenced by on_baro_abs_event().
void vi_notify_gps_available (void)
Definition at line 89 of file vi_overo_link.c.
References VehicleInterface::available_sensors, and vi.
Referenced by on_gps_event().
void vi_notify_imu_available (void)
Definition at line 85 of file vi_overo_link.c.
References VehicleInterface::available_sensors, and vi.
Referenced by on_gyro_event().
void vi_notify_mag_available (void)
Definition at line 93 of file vi_overo_link.c.
References VehicleInterface::available_sensors, and vi.
Referenced by on_mag_event().
void vi_overo_link_on_crc_err (void)
Definition at line 79 of file vi_overo_link.c.
void vi_overo_link_on_msg_received (void)
Definition at line 53 of file vi_overo_link.c.
References Baro::absolute, Imu::accel, VehicleInterface::available_sensors, baro, GpsState::ecef_pos, GpsState::ecef_vel, gps, Imu::gyro, imu, Imu::mag, LisaOveroLink::msg, overo_link, RATES_COPY, LisaOveroLink::up, VECT3_COPY, and vi.