Paparazzi UAS: sw/airborne/firmwares/rotorcraft/actuators/arch/stm32/actuators_pwm_arch.h File Reference
actuators_pwm_arch.h File Reference
Defines
#define ACTUATORS_PWM_NB 6
#define ChopServo(_x, _a, _b) Chop(_x, _a, _b)
#define Actuator(_x) actuators_pwm_values[_x]
#define SERVOS_TICS_OF_USEC(_v) (_v)
Functions
void actuators_pwm_arch_init (void)
void actuators_pwm_commit (void)
Define Documentation
#define Actuator (_x) actuators_pwm_values[_x]
Definition at line 42 of file actuators_pwm_arch.h.
#define ACTUATORS_PWM_NB 6
Definition at line 35 of file actuators_pwm_arch.h.
#define ChopServo (_x, _a, _b) Chop(_x, _a, _b)
Definition at line 41 of file actuators_pwm_arch.h.
#define SERVOS_TICS_OF_USEC (_v) (_v)
Definition at line 43 of file actuators_pwm_arch.h.
Function Documentation
void actuators_pwm_arch_init (void)
Definition at line 58 of file actuators_pwm_arch.c.
References ONE_MHZ_CLK, PCLK, PWM5_OC, PWM5_Pin, PWM6_OC, PWM_5AND6_GPIO, PWM_5AND6_RCC, PWM_5AND6_TIMER, TIM_OC_INIT, and TIM_OC_PRELOADCONFIG.
Referenced by actuators_init().
void actuators_pwm_commit (void)
Definition at line 166 of file actuators_pwm_arch.c.
References actuators_pwm_values, PWM5_OC, PWM6_OC, and TIM_SETCOMPARE.
Referenced by actuators_set(), main_periodic(), on_overo_link_msg_received(), and test_srvo_periodic().