Paparazzi UAV: sw/airborne/firmwares/rotorcraft/actuators/actuators_pwm_supervision.c File Reference
actuators_pwm_supervision.c File Reference
#include "firmwares/rotorcraft/actuators.h"
#include "firmwares/rotorcraft/commands.h"
#include "actuators_pwm_supervision.h"
#include "subsystems/radio_control.h"
#include "firmwares/rotorcraft/actuators/actuators_pwm.h"
#include "generated/airframe.h"
Defines
#define actuators actuators_pwm_values
#define Actuator(_x) actuators_pwm_values[_x]
#define ActuatorsCommit() do { } while(0);
#define PWM_GAIN_SCALE 2
#define PWM_OFF 1000
Functions
void actuators_init (void)
void actuators_set (bool_t motors_on)
Variables
int32_t actuators_pwm_values [ACTUATORS_PWM_NB]
Define Documentation
#define Actuator (_x) actuators_pwm_values[_x]
Definition at line 35 of file actuators_pwm_supervision.c.
#define actuators actuators_pwm_values
Definition at line 34 of file actuators_pwm_supervision.c.
#define ActuatorsCommit (void) do { } while(0);
Definition at line 36 of file actuators_pwm_supervision.c.
#define PWM_GAIN_SCALE 2
Definition at line 46 of file actuators_pwm_supervision.c.
Referenced by actuators_set().
#define PWM_OFF 1000
Definition at line 47 of file actuators_pwm_supervision.c.
Referenced by actuators_set().
Function Documentation
void actuators_init (void)
Definition at line 40 of file actuators_pwm_supervision.c.
References actuators_pwm_arch_init(), and supervision_init().
void actuators_set (bool_t motors_on)
Definition at line 49 of file actuators_pwm_supervision.c.
References actuators_pwm_commit(), actuators_pwm_values, Supervision::commands, commands, FALSE, MAX_PPRZ, PWM_GAIN_SCALE, PWM_OFF, supervision, SUPERVISION_MAX_MOTOR, SUPERVISION_MIN_MOTOR, and supervision_run().
Variable Documentation
int32_t actuators_pwm_values[ACTUATORS_PWM_NB]
Definition at line 38 of file actuators_pwm_supervision.c.