Paparazzi UAV: sw/airborne/subsystems/ahrs/ahrs_float_cmpl_rmat.c File Reference
ahrs_float_cmpl_rmat.c File Reference
#include "subsystems/ahrs.h"
#include "subsystems/ahrs/ahrs_float_cmpl_rmat.h"
#include "subsystems/ahrs/ahrs_float_utils.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "subsystems/imu.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_simple_matrix.h"
#include "generated/airframe.h"
#include "../../test/pprz_algebra_print.h"
Functions
void ahrs_update_mag_full (void)
void ahrs_update_mag_2d (void)
void ahrs_update_mag_2d_dumb (void)
static void compute_imu_quat_and_euler_from_rmat (void)
static void compute_imu_rmat_and_euler_from_quat (void)
static void compute_body_orientation_and_rates (void)
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_mag_full_2d_dumb (void)
Variables
struct AhrsFloatCmplRmat ahrs_impl
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 71 of file ahrs_float_cmpl_rmat.c.
Referenced by on_gyro_accel_event(), and on_gyro_event().
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 46 of file ahrs_float_cmpl_rmat.c.
Referenced by init_ap(), and main_init().
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 91 of file ahrs_float_cmpl_rmat.c.
Referenced by on_gyro_accel_event(), and on_gyro_event().
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 127 of file ahrs_float_cmpl_rmat.c.
Referenced by ahrs_update(), on_accel_event(), and on_gyro_accel_event().
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 166 of file ahrs_float_cmpl_rmat.c.
Referenced by ahrs_update(), and on_mag_event().
static void ahrs_update_mag_2d (void) [inline]
Definition at line 198 of file ahrs_float_cmpl_rmat.c.
References ahrs_float, AHRS_H_X, AHRS_H_Y, ahrs_impl, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, FLOAT_RMAT_VECT3_TRANSP_MUL, AhrsFloatCmplRmat::gyro_bias, imu, AhrsFloat::ltp_to_imu_rmat, Imu::mag, MAGS_FLOAT_OF_BFP, AhrsFloatCmplRmat::rate_correction, FloatVect2::x, FloatVect3::x, FloatVect3::y, and FloatVect2::y.
Referenced by ahrs_update_mag().
void ahrs_update_mag_2d_dumb (void)
static void ahrs_update_mag_full (void) [inline]
Definition at line 175 of file ahrs_float_cmpl_rmat.c.
References ahrs_float, AHRS_H_X, AHRS_H_Y, ahrs_impl, FLOAT_RATES_ADD_SCALED_VECT, FLOAT_RMAT_VECT3_MUL, FLOAT_VECT3_CROSS_PRODUCT, AhrsFloatCmplRmat::gyro_bias, imu, AhrsFloat::ltp_to_imu_rmat, Imu::mag, MAGS_FLOAT_OF_BFP, and AhrsFloatCmplRmat::rate_correction.
Referenced by ahrs_update_mag().
void ahrs_update_mag_full_2d_dumb (void)
Definition at line 226 of file ahrs_float_cmpl_rmat.c.
References ahrs_float, ahrs_impl, FLOAT_RATES_ADD_SCALED_VECT, AhrsFloatCmplRmat::gyro_bias, imu, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_rmat, Imu::mag, MAGS_FLOAT_OF_BFP, FloatEulers::phi, AhrsFloatCmplRmat::rate_correction, RMAT_ELMT, FloatEulers::theta, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
static void compute_body_orientation_and_rates (void) [inline, static]
Definition at line 273 of file ahrs_float_cmpl_rmat.c.
References ahrs_float, ahrs_impl, AhrsFloat::body_rate, AhrsFloatCmplRmat::body_to_imu_quat, AhrsFloatCmplRmat::body_to_imu_rmat, FLOAT_EULERS_OF_RMAT, FLOAT_QUAT_COMP_INV, FLOAT_RMAT_COMP_INV, FLOAT_RMAT_TRANSP_RATEMULT, AhrsFloat::imu_rate, AhrsFloat::ltp_to_body_euler, AhrsFloat::ltp_to_body_quat, AhrsFloat::ltp_to_body_rmat, AhrsFloat::ltp_to_imu_quat, and AhrsFloat::ltp_to_imu_rmat.
Referenced by ahrs_align(), ahrs_propagate(), and ahrs_update_fw_estimator().
static void compute_imu_quat_and_euler_from_rmat (void) [inline, static]
Definition at line 257 of file ahrs_float_cmpl_rmat.c.
References ahrs_float, FLOAT_EULERS_OF_RMAT, FLOAT_QUAT_OF_RMAT, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_quat, and AhrsFloat::ltp_to_imu_rmat.
Referenced by ahrs_propagate().
static void compute_imu_rmat_and_euler_from_quat (void) [inline, static]
Definition at line 263 of file ahrs_float_cmpl_rmat.c.
References ahrs_float, FLOAT_EULERS_OF_RMAT, FLOAT_RMAT_OF_QUAT, AhrsFloat::ltp_to_imu_euler, AhrsFloat::ltp_to_imu_quat, and AhrsFloat::ltp_to_imu_rmat.
Referenced by ahrs_propagate().
Variable Documentation
struct AhrsFloatCmplRmat ahrs_impl
Definition at line 44 of file ahrs_float_cmpl_rmat.c.
Referenced by ahrs_align(), ahrs_init(), ahrs_propagate(), ahrs_update_accel(), ahrs_update_mag(), ahrs_update_mag_2d(), ahrs_update_mag_full(), ahrs_update_mag_full_2d_dumb(), compute_body_orientation_and_rates(), and Normalize().