Paparazzi UAV: sw/airborne/modules/digital_cam/atmega_i2c_cam_ctrl.h File Reference
atmega_i2c_cam_ctrl.h File Reference
#include "dc.h"
Defines
#define ParseCameraCommand()
Functions
void atmega_i2c_cam_ctrl_init (void)
void atmega_i2c_cam_ctrl_periodic (void)
void atmega_i2c_cam_ctrl_event (void)
void atmega_i2c_cam_ctrl_send (uint8_t cmd)
static void dc_send_command (uint8_t cmd)
Define Documentation
#define ParseCameraCommand ()
Value:
{                 \
  {                     \
    if ( DL_PAYLOAD_COMMAND_command_length(dl_buffer) == 1){        \
      dc_send_command(DL_PAYLOAD_COMMAND_command(dl_buffer)[0]);      \
    }                     \
  }                       \
}
Definition at line 42 of file atmega_i2c_cam_ctrl.h.
Function Documentation
void atmega_i2c_cam_ctrl_event (void)
Definition at line 92 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_trans, i2c_transaction::buf, DefaultChannel, I2CTransDone, I2CTransSuccess, and i2c_transaction::status.
void atmega_i2c_cam_ctrl_init (void)
Definition at line 58 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_trans, dc_init(), I2CTransDone, and i2c_transaction::status.
void atmega_i2c_cam_ctrl_periodic (void)
Definition at line 64 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_just_sent_command, atmega_i2c_cam_ctrl_send(), DC_GET_STATUS, dc_periodic_4Hz(), and dc_send_command().
void atmega_i2c_cam_ctrl_send (uint8_t cmd)
Definition at line 78 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_just_sent_command, atmega_i2c_cam_ctrl_trans, ATMEGA_I2C_DEV, ATMEGA_SLAVE_ADDR, i2c_transaction::buf, DC_GET_STATUS, dc_send_shot_position, DC_SHOOT, DC_TALLER, DC_WIDER, DefaultChannel, and I2CTransceive.
Referenced by atmega_i2c_cam_ctrl_periodic(), and dc_send_command().
static void dc_send_command (uint8_t cmd) [inline, static]
Definition at line 36 of file atmega_i2c_cam_ctrl.h.
References atmega_i2c_cam_ctrl_send().
Referenced by atmega_i2c_cam_ctrl_periodic(), and SpiralNav().