Paparazzi UAS: sw/airborne/modules/sensors/baro_ms5611_i2c.h File Reference
baro_ms5611_i2c.h File Reference
#include "std.h"
Defines
#define MS5611_SOFT_RESET 0x1E
#define MS5611_PROM_READ 0xA0
#define MS5611_START_CONV_D1 0x48
#define MS5611_START_CONV_D2 0x58
#define MS5611_ADC_READ 0x00
#define PROM_NB 8
Enumerations
enum ms5611_stat {
MS5611_UNINIT, MS5611_RESET, MS5611_RESET_OK, MS5611_PROM,
MS5611_IDLE, MS5611_CONV_D1, MS5611_CONV_D1_OK, MS5611_ADC_D1,
MS5611_CONV_D2, MS5611_CONV_D2_OK, MS5611_ADC_D2
}
Functions
void baro_ms5611_init (void)
void baro_ms5611_periodic (void)
void baro_ms5611_d1 (void)
void baro_ms5611_d2 (void)
void baro_ms5611_event (void)
Define Documentation
#define MS5611_ADC_READ 0x00
Definition at line 11 of file baro_ms5611_i2c.h.
#define MS5611_PROM_READ 0xA0
Definition at line 8 of file baro_ms5611_i2c.h.
Referenced by baro_ms5611_event(), and baro_ms5611_periodic().
#define MS5611_SOFT_RESET 0x1E
Definition at line 7 of file baro_ms5611_i2c.h.
#define MS5611_START_CONV_D1 0x48
Definition at line 9 of file baro_ms5611_i2c.h.
#define MS5611_START_CONV_D2 0x58
Definition at line 10 of file baro_ms5611_i2c.h.
#define PROM_NB 8
Definition at line 13 of file baro_ms5611_i2c.h.
Referenced by baro_ms5611_event().
Enumeration Type Documentation
enum ms5611_stat
Enumerator:
MS5611_UNINIT
MS5611_RESET
MS5611_RESET_OK
MS5611_PROM
MS5611_IDLE
MS5611_CONV_D1
MS5611_CONV_D1_OK
MS5611_ADC_D1
MS5611_CONV_D2
MS5611_CONV_D2_OK
MS5611_ADC_D2
Definition at line 15 of file baro_ms5611_i2c.h.
Function Documentation
void baro_ms5611_d1 (void)
Definition at line 111 of file baro_ms5611_i2c.c.
References i2c_transaction::buf, cpu_time_sec, I2CTransceive, MS5611_CONV_D1_OK, MS5611_I2C_DEV, MS5611_SLAVE_ADDR, ms5611_status, and ms5611_trans.
void baro_ms5611_d2 (void)
Definition at line 122 of file baro_ms5611_i2c.c.
References i2c_transaction::buf, cpu_time_sec, I2CTransceive, MS5611_CONV_D2_OK, MS5611_I2C_DEV, MS5611_SLAVE_ADDR, ms5611_status, and ms5611_trans.
void baro_ms5611_event (void)
Definition at line 133 of file baro_ms5611_i2c.c.
References baro_ms5611_crc(), baro_ms5611_init(), i2c_transaction::buf, DefaultChannel, fbaroms, ftempms, I2CTransceive, I2CTransmit, I2CTransSuccess, MS5611_ADC_D1, MS5611_ADC_D2, ms5611_c, MS5611_CONV_D1, MS5611_CONV_D2, ms5611_d1, ms5611_d2, MS5611_I2C_DEV, MS5611_PROM, MS5611_PROM_READ, MS5611_RESET, MS5611_SLAVE_ADDR, ms5611_status, ms5611_trans, prom_cnt, PROM_NB, i2c_transaction::status, and t2.
void baro_ms5611_init (void)
Definition at line 80 of file baro_ms5611_i2c.c.
References ms5611_status, and prom_cnt.
Referenced by baro_ms5611_event().
void baro_ms5611_periodic (void)
Definition at line 85 of file baro_ms5611_i2c.c.
References i2c_transaction::buf, cpu_time_sec, DefaultChannel, I2CTransceive, I2CTransmit, ms5611_c, MS5611_I2C_DEV, MS5611_IDLE, MS5611_PROM_READ, MS5611_RESET_OK, MS5611_SLAVE_ADDR, ms5611_status, ms5611_trans, MS5611_UNINIT, and prom_cnt.