Paparazzi UAV: sw/airborne/boards/booz/test_baro.c File Reference
test_baro.c File Reference
#include "mcu.h"
#include "sys_time.h"
#include "downlink.h"
#include "subsystems/sensors/baro.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_on_baro_diff (void)
static void main_on_baro_abs (void)
int main (void)
Function Documentation
int main (void)
Definition at line 46 of file test_baro.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 78 of file test_baro.c.
References BaroEvent, main_on_baro_abs(), and main_on_baro_diff().
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 58 of file test_baro.c.
References baro_init(), mcu_init(), mcu_int_enable, and sys_time_init().
Referenced by main().
static void main_on_baro_abs (void) [inline, static]
Definition at line 87 of file test_baro.c.
References Baro::absolute, baro, DefaultChannel, and Baro::differential.
Referenced by main_event_task().
static void main_on_baro_diff (void) [inline, static]
Definition at line 83 of file test_baro.c.
Referenced by main_event_task().
static void main_periodic_task (void) [inline, static]
Definition at line 68 of file test_baro.c.
References baro_periodic(), DefaultChannel, and LED_PERIODIC.
Referenced by main().