Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/can_arch.h File Reference
can_arch.h File Reference
Functions
void can_hw_init (void)
void usb_lp_can1_rx0_irq_handler (void)
int can_hw_transmit (uint32_t id, const uint8_t *buf, uint8_t len)
Function Documentation
void can_hw_init (void)
Definition at line 49 of file can_arch.c.
References CAN1, and can_tx_msg.
Referenced by can_init().
int can_hw_transmit (uint32_t id, const uint8_t * buf, uint8_t len)
Definition at line 126 of file can_arch.c.
References CAN1, and can_tx_msg.
Referenced by can_transmit().
void usb_lp_can1_rx0_irq_handler (void)
Definition at line 146 of file can_arch.c.
References _can_run_rx_callback(), CAN1, and can_rx_msg.