Paparazzi UAV: sw/airborne/gyro.c File Reference
gyro.c File Reference
Basic code for gyro acquisition on ADC channels.
#include "gyro.h"
#include "std.h"
#include "mcu_periph/adc.h"
#include "generated/airframe.h"
#include "estimator.h"
Defines
#define RadiansOfADC(_adc, scale) RadOfDeg((_adc * scale))
Functions
void gyro_init (void)
Hardware dependent code.
void gyro_update (void)
Sets roll_rate_adc and pitch_rate_adc (or temp_comp), and estimator_p.
Variables
int16_t roll_rate_adc
Raw (for debug), taking into accound neutral and temp compensation (if any)
float temp_comp
static struct adc_buf buf_roll
Detailed Description
Basic code for gyro acquisition on ADC channels.
Definition in file gyro.c.
Define Documentation
#define RadiansOfADC (_adc, scale) RadOfDeg((_adc * scale))
Definition at line 41 of file gyro.c.
Referenced by gyro_update().
Function Documentation
void gyro_init (void)
Hardware dependent code.
Definition at line 52 of file gyro.c.
References adc_buf_channel(), and buf_roll.
Referenced by init_ap().
void gyro_update (void)
Sets roll_rate_adc and pitch_rate_adc (or temp_comp), and estimator_p.
Definition at line 66 of file gyro.c.
References adc_buf::av_nb_sample, buf_roll, EstimatorSetRate, RadiansOfADC, roll_rate_adc, adc_buf::sum, and temp_comp.
Referenced by attitude_loop().
Variable Documentation
struct adc_buf buf_roll [static]
Definition at line 39 of file gyro.c.
Referenced by gyro_init(), and gyro_update().
int16_t roll_rate_adc
Raw (for debug), taking into accound neutral and temp compensation (if any)
Definition at line 37 of file gyro.c.
Referenced by gyro_update().
float temp_comp
Definition at line 38 of file gyro.c.
Referenced by gyro_update().