Paparazzi UAS: sw/airborne/gyro.h File Reference
gyro.h File Reference
Basic code for gyro acquisition on ADC channels.
#include <inttypes.h>
Functions
void gyro_init (void)
Hardware dependent code.
void gyro_update (void)
Sets roll_rate_adc and pitch_rate_adc (or temp_comp), and estimator_p.
Variables
int16_t roll_rate_adc
Raw (for debug), taking into accound neutral and temp compensation (if any).
Detailed Description
Basic code for gyro acquisition on ADC channels.
Definition in file gyro.h.
Function Documentation
void gyro_init (void)
Hardware dependent code.
Definition at line 52 of file gyro.c.
References adc_buf_channel(), and buf_roll.
Referenced by init_ap().
void gyro_update (void)
Sets roll_rate_adc and pitch_rate_adc (or temp_comp), and estimator_p.
Definition at line 66 of file gyro.c.
References adc_buf::av_nb_sample, buf_roll, EstimatorSetRate, RadiansOfADC, roll_rate_adc, adc_buf::sum, and temp_comp.
Referenced by attitude_loop().
Variable Documentation
int16_t roll_rate_adc
Raw (for debug), taking into accound neutral and temp compensation (if any).
Definition at line 37 of file gyro.c.
Referenced by gyro_update().