Paparazzi UAS: sw/airborne/subsystems/imu/imu_dummy.c File Reference
imu_dummy.c File Reference
Functions
void imu_impl_init (void)
Function Documentation
void imu_impl_init (void)
Definition at line 3 of file imu_dummy.c.
References adxl345_init(), hmc58xx_init(), and itg3200_init().