Paparazzi UAS: sw/airborne/subsystems/sensors/infrared.h File Reference
infrared.h File Reference
#include "std.h"
#include "generated/airframe.h"
Data Structures
struct Infrared_raw
struct Infrared
Infrared structure.
Defines
#define IR_IR1_SIGN 1
#define IR_IR2_SIGN 1
#define IR_TOP_SIGN 1
#define IR_TopOfIr(_ir) (_ir)
#define IR_LATERAL_CORRECTION 1.
#define IR_LONGITUDINAL_CORRECTION 1.
#define IR_VERTICAL_CORRECTION 1.
#define IR_CORRECTION_LEFT 1.
#define IR_CORRECTION_RIGHT 1.
#define IR_CORRECTION_UP 1.
#define IR_CORRECTION_DOWN 1.
#define IR_ROLL_NEUTRAL_DEFAULT 0.0
#define IR_PITCH_NEUTRAL_DEFAULT 0.0
#define UpdateIRValue(_v)
Functions
void infrared_struct_init (void)
Initialisation of ir structure.
void infrared_init (void)
void infrared_update (void)
void infrared_event (void)
Variables
struct Infrared infrared
Define Documentation
#define IR_CORRECTION_DOWN 1.
Definition at line 96 of file infrared.h.
#define IR_CORRECTION_LEFT 1.
Definition at line 84 of file infrared.h.
#define IR_CORRECTION_RIGHT 1.
Definition at line 88 of file infrared.h.
#define IR_CORRECTION_UP 1.
Definition at line 92 of file infrared.h.
#define IR_IR1_SIGN 1
Definition at line 36 of file infrared.h.
#define IR_IR2_SIGN 1
Definition at line 40 of file infrared.h.
#define IR_LATERAL_CORRECTION 1.
Definition at line 72 of file infrared.h.
#define IR_LONGITUDINAL_CORRECTION 1.
Definition at line 76 of file infrared.h.
#define IR_PITCH_NEUTRAL_DEFAULT 0.0
Definition at line 108 of file infrared.h.
Referenced by infrared_struct_init().
#define IR_ROLL_NEUTRAL_DEFAULT 0.0
Definition at line 104 of file infrared.h.
Referenced by infrared_struct_init().
#define IR_TOP_SIGN 1
Definition at line 44 of file infrared.h.
#define IR_TopOfIr (_ir) (_ir)
Definition at line 64 of file infrared.h.
#define IR_VERTICAL_CORRECTION 1.
Definition at line 80 of file infrared.h.
#define UpdateIRValue (_v)
Value:
{                  \
  infrared.value.ir1 = (IR_IR1_SIGN)*_v.ir1; \
  infrared.value.ir2 = (IR_IR2_SIGN)*_v.ir2; \
  infrared.value.ir3 = (IR_TOP_SIGN)*_v.ir3; \
  infrared.roll = infrared.lateral_correction * IR_RollOfIrs(infrared.value.ir1, infrared.value.ir2); \
  infrared.pitch = infrared.longitudinal_correction * IR_PitchOfIrs(infrared.value.ir1, infrared.value.ir2); \
  infrared.top = infrared.vertical_correction * IR_TopOfIr(infrared.value.ir3); \
}
Definition at line 151 of file infrared.h.
Referenced by infrared_adc_update(), infrared_i2c_hor_event(), and infrared_i2c_ver_event().
Function Documentation
void infrared_event (void)
Definition at line 66 of file infrared_adc.c.
References infrared_i2cEvent.
void infrared_init (void)
Definition at line 57 of file infrared_adc.c.
References infrared_adc_init(), and infrared_i2c_init().
void infrared_struct_init (void)
Initialisation of ir structure.
Definition at line 40 of file infrared.c.
References Infrared::correction_down, Infrared::correction_left, Infrared::correction_right, Infrared::correction_up, infrared, IR_PITCH_NEUTRAL_DEFAULT, IR_ROLL_NEUTRAL_DEFAULT, Infrared::lateral_correction, Infrared::longitudinal_correction, Infrared::pitch_neutral, Infrared::roll_neutral, and Infrared::vertical_correction.
Referenced by infrared_adc_init(), and infrared_i2c_init().
void infrared_update (void)
Definition at line 61 of file infrared_adc.c.
References infrared_adc_update(), and infrared_i2c_update().
Variable Documentation
struct Infrared infrared
Definition at line 36 of file infrared.c.
Referenced by ahrs_update_infrared(), dl_parse_msg(), infrared_struct_init(), set_ir(), and set_ir_and_airspeed().