Paparazzi UAS: sw/airborne/modules/display/lcd_dogm.h File Reference
lcd_dogm.h File Reference
#include <stdbool.h>
#include "std.h"
#include "mcu_periph/spi.h"
#include "led.h"
Defines
#define DOGM_FUN_SET_1 0x39
#define DOGM_BIAS_SET 0x15
#define DOGM_PWR_CTRL 0x55
#define DOGM_FOLLOWER 0x6E
#define DOGM_CONTRAST 0x70
#define DOGM_FUN_SET_2 0x38
#define DOGM_DISP_ON 0x0C
#define DOGM_CLEAR 0x01
#define DOGM_ENTRY_MODE 0x06
Functions
void lcd_cmd (uint8_t command)
void lcd_data (uint8_t data)
void lcd_dogm_init (void)
Define Documentation
#define DOGM_BIAS_SET 0x15
Definition at line 11 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
#define DOGM_CLEAR 0x01
Definition at line 17 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
#define DOGM_CONTRAST 0x70
Definition at line 14 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
#define DOGM_DISP_ON 0x0C
Definition at line 16 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
#define DOGM_ENTRY_MODE 0x06
Definition at line 18 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
#define DOGM_FOLLOWER 0x6E
Definition at line 13 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
#define DOGM_FUN_SET_1 0x39
Definition at line 10 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
#define DOGM_FUN_SET_2 0x38
Definition at line 15 of file lcd_dogm.h.
#define DOGM_PWR_CTRL 0x55
Definition at line 12 of file lcd_dogm.h.
Referenced by lcd_dogm_init().
Function Documentation
void lcd_cmd (uint8_t command)
Definition at line 43 of file lcd_dogm.c.
References lcd_spi_tx(), lcddogmCmdMode, and lcddogmSelect.
Referenced by lcd_dogm_init().
void lcd_data (uint8_t data)
Definition at line 51 of file lcd_dogm.c.
References lcd_spi_tx(), lcddogmDataMode, and lcddogmSelect.
Referenced by lcd_dogm_init().
void lcd_dogm_init (void)
Definition at line 59 of file lcd_dogm.c.
References DOGM_BIAS_SET, DOGM_CLEAR, DOGM_CONTRAST, DOGM_DISP_ON, DOGM_ENTRY_MODE, DOGM_FOLLOWER, DOGM_FUN_SET_1, DOGM_PWR_CTRL, lcd_cmd(), lcd_data(), and lcd_dogm_init_hw().