Paparazzi UAS: sw/airborne/led.h File Reference
led.h File Reference
arch independent LED (Light Emitting Diodes) API
Defines
#define LED_ON(i) {}
#define LED_OFF(i) {}
#define LED_TOGGLE(i) {}
#define LED_PERIODIC() {}
Functions
static void led_init (void)
Detailed Description
arch independent LED (Light Emitting Diodes) API
Definition in file led.h.
Define Documentation
#define LED_OFF (i) {}
Definition at line 83 of file led.h.
#define LED_ON (i) {}
Definition at line 82 of file led.h.
#define LED_PERIODIC () {}
Definition at line 85 of file led.h.
#define LED_TOGGLE (i) {}
Definition at line 84 of file led.h.
Function Documentation
static void led_init (void) [inline, static]
Definition at line 81 of file led.h.
Referenced by init_fbw(), main(), main_init(), and mcu_init().