Paparazzi UAS: sw/airborne/lisa/test/lisa_test_max1168.c File Reference
lisa_test_max1168.c File Reference
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/spi.h>
#include <stm32/dma.h>
#include <stm32/exti.h>
#include "mcu.h"
#include "sys_time.h"
#include "downlink.h"
#include "peripherals/max1168.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_spi2_init (void)
int main (void)
Function Documentation
int main (void)
Definition at line 43 of file lisa_test_max1168.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 74 of file lisa_test_max1168.c.
References DefaultChannel, max1168_status, max1168_values, and STA_MAX1168_DATA_AVAILABLE.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 56 of file lisa_test_max1168.c.
References main_spi2_init(), max1168_init(), mcu_init(), and sys_time_init().
static void main_periodic_task (void) [inline, static]
Definition at line 63 of file lisa_test_max1168.c.
References cpu_time_sec, DefaultChannel, LED_PERIODIC, and max1168_read().
Referenced by main().
static void main_spi2_init (void) [inline, static]
Definition at line 86 of file lisa_test_max1168.c.
References Max1168ConfigureSPI.
Referenced by main_init().