Paparazzi UAS: sw/airborne/lisa/test/lisa_test_sc18is600.c File Reference
lisa_test_sc18is600.c File Reference
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include "mcu.h"
#include "sys_time.h"
#include "downlink.h"
#include "peripherals/sc18is600.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_spi2_init (void)
int main (void)
Function Documentation
int main (void)
Definition at line 40 of file lisa_test_sc18is600.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 95 of file lisa_test_sc18is600.c.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 53 of file lisa_test_sc18is600.c.
References main_spi2_init(), mcu_init(), sc18is600_init(), and sys_time_init().
static void main_periodic_task (void) [inline, static]
Definition at line 60 of file lisa_test_sc18is600.c.
References DefaultChannel, foo, LED_PERIODIC, Sc18Is600::priv_tx_buf, sc18is600, Sc18Is600_I2CClock, sc18is600_read_from_register(), sc18is600_tranceive(), sc18is600_transmit(), and sc18is600_write_to_register().
Referenced by main().
static void main_spi2_init (void) [inline, static]
Definition at line 100 of file lisa_test_sc18is600.c.
Referenced by main_init().