Paparazzi UAS: sw/airborne/lisa/test/lisa_test_ms2100.c File Reference
lisa_test_ms2100.c File Reference
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/spi.h>
#include <stm32/dma.h>
#include <stm32/exti.h>
#include "mcu.h"
#include "sys_time.h"
#include "downlink.h"
#include "peripherals/ms2100.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_spi2_init (void)
int main (void)
Function Documentation
int main (void)
Definition at line 43 of file lisa_test_ms2100.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 82 of file lisa_test_ms2100.c.
References DefaultChannel, MS2100_DATA_AVAILABLE, ms2100_status, and ms2100_values.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 56 of file lisa_test_ms2100.c.
References main_spi2_init(), mcu_init(), ms2100_init(), and sys_time_init().
static void main_periodic_task (void) [inline, static]
Definition at line 63 of file lisa_test_ms2100.c.
References cpu_time_sec, DefaultChannel, LED_PERIODIC, Ms2001HasEOC, Ms2001ReadRes, Ms2001SendReq, MS2100_IDLE, ms2100_status, and MS2100_WAITING_EOC.
Referenced by main().
static void main_spi2_init (void) [inline, static]
Definition at line 94 of file lisa_test_ms2100.c.
Referenced by main_init().