Paparazzi UAS: sw/airborne/lisa/test/lisa_test_actuators_mkk.c File Reference
lisa_test_actuators_mkk.c File Reference
#include "mcu.h"
#include "sys_time.h"
#include "firmwares/rotorcraft/commands.h"
#include "actuators.h"
#include "downlink.h"
#include "actuators/actuators_asctec.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
int main (void)
Function Documentation
int main (void)
Definition at line 39 of file lisa_test_actuators_mkk.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 105 of file lisa_test_actuators_mkk.c.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 51 of file lisa_test_actuators_mkk.c.
References actuators_init(), mcu_init(), and sys_time_init().
static void main_periodic_task (void) [inline, static]
Definition at line 59 of file lisa_test_actuators_mkk.c.
References actuators_asctec, actuators_set(), ActuatorsAsctec::cmd, commands, ActuatorsAsctec::cur_addr, DefaultChannel, FALSE, LED_PERIODIC, LED_TOGGLE, and ActuatorsAsctec::new_addr.
Referenced by main().