Paparazzi UAS: sw/airborne/lisa/lisa_stm_passthrough_main.c File Reference
lisa_stm_passthrough_main.c File Reference
#include "mcu.h"
#include "mcu_periph/uart.h"
#include "sys_time.h"
#include "downlink.h"
#include "firmwares/rotorcraft/commands.h"
#include "actuators.h"
#include "actuators/actuators_pwm.h"
#include "subsystems/imu.h"
#include "subsystems/radio_control.h"
#include "autopilot.h"
#include "subsystems/ins.h"
#include "guidance.h"
#include "navigation.h"
#include "lisa/lisa_overo_link.h"
#include "generated/airframe.h"
#include "subsystems/ahrs.h"
#include "stm32/can.h"
#include "csc_msg_def.h"
#include "csc_protocol.h"
#include "subsystems/sensors/baro.h"
#include "mcu_periph/adc.h"
Defines
#define ActuatorsCommit() actuators_pwm_commit();
#define actuators actuators_pwm_values
#define ChopServo(x, a, b) Chop(x, a, b)
#define Actuator(i) actuators[i]
#define SERVOS_TICS_OF_USEC(_s) (_s)
Functions
static void main_init (void)
static void main_periodic (void)
static void main_event (void)
static void on_gyro_accel_event (void)
static void on_accel_event (void)
static void on_mag_event (void)
static void on_overo_link_msg_received (void)
static void on_overo_link_lost (void)
static void on_overo_link_crc_failed (void)
static void on_rc_message (void)
static void on_vane_msg (void *data)
int main (void)
static void check_radio_lost (void)
static void main_on_baro_diff (void)
static void main_on_baro_abs (void)
Variables
static bool_t new_radio_msg
static bool_t new_baro_diff
static bool_t new_baro_abs
static bool_t new_vane
static bool_t new_adc
struct CscVaneMsg csc_vane_msg
static struct adc_buf adc0_buf
static struct adc_buf adc1_buf
static struct adc_buf adc2_buf
static struct adc_buf adc3_buf
uint8_t adc_new_data_trigger
struct CscServoCmd csc_servo_cmd
Define Documentation
#define Actuator (i) actuators[i]
Definition at line 90 of file lisa_stm_passthrough_main.c.
#define actuators actuators_pwm_values
Definition at line 87 of file lisa_stm_passthrough_main.c.
#define ActuatorsCommit (void) actuators_pwm_commit();
Definition at line 86 of file lisa_stm_passthrough_main.c.
Referenced by on_rc_message().
#define ChopServo (x, a, b) Chop(x, a, b)
Definition at line 89 of file lisa_stm_passthrough_main.c.
#define SERVOS_TICS_OF_USEC (_s) (_s)
Definition at line 91 of file lisa_stm_passthrough_main.c.
Function Documentation
static void check_radio_lost (void) [static]
Definition at line 145 of file lisa_stm_passthrough_main.c.
References commands_failsafe, and radio_control.
Referenced by main_periodic().
int main (void)
Definition at line 93 of file lisa_stm_passthrough_main.c.
References main_event(), main_init(), main_periodic(), and sys_time_periodic.
static void main_event (void) [inline, static]
Definition at line 342 of file lisa_stm_passthrough_main.c.
References BaroEvent, ImuEvent, main_on_baro_abs(), main_on_baro_diff(), on_accel_event(), on_gyro_accel_event(), on_mag_event(), on_overo_link_crc_failed(), on_overo_link_msg_received(), on_rc_message(), OveroLinkEvent, and RadioControlEvent.
static void main_init (void) [inline, static]
Definition at line 106 of file lisa_stm_passthrough_main.c.
References actuators_init(), adc0_buf, adc1_buf, adc2_buf, adc3_buf, adc_buf_channel(), ahrs_aligner_init(), ahrs_init(), autopilot_init(), baro_init(), csc_vane_msg, guidance_h_init(), guidance_v_init(), imu_init(), ins_init(), mcu_init(), LisaOveroLink::msg, nav_init(), new_adc, new_baro_abs, new_baro_diff, new_radio_msg, new_vane, on_vane_msg(), overo_link, overo_link_init(), stabilization_init(), sys_time_init(), and LisaOveroLink::up.
static void main_on_baro_abs (void) [inline, static]
Definition at line 338 of file lisa_stm_passthrough_main.c.
References new_baro_abs.
Referenced by main_event().
static void main_on_baro_diff (void) [inline, static]
Definition at line 334 of file lisa_stm_passthrough_main.c.
References new_baro_diff.
Referenced by main_event().
static void main_periodic (void) [inline, static]
Definition at line 156 of file lisa_stm_passthrough_main.c.
References Baro::absolute, adc0_buf, adc1_buf, adc_new_data_trigger, autopilot_periodic(), adc_buf::av_nb_sample, baro, baro_periodic(), check_radio_lost(), DefaultChannel, Baro::differential, imu_periodic(), LED_PERIODIC, new_adc, on_overo_link_lost(), OveroLinkPeriodic, adc_buf::sum, and adc_buf::values.
static void on_accel_event (void) [inline, static]
Definition at line 288 of file lisa_stm_passthrough_main.c.
Referenced by main_event().
static void on_gyro_accel_event (void) [inline, static]
Definition at line 291 of file lisa_stm_passthrough_main.c.
References ahrs, ahrs_align(), ahrs_aligner, AHRS_ALIGNER_LOCKED, ahrs_aligner_run(), ahrs_propagate(), AHRS_UNINIT, ahrs_update_accel(), imu, ImuScaleAccel, ImuScaleGyro, ins_propagate(), LisaOveroLink::msg, overo_link, AhrsAligner::status, Ahrs::status, and LisaOveroLink::up.
Referenced by main_event().
static void on_mag_event (void) [inline, static]
Definition at line 309 of file lisa_stm_passthrough_main.c.
References ahrs, AHRS_RUNNING, ahrs_update_mag(), imu, ImuScaleMag, and Ahrs::status.
Referenced by main_event().
static void on_overo_link_crc_failed (void) [inline, static]
Definition at line 285 of file lisa_stm_passthrough_main.c.
Referenced by main_event().
static void on_overo_link_lost (void) [inline, static]
Definition at line 282 of file lisa_stm_passthrough_main.c.
Referenced by main_periodic().
static void on_overo_link_msg_received (void) [inline, static]
Definition at line 205 of file lisa_stm_passthrough_main.c.
References Baro::absolute, Imu::accel, actuators, actuators_pwm_commit(), actuators_pwm_values, adc0_buf, adc1_buf, adc2_buf, adc3_buf, adc_buf::av_nb_sample, baro, LisaOveroLink::crc_err_cnt, csc_servo_cmd, csc_vane_msg, Baro::differential, LisaOveroLink::down, Imu::gyro, imu, Imu::mag, LisaOveroLink::msg, LisaOveroLink::msg_cnt, new_adc, new_baro_abs, new_baro_diff, new_radio_msg, new_vane, overo_link, radio_control, RADIO_KILL, RADIO_MODE, RATES_COPY, adc_buf::sum, LisaOveroLink::up, and VECT3_COPY.
Referenced by main_event().
static void on_rc_message (void) [inline, static]
Definition at line 186 of file lisa_stm_passthrough_main.c.
References actuators, ActuatorsCommit, autopilot_on_rc_frame(), commands, new_radio_msg, radio_control, RADIO_KILL, and RADIO_MODE.
Referenced by main_event().
static void on_vane_msg (void * data) [inline, static]
Definition at line 318 of file lisa_stm_passthrough_main.c.
References csc_vane_msg, DefaultChannel, and new_vane.
Referenced by main_init().
Variable Documentation
struct adc_buf adc0_buf [static]
Definition at line 77 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), main_periodic(), and on_overo_link_msg_received().
struct adc_buf adc1_buf [static]
Definition at line 78 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), main_periodic(), and on_overo_link_msg_received().
struct adc_buf adc2_buf [static]
Definition at line 79 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), and on_overo_link_msg_received().
struct adc_buf adc3_buf [static]
Definition at line 80 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), and on_overo_link_msg_received().
uint8_t adc_new_data_trigger
Definition at line 100 of file adc_arch.c.
struct CscServoCmd csc_servo_cmd
Definition at line 84 of file lisa_stm_passthrough_main.c.
Referenced by on_overo_link_msg_received().
struct CscVaneMsg csc_vane_msg
Definition at line 75 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), main_on_vane_msg(), on_overo_link_msg_received(), and on_vane_msg().
bool_t new_adc [static]
Definition at line 72 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), main_periodic(), and on_overo_link_msg_received().
bool_t new_baro_abs [static]
Definition at line 70 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), main_on_baro_abs(), and on_overo_link_msg_received().
bool_t new_baro_diff [static]
Definition at line 69 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), main_on_baro_diff(), and on_overo_link_msg_received().
bool_t new_radio_msg [static]
Definition at line 68 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), on_overo_link_msg_received(), and on_rc_message().
bool_t new_vane [static]
Definition at line 71 of file lisa_stm_passthrough_main.c.
Referenced by main_init(), on_overo_link_msg_received(), and on_vane_msg().