Paparazzi UAS: sw/airborne/boards/lisa_l/baro_board.c File Reference
baro_board.c File Reference
#include "subsystems/sensors/baro.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "downlink.h"
Defines
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
#define BARO_ABS_ADDR 0x90
#define BARO_DIFF_ADDR 0x92
Functions
static void baro_board_write_to_register (uint8_t baro_addr, uint8_t reg_addr, uint8_t val_msb, uint8_t val_lsb)
static void baro_board_read_from_register (uint8_t baro_addr, uint8_t reg_addr)
static void baro_board_set_current_register (uint8_t baro_addr, uint8_t reg_addr)
static void baro_board_read_from_current_register (uint8_t baro_addr)
void baro_init (void)
void baro_downlink_raw (void)
void baro_periodic (void)
void baro_board_send_config_abs (void)
void baro_board_send_config_diff (void)
void baro_board_send_reset (void)
Variables
struct Baro baro
struct BaroBoard baro_board
struct i2c_transaction baro_trans
Define Documentation
#define BARO_ABS_ADDR 0x90
Definition at line 24 of file baro_board.c.
Referenced by baro_board_send_config_abs(), and baro_periodic().
#define BARO_DIFF_ADDR 0x92
Definition at line 26 of file baro_board.c.
Referenced by baro_board_send_config_diff(), and baro_periodic().
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 10 of file baro_board.c.
Function Documentation
static void baro_board_read_from_current_register (uint8_t baro_addr) [inline, static]
Definition at line 130 of file baro_board.c.
References baro_trans, i2c_submit(), I2CTransRx, i2c_transaction::len_r, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by baro_periodic().
static void baro_board_read_from_register (uint8_t baro_addr, uint8_t reg_addr) [inline, static]
Definition at line 109 of file baro_board.c.
References baro_trans, i2c_transaction::buf, i2c_submit(), I2CTransTxRx, i2c_transaction::len_r, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
void baro_board_send_config_abs (void)
Definition at line 83 of file baro_board.c.
References BARO_ABS_ADDR, and baro_board_write_to_register().
Referenced by baro_periodic().
void baro_board_send_config_diff (void)
Definition at line 87 of file baro_board.c.
References baro_board_write_to_register(), and BARO_DIFF_ADDR.
Referenced by baro_periodic().
void baro_board_send_reset (void)
Definition at line 91 of file baro_board.c.
Referenced by baro_periodic().
static void baro_board_set_current_register (uint8_t baro_addr, uint8_t reg_addr) [inline, static]
Definition at line 120 of file baro_board.c.
References baro_trans, i2c_transaction::buf, i2c_submit(), I2CTransTx, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by baro_periodic().
static void baro_board_write_to_register (uint8_t baro_addr, uint8_t reg_addr, uint8_t val_msb, uint8_t val_lsb) [inline, static]
Definition at line 99 of file baro_board.c.
References baro_trans, i2c_transaction::buf, i2c_submit(), I2CTransTx, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by baro_board_send_config_abs(), and baro_board_send_config_diff().
void baro_downlink_raw (void)
Definition at line 35 of file baro_board.c.
void baro_init (void)
Definition at line 28 of file baro_board.c.
References Baro::absolute, baro, baro_board, BS_UNINITIALIZED, Baro::differential, LBS_UNINITIALIZED, BaroBoard::status, and Baro::status.
void baro_periodic (void)
Definition at line 41 of file baro_board.c.
References baro, BARO_ABS_ADDR, baro_board, baro_board_read_from_current_register(), baro_board_send_config_abs(), baro_board_send_config_diff(), baro_board_send_reset(), baro_board_set_current_register(), BARO_DIFF_ADDR, BS_RUNNING, i2c_idle(), LBS_INITIALIZING_ABS, LBS_INITIALIZING_ABS_1, LBS_INITIALIZING_DIFF, LBS_INITIALIZING_DIFF_1, LBS_READ_ABS, LBS_READ_DIFF, LBS_READING_ABS, LBS_READING_DIFF, LBS_RESETED, LBS_UNINITIALIZED, Baro::status, and BaroBoard::status.
Variable Documentation
struct Baro baro
Definition at line 13 of file baro_board.c.
struct BaroBoard baro_board
Definition at line 14 of file baro_board.c.
struct i2c_transaction baro_trans
Definition at line 15 of file baro_board.c.
Referenced by baro_board_read_from_current_register(), baro_board_read_from_register(), baro_board_send_reset(), baro_board_set_current_register(), baro_board_write_to_register(), baro_event(), baro_periodic(), bmp085_read_reg16(), bmp085_read_reg16_blocking(), bmp085_read_reg24(), and bmp085_write_reg().