Paparazzi UAS: sw/airborne/lisa/lisa_overo_link.c File Reference
lisa_overo_link.c File Reference
#include "lisa/lisa_overo_link.h"
Functions
void overo_link_init (void)
Variables
struct LisaOveroLink overo_link
Function Documentation
void overo_link_init (void)
Definition at line 5 of file lisa_overo_link.c.
References LisaOveroLink::crc_err_cnt, LisaOveroLink::crc_error, LisaOveroLink::msg_cnt, overo_link, overo_link_arch_init(), OVERO_LINK_TIMEOUT, LisaOveroLink::status, LisaOveroLink::timeout, and LisaOveroLink::timeout_cnt.
Referenced by main(), main_init(), and vi_impl_init().
Variable Documentation
struct LisaOveroLink overo_link
Definition at line 3 of file lisa_overo_link.c.
Referenced by dma1_c2_irq_handler(), main_init(), on_gyro_accel_event(), on_overo_link_msg_received(), overo_link_arch_prepare_next_transfert(), overo_link_init(), and vi_overo_link_on_msg_received().