Paparazzi UAS: sw/airborne/lisa/lisa_stm_gps_passthrough_main.c File Reference
lisa_stm_gps_passthrough_main.c File Reference
#include "mcu.h"
#include "sys_time.h"
#include "lisa/lisa_overo_link.h"
#include "lisa/lisa_spistream.h"
#include "generated/airframe.h"
#include "mcu_periph/uart.h"
Data Structures
struct uart_state
Functions
static void main_init (void)
static void main_periodic (void)
static void main_event (void)
static void uart_transfer_event (void)
spistream stress test: Send big (500-700 bytes) messages with different message lengths for every channel and length varying in every message.
static void on_spistream_msg_received (uint8_t msg_id, uint8_t *data, uint16_t num_bytes)
Handler for commands (messages from Overo->STM).
static void on_spistream_msg_sent (uint8_t msg_id)
static void on_overo_link_msg_received (void)
Every SPI transfer contains exactly two packages of type AutopilotMessagePTStream, one for each direction (up: STM->Overo, down: Overo->STM).
static void on_overo_link_lost (void)
static void on_overo_link_crc_failed (void)
struct __attribute__ ((packed))
int main (void)
Variables
static struct spistream_uart_msg spistream_uart1_msg
static struct spistream_uart_msg spistream_uart2_msg
static struct spistream_uart_msg spistream_uart3_msg
static uint8_t spistream_wait_for_num_transfers = 0
Function Documentation
struct __attribute__ ((packed)) [read]
Definition at line 49 of file lisa_stm_gps_passthrough_main.c.
int main (void)
Definition at line 78 of file lisa_stm_gps_passthrough_main.c.
References main_event(), main_init(), main_periodic(), and sys_time_periodic.
static void main_event (void) [inline, static]
Definition at line 164 of file lisa_stm_gps_passthrough_main.c.
References on_overo_link_crc_failed(), on_overo_link_msg_received(), OveroLinkEvent, and uart_transfer_event().
static void main_init (void) [inline, static]
Definition at line 92 of file lisa_stm_gps_passthrough_main.c.
References mcu_init(), on_spistream_msg_received(), on_spistream_msg_sent(), overo_link_init(), spistream_init(), spistream_uart1_msg, spistream_uart2_msg, spistream_uart3_msg, and sys_time_init().
static void main_periodic (void) [inline, static]
Definition at line 133 of file lisa_stm_gps_passthrough_main.c.
References LED_PERIODIC, on_overo_link_lost(), and OveroLinkPeriodic.
static void on_overo_link_crc_failed (void) [inline, static]
Definition at line 161 of file lisa_stm_gps_passthrough_main.c.
Referenced by main_event().
static void on_overo_link_lost (void) [inline, static]
Definition at line 158 of file lisa_stm_gps_passthrough_main.c.
Referenced by main_periodic().
static void on_overo_link_msg_received (void) [inline, static]
Every SPI transfer contains exactly two packages of type AutopilotMessagePTStream, one for each direction (up: STM->Overo, down: Overo->STM).
As we delegate SPI message handling to spistream, the SPI event just passes both packages to spistream_read_pkg(down_pkg) and spistream_write_pkg(up_pkg). Apart from that, we just don't care about the SPI driver itself.
Definition at line 152 of file lisa_stm_gps_passthrough_main.c.
References LisaOveroLink::down, LisaOveroLink::msg, overo_link, spistream_read_pkg(), spistream_write_pkg(), and LisaOveroLink::up.
Referenced by main_event().
static void on_spistream_msg_received (uint8_t msg_id, uint8_t * data, uint16_t num_bytes) [inline, static]
Handler for commands (messages from Overo->STM).
Right now, it is just sending the command back for debugging purposes.
Definition at line 120 of file lisa_stm_gps_passthrough_main.c.
References SPISTREAM_NO_WAIT, and spistream_send_msg().
Referenced by main_init().
static void on_spistream_msg_sent (uint8_t msg_id) [inline, static]
Definition at line 127 of file lisa_stm_gps_passthrough_main.c.
References spistream_wait_for_num_transfers.
Referenced by main_init().
static void uart_transfer_event (void) [inline, static]
spistream stress test: Send big (500-700 bytes) messages with different message lengths for every channel and length varying in every message.
Fool around with timeout to increase/decrease message rate to see when it can't keep up any more.
Definition at line 230 of file lisa_stm_gps_passthrough_main.c.
References LED_OFF, LED_ON, SPISTREAM_MAX_MESSAGE_LENGTH, spistream_send_msg(), spistream_uart1_msg, spistream_uart2_msg, spistream_uart3_msg, spistream_wait_for_num_transfers, and SPISTREAM_WAIT_FOR_READ.
Referenced by main_event().
Variable Documentation
struct spistream_uart_msg spistream_uart1_msg [static]
Definition at line 66 of file lisa_stm_gps_passthrough_main.c.
Referenced by main_init(), and uart_transfer_event().
struct spistream_uart_msg spistream_uart2_msg [static]
Definition at line 67 of file lisa_stm_gps_passthrough_main.c.
Referenced by main_init(), and uart_transfer_event().
struct spistream_uart_msg spistream_uart3_msg [static]
Definition at line 68 of file lisa_stm_gps_passthrough_main.c.
Referenced by main_init(), and uart_transfer_event().
uint8_t spistream_wait_for_num_transfers = 0 [static]
Definition at line 76 of file lisa_stm_gps_passthrough_main.c.
Referenced by on_spistream_msg_sent(), and uart_transfer_event().