Paparazzi UAS: sw/airborne/lisa/test/lisa_test_aspirin.c File Reference
lisa_test_aspirin.c File Reference
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/exti.h>
#include <stm32/spi.h>
#include "mcu.h"
#include "sys_time.h"
#include "downlink.h"
#include "peripherals/itg3200.h"
#include "peripherals/hmc5843.h"
Defines
#define AccUnselect() GPIOB->BSRR = GPIO_Pin_12
#define AccSelect() GPIOB->BRR = GPIO_Pin_12
#define AccToggleSelect() GPIOB->ODR ^= GPIO_Pin_12
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_init_hw (void)
void exti2_irq_handler (void)
void exti3_irq_handler (void)
void exti4_irq_handler (void)
int main (void)
Variables
static volatile uint8_t gyro_ready_for_read
static uint8_t foo = 0
Define Documentation
#define AccSelect () GPIOB->BRR = GPIO_Pin_12
Definition at line 75 of file lisa_test_aspirin.c.
#define AccToggleSelect () GPIOB->ODR ^= GPIO_Pin_12
Definition at line 76 of file lisa_test_aspirin.c.
Referenced by exti2_irq_handler().
#define AccUnselect () GPIOB->BSRR = GPIO_Pin_12
Definition at line 74 of file lisa_test_aspirin.c.
Referenced by main_init_hw().
Function Documentation
void exti2_irq_handler (void)
Definition at line 267 of file lisa_test_aspirin.c.
References AccToggleSelect, foo, gyro_ready_for_read, i2c_done, ITG3200_ADDR, and RESET.
void exti3_irq_handler (void)
Definition at line 286 of file lisa_test_aspirin.c.
References RESET.
void exti4_irq_handler (void)
Definition at line 297 of file lisa_test_aspirin.c.
References RESET.
int main (void)
Definition at line 50 of file lisa_test_aspirin.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 142 of file lisa_test_aspirin.c.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 62 of file lisa_test_aspirin.c.
References gyro_ready_for_read, main_init_hw(), mcu_init(), and sys_time_init().
static void main_init_hw (void) [inline, static]
Definition at line 147 of file lisa_test_aspirin.c.
References AccUnselect.
Referenced by main_init().
static void main_periodic_task (void) [inline, static]
Definition at line 79 of file lisa_test_aspirin.c.
References DefaultChannel, foo, HMC5843_ADDR, i2c_done, ITG3200_ADDR, and LED_PERIODIC.
Referenced by main().
Variable Documentation
uint8_t foo = 0 [static]
Definition at line 71 of file lisa_test_aspirin.c.
volatile uint8_t gyro_ready_for_read [static]
Definition at line 44 of file lisa_test_aspirin.c.
Referenced by exti2_irq_handler(), and main_init().