Paparazzi UAS: sw/airborne/lisa/test/lisa_tunnel.c File Reference
lisa_tunnel.c File Reference
#include <inttypes.h>
#include "std.h"
#include "mcu.h"
#include "mcu_periph/uart.h"
#include "sys_time.h"
#include "led.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
int main (void)
Function Documentation
int main (void)
Definition at line 36 of file lisa_tunnel.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 59 of file lisa_tunnel.c.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 46 of file lisa_tunnel.c.
References mcu_init(), and sys_time_init().
static void main_periodic_task (void) [inline, static]
Definition at line 51 of file lisa_tunnel.c.
References LED_PERIODIC, and LED_TOGGLE.
Referenced by main().