Paparazzi UAS: sw/airborne/arch/lpc21/subsystems/imu/imu_aspirin_arch.c File Reference
imu_aspirin_arch.c File Reference
#include "subsystems/imu.h"
#include "mcu_periph/i2c.h"
Functions
void imu_aspirin_arch_int_enable (void)
void imu_aspirin_arch_int_disable (void)
void imu_aspirin_arch_init (void)
void adxl345_write_to_reg (uint8_t addr, uint8_t val)
void adxl345_clear_rx_buf (void)
void exti15_10_irq_handler (void)
void exti2_irq_handler (void)
void dma1_c4_irq_handler (void)
Function Documentation
void adxl345_clear_rx_buf (void)
Definition at line 32 of file imu_aspirin_arch.c.
Referenced by configure_accel().
void adxl345_write_to_reg (uint8_t addr, uint8_t val)
Definition at line 20 of file imu_aspirin_arch.c.
Referenced by configure_accel().
void dma1_c4_irq_handler (void)
Definition at line 75 of file imu_aspirin_arch.c.
References ImuAspirin::accel_available, and imu_aspirin.
Referenced by exti2_irq_handler().
void exti15_10_irq_handler (void)
Definition at line 44 of file imu_aspirin_arch.c.
References imu_aspirin, and ImuAspirin::status.
void exti2_irq_handler (void)
Definition at line 60 of file imu_aspirin_arch.c.
void imu_aspirin_arch_init (void)
Definition at line 15 of file imu_aspirin_arch.c.
Referenced by imu_impl_init().
void imu_aspirin_arch_int_disable (void)
Definition at line 11 of file imu_aspirin_arch.c.
Referenced by imu_aspirin_event().
void imu_aspirin_arch_int_enable (void)
Definition at line 7 of file imu_aspirin_arch.c.
Referenced by imu_aspirin_event(), and imu_periodic().