Paparazzi UAS: sw/airborne/arch/lpc21/peripherals/max1168_arch.c File Reference
max1168_arch.c File Reference
#include "peripherals/max1168.h"
Functions
static void EXTINT0_ISR (void)
void max1168_read (void)
Function Documentation
void EXTINT0_ISR (void) [static]
Definition at line 68 of file max1168_arch.c.
References __attribute__(), ASSERT, EXTINT, foo, ISR_ENTRY, ISR_EXIT, MAX1168_ERR_SPURIOUS_EOC, max1168_status, SSP_ClearRti, SSP_EnableRti, SSP_Send, STA_MAX1168_SENDING_REQ, and VICVectAddr.
void max1168_read (void)
Definition at line 52 of file max1168_arch.c.
Referenced by imu_periodic(), and main_periodic_task().