Paparazzi UAS: sw/airborne/arch/lpc21/micromag_hw.c File Reference
micromag_hw.c File Reference
#include "micromag.h"
Functions
static void EXTINT_ISR (void)
Variables
volatile uint8_t micromag_cur_axe
Function Documentation
void EXTINT_ISR (void) [static]
Definition at line 54 of file micromag_hw.c.
References EXTINT, ISR_ENTRY, ISR_EXIT, micromag_status, and VICVectAddr.
Referenced by baro_scp_init(), max11040_hw_init(), and micromag_hw_init().
Variable Documentation
volatile uint8_t micromag_cur_axe
Definition at line 25 of file micromag_hw.c.