Paparazzi UAS: sw/airborne/arch/lpc21/subsystems/imu/imu_crista_arch.c File Reference
imu_crista_arch.c File Reference
#include "subsystems/imu.h"
#include "LPC21xx.h"
#include "armVIC.h"
#include "ssp_hw.h"
Defines
#define ADS8344_SS_IODIR IO0DIR
#define ADS8344_SS_IOSET IO0SET
#define ADS8344_SS_IOCLR IO0CLR
#define ADS8344_SS_PIN 20
#define ADS8344Select() SetBit(ADS8344_SS_IOCLR,ADS8344_SS_PIN)
#define ADS8344Unselect() SetBit(ADS8344_SS_IOSET,ADS8344_SS_PIN)
#define POWER_MODE (1 << 1 | 1)
#define SGL_DIF 1
#define SSP_DSS 0x07 << 0
#define SSP_FRF 0x00 << 4
#define SSP_CPOL 0x00 << 6
#define SSP_CPHA 0x00 << 7
#define SSP_SCR 0x09 << 8
#define SSP_LBM 0x00 << 0
#define SSP_SSE 0x00 << 1
#define SSP_MS 0x00 << 2
#define SSP_SOD 0x00 << 3
Functions
static void SPI1_ISR (void)
static void read_values (void)
static void send_request (void)
void ADS8344_start (void)
Define Documentation
#define ADS8344_SS_IOCLR IO0CLR
Definition at line 33 of file imu_crista_arch.c.
#define ADS8344_SS_IODIR IO0DIR
Definition at line 31 of file imu_crista_arch.c.
#define ADS8344_SS_IOSET IO0SET
Definition at line 32 of file imu_crista_arch.c.
#define ADS8344_SS_PIN 20
Definition at line 34 of file imu_crista_arch.c.
#define ADS8344Select () SetBit(ADS8344_SS_IOCLR,ADS8344_SS_PIN)
Definition at line 36 of file imu_crista_arch.c.
Referenced by ADS8344_start().
#define ADS8344Unselect () SetBit(ADS8344_SS_IOSET,ADS8344_SS_PIN)
Definition at line 37 of file imu_crista_arch.c.
Referenced by SPI1_ISR().
#define POWER_MODE (1 << 1 | 1)
Definition at line 39 of file imu_crista_arch.c.
#define SGL_DIF 1
Definition at line 40 of file imu_crista_arch.c.
Referenced by send_request().
#define SSP_CPHA 0x00 << 7
Definition at line 46 of file imu_crista_arch.c.
#define SSP_CPOL 0x00 << 6
Definition at line 45 of file imu_crista_arch.c.
#define SSP_DSS 0x07 << 0
Definition at line 43 of file imu_crista_arch.c.
#define SSP_FRF 0x00 << 4
Definition at line 44 of file imu_crista_arch.c.
#define SSP_LBM 0x00 << 0
Definition at line 50 of file imu_crista_arch.c.
#define SSP_MS 0x00 << 2
Definition at line 52 of file imu_crista_arch.c.
#define SSP_SCR 0x09 << 8
Definition at line 47 of file imu_crista_arch.c.
#define SSP_SOD 0x00 << 3
Definition at line 53 of file imu_crista_arch.c.
#define SSP_SSE 0x00 << 1
Definition at line 51 of file imu_crista_arch.c.
Function Documentation
void ADS8344_start (void)
Definition at line 98 of file imu_crista_arch.c.
References ADS8344Select, send_request(), SSP_ClearRti, SSP_Enable, and SSP_EnableRti.
static void read_values (void) [inline, static]
Definition at line 82 of file imu_crista_arch.c.
References __attribute__(), ADS8344_values, channel, and foo.
Referenced by SPI1_ISR().
static void send_request (void) [inline, static]
Definition at line 90 of file imu_crista_arch.c.
References channel, SGL_DIF, and SSP_Send.
Referenced by ADS8344_start(), and SPI1_ISR().
void SPI1_ISR (void) [static]
Definition at line 106 of file imu_crista_arch.c.
References ADS8344_available, ADS8344Unselect, channel, ISR_ENTRY, ISR_EXIT, read_values(), send_request(), SSP_ClearRti, and VICVectAddr.