Paparazzi UAS: sw/airborne/firmwares/tutorial/main_demo5.c File Reference
main_demo5.c File Reference
#include "std.h"
#include "mcu.h"
#include "sys_time.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "downlink.h"
#include "generated/settings.h"
Defines
#define MSG_SIZE 128
#define IdOfMsg(x) (x[1])
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_dl_parse_msg (void)
int main (void)
uint8_t dl_buffer[MSG_SIZE] __attribute__ ((aligned))
Variables
uint16_t foo
bool_t dl_msg_available
Define Documentation
#define IdOfMsg (x) (x[1])
Definition at line 63 of file main_demo5.c.
Referenced by main_dl_parse_msg().
#define MSG_SIZE 128
Definition at line 58 of file main_demo5.c.
Function Documentation
uint8_t dl_buffer [MSG_SIZE] __attribute__ ((aligned))
int main (void)
Definition at line 16 of file main_demo5.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_dl_parse_msg (void) [inline, static]
Definition at line 65 of file main_demo5.c.
References IdOfMsg.
Referenced by main_event_task().
static void main_event_task (void) [inline, static]
Definition at line 39 of file main_demo5.c.
References dl_msg_available, LED_TOGGLE, main_dl_parse_msg(), pprz_msg_received, pprz_parse_payload(), PprzBuffer, and ReadPprzBuffer.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 26 of file main_demo5.c.
References led_init(), mcu_init(), mcu_int_enable, and sys_time_init().
static void main_periodic_task (void) [inline, static]
Definition at line 34 of file main_demo5.c.
References cpu_time_sec.
Referenced by main().
Variable Documentation
bool_t dl_msg_available
Definition at line 56 of file main_demo5.c.
uint16_t foo
Definition at line 54 of file main_demo5.c.
Referenced by exti2_irq_handler(), EXTINT0_ISR(), main(), main_event(), main_periodic(), main_periodic_task(), overo_link_arch_prepare_next_transfert(), read_data(), read_values(), spi1_irq_handler(), SPI1_ISR(), SSP_ISR(), and test_srvo_periodic().