Paparazzi UAS: sw/airborne/mcu.h File Reference
mcu.h File Reference
arch independent mcu (Micro Controller Unit) utilities
#include <mcu_arch.h>
Functions
void mcu_init (void)
Detailed Description
arch independent mcu (Micro Controller Unit) utilities
Definition in file mcu.h.
Function Documentation
void mcu_init (void)
Definition at line 56 of file mcu.c.
References adc_init(), dac_init(), led_init(), mcu_arch_init(), spi_init(), and VCOM_init().
Referenced by init_fbw(), main(), and main_init().