Paparazzi UAV: sw/airborne/subsystems/navigation/poly_survey_adv.h File Reference
poly_survey_adv.h File Reference
#include "std.h"
Data Structures
struct point2d
Enumerations
enum survey_stage {
ERR, ENTRY, SEG, TURN1,
RET, TURN2
}
Functions
bool_t init_poly_survey_adv (uint8_t first_wp, uint8_t size, float angle, float sweep_width, float shot_dist, float min_rad, float altitude)
initializes the variables needed for the survey to start first_wp : the first Waypoint of the polygon size : the number of points that make up the polygon angle : angle in which to do the flyovers sweep_width : distance between the sweeps shot_dist : distance between the shots min_rad : minimal radius when navigating altitude : the altitude that must be reached before the flyover starts
bool_t poly_survey_adv (void)
main navigation routine.
Enumeration Type Documentation
enum survey_stage
Enumerator:
ERR
ENTRY
SEG
TURN1
RET
TURN2
Definition at line 8 of file poly_survey_adv.h.
Function Documentation
bool_t init_poly_survey_adv (uint8_t first_wp, uint8_t size, float angle, float sweep_width, float shot_dist, float min_rad, float altitude)
initializes the variables needed for the survey to start first_wp : the first Waypoint of the polygon size : the number of points that make up the polygon angle : angle in which to do the flyovers sweep_width : distance between the sweeps shot_dist : distance between the shots min_rad : minimal radius when navigating altitude : the altitude that must be reached before the flyover starts
Definition at line 163 of file poly_survey_adv.c.
References ENTRY, ERR, FALSE, get_two_intersects(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, poly_count, poly_first, psa_altitude, psa_min_rad, psa_shot_dist, psa_stage, psa_sweep_width, return_angle, segment_angle, VEC_CALC, waypoints, EnuCoor_i::x, point2d::x, EnuCoor_i::y, and point2d::y.
bool_t poly_survey_adv (void)
main navigation routine.
This is called periodically evaluates the current Position and stage and navigates accordingly. Returns True until the survey is finished
Definition at line 272 of file poly_survey_adv.c.
References dc_stop(), dc_survey(), ENTRY, estimator_z, FALSE, get_two_intersects(), last_x, last_y, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_points(), NavCourseCloseTo, NavVerticalAutoThrottleMode, psa_altitude, psa_min_rad, psa_shot_dist, psa_stage, psa_sweep_width, RET, return_angle, SEG, segment_angle, TRUE, TURN1, TURN2, vec_add(), VEC_CALC, point2d::x, and point2d::y.