Paparazzi UAV: sw/airborne/firmwares/rotorcraft/stabilization/quat_setpoint.h File Reference
quat_setpoint.h File Reference
#include "stabilization.h"
#include "subsystems/radio_control.h"
#include "math/pprz_algebra.h"
#include "stabilization/stabilization_attitude_ref_int.h"
Functions
void stabilization_attitude_sp_enter (void)
void stabilization_attitude_read_rc_incremental (bool_t enable_alpha_vane, bool_t enable_beta_vane)
void stabilization_attitude_read_rc_absolute (struct Int32Eulers sp, bool_t in_flight)
void quat_setpoint_enter_absolute (void)
void booz_stab_att_vane_on (void)
void booz_stab_att_vane_off (void)
Function Documentation
void booz_stab_att_vane_off (void)
void booz_stab_att_vane_on (void)
void quat_setpoint_enter_absolute (void)
Definition at line 155 of file quat_setpoint.c.
References ahrs, Ahrs::ltp_to_body_quat, and reset_sp_quat().
Referenced by stabilization_attitude_sp_enter().
void stabilization_attitude_read_rc_absolute (struct Int32Eulers sp, bool_t in_flight)
Definition at line 111 of file quat_setpoint.c.
References ahrs, APPLY_DEADBAND, INT32_EULERS_OF_QUAT, INT32_QUAT_COMP_NORM_SHORTEST, INT32_QUAT_OF_EULERS, Ahrs::ltp_to_body_quat, Int32Eulers::phi, PITCH_COEF, Int32Eulers::psi, QUAT_COPY, radio_control, RADIO_PITCH, RADIO_ROLL, RADIO_YAW, RATE_BFP_OF_REAL, RC_UPDATE_FREQ, reset_sp_quat(), ROLL_COEF, stab_att_sp_euler, stab_att_sp_quat, Int32Eulers::theta, and YAW_COEF.
void stabilization_attitude_read_rc_incremental (bool_t enable_alpha_vane, bool_t enable_beta_vane)
void stabilization_attitude_sp_enter (void)
Definition at line 149 of file quat_setpoint.c.
References quat_setpoint_enter_absolute().
Referenced by stabilization_attitude_ref_enter().