Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_int.h File Reference
stabilization_attitude_ref_quat_int.h File Reference
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/stabilization/quat_setpoint.h"
#include "subsystems/radio_control.h"
#include "math/pprz_algebra_float.h"
#include "stabilization_attitude_ref_int.h"
Defines
#define REF_ACCEL_FRAC 12
#define REF_RATE_FRAC 16
#define REF_ANGLE_FRAC 20
#define REF_ANGLE_PI BFP_OF_REAL(3.1415926535897932384626433832795029, REF_ANGLE_FRAC)
#define REF_ANGLE_TWO_PI BFP_OF_REAL(2.*3.1415926535897932384626433832795029, REF_ANGLE_FRAC)
#define ANGLE_REF_NORMALIZE(_a)
#define RC_UPDATE_FREQ 40.
#define ROLL_COEF (STABILIZATION_ATTITUDE_SP_MAX_P / MAX_PPRZ)
#define ROLL_COEF_H (STABILIZATION_ATTITUDE_SP_MAX_P_H / MAX_PPRZ)
#define PITCH_COEF (STABILIZATION_ATTITUDE_SP_MAX_THETA / MAX_PPRZ)
#define YAW_COEF (STABILIZATION_ATTITUDE_SP_MAX_PSI / MAX_PPRZ)
#define ROLL_COEF_RATE (-STABILIZATION_ATTITUDE_SP_MAX_P / MAX_PPRZ)
#define PITCH_COEF_RATE (STABILIZATION_ATTITUDE_SP_MAX_Q / MAX_PPRZ)
#define YAW_COEF_RATE (STABILIZATION_ATTITUDE_SP_MAX_R / MAX_PPRZ)
#define DEADBAND_EXCEEDED(VARIABLE, VALUE) ((VARIABLE > VALUE) || (VARIABLE < -VALUE))
#define APPLY_DEADBAND(VARIABLE, VALUE) (DEADBAND_EXCEEDED(VARIABLE, VALUE) ? VARIABLE : 0.0)
#define ROLL_DEADBAND_EXCEEDED()
#define PITCH_DEADBAND_EXCEEDED()
#define YAW_DEADBAND_EXCEEDED()
#define STABILIZATION_ATTITUDE_READ_RC(_sp, _in_flight) do { stabilization_attitude_read_rc_absolute(_sp, _in_flight); } while(0)
#define STABILIZATION_ATTITUDE_RESET_PSI_REF(_sp) do {} while(0)
Functions
void stabilization_attitude_ref_enter (void)
void stabilization_attitude_ref_schedule (uint8_t idx)
Define Documentation
#define ANGLE_REF_NORMALIZE (_a)
Value:
{         \
      while (_a >  REF_ANGLE_PI)  _a -= REF_ANGLE_TWO_PI;     \
      while (_a < -REF_ANGLE_PI)  _a += REF_ANGLE_TWO_PI;     \
    }
Definition at line 38 of file stabilization_attitude_ref_quat_int.h.
#define APPLY_DEADBAND (VARIABLE, VALUE) (DEADBAND_EXCEEDED(VARIABLE, VALUE) ? VARIABLE : 0.0)
Definition at line 55 of file stabilization_attitude_ref_quat_int.h.
#define DEADBAND_EXCEEDED (VARIABLE, VALUE) ((VARIABLE > VALUE) || (VARIABLE < -VALUE))
Definition at line 54 of file stabilization_attitude_ref_quat_int.h.
#define PITCH_COEF (STABILIZATION_ATTITUDE_SP_MAX_THETA / MAX_PPRZ)
Definition at line 47 of file stabilization_attitude_ref_quat_int.h.
#define PITCH_COEF_RATE (STABILIZATION_ATTITUDE_SP_MAX_Q / MAX_PPRZ)
Definition at line 51 of file stabilization_attitude_ref_quat_int.h.
#define PITCH_DEADBAND_EXCEEDED ()
Value:
(radio_control.values[RADIO_PITCH] >  STABILIZATION_ATTITUDE_DEADBAND_E || \
   radio_control.values[RADIO_PITCH] < -STABILIZATION_ATTITUDE_DEADBAND_E)
Definition at line 60 of file stabilization_attitude_ref_quat_int.h.
#define RC_UPDATE_FREQ 40.
Definition at line 44 of file stabilization_attitude_ref_quat_int.h.
#define REF_ACCEL_FRAC 12
Definition at line 32 of file stabilization_attitude_ref_quat_int.h.
#define REF_ANGLE_FRAC 20
Definition at line 34 of file stabilization_attitude_ref_quat_int.h.
#define REF_ANGLE_PI BFP_OF_REAL(3.1415926535897932384626433832795029, REF_ANGLE_FRAC)
Definition at line 36 of file stabilization_attitude_ref_quat_int.h.
#define REF_ANGLE_TWO_PI BFP_OF_REAL(2.*3.1415926535897932384626433832795029, REF_ANGLE_FRAC)
Definition at line 37 of file stabilization_attitude_ref_quat_int.h.
#define REF_RATE_FRAC 16
Definition at line 33 of file stabilization_attitude_ref_quat_int.h.
#define ROLL_COEF (STABILIZATION_ATTITUDE_SP_MAX_P / MAX_PPRZ)
Definition at line 45 of file stabilization_attitude_ref_quat_int.h.
#define ROLL_COEF_H (STABILIZATION_ATTITUDE_SP_MAX_P_H / MAX_PPRZ)
Definition at line 46 of file stabilization_attitude_ref_quat_int.h.
#define ROLL_COEF_RATE (-STABILIZATION_ATTITUDE_SP_MAX_P / MAX_PPRZ)
Definition at line 50 of file stabilization_attitude_ref_quat_int.h.
#define ROLL_DEADBAND_EXCEEDED ()
Value:
(radio_control.values[RADIO_ROLL] >  STABILIZATION_ATTITUDE_DEADBAND_A || \
   radio_control.values[RADIO_ROLL] < -STABILIZATION_ATTITUDE_DEADBAND_A)
Definition at line 57 of file stabilization_attitude_ref_quat_int.h.
#define STABILIZATION_ATTITUDE_READ_RC (_sp, _in_flight) do { stabilization_attitude_read_rc_absolute(_sp, _in_flight); } while(0)
Definition at line 67 of file stabilization_attitude_ref_quat_int.h.
#define STABILIZATION_ATTITUDE_RESET_PSI_REF (_sp) do {} while(0)
Definition at line 68 of file stabilization_attitude_ref_quat_int.h.
#define YAW_COEF (STABILIZATION_ATTITUDE_SP_MAX_PSI / MAX_PPRZ)
Definition at line 48 of file stabilization_attitude_ref_quat_int.h.
#define YAW_COEF_RATE (STABILIZATION_ATTITUDE_SP_MAX_R / MAX_PPRZ)
Definition at line 52 of file stabilization_attitude_ref_quat_int.h.
#define YAW_DEADBAND_EXCEEDED ()
Value:
(radio_control.values[RADIO_YAW] >  STABILIZATION_ATTITUDE_DEADBAND_R || \
   radio_control.values[RADIO_YAW] < -STABILIZATION_ATTITUDE_DEADBAND_R)
Definition at line 63 of file stabilization_attitude_ref_quat_int.h.
Function Documentation
void stabilization_attitude_ref_enter (void)
Definition at line 97 of file stabilization_attitude_ref_quat_float.c.
References reset_psi_ref_from_body(), stab_att_ref_accel, stab_att_ref_quat, stab_att_ref_rate, stab_att_sp_quat, stabilization_attitude_sp_enter(), and update_ref_quat_from_eulers().
Referenced by stabilization_attitude_enter().
void stabilization_attitude_ref_schedule (uint8_t idx)
Definition at line 92 of file stabilization_attitude_ref_quat_float.c.
References ref_idx.
Referenced by stabilization_attitude_gain_schedule().