Paparazzi UAS: sw/airborne/lisa/stm_test_spi_link.c File Reference
stm_test_spi_link.c File Reference
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <string.h>
#include "mcu.h"
#include "sys_time.h"
#include "lisa/lisa_overo_link.h"
#include "my_debug_servo.h"
Functions
static void main_periodic (void)
static void main_event (void)
static void on_overo_link_msg_received (void)
static void on_overo_link_crc_err (void)
static void on_overo_link_lost (void)
int main (void)
Function Documentation
int main (void)
Definition at line 43 of file stm_test_spi_link.c.
References DEBUG_SERVO1_INIT, main_event(), main_periodic(), mcu_init(), overo_link_init(), sys_time_init(), and sys_time_periodic.
static void main_event (void) [inline, static]
Definition at line 68 of file stm_test_spi_link.c.
References on_overo_link_crc_err(), on_overo_link_msg_received(), and OveroLinkEvent.
static void main_periodic (void) [inline, static]
Definition at line 60 of file stm_test_spi_link.c.
References LED_PERIODIC, on_overo_link_lost(), and OveroLinkPeriodic.
static void on_overo_link_crc_err (void) [inline, static]
Definition at line 88 of file stm_test_spi_link.c.
Referenced by main_event().
static void on_overo_link_lost (void) [inline, static]
Definition at line 75 of file stm_test_spi_link.c.
Referenced by main_periodic().
static void on_overo_link_msg_received (void) [inline, static]
Definition at line 79 of file stm_test_spi_link.c.
References DEBUG_S1_TOGGLE, LisaOveroLink::down, LisaOveroLink::msg, overo_link, and LisaOveroLink::up.
Referenced by main_event().