Paparazzi UAS: TestFuns Struct Reference
TestFuns Struct Reference
Data Fields
void(* _start)(void)
void(* _periodic)(void)
void(* _event)(void)
Detailed Description
Definition at line 72 of file test_board.c.
Field Documentation
void(* TestFuns::_event)(void)
Definition at line 75 of file test_board.c.
Referenced by main_event_task().
void(* TestFuns::_periodic)(void)
Definition at line 74 of file test_board.c.
Referenced by main_periodic_task().
void(* TestFuns::_start)(void)
Definition at line 73 of file test_board.c.
Referenced by start_test().
The documentation for this struct was generated from the following file:
sw/airborne/lisa/test/test_board.c