Paparazzi UAS: sw/airborne/lisa/test_adc.c File Reference
test_adc.c File Reference
#include <stm32/flash.h>
#include <stm32/misc.h>
#include "mcu.h"
#include "sys_time.h"
#include "led.h"
#include "mcu_periph/adc.h"
#include "mcu_periph/uart.h"
#include "downlink.h"
Functions
int main_periodic (void)
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
int main (void)
Variables
static struct adc_buf adc0_buf
static struct adc_buf adc1_buf
static struct adc_buf adc2_buf
static struct adc_buf adc3_buf
uint8_t adc_new_data_trigger
Function Documentation
int main (void)
Definition at line 58 of file test_adc.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 76 of file test_adc.c.
References adc0_buf, adc3_buf, adc_new_data_trigger, adc_buf::av_nb_sample, DefaultChannel, adc_buf::sum, and adc_buf::values.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 48 of file test_adc.c.
References adc0_buf, adc1_buf, adc2_buf, adc3_buf, adc_buf_channel(), adc_init(), mcu_init(), and sys_time_init().
int main_periodic (void) [inline]
Definition at line 135 of file main.c.
References actuators_set(), AP_MODE_FAILSAFE, AP_MODE_KILL, AP_MODE_NAV, autopilot_flight_time, autopilot_in_flight, autopilot_mode, autopilot_motors_on, autopilot_periodic(), autopilot_set_mode(), baro_periodic(), Booz2TelemetryPeriodic, datalink_time, electrical_periodic(), GpsIsLost, imu_periodic(), LED_PERIODIC, and radio_control.
Referenced by main().
static void main_periodic_task (void) [inline, static]
Definition at line 70 of file test_adc.c.
References cpu_time_sec, DefaultChannel, and LED_PERIODIC.
Referenced by main().
Variable Documentation
struct adc_buf adc0_buf [static]
Definition at line 41 of file test_adc.c.
Referenced by main_event_task(), and main_init().
struct adc_buf adc1_buf [static]
Definition at line 42 of file test_adc.c.
Referenced by main_init().
struct adc_buf adc2_buf [static]
Definition at line 43 of file test_adc.c.
Referenced by main_init().
struct adc_buf adc3_buf [static]
Definition at line 44 of file test_adc.c.
Referenced by main_event_task(), and main_init().
uint8_t adc_new_data_trigger
Definition at line 100 of file adc_arch.c.
Referenced by adc1_2_irq_handler(), adc_init(), main_event_task(), and main_periodic().