Paparazzi UAS: sw/airborne/lisa/test_spi_slave.c File Reference
test_spi_slave.c File Reference
#include <stm32/flash.h>
#include <stm32/misc.h>
#include <stm32/spi.h>
#include "mcu.h"
#include "sys_time.h"
#include "downlink.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
static void main_spi_slave_init (void)
int main (void)
void spi1_irq_handler (void)
Function Documentation
int main (void)
Definition at line 40 of file test_spi_slave.c.
References main_event_task(), main_init(), main_periodic_task(), and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 72 of file test_spi_slave.c.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 53 of file test_spi_slave.c.
References main_spi_slave_init(), mcu_init(), and sys_time_init().
static void main_periodic_task (void) [inline, static]
Definition at line 59 of file test_spi_slave.c.
References cpu_time_sec, DefaultChannel, foo, and LED_PERIODIC.
Referenced by main().
static void main_spi_slave_init (void) [inline, static]
Definition at line 77 of file test_spi_slave.c.
References SPI1.
Referenced by main_init().
void spi1_irq_handler (void)
Definition at line 126 of file test_spi_slave.c.
References DefaultChannel, foo, LED_TOGGLE, and SPI1.