Paparazzi UAS: sw/airborne/lisa/test_csc_servo.c File Reference
test_csc_servo.c File Reference
#include "mcu.h"
#include "sys_time.h"
#include "csc_msg_def.h"
#include "csc_protocol.h"
#include "stm32/can.h"
#include "downlink.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
static void main_event_task (void)
void main_on_vane_msg (void *data)
int main (void)
Variables
uint16_t servos [4]
FlagStatus can_error_warning = RESET
FlagStatus can_error_passive = RESET
FlagStatus can_bus_off = RESET
struct CscVaneMsg csc_vane_msg
Function Documentation
int main (void)
Definition at line 46 of file test_csc_servo.c.
References main_event_task(), main_init(), main_periodic_task(), servos, and sys_time_periodic.
static void main_event_task (void) [inline, static]
Definition at line 100 of file test_csc_servo.c.
References LED_OFF.
Referenced by main().
static void main_init (void) [inline, static]
Definition at line 63 of file test_csc_servo.c.
References csc_vane_msg, main_on_vane_msg(), and sys_time_init().
void main_on_vane_msg (void * data)
Definition at line 111 of file test_csc_servo.c.
References csc_vane_msg, and DefaultChannel.
Referenced by main_init().
static void main_periodic_task (void) [inline, static]
Definition at line 70 of file test_csc_servo.c.
References CAN1, can_bus_off, can_error_passive, can_error_warning, DefaultChannel, LED_OFF, LED_ON, LED_PERIODIC, and servos.
Referenced by main().
Variable Documentation
FlagStatus can_bus_off = RESET
Definition at line 40 of file test_csc_servo.c.
Referenced by main_periodic_task().
FlagStatus can_error_passive = RESET
Definition at line 39 of file test_csc_servo.c.
Referenced by main_periodic_task().
FlagStatus can_error_warning = RESET
Definition at line 38 of file test_csc_servo.c.
Referenced by main_periodic_task().
struct CscVaneMsg csc_vane_msg
Definition at line 42 of file test_csc_servo.c.
uint16_t servos[4]
Definition at line 36 of file test_csc_servo.c.
Referenced by main(), and main_periodic_task().