Paparazzi UAS: sw/airborne/lisa/test_uart.c File Reference
test_uart.c File Reference
#include <stm32/rcc.h>
#include <stm32/gpio.h>
#include <stm32/flash.h>
#include <stm32/misc.h>
#include "mcu.h"
#include "mcu_periph/uart.h"
#include "sys_time.h"
Functions
static void main_init (void)
static void main_periodic (void)
int main (void)
Function Documentation
int main (void)
Definition at line 38 of file test_uart.c.
References main_init(), main_periodic(), and sys_time_periodic.
static void main_init (void) [inline, static]
Definition at line 49 of file test_uart.c.
References mcu_init(), and sys_time_init().
static void main_periodic (void) [inline, static]
Definition at line 54 of file test_uart.c.
References LED_OFF, LED_ON, and LED_PERIODIC.