Paparazzi UAS: sw/airborne/arch/lpc21/uart_tunnel.c File Reference
uart_tunnel.c File Reference
#include "LPC21xx.h"
#include "std.h"
#include "mcu.h"
#include "led.h"
Defines
#define TXD0_PIN 0
#define RXD0_PIN 1
#define TXD1_PIN 8
#define RXD1_PIN 9
Functions
int main (int argc, char **argv)
Define Documentation
#define RXD0_PIN 1
Definition at line 10 of file uart_tunnel.c.
Referenced by main().
#define RXD1_PIN 9
Definition at line 12 of file uart_tunnel.c.
Referenced by main().
#define TXD0_PIN 0
Definition at line 9 of file uart_tunnel.c.
Referenced by main().
#define TXD1_PIN 8
Definition at line 11 of file uart_tunnel.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 14 of file uart_tunnel.c.
References IO0CLR, IO0DIR, IO0PIN, IO0SET, led_init(), LED_ON, LED_TOGGLE, mcu_init(), RXD0_PIN, RXD1_PIN, TXD0_PIN, and TXD1_PIN.
Referenced by reset_handler_stage2().