Paparazzi UAV: sw/airborne/boards/umarim/baro_board.c File Reference
baro_board.c File Reference
#include "subsystems/sensors/baro.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "downlink.h"
Defines
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void baro_init (void)
void baro_periodic (void)
void baro_downlink_raw (void)
Variables
struct Baro baro
Define Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 36 of file baro_board.c.
Function Documentation
void baro_downlink_raw (void)
Definition at line 81 of file baro_board.c.
References Baro::absolute, baro, DefaultChannel, and Baro::differential.
void baro_init (void)
Definition at line 54 of file baro_board.c.
References Baro::absolute, adc_buf_channel(), ADC_CHANNEL_BARO, ads1114_init(), baro, baro_board, BS_UNINITIALIZED, BaroBoard::buf, DACSet(), BaroBoard::data_available, DEFAULT_AV_NB_SAMPLE, Baro::differential, FALSE, LED_OFF, BaroBoard::offset, offset_cnt, OFFSET_NBSAMPLES_AVRG, Baro::status, and BaroBoard::value_filtered.
void baro_periodic (void)
Definition at line 66 of file baro_board.c.
References Baro::absolute, ads1114_read(), adc_buf::av_nb_sample, baro, BARO_ABS_ADS, baro_board, baro_board_calibrate(), BS_RUNNING, BS_UNINITIALIZED, BaroBoard::buf, BaroBoard::data_available, offset_cnt, Baro::status, adc_buf::sum, TRUE, and BaroBoard::value_filtered.
Variable Documentation
struct Baro baro
Definition at line 40 of file baro_board.c.