Paparazzi UAS: sw/airborne/mcu_periph/usb_serial.h File Reference
usb_serial.h File Reference
arch independent USB API
#include <inttypes.h>
#include "std.h"
Defines
#define UsbSInit() VCOM_init()
#define UsbSCheckFreeSpace(_x) VCOM_check_free_space(_x)
#define UsbSTransmit(_x) VCOM_putchar(_x)
#define UsbSSendMessage() {}
#define UsbSGetch() VCOM_getchar()
#define UsbSChAvailable() VCOM_check_available()
Functions
void VCOM_init (void)
int VCOM_putchar (int c)
int VCOM_getchar (void)
bool_t VCOM_check_free_space (uint8_t len)
int VCOM_check_available (void)
void VCOM_set_linecoding (uint8_t mode)
void VCOM_allow_linecoding (uint8_t mode)
Detailed Description
arch independent USB API
Definition in file usb_serial.h.
Define Documentation
#define UsbSChAvailable () VCOM_check_available()
Definition at line 50 of file usb_serial.h.
#define UsbSCheckFreeSpace (_x) VCOM_check_free_space(_x)
Definition at line 46 of file usb_serial.h.
#define UsbSGetch () VCOM_getchar()
Definition at line 49 of file usb_serial.h.
#define UsbSInit () VCOM_init()
Definition at line 45 of file usb_serial.h.
#define UsbSSendMessage () {}
Definition at line 48 of file usb_serial.h.
#define UsbSTransmit (_x) VCOM_putchar(_x)
Definition at line 47 of file usb_serial.h.
Function Documentation
void VCOM_allow_linecoding (uint8_t mode)
Referenced by main().
int VCOM_check_available (void)
Referenced by main().
bool_t VCOM_check_free_space (uint8_t len)
Referenced by main().
int VCOM_getchar (void)
Referenced by main().
void VCOM_init (void)
Referenced by main(), and mcu_init().
int VCOM_putchar (int c)
Referenced by main().
void VCOM_set_linecoding (uint8_t mode)